const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{chromium}=require('playwright-core'),{execFileSync}=require('node:child_process'),{createHash}=require('node:crypto');
function independentlyVerify(file,provenance){
 const videoSHA256=createHash('sha256').update(fs.readFileSync(file)).digest('hex');assert.equal(videoSHA256,provenance.videoSHA256,'Saved MP4 differs from certified Blob');
 const probe=JSON.parse(execFileSync('ffprobe',['-v','error','-show_streams','-show_format','-of','json',file],{encoding:'utf8',timeout:120000}));
 assert(probe.streams.some(s=>s.codec_type==='video'&&s.codec_name==='h264'));assert(probe.streams.some(s=>s.codec_type==='audio'&&s.codec_name==='aac'));
 execFileSync('ffmpeg',['-v','error','-xerror','-i',file,'-map','0:v:0','-map','0:a:0','-f','null','-'],{timeout:120000,stdio:'pipe'});
 return {status:'PASS',videoSHA256,provenanceMatch:true,completeDecode:true,probe};
}
(async()=>{
 const [executable,fixture,audioPath,outDir,label='Chrome',social='full']=process.argv.slice(2);if(!executable||!fs.existsSync(executable))throw Error('UNVERIFIED_BROWSER: executable unavailable');fs.mkdirSync(outDir,{recursive:true});
 const browser=await chromium.launch({executablePath:executable,headless:true,args:['--no-sandbox','--disable-dev-shm-usage','--allow-file-access-from-files'],timeout:60000});const page=await browser.newPage({acceptDownloads:true,viewport:{width:1365,height:900}});const errors=[];page.on('pageerror',e=>{errors.push(e.message);console.error('UIERROR',e.message)});page.on('console',m=>{if(m.type()==='error')console.log('CONSOLE',m.text().slice(0,180))});
 const saveMode=process.env.KAMEN_HEADLESS_SAVE||'download';assert(['download','native'].includes(saveMode),'Unknown headless save mode');if(saveMode==='download')await page.addInitScript(()=>{window.qaHeadlessNativePickerAvailable=typeof window.showSaveFilePicker==='function';Object.defineProperty(window,'showSaveFilePicker',{value:undefined,configurable:true});});
 try{await page.goto(process.env.KAMEN_QA_URL||'file://'+path.resolve(__dirname,'../dist/index.html'),{waitUntil:'load'});await page.waitForFunction(()=>window.J?.ui?.project&&document.querySelector('#studioExport'));await page.locator('#fileProject').setInputFiles(fixture);await page.waitForTimeout(1500);await page.evaluate(()=>{const input=document.querySelector('#audioFile');input.addEventListener('change',()=>window.qaAudioFile=input.files[0],{once:true});window.JIZURA_QA_AUDIO_FILE=async()=>window.qaAudioFile;});await page.locator('#audioFile').setInputFiles(audioPath);await page.waitForFunction(()=>document.querySelector('#audioName').textContent.includes('BPM'),null,{timeout:120000});
  await page.evaluate(()=>{const original=J.exportMP4;window.exportObservation={};J.exportMP4=async a=>{window.exportObservation.started=true;window.exportObservation.plan=a.plan;window.exportObservation.project=a.project;window.exportObservation.audio=a.audio;const r=await original(a);window.exportObservation.result=r.validation;window.exportObservation.provenance=r.provenance;return r;};});
  await page.waitForFunction(()=>!document.querySelector('#btnAutoDirection').disabled,null,{timeout:600000});
  if(!await page.locator('#studioResult').isVisible()){await page.locator('#btnAutoDirection').click({timeout:30000});await page.locator('#studioResult').waitFor({state:'visible',timeout:600000});}
  // Visible intermediate results do not imply generation has completed.
  await page.waitForFunction(()=>!document.querySelector('#studioResult').hidden&&!document.querySelector('#btnAutoDirection').disabled&&!document.querySelector('#studioRes').disabled&&!document.querySelector('#studioFPS').disabled,null,{timeout:600000});
  const details=page.locator('#studioExportDetails');await details.evaluate(el=>el.open=true);if(social==='social'){await page.locator('#studioExportRange').selectOption('socialHook');await page.locator('#studioAspect').selectOption('9:16');}await page.locator('#studioRes').selectOption('720');await page.locator('#studioFPS').selectOption('24');
  // Use the actual export button; imported saved directions are retained.
  const button=page.locator('#studioExport');await button.evaluate(el=>el.closest('#studioResult').hidden=false);await page.screenshot({path:path.join(outDir,label+'-'+social+'-ui.png')});page.on('download',async d=>{if(d.suggestedFilename().endsWith('.jizura-qa.json'))await d.saveAs(path.join(outDir,label+'-'+social+'.mp4.jizura-qa.json'));});const download=page.waitForEvent('download',{timeout:1200000});await button.click({timeout:30000});let draftReason=null;assert.equal(await page.locator('#qualityDraftExport').count(),0);const dl=await download;await dl.saveAs(path.join(outDir,label+'-'+social+'.mp4'));
  const pixels=await page.evaluate(async()=>{const {plan,project}=exportObservation,range=plan.socialHook?{start:plan.socialHook.start,end:plan.socialHook.end}:null,start=range?.start||0,end=range?.end||plan.duration,fps=plan.fps,w=plan.H>plan.W?108:192,h=plan.H>plan.W?192:108,R=new J.Renderer(),c=document.createElement('canvas'),mask=document.createElement('canvas');c.width=mask.width=plan.W;c.height=mask.height=plan.H;J.glyphs.maxRes=plan.H>=1000?768:512;const proxy=document.createElement('canvas'),pm=document.createElement('canvas');proxy.width=pm.width=w;proxy.height=pm.height=h;const pc=proxy.getContext('2d'),pmc=pm.getContext('2d');if(plan.customBg?.enabled)await R.loadCustomBackground(plan.customBg.dataUrl);const points=[...plan.lastPixelQA.metrics.lyricPoints,...plan.musicalStructure.sections.filter(s=>s.from>=start&&s.from<end).map(s=>({time:s.from+.08,phase:'macro',allowEmpty:true})),...plan.eventRealization.samples.map(e=>({time:e.peakTime,phase:'major-event',allowEmpty:true})),...(plan.lastPixelQA.metrics.observer?.peaks||[]).map(e=>({time:e.time,phase:'observed-peak',allowEmpty:true})),{time:start+.01,phase:'first',allowEmpty:true},{time:end-.1,phase:'last',allowEmpty:true}],ctx=c.getContext('2d'),mc=mask.getContext('2d'),output=[],b64=bytes=>{let s='';for(let i=0;i<bytes.length;i+=8192)s+=String.fromCharCode(...bytes.subarray(i,i+8192));return btoa(s);};for(const point of points){const frameIndex=Math.max(0,Math.round((point.time-start)*fps)),time=start+frameIndex/fps;R.frame(ctx,plan,time,{scale:1,production:true,range:range||{start:0,end:plan.duration},lyricAuditCtx:mc,lyricAuditItems:[]});pc.clearRect(0,0,w,h);pmc.clearRect(0,0,w,h);pc.drawImage(c,0,0,w,h);pmc.drawImage(mask,0,0,w,h);output.push({...point,frameIndex,time,expected:b64(pc.getImageData(0,0,w,h).data),mask:b64(pmc.getImageData(0,0,w,h).data)});}R.customBgBitmap?.close?.();return {width:w,height:h,points:output};});fs.writeFileSync(path.join(outDir,label+'-'+social+'-pixels.json'),JSON.stringify(pixels));
  if(social==='full'){const packs=await page.evaluate(async()=>{const {plan,project,audio}=exportObservation;J.checkMVQuality(project,plan,audio,null,plan.lastPixelQA,{h264:true,aac:true,webCodecs:true},exportObservation.result);const file=await window.JIZURA_QA_AUDIO_FILE(),b64=async blob=>{const bytes=new Uint8Array(await blob.arrayBuffer());let s='';for(let i=0;i<bytes.length;i+=8192)s+=String.fromCharCode(...bytes.subarray(i,i+8192));return btoa(s);};return {initial:await b64(await J.createDirectorPack({context:J.directorContext(project,plan,audio),project,audioFile:file})),revision:await b64(await J.createDirectorRevisionPack({project,plan,audio,audioFile:file,pixelQA:plan.lastPixelQA}))};});for(const [name,data] of Object.entries(packs))fs.writeFileSync(path.join(outDir,label+'-'+name+'-pack.zip'),Buffer.from(data,'base64'));}
  const mainObservation=await page.evaluate(()=>{const o=exportObservation;const quality=J.checkMVQuality(o.project,o.plan,o.audio,o.plan.socialHook?{start:o.plan.socialHook.start,end:o.plan.socialHook.end}:null,o.plan.lastPixelQA,{h264:true,aac:true,webCodecs:true},o.result).quality;return {validation:o.result,provenance:o.provenance,plan:o.plan,project:o.project,quality,text:document.querySelector('#studioQuality').textContent};});
  const fontPath=process.env.JIZURA_VARIABLE_FONT;let variableFont={tested:false,status:'UNVERIFIED_FONT'};
  if(fontPath&&fs.existsSync(fontPath)){const bytes=fs.readFileSync(fontPath).toString('base64');variableFont=await page.evaluate(async bytes=>{const binary=atob(bytes),array=new Uint8Array(binary.length);for(let i=0;i<binary.length;i++)array[i]=binary.charCodeAt(i);const buffer=array.buffer,key=await J.loadFontFile(new File([buffer],'VariableJP.ttf')),r=await J.verifyVariableFontRaster(key);const p=structuredClone(exportObservation.project);p.fonts={...p.fonts,display:key,body:key};p.artDirection.typography={...p.artDirection.typography,display:key,body:key};const audio=exportObservation.audio,plan=J.plan(p,audio);for(const cut of plan.cuts)cut.params.font=key;const result=await J.exportMP4({project:p,plan,audio,range:{start:0,end:3}});return {...r,tested:true,axes:J.fontCapabilities(key).axes,fallback:!plan.variableFontVerified,exportCertification:result.validation.certification,provenance:result.provenance,videoBase64:await (async()=>{const bytes=new Uint8Array(await result.blob.arrayBuffer());let s='';for(let i=0;i<bytes.length;i+=8192)s+=String.fromCharCode(...bytes.subarray(i,i+8192));return btoa(s);})()};},bytes);}
  const independentDecode=independentlyVerify(path.join(outDir,label+'-'+social+'.mp4'),mainObservation.provenance);
  if(variableFont.tested){assert(variableFont.exportCertification?.passed,'Variable-font MP4 certification failed');const file=path.join(outDir,label+'-'+social+'-variable-font.mp4');fs.writeFileSync(file,Buffer.from(variableFont.videoBase64,'base64'));delete variableFont.videoBase64;variableFont.independentDecode=independentlyVerify(file,variableFont.provenance);}
  const observation=mainObservation;assert(observation.validation?.certification?.passed,'MP4 reload certification failed');assert(observation.validation.audioCodec==='mp4a');assert(observation.validation.videoCodec==='avc1');assert.equal(errors.length,0,errors.join('\n'));fs.writeFileSync(path.join(outDir,label+'-'+social+'-report.json'),JSON.stringify({status:'PASS',browser:label,version:browser.version(),saveMode,independentDecode,uiDownload:true,errors,variableFont,draftReason,...observation},null,2));console.log(label,social,'UI EXPORT PASS',JSON.stringify({duration:observation.validation.duration,width:observation.validation.width,height:observation.validation.height,verified:observation.validation.certification.passed,provenanceMatch:observation.validation.provenanceMatch}));
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1});
