// Real encoded controls: injected native paint failure and a genuinely black MP4.
'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{chromium}=require('playwright-core'),crypto=require('node:crypto'),{spawnSync}=require('node:child_process');
module.exports=async({url,output})=>{const browser=await chromium.launch({executablePath:process.env.KAMEN_CHROME||'/usr/bin/chromium',headless:true,args:['--no-sandbox','--disable-dev-shm-usage']});try{const page=await browser.newPage();await page.goto(url,{waitUntil:'load'});await page.waitForFunction(()=>window.J?.certifyExport&&window.JIZURAMedia?.sampleMP4);const bytes=fs.readFileSync(path.join(output,'ui-export.mp4')).toString('base64');const source=fs.readFileSync(path.join(__dirname,'../src/11v_perceptual_director.js'),'utf8'),wrapperStart=source.indexOf('const exportMP4=J.exportMP4;J.exportMP4=async args=>'),postEncodeWrapper=source.slice(wrapperStart,source.indexOf('\n})();',wrapperStart));const result=await page.evaluate(async ({encoded,postEncodeWrapper})=>{const J=window.J,blob=new Blob([Uint8Array.from(atob(encoded),c=>c.charCodeAt(0))],{type:'video/mp4'}),inspection=J.inspectMP4Buffer(await blob.arrayBuffer(),{requireAudio:true}),draw=CanvasRenderingContext2D.prototype.drawImage;CanvasRenderingContext2D.prototype.drawImage=function(image,...args){if(image instanceof HTMLVideoElement&&this.canvas.width===96&&this.canvas.height===54){this.clearRect(0,0,96,54);return;}return draw.call(this,image,...args);};try{const recovered=await J.certifyExport(blob,{width:inspection.width,height:inspection.height,fps:24,duration:inspection.videoDuration,audio:true});
 const cv=document.createElement('canvas');cv.width=96;cv.height=54;cv.getContext('2d').fillStyle='#000';cv.getContext('2d').fillRect(0,0,96,54);const vc=await J.pickVideoCodec(96,54,24,500000),target=new Mp4Muxer.ArrayBufferTarget(),mux=new Mp4Muxer.Muxer({target,video:{codec:vc.mux,width:96,height:54,frameRate:24},fastStart:'in-memory',firstTimestampBehavior:'offset'});let error;const enc=new VideoEncoder({output:(chunk,metadata)=>mux.addVideoChunk(chunk,metadata),error:e=>error=e});try{enc.configure(vc.cfg);for(let i=0;i<24;i++){const frame=new VideoFrame(cv,{timestamp:Math.round(i*1e6/24),duration:Math.round(1e6/24)});try{enc.encode(frame,{keyFrame:i===0});}finally{frame.close();}}await enc.flush();if(error)throw error;mux.finalize();}finally{enc.close();cv.width=cv.height=1;}const blackBlob=new Blob([target.buffer],{type:'video/mp4'}),black=await J.certifyExport(blackBlob,{width:96,height:54,fps:24,duration:1,audio:false});
 // Execute the exact shipping certification wrapper after an actual encode.
 // The isolated base returns the real black control; no application state or
 // successful production export is replaced by this negative test.
 const isolated={exportMP4:async()=>({blob:blackBlob,width:96,height:54,audio:false}),certifyExport:J.certifyExport,sha256:J.sha256};new Function('J',postEncodeWrapper)(isolated);let failure;
 try{await isolated.exportMP4({plan:{fps:24,duration:1}});}catch(error){failure=error;}
 const retained=isolated.lastFailedExportArtifact,retention={rejected:!!failure,originalError:failure?.message,retainedSameBlob:retained?.blob===blackBlob,attachedSameArtifact:failure?.failedArtifact===retained,status:retained?.status,videoHash:retained?.videoHash,inspectionPassed:retained?.inspection?.certification?.passed,planHash:retained?.planHash??null};
 const buffer=new Uint8Array(await blackBlob.arrayBuffer());let binary='';for(let offset=0;offset<buffer.length;offset+=32768)binary+=String.fromCharCode(...buffer.subarray(offset,offset+32768));return {recovered:recovered.certification,black:black.certification,retention,blackBase64:btoa(binary)};}finally{CanvasRenderingContext2D.prototype.drawImage=draw;}},{encoded:bytes,postEncodeWrapper});
 assert.equal(result.recovered.nativeChecks.blackFrames,false,'Injected native paint failure must be visible');assert.equal(result.recovered.independentPixels.status,'MEASURED');assert.equal(result.recovered.passed,true,'Real valid MP4 must be independently verified');assert.equal(result.black.independentPixels.status,'MEASURED');assert.equal(result.black.checks.blackFrames,false);assert.equal(result.black.passed,false,'Real black H264 must remain rejected');const blackPath=path.join(output,'failed-black-control.mp4');fs.writeFileSync(blackPath,Buffer.from(result.blackBase64,'base64'));delete result.blackBase64;const decode=spawnSync('ffmpeg',['-v','error','-i',blackPath,'-f','null','-'],{encoding:'utf8'});assert.equal(decode.status,0,decode.stderr);assert.equal(result.retention.videoHash,crypto.createHash('sha256').update(fs.readFileSync(blackPath)).digest('hex'));assert.equal(result.retention.rejected,true);assert.equal(result.retention.retainedSameBlob,true);assert.equal(result.retention.attachedSameArtifact,true);assert.equal(result.retention.inspectionPassed,false);assert.equal(result.retention.status,'FAILED');result.retention.fullDecode='PASS';result.retention.file=path.basename(blackPath);const report={status:'PASS',controls:3,method:'actual H264/AAC UI artifact plus actual H264 black control; only native HTMLVideoElement canvas paint is injected to zero',thresholdChanged:false,previousTransientFailureCause:'UNRESOLVED: initial failed blob was not retained',...result};fs.writeFileSync(path.join(output,'cinema-v3-decoder-probe.json'),JSON.stringify(report,null,2)+'\n');console.log('Independent actual MP4 pixels recover injected native paint failure; actual black H264 rejected PASS');return report;
}finally{await browser.close();}};
