// Aggregate supplied human responses. An empty template never creates ratings.
'use strict';
const fs=require('node:fs'),assert=require('node:assert/strict');
const [csvPath,keyPath,output]=process.argv.slice(2);assert(csvPath&&keyPath&&output,'Usage: ratings.csv answer-key.json output.json');
function parseCSV(text){const rows=[];let row=[],field='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){field+='"';i++;}else quoted=!quoted;}else if(!quoted&&(c===','||c==='\n')){row.push(field.replace(/\r$/,''));field='';if(c==='\n'){rows.push(row);row=[];}}else field+=c;}assert(!quoted,'Unclosed CSV quote');if(field||row.length){row.push(field);rows.push(row);}return rows;}
const rows=parseCSV(fs.readFileSync(csvPath,'utf8').replace(/^\uFEFF/,'')),header=rows.shift(),key=new Map(JSON.parse(fs.readFileSync(keyPath,'utf8')).map(p=>[p.id,p])),metrics=['readability','musicfit','coherence','interest'],seen=new Set(),responses=[];
assert(header.includes('rater')&&header.includes('case'));
for(const row of rows){const r=Object.fromEntries(header.map((h,i)=>[h,row[i]||'']));if(!r.rater&&!metrics.some(m=>r[m+'_A']||r[m+'_B'])&&!r.preference)continue;assert(r.rater.trim(),'Answered row needs a rater code');assert(key.has(r.case),'Unknown pair');const id=r.rater+':'+r.case;assert(!seen.has(id),'Duplicate rater/pair');seen.add(id);const pair=key.get(r.case),values={};for(const m of metrics){const a=Number(r[m+'_A']),b=Number(r[m+'_B']);assert(Number.isInteger(a)&&a>=1&&a<=5&&Number.isInteger(b)&&b>=1&&b<=5,'Incomplete or invalid rating');values[m]={baseline:pair.A==='baseline'?a:b,v3:pair.A==='v3'?a:b};}assert(['A','B','同等'].includes(r.preference),'Missing/invalid preference');responses.push({rater:r.rater,fixture:pair.fixture,values,preference:r.preference==='同等'?'tie':pair[r.preference]});}
const raters=[...new Set(responses.map(r=>r.rater))],cases=[...new Set(responses.map(r=>r.fixture))],mean=a=>a.length?a.reduce((s,v)=>s+v,0)/a.length:null,result={status:responses.length?'HUMAN_RESPONSES_RECEIVED':'HUMAN_EVALUATION_PENDING',independentRaterIdentity:'NOT_VERIFIED_BY_SCRIPT',raters:raters.length,cases:cases.length,responses:responses.length,complete24By3:raters.length>=3&&raters.every(r=>responses.filter(x=>x.rater===r).length===24),artistic100Established:false,metrics:Object.fromEntries(metrics.map(m=>[m,{baselineMean:mean(responses.map(r=>r.values[m].baseline)),v3Mean:mean(responses.map(r=>r.values[m].v3)),pairedMeanDelta:mean(responses.map(r=>r.values[m].v3-r.values[m].baseline))}])),preference:Object.fromEntries(['baseline','v3','tie'].map(v=>[v,responses.filter(r=>r.preference===v).length]))};
fs.writeFileSync(output,JSON.stringify(result,null,2)+'\n');console.log(result.status);
