// Final-quality evidence keeps original and actual-decoder-clock observations separate.
'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const [output,...dirs]=process.argv.slice(2);assert(output&&dirs.length,'Usage: OUTPUT.json ROUND_DIR ...');
const labels={baseline:'main',pr5:'pr6',v3:'pr7'},hash=b=>crypto.createHash('sha256').update(b).digest('hex');
const stats=values=>{const a=values.filter(Number.isFinite).sort((x,y)=>x-y),n=a.length,mean=n?a.reduce((s,x)=>s+x,0)/n:null;return {n,p50:n?n%2?a[(n-1)/2]:(a[n/2-1]+a[n/2])/2:null,p95:n?a[Math.ceil(n*.95)-1]:null,min:n?a[0]:null,max:n?a.at(-1):null,sampleStandardDeviation:n>1?Math.sqrt(a.reduce((s,x)=>s+(x-mean)**2,0)/(n-1)):null};};
const historical=r=>(r.decoded?.layerPresence?.primaryText?.samples||[]).flatMap(line=>(line.samples||[]).map(s=>({line:line.line,time:s.time,score:s.contrast?.score??null})));
const aligned=r=>(r.independentlyAlignedReadability?.samples||[]).map(s=>({line:s.line,time:s.time,actualTime:s.actualTime,score:s.contrast?.score??null,visible:s.visible}));
const backgroundConsistent=r=>(r.independentlyProtectedIntervalReadability?.backgroundConsistentReadability?.samples||r.independentlyAlignedReadability?.backgroundConsistentReadability?.samples||[]).map(s=>({line:s.line,time:s.time,actualTime:s.actualTime,score:s.contrast?.score??null,visible:s.visible}));
const compare=(a,b)=>{const bm=new Map(b.map(s=>[s.line+':'+s.time,s]));return a.map(s=>{const t=bm.get(s.line+':'+s.time);return {...s,after:t?.score??null,actualTimeAfter:t?.actualTime??null,comparisonStatus:!t?'NO_SAME_PHRASE_TIME':!Number.isFinite(s.score)||!Number.isFinite(t.score)?'UNMEASURED':Number.isFinite(s.actualTime)&&Number.isFinite(t.actualTime)&&Math.abs(s.actualTime-t.actualTime)>1e-6?'INCOMPARABLE_ACTUAL_FRAME_TIME':'MEASURED',delta:Number.isFinite(s.score)&&Number.isFinite(t?.score)&&(!Number.isFinite(s.actualTime)||!Number.isFinite(t.actualTime)||Math.abs(s.actualTime-t.actualTime)<=1e-6)?t.score-s.score:null};});};
const rounds=dirs.map(dir=>{const raw=JSON.parse(fs.readFileSync(path.join(dir,'results.json'))),ids=new Set(raw.rows.map(r=>r.fixture.id)),cohort=[...ids].some(id=>id.startsWith('general-'))?'additional-eight':[...ids].some(id=>id.startsWith('independent-'))?'independent-six':'original-24-plus-repeats';assert.equal(ids.size,cohort==='additional-eight'?8:cohort==='independent-six'?6:28,'Keep complete cohort');assert.equal(raw.rows.length,ids.size*3);assert(raw.rows.every(r=>r.status==='PASS'),'Failed rows cannot be omitted');for(const r of raw.rows){assert.equal(hash(fs.readFileSync(path.join(dir,r.fixture.id+'-'+r.variant+'.mp4'))),r.sha256);assert.equal(r.sourceInvariant?.status,'PASS');assert(r.ffprobe.streams.some(s=>s.codec_name==='h264'));assert(r.ffprobe.streams.some(s=>s.codec_name==='aac'));}return {dir,cohort,round:raw.round,environment:raw.environment,failureHistory:raw.failureHistory||[],rows:raw.rows};});
const pairs=[];for(const round of rounds)for(const id of new Set(round.rows.map(r=>r.fixture.id))){const rows=round.rows.filter(r=>r.fixture.id===id),after=rows.find(r=>r.variant==='v3');for(const before of rows.filter(r=>r.variant!=='v3')){assert.deepEqual(before.input,after.input,'Same input/profile');assert.deepEqual(before.sourceInvariant,after.sourceInvariant,'Same immutable sources');pairs.push({cohort:round.cohort,round:round.round,id,before:labels[before.variant],after:'pr7',localContrastBefore:before.decoded?.metrics?.localContrast??null,localContrastAfter:after.decoded?.metrics?.localContrast??null,historicalIntervals:compare(historical(before),historical(after)),alignedIntervals:compare(aligned(before),aligned(after)),backgroundConsistentIntervals:compare(backgroundConsistent(before),backgroundConsistent(after)),totalDeltaMs:after.timing.totalMs-before.timing.totalMs,searchDeltaMs:after.timing.searchMs-before.timing.searchMs,exportDeltaMs:after.timing.exportMs-before.timing.exportMs});}}
const all=rounds.flatMap(round=>round.rows.map(r=>({...r,cohort:round.cohort,round:round.round}))),cohorts={};
for(const cohort of new Set(all.map(r=>r.cohort))){cohorts[cohort]={};for(const variant of ['baseline','pr5','v3']){const rows=all.filter(r=>r.cohort===cohort&&r.variant===variant),contrast=rows.map(r=>r.decoded?.metrics?.localContrast),original=rows.filter(r=>!r.fixture.id.startsWith('repeat-'));cohorts[cohort][labels[variant]]={exports:rows.length,totalMs:stats(rows.map(r=>r.timing.totalMs)),searchMs:stats(rows.map(r=>r.timing.searchMs)),exportMs:stats(rows.map(r=>r.timing.exportMs)),localContrast:stats(contrast),nonRepeatTrialLocalContrast:stats(original.map(r=>r.decoded?.metrics?.localContrast)),distinctInputLocalContrast:stats([...new Set(original.map(r=>r.fixture.id))].map(id=>stats(original.filter(r=>r.fixture.id===id).map(r=>r.decoded?.metrics?.localContrast)).p50)),unmeasuredTrials:contrast.filter(x=>!Number.isFinite(x)).length,unmeasuredInputs:[...new Set(rows.filter(r=>!Number.isFinite(r.decoded?.metrics?.localContrast)).map(r=>r.fixture.id))],perCase:Object.fromEntries([...new Set(rows.map(r=>r.fixture.id))].map(id=>{const rs=rows.filter(r=>r.fixture.id===id);return [id,{trials:rs.length,totalMs:stats(rs.map(r=>r.timing.totalMs)),localContrast:rs.map(r=>r.decoded?.metrics?.localContrast??null)}];})),inclusiveProfile:Object.fromEntries([...new Set(rows.flatMap(r=>Object.keys(r.profile||{})))].map(key=>[key,stats(rows.map(r=>r.profile?.[key]?.ms))]))};}}
const result={status:'MEASURED',rawVariantAlias:{pr5:'PR #6 (not PR #5)'},humanEvaluation:'HUMAN_EVALUATION_PENDING',artisticImprovementEstablished:false,environments:rounds.map(r=>({cohort:r.cohort,round:r.round,environment:r.environment})),method:'Same synthetic input/seed/profile, counterbalanced variant order and two original/additional rounds; historical localContrast unchanged. Aligned observer runs after timed export on all builds; PR7 shipping aligned QA is included in export time.',limits:['Shared host CPU scheduling is uncontrolled; no exclusive reservation','Two per-case original/additional trials do not establish per-case P95 confidence','Synthetic fixtures and short ranges do not establish full-song artistic quality','Peak process/GPU memory, cache-hit ratio and native save picker are UNMEASURED'],cohorts,pairs,failureHistory:rounds.flatMap(r=>r.failureHistory),exports:all.length,rows:all.map(r=>({cohort:r.cohort,round:r.round,id:r.fixture.id,variant:labels[r.variant],input:r.input,inputHash:hash(JSON.stringify({input:r.input,sourceInvariant:r.sourceInvariant})),immutableSnapshotInputHash:r.provenance?.cinemaV3?.input?.inputHash??null,sourceInvariant:r.sourceInvariant,videoHash:r.sha256,planHash:r.provenance?.cinemaV3?.planHash||r.provenance?.planHash,selectedCandidate:r.provenance?.compositionSearch?.selectedCandidate,selection:r.provenance?.compositionSearch?.v3Selection,selectionEvents:r.selectionEvents,repairHistory:r.provenance?.cinemaV3?.history??null,certificationPassed:r.validation?.certification?.passed??null,frameEvidence:r.frameEvidence,decodedMetrics:r.decoded?.metrics,lowerTail:r.decoded?.lowerTailQuality??null,historicalIntervals:historical(r),backgroundConsistentIntervals:backgroundConsistent(r),selectedPlanSummary:r.selectedPlanSummary??null,aligned:r.independentlyAlignedReadability,protectedIntervals:r.independentlyProtectedIntervalReadability??null,sameVideoObserverRepeats:r.sameVideoObserverRepeats??[],manualLockUnchanged:r.manualLockUnchanged,manualLockedCutCount:r.manualLockedCutCount,timing:r.timing,searchStageWallMs:r.searchStageWallMs??null,heapSnapshot:r.heap??null,candidateCount:r.candidateCount,nativeEvidenceReuseSource:r.provenance?.compositionSearch?.readabilityTrial?.beforeSource??null,profile:r.profile}))};
fs.mkdirSync(path.dirname(output),{recursive:true});fs.writeFileSync(output,JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({exports:result.exports,cohorts:result.cohorts}));
