// Formal Cinema V3 export check. Default mode runs the shipping UI runner.
// --verify OUTPUT_DIR validates its actual MP4/report without fabricating a new export.
'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto'),{spawnSync}=require('node:child_process');
const args=process.argv.slice(2),verify=args[0]==='--verify',out=path.resolve(verify?args[1]:args[1]||'/tmp/kamen-cinema-export');
if(!verify){assert(args[0],'Usage: cinema_v3_export_e2e.cjs URL OUTPUT_DIR');const run=spawnSync(process.execPath,[path.join(__dirname,'pages_e2e.cjs'),args[0],out],{stdio:'inherit'});if(run.error||run.status!==0)process.exit(run.status||1);}
const report=JSON.parse(fs.readFileSync(path.join(out,'report.json'),'utf8')),v3=report.provenance?.cinemaV3;assert.equal(report.status,'PASS');assert.equal(report.pageErrors.length,0);assert.equal(report.resourceFailures.length,0);assert.equal(report.checks.length,10);assert(v3,'Real UI export must activate Cinema V3');assert.equal(v3.artistic100Established,false);assert.equal(v3.budgetPolicy.hardProcessMemoryLimitEnforced,false);assert(v3.budgetPolicy.stageB<=8&&v3.budgetPolicy.stageC<=3);assert.equal(v3.peakMemoryStatus,'UNMEASURED');assert.equal(v3.peakMemoryBytes,null);assert.match(v3.input.inputHash,/^[a-f0-9]{64}$/);assert.equal(v3.planHash,v3.selectedEvidence.planHash);assert.equal(v3.videoHash,report.provenance.videoSHA256);const mp4=path.join(out,'ui-export.mp4');assert.equal(v3.videoHash,crypto.createHash('sha256').update(fs.readFileSync(mp4)).digest('hex'));assert(v3.history.length>=1);assert(v3.history.filter(h=>!h.failed).every(h=>h.stateHistory.some(s=>s.state==='FULL_ENCODED')&&h.stateHistory.some(s=>s.state==='DECODED_QA')));
const selected=v3.history.find(h=>h.videoHash===v3.videoHash);assert(selected,'Selected artifact must have its own observed history');assert.equal(selected.planHash,v3.planHash);assert(report.validation.certification.passed);
const decode=spawnSync('ffmpeg',['-v','error','-i',mp4,'-f','null','-'],{encoding:'utf8'});assert.equal(decode.status,0,decode.stderr);
const summary={name:'cinema_v3_export_e2e.cjs',status:'PASS',mode:verify?'verify-existing-actual-export':'run-actual-UI-export',checks:report.checks.length,videoHash:v3.videoHash,planHash:v3.planHash,state:v3.state,attempts:v3.history.length,decisions:v3.history.map(h=>h.failed?'CANDIDATE_FAILURE_RETAINED_BEST':h.decision.reason),artistic100Established:false,peakMemoryStatus:'UNMEASURED',browser:report.browser};const finish=decoderProbe=>{fs.writeFileSync(path.join(out,'cinema-v3-export-test.json'),JSON.stringify({...summary,decoderProbe},null,2)+'\n');console.log('Cinema V3 real UI, encoded MP4 hash, selected plan/evidence, independent full decode, draft and history PASS');};if(verify)finish({status:'NOT_RUN',reason:'verify-existing-artifact mode'});else require('./cinema_v3_decoder_probe.cjs')({url:args[0],output:out}).then(async result=>{const cancellation=await require('./cinema_v3_cancel_probe.cjs')({url:args[0],output:out});finish({...result,cancellation});}).catch(error=>{fs.writeFileSync(path.join(out,'cinema-v3-export-test.json'),JSON.stringify({name:summary.name,status:'FAIL',error:String(error.stack)},null,2)+'\n');console.error(error);process.exitCode=1;});
