'use strict';
const assert=require('node:assert/strict'),{engine}=require('./custom_test_support.cjs');
const {J}=engine(),V=J.cinemaV3;
// Independent pre-hardening oracle: preserve the metric, including UNMEASURED.
function reference(actual,background,mask,w,h){const cores=[],rings=[];for(let y=1;y<h-1;y++)for(let x=1;x<w-1;x++){const i=y*w+x;if(mask[i]>.75&&[-w,-1,1,w].every(k=>mask[i+k]>.75))cores.push(i);else if(mask[i]<.05&&[-w-1,-w,-w+1,-1,1,w-1,w,w+1].some(k=>mask[i+k]>.5))rings.push(i);}if(cores.length<3||rings.length<3)return {status:'UNMEASURED',score:null};const mean=a=>a.reduce((n,v)=>n+v,0)/a.length,ink=mean(cores.map(i=>actual[i])),surround=mean(rings.map(i=>actual[i])),ratio=(Math.max(ink,surround)+.05)/(Math.min(ink,surround)+.05);return {score:Math.round(100*Math.min(cores.filter(i=>Math.abs(actual[i]-background[i])>=.25).length/cores.length,Math.max(0,Math.min(1,(ratio-1)/2)))),contrastRatio:ratio,corePixels:cores.length,ringPixels:rings.length};}
let seed=63219;const random=()=>((seed=(Math.imul(seed,1664525)+1013904223)>>>0)/4294967296);
for(let trial=0;trial<240;trial++){const w=31+trial%17,h=23+trial%13,mask=Array.from({length:w*h},()=>trial%4?0:random()),bg=Array.from({length:w*h},()=>random()),pixels=bg.map(v=>v);for(let y=4;y<h-4;y++)for(let x=4;x<w-4;x++)if(x%12<7){const i=y*w+x;mask[i]=1;pixels[i]=trial%3===0?.98:trial%3===1?.02:random();}const expected=reference(pixels,bg,mask,w,h),actual=J.decodedGlyphContrast(pixels,bg,mask,w,h);for(const key of Object.keys(expected))assert.equal(actual[key],expected[key],`trial ${trial} ${key}`);const rgba=new Uint8ClampedArray(w*h*4);for(let i=0;i<rgba.length;i++)rgba[i]=Math.floor(random()*256);assert.deepEqual(Array.from(J.cinemaReferenceLuma(rgba)),Array.from(J.observePixelFrame(rgba,w,h).luma));assert.deepEqual(Array.from(J.cinemaPrimaryAlpha(rgba)),Array.from(rgba).filter((_,i)=>i%4===3).map(v=>v/255));}
for(const mask of [Array(100).fill(0),Array(100).fill(1)])assert.equal(J.decodedGlyphContrast(Array(100).fill(1),Array(100).fill(0),mask,10,10).status,'UNMEASURED');
const p={...J.defaultProject(),W:640,H:360,duration:4,fps:24,cuts:[]};
function item(id,contrast=94){return {id,planHash:'plan-'+id,outputReadability:{score:contrast,frameAlignedScore:contrast,samples:Array(6).fill({})},raster:{rank:10,samples:[{line:0,safe:true}]},video:{score:80,samples:[{intentionalHold:false}]},encoded:{completed:true,metrics:{localContrast:contrast},readability:{sampleCount:6},lowerTailQuality:80,sceneQuality:[{line:0}],layerPresence:{primaryText:{samples:[{visibleSamples:6,samples:Array(6).fill({})}]}}}};}
const ineligibleIncumbent={id:'baseline',proxyEligibility:{eligible:false}},eligibleReplacement={id:'1',proxyEligibility:{eligible:true}};assert.equal(V.needsOutputReadability([ineligibleIncumbent,eligibleReplacement],ineligibleIncumbent),true,'baseline evidence remains necessary to protect a potential replacement');assert.equal(V.needsOutputReadability([ineligibleIncumbent],ineligibleIncumbent),false,'no promotable proxy needs no extra native render');
const base=item('baseline'),changed=item('1');assert.equal(V.proxyEligibility(base,p,null,'same-input').eligible,true);const unmeasuredProxy=item('unknown');unmeasuredProxy.encoded={completed:false,status:'UNMEASURED'};assert.equal(V.proxyEligibility(unmeasuredProxy,p,null,'same-input').eligible,false,'an ineligible codec proxy cannot justify more native renders');for(const candidates of [[base,changed],[changed,base]]){const selected=V.selectSearch(candidates,p,'C',null,'same-input');assert.equal(selected.item.id,'baseline');assert.equal(selected.reason,'BASELINE_EQUAL_MEASURED_EVIDENCE');}
assert.equal(V.selectSearch([base,item('1',96)],p,'C',null,'same-input').item.id,'1','measured improvement remains eligible');assert.equal(V.selectSearch([base,item('1',93)],p,'C',null,'same-input').item.id,'baseline','protected readability rejects a regression');
const nativeRegression=item('1',96);nativeRegression.outputReadability.score=80;nativeRegression.encoded.lowerTailQuality=99;assert.equal(V.selectSearch([base,nativeRegression],p,'C',null,'same-input').item.id,'baseline','output-profile readability cannot be traded for proxy motion');
const phaseBaseline=item('baseline',94),phaseChanged=item('1',95);phaseBaseline.outputReadability.samples=[{line:0,time:1,contrast:{score:100}},{line:1,time:2,contrast:{score:94}}];phaseChanged.outputReadability.samples=[{line:0,time:1,contrast:{score:99}},{line:1,time:2,contrast:{score:95}}];assert.equal(V.selectSearch([phaseBaseline,phaseChanged],p,'C',null,'same-input').item.id,'baseline','better minimum cannot conceal a regression in an already-readable phrase interval');
const nearTimes=item('near',94);nearTimes.outputReadability.samples=[{line:0,time:1,contrast:{score:100}},{line:0,time:1+1e-10,contrast:{score:94}}];assert.doesNotThrow(()=>V.searchEvaluation(nearTimes,p,'C','same-input'), 'distinct floating-point sample times must not produce duplicate evidence IDs');
const missing=item('1');missing.encoded={completed:false,status:'UNMEASURED'};assert.equal(V.selectSearch([missing],p,'C',null,'same-input').item,null);const unsafe=item('1',100);unsafe.raster.samples[0].safe=false;assert.equal(V.selectSearch([base,unsafe],p,'C',null,'same-input').item.id,'baseline');
console.log('240 differential contrast/luma/alpha fixtures; equal-evidence baseline, actual improvement, missing evidence and hard safety PASS');
(async()=>{
 const project={...J.defaultProject(),res:360,aspect:'16:9'},plan=J.plan(project,{duration:3,beats:[]});assert.deepEqual(Array.from(V.outputProfile(plan).resolution),[640,360]);assert.equal(plan.W,1920,'design coordinates remain unchanged');
 plan.musicalPhoto={cinema:{architectureSearch:{selectedCandidate:'old'}},preparation:{}};V.bindDelivery(plan,project);assert(plan.musicalPhoto.cinema.architectureSearch,'same raster preserves search');V.bindDelivery(plan,{...project,res:720});assert.equal(plan.musicalPhoto.cinema.architectureSearch,undefined,'delivery change invalidates previous search');assert.equal(plan.musicalPhoto.preparation,undefined);assert.deepEqual(Array.from(V.outputProfile(plan).resolution),[1280,720]);
 const unknown=await J.measureCinemaOutputReadability({W:1920,H:1080,cuts:[],duration:3,fps:24},null);assert.equal(unknown.status,'UNMEASURED');assert.equal(unknown.score,null,'old/unbound plan is not silently measured at design resolution');
 const measured=(score,values=[100,score])=>({score,samples:values.map((value,i)=>({time:i,contrast:{score:value}}))});
 assert.equal(V.initialGrammarAcceptable(measured(50),measured(54)),false,'quieter initial motion cannot reduce delivered-raster readability');assert.equal(V.initialGrammarAcceptable(measured(60,[99,60]),measured(54)),false,'protect strong legacy intervals even with better weakest score');assert.equal(V.initialGrammarAcceptable(measured(60),measured(54)),true);assert.equal(V.initialGrammarAcceptable({score:null},measured(54)),false);
 const originalGuard=J.measureCinemaOutputReadability,originalLock=J.photoChoreographyLocked;
 try{J.photoChoreographyLocked=(_p,c)=>!!c.locked;const legacy={temporal:{level:.8},motion:.8},adapted={temporal:{level:.2},motion:.2},make=()=>({cuts:[{line:0,start:0,grammar:structuredClone(adapted),cinemaV3LegacyGrammar:structuredClone(legacy)},{line:1,start:1,locked:true,grammar:structuredClone(adapted),cinemaV3LegacyGrammar:structuredClone(legacy)}],storyboard:[{from:0}],musicalPhoto:{cinema:{grammar:{}}}});
 const guarded=make();J.measureCinemaOutputReadability=async p=>measured(p.cuts[0].grammar.motion===.8?54:50);await V.protectInitialGrammar(guarded,null);assert.equal(guarded.cuts[0].grammar.motion,.8);assert.equal(guarded.cuts[1].grammar.motion,.2,'manual grammar never restored or changed');assert.equal(guarded.storyboard[0].shotGrammar.motion,.8);assert.equal(guarded.musicalPhoto.cinema.initialGrammarProtection.decision,'KEEP_INTERNAL_LEGACY_GRAMMAR');
 const cancelled=make();let calls=0;J.measureCinemaOutputReadability=async()=>{if(++calls===2)throw Error('abort after legacy comparison starts');return measured(50);};await assert.rejects(V.protectInitialGrammar(cancelled,null),/abort/);assert.equal(cancelled.cuts[0].grammar.motion,.2,'cancel restores the original adapted plan');
 }finally{J.measureCinemaOutputReadability=originalGuard;J.photoChoreographyLocked=originalLock;}
 console.log('Actual delivery dimensions, design-coordinate separation, profile invalidation and honest unbound legacy guard PASS');
})().catch(error=>{console.error(error);process.exitCode=1;});
