'use strict';const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),{engine}=require('./custom_test_support.cjs');
const {J,context}=engine();const V=J.cinemaV3,project=J.defaultProject();project.lyrics='[00:00.00]光へ\n[00:02.00]Hello 世界';project.fps=24;const audio={duration:4,energyRate:10,energy:new Float32Array(40).fill(.2),onset:new Float32Array(40),tempoConfidence:.1,features:{statistics:{energy:{confidence:.8}}}},p=J.plan(project,audio);p.musicalPhoto={cinema:{grammar:{}}};p.cuts.forEach(c=>c.grammar={quiet:true,temporal:{level:.5,motionPrinciple:'weighted-hold'}});const before=JSON.stringify(p.lines);V.adaptPlan(p,audio,project);assert.equal(JSON.stringify(p.lines),before);assert(p.cuts.every(c=>c.grammar.intentionalHold));assert(p.cuts.every(c=>c.grammar.directionPolicy.mode==='lyric_first'));assert.equal(p.cinemaV3Features.vocalSynchronization.status,'UNMEASURED');
const f=V.sectionFeatures(p,audio),g=V.sectionFeatures(p,{...audio,energy:Float32Array.from(audio.energy,x=>x*2)});assert.equal(J.canonicalJSON(f),J.canonicalJSON(g),'volume-only scaling preserves normalized features');
const phase=V.phases({start:1,end:1.05,lineText:'短'},24);const order=['PREPARE','ENTER','SETTLE','HOLD','RELEASE','EXIT'];order.forEach((key,i)=>{assert(phase[key][0]<=phase[key][1]);if(i)assert(phase[order[i-1]][1]<=phase[key][0]);});assert.equal(V.phaseAt(phase,1),'ENTER');
for(const text of ['短','長い歌詞を読みやすい余白の中へ配置する','Hello 世界 2026','漢字《かんじ》','前半\n後半','「句読点、禁則。」'])for(const [W,H]of [[1920,1080],[1080,1920],[1080,1080]]){const plan={W,H,fps:24},cut={start:0,end:4,lineText:text,params:{font:'embedded_bold'}},r=V.typographyPreflight(plan,cut);assert(r.widths.every(Number.isFinite));assert(r.size>0);assert.equal(r.fontCoverage.value,null);assert.equal(cut.lineText,text);}
const locked=V.clone(p);locked.cuts[0].locked=true;const manual=J.canonicalJSON(locked.cuts[0]);V.adaptGrammar(locked);assert.equal(J.canonicalJSON(locked.cuts[0]),manual);assert.equal(V.sectionFeatures(p,{duration:4})[0].energy.status,'UNMEASURED');
for(const [W,H,aspect] of [[1920,1080,'16:9'],[1080,1920,'9:16'],[1080,1080,'1:1'],[1080,1350,'4:5']]){const q={W,H,fps:24,duration:4,exportSettings:{},cinemaV3Features:{}};assert.equal(V.outputProfile(q).aspect,aspect);assert.equal(J.cinemaOutputProfile(q).loopRequired,false);q.socialHook={start:0,end:2};assert.equal(J.cinemaOutputProfile(q).loopRequired,false,'short is not implicitly a loop');q.exportSettings.loopRequired=true;assert.equal(J.cinemaOutputProfile(q).loopRequired,true);}
const archivedPlan={duration:4,lines:[],cuts:[],visualAssets:[{dataUrl:'data:image/png,one'}]};V.adaptPlan(archivedPlan,audio,{customBg:{enabled:true},visualAssets:[{dataUrl:'a'},{dataUrl:'b'}]});assert.equal(archivedPlan.cinemaV3Features.inputMode,'single-image','archived images are not active multi-image evidence');
const malformed={...audio,energy:[.2,NaN,.4,.8],energyRate:1};const regions={duration:4,lines:[],musicalStructure:{sections:[{from:0,to:2},{from:2,to:4}]}};const regionFeatures=V.sectionFeatures(regions,malformed);assert(Math.abs(regionFeatures[0].energy.value-.25)<1e-7,'unknown energy bins cannot shift section timing');assert(Math.abs(regionFeatures[1].energy.value-.75)<1e-7);
V.invalidate(p);assert.equal(p.lastPixelQA,null);assert.equal(p.lastQualityTarget,undefined);
const makeCanvas=context.document.createElement;try{context.document.createElement=()=>({getContext:()=>({})});const unknown=V.typographyPreflight({W:640,H:360,fps:24},{start:0,end:1,lineText:'幅は未測定',params:{font:'embedded_bold'}});assert.equal(unknown.widthStatus,'UNMEASURED');assert.equal(unknown.widths,null);assert(unknown.constraintFailures.includes('CANVAS_TEXT_MEASUREMENT_UNAVAILABLE'));}finally{context.document.createElement=makeCanvas;}
const quietCut=p.cuts[0],middle=(quietCut.grammar.scenePhases.HOLD[0]+quietCut.grammar.scenePhases.HOLD[1])/2;const stateA=J.cinemaTemporalState(p,quietCut,middle),stateB=J.cinemaTemporalState(p,quietCut,middle+.1);assert.equal(stateA.stagePhase,'HOLD');assert.equal(stateA.entry,0);assert.equal(stateA.travel,stateB.travel,'deliberate HOLD has a real camera travel plateau');const moving=V.clone(quietCut);moving.grammar.intentionalHold=false;assert(J.cinemaTemporalState(p,moving,middle+.1).travel>J.cinemaTemporalState(p,moving,middle).travel,'moving HOLD uses continuous real travel');
console.log('confidence fallback, normalized volume invariance, intentional HOLD, short phrase phase ordering, Japanese/mixed/ruby typography, aspect geometry and exact locked preservation PASS');
