'use strict';
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const {engine,root}=require('./custom_test_support.cjs');
const baseline=process.argv[2];if(!baseline)throw Error('Provide archived v35 directory');
const out=process.argv[3]||path.join(root,'dev','custom-quality-measurements.json');
const median=a=>[...a].sort((a,b)=>a-b)[Math.floor(a.length/2)],results={baselineCommit:'4015911370e059147ee12cb8c124afcc1e3cd78c',environment:{node:process.version,canvas:require('@napi-rs/canvas/package.json').version},measurements:[],integrity:[]};
function audioEngine(directory,sr,seconds,channels,silent=false){
 const samples=Array.from({length:channels},(_,c)=>Float32Array.from({length:Math.round(sr*seconds)},(_,i)=>silent?0:Math.sin(i*2*Math.PI*(220+c*55)/sr)*(.13+.06*Math.sin(i/sr*4))+(i%Math.round(sr*.5)<sr*.02?.22*Math.sin(i*2*Math.PI*80/sr):0)));
 const buffer={sampleRate:sr,length:samples[0].length,numberOfChannels:channels,duration:samples[0].length/sr,getChannelData:c=>samples[c]};let closed=0;
 const J={BPM_RANGE:{min:45,max:240}},context=vm.createContext({J,window:{AudioContext:class{async decodeAudioData(){return buffer;}async close(){closed++;}}},setTimeout,clearTimeout});vm.runInContext(fs.readFileSync(path.join(directory,'src/10_audio.js'),'utf8'),context);
 return {J,buffer,get closed(){return closed;},file:{name:'検証_音源「A&B」.wav',arrayBuffer:async()=>new ArrayBuffer(16)}};
}
async function compareTimes(label,a,b,rounds=5){const before=[],after=[];await a();await b();for(let i=0;i<rounds;i++){for(const [f,times] of i%2?[[b,after],[a,before]]:[[a,before],[b,after]]){global.gc?.();let t=performance.now();await f();times.push(performance.now()-t);}}const old=median(before),next=median(after);results.measurements.push({label,unit:'ms',before:old,after:next,improvementPercent:(1-next/old)*100,samplesBefore:before,samplesAfter:after});}
(async()=>{
 for(const [sr,secs,ch,silent]of [[8000,.1,1,true],[16000,6,1,false],[44100,30,2,false]]){
  const old=audioEngine(baseline,sr,secs,ch,silent),next=audioEngine(root,sr,secs,ch,silent),a=await old.J.analyzeAudio(old.file),b=await next.J.analyzeAudio(next.file);
  const plain=o=>JSON.stringify({...o,buffer:undefined});assert.equal(plain(a),plain(b));assert.equal(next.closed,1);results.integrity.push({test:'full_audio_descriptor_equality',sampleRate:sr,seconds:secs,channels:ch,silent,exact:true});
 }
 const old=audioEngine(baseline,44100,120,2),next=audioEngine(root,44100,120,2);await compareTimes('120s stereo PCM analysis; decode mocked, no UI stage yields',()=>old.J.analyzeAudio(old.file),()=>next.J.analyzeAudio(next.file),5);
 const previous=engine(baseline,true),current=engine(root,true);
 const project=previous.J.defaultProject();project.seed=777;project.title='日本語「光」';project.lyrics='[00:00.00]光をつなぐ\n[00:01.00]未来へ進む\n[00:02.00]響く声';project.res=1080;project.fps=30;
 const audio={duration:3,bpm:120,beats:[0,.5,1,1.5,2,2.5],features:{energy:.7,beatStrength:.8,density:.6,brightness:.5,bass:.6,high:.4,timeline:[{time:0,energy:.7,density:.6,spectralFlux:.5}]}};
 for(const aspect of ['16:9','9:16','1:1','4:5']){
  const p={...project,aspect};const a=previous.J.plan(JSON.parse(JSON.stringify(p)),audio),b=current.J.plan(JSON.parse(JSON.stringify(p)),audio);assert.equal(JSON.stringify(a),JSON.stringify(b));
  previous.resetRandom();current.resetRandom();const ar=new previous.J.Renderer(),br=new current.J.Renderer(),h=180,w=Math.round(h*a.W/a.H),ac=previous.createCanvas(w,h),bc=current.createCanvas(w,h);
  for(const t of [0,.08,.4,.98,1.02,1.5,2.2,2.95]){ar.frame(ac.getContext('2d'),a,t,{scale:w/a.W,production:true});br.frame(bc.getContext('2d'),b,t,{scale:w/b.W,production:true});const ap=ac.getContext('2d').getImageData(0,0,w,h).data,bp=bc.getContext('2d').getImageData(0,0,w,h).data;assert.deepEqual(ap,bp);}
  results.integrity.push({test:'plan_and_render_pixel_equality',aspect,frames:8,exact:true});
 }
 const bg=previous.createCanvas(640,360),bx=bg.getContext('2d');bx.fillStyle='#416d97';bx.fillRect(0,0,640,360);bx.fillStyle='#e2a344';bx.fillRect(350,20,200,300);const url=bg.toDataURL('image/png');const alt=previous.createCanvas(640,360),ax=alt.getContext('2d');ax.fillStyle='#583347';ax.fillRect(0,0,640,360);const url2=alt.toDataURL('image/png');
 for(const count of [1,2])for(const aspect of ['16:9','9:16']){const p=JSON.parse(JSON.stringify(project));p.aspect=aspect;p.customBg={...p.customBg,enabled:true,dataUrl:url};p.visualAssets=count===2?[{id:'hero',name:'主役.png',dataUrl:url,role:'AUTO',pin:'auto',analysis:previous.J.analyzeVisualAsset(bg)},{id:'other',name:'章.png',dataUrl:url2,role:'AUTO',pin:'auto',analysis:previous.J.analyzeVisualAsset(alt)}]:[];const a=previous.J.plan(p,audio),b=current.J.plan(p,audio);assert.equal(JSON.stringify(a),JSON.stringify(b));previous.resetRandom();current.resetRandom();const ar=new previous.J.Renderer(),br=new current.J.Renderer();await ar.loadCustomBackground(url);await br.loadCustomBackground(url);await ar.loadAssetDeck(a);await br.loadAssetDeck(b);const w=320,h=Math.round(w*a.H/a.W),ac=previous.createCanvas(w,h),bc=current.createCanvas(w,h);for(const t of [.05,.5,1.05,1.8,2.6]){ar.frame(ac.getContext('2d'),a,t,{scale:w/a.W,production:true});br.frame(bc.getContext('2d'),b,t,{scale:w/b.W,production:true});assert.deepEqual(ac.getContext('2d').getImageData(0,0,w,h).data,bc.getContext('2d').getImageData(0,0,w,h).data);}ar.disposeAssets();br.disposeAssets();results.integrity.push({test:'background_and_multi_asset_pixel_equality',aspect,images:count,frames:5,exact:true});}
 const historyBytes=[];for(const e of [previous,current]){e.J.ui.project=JSON.parse(JSON.stringify(project));e.J.ui.project.proAssets=[{id:'logo',dataUrl:'data:image/png;base64,'+'A'.repeat(300000)}];let bytes=0;for(let i=0;i<60;i++){e.J.ui.project.seed=i;bytes+=Buffer.byteLength(e.J.uiApi.lookSnap());}historyBytes.push(bytes);}results.historySnapshotPayload={fixtureProAssetCharacters:300000,retainedStates:60,beforeBytes:historyBytes[0],afterBytes:historyBytes[1],reductionPercent:(1-historyBytes[1]/historyBytes[0])*100,notHeapMeasurement:true};
 for(const e of [previous,current]){const tl=e.createCanvas(1200,160);tl.clientWidth=1200;tl.clientHeight=160;e.nodes.set('timeline',tl);e.J.ui.project=project;e.J.ui.plan=e.J.plan(project,audio);e.J.ui.audio={duration:3,peaks:new Float32Array(1600).fill(.5)};e.J.ui.t=.6;e.J.uiApi.drawTimeline();}
 assert.deepEqual(previous.nodes.get('timeline').getContext('2d').getImageData(0,0,1200,160).data,current.nodes.get('timeline').getContext('2d').getImageData(0,0,1200,160).data);results.integrity.push({test:'timeline_first_frame_pixel_equality',exact:true});
 await compareTimes('100 editor timeline playhead updates; 1200x160 canvas',()=>{for(let i=0;i<100;i++){previous.J.ui.t=(i%90)/30;previous.J.uiApi.drawTimeline();}},()=>{for(let i=0;i<100;i++){current.J.ui.t=(i%90)/30;current.J.uiApi.drawTimeline();}},5);
 const pixels=Uint8ClampedArray.from({length:1920*1080*4},(_,i)=>i%31);
 await compareTimes('MP4 reload RGB black-frame scan; 1080p synthetic buffer',()=>{const a=Array.from(pixels).filter((_,i)=>i%4!==3).map(v=>v>8?1:0);return a.reduce((s,v)=>s+v,0)/a.length;},()=>current.J.nonBlackRGBFraction(pixels),5);
 const small=Uint8ClampedArray.from({length:96*54*4},(_,i)=>i%31);await compareTimes('100 MP4 reload RGB scans at actual 96x54 inspection size',()=>{for(let k=0;k<100;k++){const a=Array.from(small).filter((_,i)=>i%4!==3).map(v=>v>8?1:0);a.reduce((s,v)=>s+v,0)/a.length;}},()=>{for(let k=0;k<100;k++)current.J.nonBlackRGBFraction(small);},5);
 results.unmeasured=['Browser startup','Real decodeAudioData/audio file loading','Real IndexedDB project loading','Browser preview startup','Full WebCodecs H.264/AAC export','Browser process RSS/heap/GPU'];
 results.memoryEvidence={history:'Pro media are interned once across 60 snapshots and unreferenced media are pruned',compressedInputCopy:'Removed one full input ArrayBuffer clone from decodeAudioData',blackFrameScan:'Removed full RGBA numeric array and two RGB numeric intermediate arrays; bytes depend on JS engine',rendererBudget:'Unchanged 48 MiB visual decode budget, 2048 dimension cap; originals preserved'};
 fs.writeFileSync(out,JSON.stringify(results,null,2));console.log(JSON.stringify(results,null,2));
})().catch(e=>{console.error(e);process.exitCode=1});
