// Network diagnosis, separate from performance measurements and production QA.
'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{chromium}=require('playwright-core');
const [url,out]=process.argv.slice(2);assert(url&&out);fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await chromium.launch({executablePath:process.env.KAMEN_CHROME,headless:true,args:['--no-sandbox','--disable-dev-shm-usage']});const cases=[];
 try{for(const blocked of [false,true]){const context=await browser.newContext();try{const page=await context.newPage(),failures=[],errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('requestfailed',r=>failures.push({url:r.url(),reason:r.failure()?.errorText}));if(blocked)await context.route(/https:\/\/fonts\.(googleapis|gstatic)\.com\//,r=>r.abort('internetdisconnected'));
 await page.goto(url);await page.waitForFunction(()=>window.J?.ui);const observation=await page.evaluate(async()=>{const start=performance.now();await J.ensureFonts('光と夢',['gothic_bold','embedded_bold']);return {elapsedMs:performance.now()-start,evidence:Object.fromEntries(J.fontLoadEvidence),embeddedAvailable:document.fonts.check('700 32px "JIZURA Noto CJK JP"','光と夢')};});
 assert.equal(errors.length,0);assert.equal(observation.embeddedAvailable,true,'embedded font must survive external network failure');assert.equal(observation.evidence.embedded_bold.status,'LOADED');if(blocked){assert.notEqual(observation.evidence.gothic_bold.status,'LOADED','failed external font must not be marked loaded');assert(failures.length>0);}
 cases.push({mode:blocked?'CONTROLLED_EXTERNAL_NETWORK_FAILURE':'NORMAL_NETWORK',...observation,failures,pageErrors:errors});}finally{await context.close();}}
 const externalLoaded=cases[0].evidence.gothic_bold?.status==='LOADED';fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({status:externalLoaded?'PASS':'EXTERNAL_LOAD_UNRESOLVED',browser:browser.version(),cases,historicalFailureCause:'UNRESOLVED: old-instance failure artifacts unavailable; present success cannot prove past cause'},null,2));console.log('Font probe:',externalLoaded?'normal external load and explicit unavailable evidence under controlled network failure PASS':'external loading unresolved; inspect report');if(!externalLoaded)process.exitCode=1;
 }finally{await browser.close();}})().catch(error=>{console.error(error);process.exitCode=1});
