'use strict';const assert=require('node:assert/strict'),{engine}=require('./custom_test_support.cjs');const {J,createCanvas}=engine();
(async()=>{
 J.enableSingleBackgroundMode();const bg=createCanvas(320,180),x=bg.getContext('2d');x.fillStyle='#17354a';x.fillRect(0,0,320,180);const p=J.defaultProject();Object.assign(p,{autoDirection:true,title:'テスト',artist:'作者',lyrics:'[00:02.00]遠くまで歌声を届けよう\n[00:05.00]オー We are ガンバ\n[00:08.00]青黒\n[00:11.00]遠くまで歌声を届けよう\n[00:14.00]オー We are ガンバ\n[00:17.00]青黒'});p.customBg={...p.customBg,enabled:true,dataUrl:bg.toDataURL()};const a={duration:22,beats:[.1,2,5,8,11,14,17],features:{energy:.7}},d=J.proposeDirection(p,a,{});Object.assign(p,{style:d.style,mood:d.mood,fx:d.fx,enabled:d.enabled,seed:d.seed});p.artDirection=J.makeArtDirection(p,a,d);const base=J.plan(p,a);
 d.registrySelection={style:p.style,font:'embedded_bold',backgroundKey:J.registrySelectionBackgroundKey(p),lyricsKey:J.registrySelectionLyricsKey(base),entries:Object.fromEntries(base.cuts.filter(c=>c.line>=0).map(c=>[c.line,{layout:c.line<3?'photoStatement':'photoPhrase',params:{font:'embedded_bold',displayText:c.line<3?c.lineText:J.composeLyricPhrase(c.lineText),composition:c.line<3?'statement':'phrase'},enter:'photoSettle',hold:'pulse',inDur:.12,family:c.line<3?'statement':'phrase'}]))};d.visualDNA={...d.visualDNA,layoutStrategy:'phraseRenderSelection',decorationStrategy:'none'};p.artDirection=J.makeArtDirection(p,a,d);
 const source=JSON.stringify(p),plan=J.plan(p,a);assert.equal(JSON.stringify(p),source);assert(plan.musicalPhoto);assert(plan.cuts.filter(c=>c.line>=0).every(c=>c.registrySelected&&(c.story.holdRepair?c.hold===c.story.holdRepair.to:c.hold==='pulse')&&c.enter==='photoSettle'&&c.lineText===plan.lines[c.line].text));
 const R=new J.Renderer(),cv=createCanvas(640,360);await R.loadCustomBackground(p.customBg.dataUrl);await R.loadAssetDeck(plan);const first=plan.cuts.find(c=>c.line===0),snap=JSON.stringify({params:first.params,events:plan.events,hype:plan.hypeTimeline});
 for(const time of [2.03,2.2,2.7,2.03]){R.frame(cv.getContext('2d'),plan,time,{scale:640/plan.W,production:true});assert.equal(JSON.stringify({params:first.params,events:plan.events,hype:plan.hypeTimeline}),snap,'render must preserve stored hook scale and event arrays');}
 const manual=J.plan({...p,overrides:{0:{enter:'pop',hold:'breathe',cam:'panL'}}},a),cut=manual.cuts.find(c=>c.line===0);assert.equal(cut.enter,'pop');assert.equal(cut.hold,'breathe');assert.equal(cut.cam,'panL');
 const targetBefore=JSON.stringify(plan.visualWorld.chapters.map(c=>c.targetWorldDistance));await J.refineMusicalPhotoPlan(plan);assert.equal(JSON.stringify(plan.visualWorld.chapters.map(c=>c.targetWorldDistance)),targetBefore);assert(plan.musicalPhoto.story,'single-image plans use a narrative director instead of crop-only refinement');assert(!plan.musicalPhoto.refinement,'do not run an ineffective camera crop search on narrative camera poses');assert(plan.musicalPhoto.chapterGrades.every(g=>g>=0&&g<=.08));assert(plan.musicalPhoto.chapterZooms.every(z=>z<=1.46));R.disposeAssets();console.log('Music-timed photo poses, unchanged QA targets, repeatable rendering and manual overrides PASS');
})().catch(e=>{console.error(e);process.exitCode=1;});
