'use strict';const assert=require('node:assert/strict'),{engine}=require('./custom_test_support.cjs');
(async()=>{const {J,createCanvas}=engine();J.enableSingleBackgroundMode();assert.equal(J.composeLyricPhrase('俺らはいつものように'),'俺らは\nいつものように');assert.equal(J.composeLyricPhrase('私たちは明日を信じてる'),'私たちは\n明日を信じてる');const bg=createCanvas(480,320),bx=bg.getContext('2d');bx.fillStyle='#102030';bx.fillRect(0,0,480,320);for(let i=0;i<5;i++){bx.fillStyle=i%2?'#b9c6d8':'#328abe';bx.fillRect(i*95+10,30+i*20,60,210);}
const source=J.defaultProject();Object.assign(source,{autoDirection:true,style:'blueprint',res:720,fps:30,title:'Test',lyrics:'[00:02]声が聞こえるだろ\n[00:05]今日もここにいるぜ\n[00:08]ラララーラララー\n[00:11]ラララーラララー\n[00:14]ラララーラララー\n[00:17]ラララーラララー\n[00:20]オオオーオオオー\n[00:23]オオオーオオオー\n[00:26]オオオーオオオー\n[00:29]オオオーオオオー'});source.customBg={...source.customBg,enabled:true,dataUrl:bg.toDataURL()};const a={duration:32,beats:Array.from({length:90},(_,i)=>i*.36),features:{energy:.85,bpm:165,beatStrength:.95,percussive:.9,smoothness:.15}};
const d=J.proposeDirection(source,a,{});d.style='blueprint';Object.assign(source,{style:d.style,mood:d.mood,fx:d.fx,enabled:d.enabled,seed:d.seed});source.artDirection=J.makeArtDirection(source,a,d);const initial=J.plan(source,a);d.registrySelection={style:'blueprint',font:'gothic_black',lyricsKey:J.registrySelectionLyricsKey(initial),backgroundKey:J.registrySelectionBackgroundKey(source),virtualShots:J.virtualShotCandidates(bg),entries:Object.fromEntries(initial.cuts.filter(c=>c.line>=0).map(c=>[c.line,{layout:'photoStatement',params:{font:'gothic_black',displayText:c.lineText},enter:'cut',hold:'still',inDur:0}]))};source.artDirection=J.makeArtDirection(source,a,d);const p=J.plan(source,a);
assert(p.cuts.filter(c=>c.grammar).every(c=>!c.grammar.foregroundLayers||c.grammar.safeDerived));const la=Array.from(p.cuts.filter(c=>c.story?.group==='la'),c=>c.grammar.mode),oh=Array.from(p.cuts.filter(c=>c.story?.group==='oh'),c=>c.grammar.mode);assert.notDeepEqual(la,oh,'second chant group must not replay first arc');
const R=new J.Renderer(),cv=createCanvas(320,180),x=cv.getContext('2d');await R.loadCustomBackground(source.customBg.dataUrl);const render=plan=>{R.frame(x,plan,9,{scale:320/plan.W,production:true});return Buffer.from(x.getImageData(0,0,320,180).data);},baseline=render(p),neutral=J.clonePhotoRenderPlan(p);neutral.cuts.forEach(c=>c.decor=[]);assert(!baseline.equals(render(neutral)),'style cue must exist in production pixels and disappear when decoration is ablated');assert(baseline.equals(render(p)),'seeking remains deterministic');
const trial=J.measurePhotoStyleTrial(R,x,p);assert(trial.passed,'selected blueprint must survive actual font/decor/accent comparison: '+JSON.stringify({trial,signature:J.styleSignature('blueprint'),font:p.cuts[0].params.font,audit:J.auditDirectionReality(p,{completed:true,metrics:{styleCues:trial.styleCues}})}));assert(trial.styleCues.decor>.0001);const neutralTrial=J.measurePhotoStyleTrial(R,x,neutral);assert(!neutralTrial.passed,'missing style geometry must fail shortlist eligibility');
const masked=createCanvas(320,180);J.paintCinemaGrammarForeground(masked.getContext('2d'),p,p.cuts.find(c=>c.grammar),9,J.segmentCinemaArtwork(bg),[]);assert(masked.getContext('2d').getImageData(0,0,320,180).data.every(v=>v===0),'no regional bitmap fragment path');
const ev=await J.measureCinemaSequence(p);assert.equal(ev.templateAudit.repeats,0);const bad=J.clonePhotoRenderPlan(p),groups=bad.cuts.filter(c=>c.story?.group==='oh');groups.forEach((c,i)=>c.grammar.mode=la[i]);const badEv=await J.measureCinemaSequence(bad);assert.equal(badEv.templateAudit.repeats,1,'detect replay even when shot IDs differ');bad.lastPixelQA={metrics:{cinemaFeedback:badEv}};const repeated=J.checkMVQuality(source,bad,a,null,null,null,null);assert(repeated.errors.some(e=>e.code==='REPEATED_SHOT_SEQUENCE'),'measured replay must reach the quality hard gate');
assert.equal((await J.measureDisplayOnsets(p)).score,100);const without=J.checkMVQuality(source,p,a,null,null,null,null);assert(without.errors.some(e=>e.code==='STYLE_NOT_PIXEL_VERIFIED'));assert(!without.quality.certified100);R.disposeAssets();console.log('No source scraps; aligned blueprint contour/grid counterfactual; distinct repeat arcs and repeated-sequence detection; complete LRC onsets; unmeasured style cannot certify PASS');})().catch(e=>{console.error(e);process.exitCode=1;});
