'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{engine}=require('./custom_test_support.cjs');
(async()=>{
 const {J,createCanvas}=engine();J.enableSingleBackgroundMode();
 const lyrics='[00:02.879]今ここに集いし\n[00:05.049]青と黒の戦士たち\n[00:07.858]我らの誇りと共に輝き\n[00:10.758]荒れ狂い暴れまわる\n[00:13.788]戦士たちよ俺らの\n[00:16.519]声が聞こえるだろ\n[00:19.570]俺らはいつものように\n[00:22.459]今日もここにいるぜ\n[00:25.632]ラララーラララーララララー\n[00:28.479]ラララーラララーラララー\n[00:31.382]ラララーラララーララララー\n[00:34.450]ラララーラララーラララー\n[00:37.369]オオオーオオオーオオオオ\n[00:40.220]オオオーオオオーオオオ\n[00:43.090]オオオーオオオーオオオオ\n[00:46.022]オオオーオオオーオオオ';
 const cv=createCanvas(640,640),cx=cv.getContext('2d');cx.fillStyle='#071326';cx.fillRect(0,0,640,640);const grad=cx.createLinearGradient(0,0,640,640);grad.addColorStop(0,'#175da2');grad.addColorStop(1,'#020911');cx.fillStyle=grad;cx.fillRect(0,0,640,640);cx.fillStyle='#7592b1';cx.fillRect(170,130,90,370);cx.fillRect(420,90,80,450);
 const dir=process.env.KAMEN_REVIEW_ASSETS,context=dir?JSON.parse(fs.readFileSync(path.join(dir,'DIRECTOR_CONTEXT.json'))):null,p=J.defaultProject();Object.assign(p,{autoDirection:true,res:720,fps:30,title:'俺らにできること',artist:'@Arijigoku_GMB',lyrics:dir?fs.readFileSync(path.join(dir,'lyrics.lrc'),'utf8'):lyrics});p.customBg={...p.customBg,enabled:true,dataUrl:dir?'data:image/png;base64,'+fs.readFileSync(path.join(dir,'assets/background.png')).toString('base64'):cv.toDataURL()};
 const audio={duration:context?.duration||48.892,beats:context?.beats||Array.from({length:90},(_,i)=>i*.55),features:context?.audioFeatures||{energy:.78,bpm:110,onsetDensity:.7,beatStrength:.8,percussive:.8,smoothness:.2,brightness:.5,bass:.65,sectionContrast:.6}},source=JSON.stringify(p);
 if(dir&&fs.existsSync(path.join(dir,'audio.f32'))){const bytes=fs.readFileSync(path.join(dir,'audio.f32')),pcm=new Float32Array(bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.length));audio.buffer={length:pcm.length,duration:audio.duration,sampleRate:48000,numberOfChannels:1,getChannelData:()=>pcm};}
 const r=await J.compareRegistryCandidates(p,audio,context?.imageFeatures||{}, {ensureFonts:false}),plan=r.recommended.plan;
 assert.equal(JSON.stringify(p),source,'source project unchanged');assert.equal(plan.lines.length,16);assert.equal(plan.musicalPhoto.story.search.candidateCount,6);assert.equal(plan.musicalPhoto.story.search.fullEvaluationCount,2);assert(plan.visualWorld.chapters.length>=5&&plan.visualWorld.chapters.length<=8);
 assert.equal(J.composeLyricPhrase('今日もここにいるぜ'),'今日も\nここにいるぜ');assert.equal(J.vocaliseGroup('ラララーラララーラララー'),J.vocaliseGroup('ラララーラララーララララー'));
 for(const group of ['la','oh'])assert.deepEqual(Array.from(plan.musicalPhoto.story.narrative.filter(n=>n.group===group),n=>n.recipe),['unity','expansion','crowd','release']);
 const holds=plan.cuts.filter(c=>c.line>=0).map(c=>c.hold);for(let i=2;i<holds.length;i++)assert(!(holds[i]===holds[i-1]&&holds[i]===holds[i-2]),'no 3 identical holds');assert(new Set(holds).size>=2);assert(J.creditStateAt(plan,12).hidden);assert(!J.creditStateAt(plan,1).hidden);assert(J.creditStateAt(plan,plan.duration-.2).hidden,'final lyric and opening title must not overlap');
 const onset=plan.lastPixelQA.metrics.displayOnsetAccuracy;assert.equal(onset.score,100,JSON.stringify(onset.samples.filter(s=>!s.pass)));assert.equal(onset.samples.length,16);
 const delayed=J.clonePhotoRenderPlan(plan);for(const c of delayed.cuts)if(c.line===4){c.start+=.3;c.dur=c.end-c.start;}const bad=await J.measureDisplayOnsets(delayed,null);assert(bad.score<100,'delayed lyrics must fail actual display onset');
 await J.preparePhotoExport({plan,project:r.recommended.project,audio,range:null});assert(plan.musicalPhoto.preparation.attempts.length<=4,'bounded repair before a single encode');
 const report=J.checkMVQuality(r.recommended.project,plan,audio,null,plan.lastPixelQA,{h264:true,aac:true,webCodecs:true},null);assert.equal(report.quality.productionDomains.displayOnsetAccuracy,100);assert.equal(report.quality.productionDomains.lyricSync,undefined);assert.equal(report.quality.syncEvidence.perceptualSingingSync,'UNMEASURED');if(!report.quality.targetAcceptance.minimumMet){assert.equal(report.quality.qualification,'QUALITY_UNMET');assert(!report.quality.certified100);}
 const R=new J.Renderer(),can=createCanvas(480,270);await R.loadCustomBackground(p.customBg.dataUrl);await R.loadAssetDeck(plan);const shots=[];for(const t of [1,8,20,26.2,29.1,32,35,38,41,44,47]){R.frame(can.getContext('2d'),plan,t,{scale:480/plan.W,production:true});shots.push(Buffer.from(can.getContext('2d').getImageData(0,0,480,270).data));}assert(new Set(shots.map(b=>b.toString('base64'))).size===shots.length);
 const end=J.cameraAt(plan,plan.duration-.001),begin=J.cameraAt(plan,0);assert(Math.abs(end.s-begin.s)<.002);assert(Math.abs(end.x-begin.x)<1);
 const output=process.env.KAMEN_REVIEW_OUTPUT;if(output){fs.mkdirSync(output,{recursive:true});fs.writeFileSync(path.join(output,'project.json'),JSON.stringify(r.recommended.project));fs.writeFileSync(path.join(output,'quality.json'),JSON.stringify({quality:report.quality,issues:report.issues,story:plan.musicalPhoto.story,holds,onset},null,2));const sheet=createCanvas(480*3,270*4),x=sheet.getContext('2d');for(let i=0;i<shots.length;i++){const img=can.getContext('2d').createImageData(480,270);img.data.set(shots[i]);x.putImageData(img,(i%3)*480,Math.floor(i/3)*270);}fs.writeFileSync(path.join(output,'storyboard.png'),sheet.toBuffer('image/png'));}
 R.disposeAssets();console.log(JSON.stringify({storyStages:8,chapters:plan.visualWorld.chapters.length,holds,onset:onset.score,style:plan.styleKey,creative:report.quality.creativeScore,qualification:report.quality.qualification,failures:report.quality.targetAcceptance.failures.map(f=>f.key)}));
 console.log('6 real-render candidates, grouped chant development, display onset vs impact, delayed cue rejection, camera loop, source preservation and truthful quality gate PASS');
})().catch(e=>{console.error(e);process.exitCode=1;});
