'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{engine}=require('./custom_test_support.cjs');
const {J,createCanvas,context}=engine();context.Path2D=require('@napi-rs/canvas').Path2D;
(async()=>{
 J.enableSingleBackgroundMode();const dir=process.argv[2],out=process.argv[3],p=J.defaultProject();let image={},audio={duration:24,beats:[2,5,8,11,14,17,20],features:{energy:.7}};
 if(dir){const c=JSON.parse(fs.readFileSync(path.join(dir,'DIRECTOR_CONTEXT.json')));Object.assign(p,{title:'闘い極めろ',artist:'@Arijigoku_GMB',lyrics:fs.readFileSync(path.join(dir,'lyrics.lrc'),'utf8'),res:720,fps:30});p.customBg={...p.customBg,enabled:true,dataUrl:'data:image/webp;base64,'+fs.readFileSync(path.join(dir,'background.webp')).toString('base64')};if(c.registrySelection?.backgroundKey){const key=c.registrySelection.backgroundKey;const saved=JSON.parse(key.slice(key.indexOf('{')));for(const field of ['enabled','filename','fit','x','y','zoom','darkness','blur'])if(saved[field]!==undefined)p.customBg[field]=saved[field];}
 p.visualAssets=c.assets.map(a=>({...a,dataUrl:p.customBg.dataUrl}));audio={duration:c.duration,beats:c.beats,features:c.audioFeatures};image=c.imageFeatures;
 }else{const cv=createCanvas(640,360),x=cv.getContext('2d');x.fillStyle='#153249';x.fillRect(0,0,640,360);Object.assign(p,{lyrics:'[00:02.00]歌声を遠くへ届けよう\n[00:05.00]オー We are ガンバ\n[00:08.00]青黒\n[00:11.00]歌声を遠くへ届けよう\n[00:14.00]オー We are ガンバ\n[00:17.00]青黒',res:720,autoDirection:true});p.customBg={...p.customBg,enabled:true,dataUrl:cv.toDataURL()};}
 const events=[],original=JSON.stringify(p),result=await J.optimizeDirectionCandidatesRendered(p,audio,image,1,{ensureFonts:false,onProgress:e=>events.push(e)}),s=result.recommended.selection;
 assert.equal(JSON.stringify(p),original);assert.equal(events.at(-1).current,events.at(-1).total);assert(events.slice(0,-1).every(e=>e.current<e.total),'progress must not finish before selection');assert.equal(result.candidates.length,1);assert.equal(s.styleComparisons.length,J.STYLE_ORDER.length);assert.equal(s.fontComparisons.length,Object.keys(J.FONTS).length);assert(s.fontComparisons.every(f=>f.loading.status==='NATIVE_FONT_NOT_BROWSER_VERIFIED'));assert(s.motionComparisons.filter(m=>m.group==='hold').every(m=>m.contribution===undefined||m.contribution>=0));assert(result.recommended.plan.styleArc.segments.every(seg=>seg.style===s.style),'unmeasured legacy styles must not replace selected identity');assert.equal(s.layoutComparisons.length,Object.keys(J.LAYOUTS).length);for(const [group,reg]of Object.entries(s.catalog))assert.equal(reg.length,Object.keys(group==='style'?J.STYLES:J.registry(group)).length);
 assert(Object.keys(s.entries).length>0);assert(new Set(Object.values(s.entries).map(e=>e.family)).size>=3,'multiple readable composition families');
 for(const e of Object.values(s.entries)){assert(e.evidence.eligible);assert(e.evidence.contrast.control?.includes('COMPOSITE_BEFORE_FIRST_PRIMARY_GLYPH'));assert(e.evidence.geometry.every(g=>g.readable));assert(s.motionComparisons.find(m=>m.group==='enter'&&m.id===e.enter)?.eligible);}
 // UI keeps only the proposal and rebuilds its project. Selection must survive.
 const q={...p,autoDirection:true,...Object.fromEntries(['style','mood','fx','enabled','seed','overrides'].map(k=>[k,result.recommended.proposal[k]]))};q.artDirection=J.makeArtDirection(q,audio,result.recommended.proposal);assert.deepEqual(q.artDirection.registrySelection.entries,s.entries);
 const preflight=J.preflightMV(q,audio);assert(q.artDirection.registrySelection,'UI preflight must retain measured selection');assert.equal(q.style,s.style);assert(preflight.plan.cuts.filter(c=>c.line>=0).every(c=>c.registrySelected));const retained=JSON.stringify(q.artDirection.registrySelection);J.fixMVQuality(q,{issues:[{code:'dna_mismatch',severity:'WARNING',fixable:true},{code:'direction_realization',severity:'WARNING',fixable:true}]},audio);assert.equal(JSON.stringify(q.artDirection.registrySelection),retained);
 let samples=0;for(const aspect of ['16:9','9:16','1:1','4:5']){const plan=J.plan({...q,aspect},audio),r=new J.Renderer(),can=createCanvas(480,Math.round(480*plan.H/plan.W)),mask=createCanvas(can.width,can.height);await r.loadCustomBackground(q.customBg.dataUrl);await r.loadAssetDeck(plan);const capture=J.drawItem;let evidence=[];J.drawItem=(env,it)=>{if(env.pass==='main'&&env.ctx===can.getContext('2d')&&it.text)evidence.push(J.selectionGlyphEvidence(env,it));return capture(env,it);};
 try{for(const c of plan.cuts.filter(c=>c.line>=0)){assert(c.registrySelected,JSON.stringify({aspect,line:c.line,key:plan.styleKey,style:s.style,lyrics:s.lyricsKey,computed:J.registrySelectionBackgroundKey(plan),stored:s.backgroundKey,hasSelection:!!plan.artDirection?.registrySelection,locked:J.photoChoreographyLocked(plan,c),planLyrics:plan.lines.map(l=>l.text).join("|"),bg:{...plan.customBg,dataUrl:undefined}}));for(const dt of [.03,.16,Math.min(.6,c.dur*.5)]){evidence=[];const items=[];r.frame(can.getContext('2d'),plan,c.start+dt,{scale:480/plan.W,production:true,lyricAuditCtx:mask.getContext('2d'),lyricAuditItems:items});assert(evidence.length&&evidence.every(g=>g.readable),`${aspect} line ${c.line} ${c.layout}/${c.enter}/${c.inDur} dt ${dt}: `+JSON.stringify(evidence));for(const {bounds:b}of items){assert(b.x0>=plan.W*.105&&b.x1<=plan.W*.895,'anchor must preserve horizontal safe area');assert(b.y0>=plan.H*.075&&b.y1<=plan.H*.925,'anchor must preserve vertical safe area');const anchor=c.params.photoAnchor||{x:.5,y:.5},half=(b.y1-b.y0)/2/plan.H,target=Math.max(.08+half,Math.min(.92-half,anchor.y));assert(Math.abs((b.y0+b.y1)/2/plan.H-target)<.01,'glyphs must follow the selected anchor within safe bounds');}samples++;}}
 if(out&&aspect==='16:9'){const contact=createCanvas(1440,540),cc=contact.getContext('2d');for(const [i,t]of [15,18,21.5,28.8,35.5,40].entries()){r.frame(can.getContext('2d'),plan,t,{scale:480/plan.W,production:true});cc.drawImage(can,i%3*480,Math.floor(i/3)*270);cc.fillStyle='#fff';cc.font='16px sans-serif';cc.fillText(t+'s',i%3*480+8,Math.floor(i/3)*270+20);}fs.writeFileSync(path.join(out,'selection-contact.png'),contact.toBuffer('image/png'));}
 }finally{J.drawItem=capture;r.disposeAssets();}}
 const shifted={...q,lyrics:q.lyrics.replace('[00:02.00]','[00:02.25]').replace('[00:14.289]','[00:14.300]')};if(shifted.lyrics!==q.lyrics)assert(J.plan(shifted,audio).cuts.filter(c=>c.line>=0).every(c=>!c.registrySelected));const spaced={...q,lyrics:q.lyrics.replace('We are','We  are')};assert(J.plan(spaced,audio).cuts.filter(c=>c.line>=0).every(c=>!c.registrySelected));
 const hooks=J.socialHookCandidates(result.recommended.plan,audio),social=J.createSocialHookPlan(J.plan(q,audio),hooks[0]);assert(social.cuts.filter(c=>c.line>=0).every(c=>c.registrySelected),'same measured selection survives short re-edit');
 const altered={...q,customBg:{...q.customBg,zoom:1.17}};assert.notEqual(J.registrySelectionBackgroundKey(altered),s.backgroundKey);assert(J.plan(altered,audio).cuts.filter(c=>c.line>=0).every(c=>!c.registrySelected));assert(J.plan({...q,lyrics:q.lyrics+'\n[00:22.00]変更'},audio).cuts.filter(c=>c.line>=0).every(c=>!c.registrySelected));
 const report={status:'PASS',styles:s.styleComparisons.length,methods:Object.values(s.catalog).reduce((n,a)=>n+a.length,0),framesCompared:s.framesCompared,aspectSamples:samples,choices:Object.values(s.entries).map(e=>({layout:e.layout,family:e.family,enter:e.enter}))};
 if(out){fs.writeFileSync(path.join(out,'selection.json'),JSON.stringify(s,null,2));fs.writeFileSync(path.join(out,'selected-project.json'),JSON.stringify(q));fs.writeFileSync(path.join(out,'selection-test.json'),JSON.stringify(report,null,2));}console.log(JSON.stringify(report));
})().catch(e=>{console.error(e);process.exitCode=1;});
