'use strict';const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const source=fs.readFileSync(require('node:path').join(__dirname,'../src/12_ui.js'),'utf8'),start=source.indexOf('async function runExport('),end=source.indexOf('/* ---------------- tap sync',start),nodes=new Map(),S={project:{revision:0,includeAudio:true},audio:{},plan:{revision:0},exportValidation:{width:999,container:'stale'}},checks=[],audits=[],encodings=[],saves=[];let failed=0,completed=0;
const noop=()=>{},task={state:{stages:[]},enter:noop,skip:noop,observe:noop,update:noop,fail:()=>failed++,complete:()=>completed++},J={prepareFileSave:async()=>null,resolveExportSettings:()=>({range:'full'}),processing:{begin:()=>task},preflightMV:(p,a,r,make)=>({fixes:0,plan:make()}),plan:p=>({revision:p.revision,fps:30}),exportCapabilities:async()=>({h264:true,aac:true,webCodecs:true}),analyzeRenderedFrames:async p=>{audits.push(p.revision);return {completed:true,revision:p.revision}},checkMVQuality:(p,plan,a,r,pixel,caps,validation)=>{checks.push({revision:plan.revision,pixel:pixel.revision,validation});return {ready:true,errors:[],quality:{targetAcceptance:{minimumMet:true}}}},preparePhotoExport:async()=>{},fixMVQuality:p=>{p.revision++;return 1},processingYield:async()=>{},ensureFonts:async()=>{},fontsOfPlan:()=>[],exportMP4:async args=>{encodings.push(args);return {blob:new Blob(['mp4']),sidecar:new Blob([JSON.stringify({videoSHA256:'fixture',creativeFindings:[{code:'BELOW_TARGET'}]})]),codec:'avc1',audio:'aac',provenance:{qualityTarget:{minimumMet:true}},validation:{certification:{passed:true},videoCodec:'avc1',audioCodec:'mp4a',duration:1}}},saveFile:async name=>{saves.push(name);if(name.endsWith('.json'))throw Error('QA destination unavailable');return 'saved'}};
const c=vm.createContext({J,S,exportPreflightBusy:false,pause:noop,exportRangeForSettings:()=>({start:0,end:1}),baseName:()=> 'test',audioLike:()=>S.audio,syncDirectionUI:noop,syncUI:noop,replan:()=>{S.plan=J.plan(S.project)},showMsg:noop,updateStudioQuality:noop,codecNote:noop,HUD_CHARS:'',EXP_BTNS:[],navigator:{},performance,AbortController,Blob,console:{error:noop,warn:noop},toast:noop,document:{getElementById:id=>nodes.get(id),createElement:()=>({remove(){nodes.delete(this.id)}})},$:id=>{if(!nodes.has(id))nodes.set(id,{textContent:'',disabled:false,hidden:true,after(node){nodes.set(node.id,node)}});return nodes.get(id)}});const policy=fs.readFileSync(require('node:path').join(__dirname,'../src/11zzd_export_policy.js'),'utf8');vm.runInContext(policy.slice(policy.indexOf('J.creativeExportState='),policy.indexOf('const provenance=')),c);vm.runInContext(source.slice(start,end),c);
(async()=>{await c.runExport('mp4');assert.equal(encodings.length,1);assert.equal(encodings[0].plan.revision,3,'last repair must reach encoder');assert.equal(S.plan.revision,3);assert.equal(audits.at(-1),3,'last repair must be inspected');assert(checks.every(x=>x.validation===null),'old file validation must not enter preflight');assert(checks.every(x=>x.pixel===x.revision),'audit and exported plan must match');assert.equal(saves.filter(x=>x==='test.mp4').length,1);assert.equal(failed,0,'QA save failure must not mark successful MP4 failed');assert.equal(completed,1);assert.equal(S.exportValidation.container,undefined,'stale validation replaced');assert.equal(c.exportPreflightBusy,false);assert.equal(S.exporting,null);let before=encodings.length;
const result=J.exportMP4;
for(const [state,acceptance] of [['TARGET_MET',{minimumMet:true}],['BELOW_TARGET',{minimumMet:false,hardFailures:['BROKEN_VISUAL_WORLD'],failures:[{key:'perceptualNovelty',score:24,minimum:80}]}],['UNMEASURED',{minimumMet:false,failures:[{score:null,minimum:80}]}]]){
 J.checkMVQuality=()=>({ready:true,errors:[],quality:{targetAcceptance:acceptance}});
 J.exportMP4=async args=>{const r=await result(args);r.provenance.machineRefinement={acceptance};return r;};
 await c.runExport('mp4');assert.equal(encodings.length,++before,'one call without Draft approval');assert.equal(S.exportOutcome.fileState,'SAVED');assert.equal(S.exportOutcome.creativeState,state);assert(!nodes.has('qualityDraftExport'));assert.equal(failed,0,'creative deficits never fail a valid MP4');
}
J.exportMP4=async()=>{throw Error('EXPORT_INVALID broken MP4')};await c.runExport('mp4');assert.equal(S.exportOutcome.fileState,'FAILED_TECHNICAL');assert.equal(failed,1);assert.equal(encodings.length,before);
J.prepareFileSave=async()=> 'declined';await c.runExport('mp4');assert.equal(S.exportOutcome.fileState,'CANCELLED');assert.equal(encodings.length,before);
J.prepareFileSave=async()=>null;J.checkMVQuality=()=>({ready:false,exportErrors:[{message:'missing lyrics'}],quality:{targetAcceptance:{minimumMet:true}}});await c.runExport('mp4');assert.equal(S.exportOutcome.fileState,'FAILED_TECHNICAL');assert.equal(encodings.length,before);
c.exportPreflightBusy=true;await c.runExport('mp4');assert.equal(encodings.length,before,'preflight double click is ignored');c.exportPreflightBusy=false;
assert.equal(J.creativeExportState({minimumMet:false,failures:[{score:0}]}),'BELOW_TARGET');assert.equal(J.creativeExportState({minimumMet:false,failures:[{score:null}]}),'UNMEASURED');assert.equal(J.creativeExportState({status:'NOT_APPLICABLE'}),'NOT_APPLICABLE');
J.checkMVQuality=()=>({ready:true,errors:[],quality:{targetAcceptance:{minimumMet:true}}});J.fixMVQuality=()=>0;J.exportMP4=result;J.canonicalJSON=JSON.stringify;
let planned=0;const plan=J.plan;J.plan=(...args)=>{planned++;return plan(...args)};
J.cinemaV3={enabled:true,snapshot:async(p,a)=>({inputHash:JSON.stringify({project:p,pcm:a.pcm})}),planHash:async p=>JSON.stringify(p)};
const confirm=async()=>{S.confirmedCinemaPlan={plan:S.plan,inputHash:(await J.cinemaV3.snapshot(S.project,S.audio)).inputHash,analysisKey:JSON.stringify(S.audio),planHash:await J.cinemaV3.planHash(S.plan)}};
await confirm();let count=planned;await c.runExport('mp4');assert.equal(planned,count,'unchanged confirmed plan is not regenerated');assert.equal(S.exportOutcome.initialConfirmedPlanReused,true);
for(const mutation of [()=>{S.project.revision++},()=>{S.audio.pcm='changed'},()=>{S.audio.analysis='changed'},()=>{S.plan.revision++}]){await confirm();count=planned;mutation();await c.runExport('mp4');assert(planned>count);assert.equal(S.exportOutcome.initialConfirmedPlanReused,false,'changed input/PCM/analysis/plan must replan');}
console.log('UI runtime: final repair/audit, one-click states, technical rejection, cancel, QA-save protection and exact confirmed plan invalidation PASS');})().catch(e=>{console.error(e);process.exitCode=1});
