'use strict';
const assert=require('node:assert/strict'),{engine}=require('./custom_test_support.cjs');
(async()=>{const {J,createCanvas}=engine();J.enableSingleBackgroundMode();const bg=createCanvas(480,320),x=bg.getContext('2d');x.fillStyle='#081025';x.fillRect(0,0,480,320);for(let i=0;i<5;i++){x.fillStyle=i%2?'#e5cda4':'#2767b5';x.fillRect(35+i*85,40+(i%2)*70,60,150);x.fillStyle='#111';x.fillRect(35+i*85,90+(i%2)*70,30,20);}
 const segmented=J.segmentCinemaArtwork(bg);assert(segmented.regions.length>=2);assert(segmented.evidence.coverage>0);assert.equal(segmented.evidence.recognizedObjects,false);assert.equal(segmented.evidence.learnedDepth,false);assert.equal(J.segmentCinemaArtwork(bg),segmented,'cache by actual bitmap');
 const flat=createCanvas(200,200);flat.getContext('2d').fillStyle='#111';flat.getContext('2d').fillRect(0,0,200,200);assert.equal(J.segmentCinemaArtwork(flat).regions.length,0,'uniform image must not fabricate foreground');
 const project=J.defaultProject();Object.assign(project,{autoDirection:true,res:720,fps:30,lyrics:'[00:01.00]今ここに集いし\n[00:04.00]我らの誇りと共に輝き\n[00:07.00]荒れ狂い暴れまわる\n[00:10.00]声が聞こえるだろ\n[00:13.00]今日もここにいるぜ\n[00:16.00]ラララーラララー\n[00:19.00]ラララーラララー\n[00:22.00]ラララーラララー\n[00:25.00]ラララーラララー\n[00:28.00]オオオーオオオー\n[00:31.00]オオオーオオオー\n[00:34.00]オオオーオオオー\n[00:37.00]オオオーオオオー'});project.customBg={...project.customBg,enabled:true,dataUrl:bg.toDataURL()};const audio={duration:40,beats:Array.from({length:108},(_,i)=>i*.372),features:{energy:.8,bpm:161,beatStrength:.8}};
 const direction=J.proposeDirection(project,audio,{});Object.assign(project,{style:direction.style,mood:direction.mood,fx:direction.fx,enabled:direction.enabled,seed:direction.seed});project.artDirection=J.makeArtDirection(project,audio,direction);const base=J.plan(project,audio);direction.registrySelection={style:project.style,font:'embedded_bold',lyricsKey:J.registrySelectionLyricsKey(base),backgroundKey:J.registrySelectionBackgroundKey(project),virtualShots:J.virtualShotCandidates(bg),entries:Object.fromEntries(base.cuts.filter(c=>c.line>=0).map(c=>[c.line,{layout:'photoStatement',params:{font:'embedded_bold',displayText:c.lineText},enter:'cut',hold:'still',inDur:0}]))};project.artDirection=J.makeArtDirection(project,audio,direction);const p=J.plan(project,audio);
 const chant=p.cuts.filter(c=>c.story?.group==='la');assert.equal(chant.length,4);for(let i=1;i<chant.length;i++)for(const k of ['occupancy','echoLayers','speed','contrast'])assert(chant[i].cinema.development[k]>chant[i-1].cinema.development[k],k+' must escalate');
 const r=segmented.regions[0],gather=p.cuts.find(c=>c.cinema?.meaning==='gather'),rage=p.cuts.find(c=>c.cinema?.meaning==='rage'),unity=p.cuts.find(c=>c.cinema?.meaning==='unity');assert.notDeepEqual(J.cinemaLayerMotion(p,gather,gather.start+.1,r),J.cinemaLayerMotion(p,rage,rage.start+.1,r));assert.equal(J.cinemaLayerMotion(p,unity,unity.start+.3,r).dx,0);
 const evidence=await J.measureArtworkForeground(p);assert(evidence.regionCount>=2);assert.equal(evidence.usedRegionCount,0,'unverified regional copies must be suppressed in production');assert(evidence.samples.some(s=>s.changedArea>0),'authored geometry must be observed');assert(evidence.usedDerivedLayerCount>0);assert.equal(evidence.score,null,'counterfactual visibility cannot certify art');assert(evidence.nonCropStructure.changes.length);
 const R=new J.Renderer(),cv=createCanvas(320,180),cx=cv.getContext('2d');await R.loadCustomBackground(project.customBg.dataUrl);const render=t=>{R.frame(cx,p,t,{scale:320/p.W,production:true});return Buffer.from(cx.getImageData(0,0,320,180).data);};assert(!render(39.96666667).equals(render(0)),'last lyric must remain instead of crossfading the title');assert(J.creditStateAt(p,39.96666667).hidden);assert(render(23).equals(render(23)),'seek deterministic');
 const q=J.checkMVQuality(project,p,audio,null,null,null,null).quality;assert(q.overallScore<=89);assert.equal(q.certified100,false);assert(q.cinemaScorePolicy.unmeasured.includes('semanticDirection'));assert.equal(q.artistic100Established,false);
 const manual=J.plan({...project,overrides:{2:{layout:'photoStatement',enter:'pop',hold:'still',cam:'panL'}}},audio);assert(!manual.cuts.find(c=>c.line===2).cinema);R.disposeAssets();console.log('Regional masks, uniform fallback, actual counterfactual foreground, semantic physics, four-axis escalation, honest certification and loop PASS');})().catch(e=>{console.error(e);process.exitCode=1;});
