'use strict';const assert=require('node:assert/strict'),{engine}=require('./custom_test_support.cjs');
(async()=>{
 const {J,createCanvas}=engine();J.enableSingleBackgroundMode();const cv=createCanvas(640,360),x=cv.getContext('2d');x.fillStyle='#193c60';x.fillRect(0,0,640,360);x.fillStyle='#628eb3';x.fillRect(410,35,160,280);
 const p=J.defaultProject();Object.assign(p,{autoDirection:true,res:720,lyrics:'[00:02]歌声を遠くへ届けよう\n[00:05]青と黒の戦士たち\n[00:08]青黒\n[00:11]歌声を遠くへ届けよう\n[00:14]青と黒の戦士たち\n[00:17]青黒'});p.customBg={...p.customBg,enabled:true,dataUrl:cv.toDataURL()};
 const fixtures=[['acoustic',{energy:.25,bpm:74,onsetDensity:.08,beatStrength:.15,percussive:.08,smoothness:.95,brightness:.7,bass:.15,sectionContrast:.2}],['percussion',{energy:.82,bpm:150,onsetDensity:.9,beatStrength:.95,percussive:.98,smoothness:.08,brightness:.7,bass:.6,sectionContrast:.5}],['rock',{energy:.95,bpm:138,onsetDensity:.7,beatStrength:.9,percussive:.4,smoothness:.3,brightness:.9,bass:.8,sectionContrast:.95}],['ambient',{energy:.12,bpm:65,onsetDensity:.03,beatStrength:.02,percussive:.01,smoothness:.95,brightness:.05,bass:.15,sectionContrast:.1}]],results=[];
 for(const [name,features]of fixtures){const a={duration:22,bpm:features.bpm,beats:Array.from({length:22},(_,i)=>i+.1),features},r=await J.compareRegistryCandidates(p,a,{}, {ensureFonts:false}),q=r.recommended.project,plan=r.recommended.plan,selection=r.recommended.selection;
  assert.equal(selection.audioKey,J.registrySelectionAudioKey(a));assert.equal(selection.musicProfile.mode,J.songDirectionProfile(a).mode);
  for(const c of plan.cuts.filter(c=>c.line>=0)){const e=selection.entries[c.line];assert(c.registrySelected);assert.equal(c.enter,e.enter,'selected entrance survives later planning');assert.equal(c.hold,e.hold,'selected hold survives later planning');assert.equal(c.lineText,plan.lines[c.line].text);}
  const renderer=new J.Renderer(),can=createCanvas(320,180);await renderer.loadCustomBackground(p.customBg.dataUrl);await renderer.loadAssetDeck(plan);for(const t of [2.1,8.5,14.7])renderer.frame(can.getContext('2d'),plan,t,{scale:320/plan.W,production:true});renderer.disposeAssets();
  for(const section of plan.musicalStructure.sections.filter(s=>s.from>3)){const left=J.cameraAt(plan,section.from-.001),right=J.cameraAt(plan,section.from);assert(Math.abs(left.s-right.s)<.02,JSON.stringify({section,left,right,cut:J.cutAt(plan,section.from)}));assert(Math.abs(left.x-right.x)/plan.W<.02);}
  const signature=JSON.stringify([selection.style,Object.values(selection.entries).map(e=>[e.layout,e.enter,e.hold]),plan.musicalPhoto.songProfile.mode]);results.push({name,mode:selection.musicProfile.mode,style:selection.style,signature,camera:J.cameraAt(plan,12.5)});console.log(name,selection.style,selection.musicProfile.mode,Object.values(selection.entries).map(e=>e.layout+'/'+e.hold).join(' '));
  const wrong={...a,features:{...a.features,percussive:1-a.features.percussive}};assert(J.plan(q,wrong).cuts.filter(c=>c.line>=0).every(c=>!c.registrySelected),'audio change invalidates measured selections');
 }
 assert.equal(new Set(results.map(r=>r.mode)).size,4);assert(new Set(results.map(r=>r.style)).size>=2,'same image must not dominate styles');assert(new Set(results.map(r=>r.signature)).size>=3,'different timbres must result in different rendered plans');assert(new Set(results.map(r=>JSON.stringify(r.camera))).size>=3,'camera varies by music');
 const a={duration:22,features:fixtures[0][1]},r1=J.proposeDirection(p,a,{}),r2=J.proposeDirection(p,a,{});assert.equal(r1.style,r2.style,'identical input remains deterministic');
 console.log('Same background/lyrics, four music profiles, retained selected motions, stale-audio rejection and repeatability PASS');
})().catch(e=>{console.error(e);process.exitCode=1;});
