'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const root=path.resolve(__dirname,'..');let time=0,nextId=0;const timers=new Map();
const schedule=(fn,delay,interval=0)=>{const id=++nextId;timers.set(id,{fn,at:time+delay,interval});return id;};
function advance(ms){const end=time+ms;for(;;){const item=[...timers].filter(([,v])=>v.at<=end).sort((a,b)=>a[1].at-b[1].at)[0];if(!item)break;const [id,t]=item;time=t.at;if(t.interval)t.at+=t.interval;else timers.delete(id);t.fn();}time=end;}
class Node{constructor(){this.dataset={};this.attrs={};this.children=[];this.map=new Map();this.textContent='';}set innerHTML(v){this.html=v;}get innerHTML(){return this.html;}appendChild(n){this.children.push(n);n.parent=this;}remove(){if(this.parent)this.parent.children=this.parent.children.filter(n=>n!==this);}setAttribute(k,v){this.attrs[k]=v;}removeAttribute(k){delete this.attrs[k];if(k==='value')delete this.value;}querySelector(k){if(!this.map.has(k))this.map.set(k,new Node());return this.map.get(k);}querySelectorAll(k){return k==='li'?this.querySelector('ol').children:[];}}
const host=new Node(),J={};const context=vm.createContext({J,console:{error(){}},performance:{now:()=>time},document:{getElementById:()=>host,createElement:()=>new Node()},setTimeout:(fn,ms)=>schedule(fn,ms),clearTimeout:id=>timers.delete(id),setInterval:(fn,ms)=>schedule(fn,ms,ms),clearInterval:id=>timers.delete(id)});
for(const name of ['01p_processing.js','12a_processing_ui.js'])vm.runInContext(fs.readFileSync(path.join(root,'src',name),'utf8'),context);
const dispose=J.mountProcessingUI();let passed=0;function test(name,fn){fn();passed++;console.log(name+' PASS');}
let main;
test('quiet_autosave_no_success_flash',()=>{const t=J.processing.begin('保存',[['save','素材保存',1]],{compact:true});t.enter('save');advance(500);assert(host.hidden);t.complete();advance(150);assert(host.hidden);assert(!J.processing.jobs.has(t.state.id));});
test('long_autosave_visible_without_fake_progress',()=>{const t=J.processing.begin('保存',[['save','素材保存',1]],{compact:true});t.enter('save');advance(1150);assert(!host.hidden);assert(!('value'in host.children[0].querySelector('.processing-total')));t.complete();advance(150);assert(host.hidden);});
test('compact_single_card_throttled_real_stage_and_frame_count',()=>{main=J.processing.begin('動画を書き出しています',[['prep','準備',1],['frames','フレーム生成',9]]);main.enter('prep');advance(150);const card=host.children[0];assert(!card.innerHTML.includes('processing-basis'));assert(!card.innerHTML.includes('processing-current"><progress'));assert(!('value'in card.querySelector('.processing-total')));main.enter('frames');for(let i=0;i<=50;i++)main.update(i,100,`${i} / 100 フレーム`);advance(150);assert.equal(card.querySelector('.processing-total').value,55);assert.equal(card.querySelector('.processing-current span').textContent,'50 / 100 フレーム');assert.equal(card.querySelector('.processing-percent').textContent,'55%');const secondary=J.processing.begin('保存',[['save','素材保存',1]],{compact:true});secondary.enter('save');advance(1200);assert.equal(host.children.length,1);assert.equal(host.children[0],card);secondary.complete();});
test('success_acknowledgement_then_auto_closes_and_cleans_timer',()=>{main.complete();advance(150);assert.equal(host.children[0].querySelector('.processing-total').value,100);advance(900);assert(!host.hidden);advance(250);assert(host.hidden);assert(!J.processing.jobs.has(main.state.id));assert.equal(timers.size,0);});
test('failure_retains_exact_stage_and_retry_after_success_auto_close',()=>{let retries=0;const failed=J.processing.begin('MV作成',[['scene','シーン構成',1]],{retry:()=>retries++});failed.enter('scene');failed.fail(Error('テスト失敗'));advance(2000);assert(host.children[0].querySelector('.processing-stage').textContent.includes('シーン構成'));const other=J.processing.begin('検証',[['verify','最終検証',1]]);other.enter('verify');advance(150);assert.equal(host.children.length,1);other.complete();advance(1400);assert.equal(host.children[0].dataset.status,'error');host.children[0].querySelector('.processing-retry').onclick();advance(150);assert.equal(retries,1);assert(host.hidden);assert.equal(timers.size,0);});
test('autosave_errors_remain_visible',()=>{const t=J.processing.begin('保存',[['save','素材保存',1]],{compact:true});t.enter('save');t.fail(Error('容量不足'));advance(2000);assert(!host.hidden);assert.equal(host.children[0].dataset.status,'error');t.dismiss();advance(150);assert(host.hidden);});
test('heartbeat_and_dispose_leave_no_ui_timer_or_duplicate_mount',()=>{const t=J.processing.begin('解析',[['audio','音声解析',1]]);t.enter('audio');advance(17000);assert(host.children[0].querySelector('.processing-heartbeat').textContent.includes('続行'));assert(host.children[0].querySelector('.processing-time').textContent.startsWith('経過 '));assert.equal(J.mountProcessingUI(),undefined);dispose();assert(host.hidden);assert.equal(timers.size,0);t.fail(Error('終了'),true);assert.equal(timers.size,0);t.dismiss();});
console.log(`${passed} KAMEN processing regression groups passed`);
