'use strict';
const fs=require('node:fs'),path=require('node:path'),{spawn}=require('node:child_process'),{once}=require('node:events'),{engine}=require('./custom_test_support.cjs');
(async()=>{
 const dir=process.argv[2],{J,createCanvas}=engine(),p=JSON.parse(fs.readFileSync(path.join(dir,'selected-project.json'))),c=JSON.parse(fs.readFileSync(path.join(dir,'DIRECTOR_CONTEXT.json'))),audio={duration:c.duration,beats:c.beats,features:c.audioFeatures};J.enableSingleBackgroundMode();const plan=J.plan(p,audio),R=new J.Renderer(),canvas=createCanvas(1280,720),ctx=canvas.getContext('2d');await R.loadCustomBackground(p.customBg.dataUrl);await R.loadAssetDeck(plan);
 const output=path.join(dir,'native-revised.mp4'),ff=spawn('ffmpeg',['-v','error','-y','-f','rawvideo','-pixel_format','rgba','-video_size','1280x720','-framerate','30','-i','pipe:0','-i',path.join(dir,'audio.m4a'),'-map','0:v','-map','1:a','-c:v','libx264','-preset','fast','-crf','19','-pix_fmt','yuv420p','-c:a','copy','-t',String(audio.duration),'-movflags','+faststart',output],{stdio:['pipe','ignore','pipe']});let errors='';ff.stderr.on('data',d=>errors+=d);const complete=once(ff,'close');
 for(let i=0;i<Math.ceil(audio.duration*30);i++){R.frame(ctx,plan,i/30,{scale:1280/plan.W,production:true});const bytes=Buffer.from(ctx.getImageData(0,0,1280,720).data);if(!ff.stdin.write(bytes))await once(ff.stdin,'drain');if(i%300===0)console.log('Rendered',i,'/',Math.ceil(audio.duration*30));}
 ff.stdin.end();const [code]=await complete;R.disposeAssets();if(code)throw Error(errors);console.log(JSON.stringify({output,frames:Math.ceil(audio.duration*30),method:'Native Canvas reference export; ffmpeg encoding. Browser WebCodecs export untested.'}));
 const observed=await J.collectCanvasObserver(plan,null,{}),world=J.measureWorldDistance7(plan,observed.frames,null),variation=await J.measurePresentationVariation(plan),contrast=await J.measureGlyphContrastEvidence(plan);
 const evidence={method:'Native Canvas renderer; attached feature context and unmodified LRC; not original full manual project',style:plan.styleKey,arc:plan.styleArc,world,variation,contrast,fontAvailability:'UNVERIFIED_IN_BROWSER',artistic100Established:false};fs.writeFileSync(path.join(dir,'revised-evidence.json'),JSON.stringify(evidence,null,2));console.log(JSON.stringify({world:world.score,weakChapters:world.weakChapters.length,changedRepeatedPairs:variation.observedChangedPairs,contrastSamples:contrast.measuredSamples}));
})().catch(e=>{console.error(e);process.exitCode=1;});
