'use strict';const assert=require('node:assert/strict'),{engine}=require('./custom_test_support.cjs');
(async()=>{const {J,createCanvas}=engine();J.enableSingleBackgroundMode();const bg=createCanvas(640,360),bx=bg.getContext('2d');bx.fillStyle='#172740';bx.fillRect(0,0,640,360);for(let i=0;i<7;i++){bx.fillStyle=i%2?'#a3bed5':'#24548f';bx.fillRect(i*90,35+i*16,60,190);}
const source=J.defaultProject();Object.assign(source,{autoDirection:true,res:720,lyrics:'[00:02]遠い空に夢を描こう\n[00:05]仲間と共に集う\n[00:08]声が聞こえるだろ\n[00:11]今日もここにいるぜ\n[00:14]ラララーラララー\n[00:17]ラララーラララー\n[00:20]ラララーラララー\n[00:23]ラララーラララー'});source.customBg={...source.customBg,enabled:true,dataUrl:bg.toDataURL()};
const profiles=[{energy:.25,bpm:74,onsetDensity:.08,beatStrength:.15,percussive:.08,smoothness:.95,brightness:.7},{energy:.82,bpm:150,onsetDensity:.9,beatStrength:.95,percussive:.98,smoothness:.08,brightness:.7},{energy:.95,bpm:138,onsetDensity:.7,beatStrength:.9,percussive:.4,smoothness:.3,brightness:.9,sectionContrast:.95},{energy:.12,bpm:65,onsetDensity:.03,beatStrength:.02,percussive:.01,smoothness:.95,brightness:.05}],plans=[],hashes=[];const crypto=require('node:crypto');
for(const f of profiles){const p=JSON.parse(JSON.stringify(source)),a={duration:27,bpm:f.bpm,features:f,beats:Array.from({length:40},(_,i)=>i*.55)};const d=J.proposeDirection(p,a,{});Object.assign(p,{style:d.style,mood:d.mood,fx:d.fx,enabled:d.enabled,seed:d.seed});p.artDirection=J.makeArtDirection(p,a,d);const initial=J.plan(p,a);d.registrySelection={style:p.style,font:'embedded_bold',lyricsKey:J.registrySelectionLyricsKey(initial),backgroundKey:J.registrySelectionBackgroundKey(p),virtualShots:J.virtualShotCandidates(bg),entries:Object.fromEntries(initial.cuts.filter(c=>c.line>=0).map(c=>[c.line,{layout:'photoStatement',params:{font:'embedded_bold',displayText:c.lineText},enter:'cut',hold:'still',inDur:0}]))};p.artDirection=J.makeArtDirection(p,a,d);const plan=J.plan(p,a);plans.push(plan);const R=new J.Renderer(),cv=createCanvas(256,144);await R.loadCustomBackground(source.customBg.dataUrl);R.frame(cv.getContext('2d'),plan,3,{scale:256/plan.W,production:true});hashes.push(crypto.createHash('sha256').update(cv.toBuffer('image/png')).digest('hex'));R.disposeAssets();assert.equal(J.measureDisplayOnsets?typeof J.measureDisplayOnsets:'','function');}
assert.equal(new Set(plans.map(p=>p.musicalPhoto.songProfile.mode)).size,4);assert.equal(new Set(hashes).size,4,'same artwork and lyric produce different actual pixels with four musical profiles');assert.notDeepEqual(plans[0].cuts.filter(c=>c.grammar).map(c=>c.grammar.mode),plans[1].cuts.filter(c=>c.grammar).map(c=>c.grammar.mode));
const plan=plans[1],before=JSON.stringify(plan.lines),ev=await J.measureCinemaSequence(plan);assert.equal(ev.status,'PRODUCTION_RASTER_SAMPLES');assert(ev.samples.some(s=>s.energy>.003));const fixed=await J.repairCinemaSequence(plan);assert(fixed.rank>=ev.rank);assert.equal(before,JSON.stringify(plan.lines));assert.equal(plan.musicalPhoto.cinema.feedback.scoreThresholdsChanged,false);assert(plan.musicalPhoto.cinema.feedback.attempts.length===32);assert.equal((await J.measureDisplayOnsets(plan)).score,100);
// A frozen production renderer must be measured as frozen, even with different IDs.
const render=J.Renderer.prototype.frame;J.Renderer.prototype.frame=function(ctx,p,t,opt){ctx.save();ctx.setTransform(1,0,0,1,0,0);ctx.fillStyle='#445566';ctx.fillRect(0,0,ctx.canvas.width,ctx.canvas.height);ctx.restore();};try{const flat=await J.measureCinemaSequence(plan);assert(flat.samples.every(s=>s.energy===0));assert(flat.samples.some(s=>s.stagnant));assert(flat.hook.weak);}finally{J.Renderer.prototype.frame=render;}
const auto=JSON.parse(JSON.stringify(source));J.applyExportPreset(auto,'auto');assert.equal(auto.res,1080);assert.equal(J.chooseAdaptiveFPS(auto).fps,30);auto.exportSettings.fpsMode='manual';auto.fps=60;assert.equal(J.chooseAdaptiveFPS(auto).fps,60);
console.log('Four same-source music profiles differ in real pixels; bounded raster repair retains best, preserves LRC onset; frozen renderer detected; 1080p/30 auto and manual 60 preserved PASS');})().catch(e=>{console.error(e);process.exitCode=1;});
