'use strict';const assert=require('node:assert/strict'),{engine}=require('./custom_test_support.cjs');const {J,createCanvas}=engine();
(async()=>{
 const mask=createCanvas(10,10),m=mask.getContext('2d');m.fillRect(2,2,4,4);const a=m.getImageData(0,0,10,10).data;assert.equal(J.comparePresentationMasks(a,a,10,10).rasterDifference,0);assert.equal(J.comparePresentationMasks(a,a,10,10).maskIoU,1);
 J.enableSingleBackgroundMode();const bg=createCanvas(640,360);bg.getContext('2d').fillRect(0,0,640,360);const p=J.defaultProject();Object.assign(p,{res:720,autoDirection:true,lyrics:'[00:02]闘い極めろ男たち\n[00:05]我らの歌声響かせろ\n[00:08]闘い極めろ男たち\n[00:11]我らの歌声響かせろ'});p.customBg={...p.customBg,enabled:true,dataUrl:bg.toDataURL()};const audio={duration:15,beats:[],features:{energy:.5}},proposal=J.proposeDirection(p,audio,{});Object.assign(p,{style:proposal.style,mood:proposal.mood,fx:proposal.fx,enabled:proposal.enabled,seed:proposal.seed});p.artDirection=J.makeArtDirection(p,audio,proposal);const plan=J.plan(p,audio),snapshot=JSON.stringify(plan),r=await J.measurePresentationVariation(plan);
 assert(r.measured);assert.equal(r.measuredPairs,2);assert.equal(r.observedChangedPairs,2);assert(r.pairs.every(x=>x.excessRasterDifference>.1));assert.equal(r.score,null);assert.equal(JSON.stringify(plan),snapshot,'measurement must not edit direction');assert.strictEqual(await J.measurePresentationVariation(plan),r,'cache evidence');
 for(const c of plan.cuts.filter(c=>c.line>=2)){const ref=plan.cuts.find(x=>x.line===c.line-2);c.layout=ref.layout;c.params={...ref.params};c.enter=ref.enter;c.architecture='fake-different-id';}
 const equal=await J.measurePresentationVariation(plan);assert.notStrictEqual(equal,r,'changed presentation invalidates cache');assert.equal(equal.observedChangedPairs,0,'metadata alone must not establish visible variety');
 assert.equal((await J.measurePresentationVariation({...plan,lines:plan.lines.slice(0,2)})).status,'NOT_APPLICABLE_NO_REPEATED_LYRIC');console.log(JSON.stringify({status:'PASS',realChangedPairs:r.observedChangedPairs,metadataOnlyChangedPairs:equal.observedChangedPairs,score:null,bounded:true}));
})().catch(e=>{console.error(e);process.exitCode=1});
