'use strict';
const fs=require('node:fs'),path=require('node:path'),{spawn,spawnSync}=require('node:child_process'),{once}=require('node:events'),{engine}=require('./custom_test_support.cjs');
(async()=>{
 const [dir,out]=process.argv.slice(2),renderFPS=Number(process.env.KAMEN_RENDER_FPS)||30,{J,createCanvas,context}=engine();context.Path2D=require('@napi-rs/canvas').Path2D;J.enableSingleBackgroundMode();
 const c=JSON.parse(fs.readFileSync(path.join(dir,'DIRECTOR_CONTEXT.json'))),p=JSON.parse(fs.readFileSync(path.join(out,'project.json'))),audio={duration:c.duration,beats:c.beats,features:c.audioFeatures},pcmBytes=fs.readFileSync(path.join(dir,'audio.f32')),pcm=new Float32Array(pcmBytes.buffer.slice(pcmBytes.byteOffset,pcmBytes.byteOffset+pcmBytes.length));audio.buffer={length:pcm.length,sampleRate:48000,numberOfChannels:1,getChannelData:()=>pcm};
 context.window.AudioContext=class{async decodeAudioData(){return audio.buffer;}async close(){}};audio.buffer.duration=audio.duration;const measured=await J.analyzeAudio(new Blob([]));Object.assign(audio,measured);audio.beats=c.beats;
 if(process.env.KAMEN_RESELECT_STORY){const selected=await J.compareRegistryCandidates(p,audio,c.imageFeatures||{}, {ensureFonts:false});Object.assign(p,selected.recommended.project);fs.writeFileSync(path.join(out,'project.json'),JSON.stringify(p));}
 const plan=J.plan(p,audio);const refinementAttempt=Number(process.env.KAMEN_REFINEMENT_ATTEMPT)||0;if(refinementAttempt){const base=JSON.parse(fs.readFileSync(process.env.KAMEN_BASELINE_REPORT));J.repairPhotoBottlenecks(plan,J.evaluateQualityTarget({quality:base.quality,errors:base.issues.filter(i=>i.severity==='ERROR')}),refinementAttempt);}await J.refineMusicalPhotoPlan(plan);let pixel=await J.analyzeRenderedFrames(plan,null,audio);if(process.env.KAMEN_RESELECT_STORY){await J.preparePhotoExport({plan,project:p,audio,range:null});pixel=plan.lastPixelQA;}const R=new J.Renderer(),[W,H]=J.outputSize(p),canvas=createCanvas(W,H),ctx=canvas.getContext('2d');await R.loadCustomBackground(p.customBg.dataUrl);await R.loadAssetDeck(plan);
 const video=path.join(out,'revised.mp4'),ff=spawn('ffmpeg',['-v','error','-y','-f','rawvideo','-pixel_format','rgba','-video_size',W+'x'+H,'-framerate',String(renderFPS),'-i','pipe:0','-i',path.join(dir,'audio.m4a'),'-map','0:v','-map','1:a','-r',String(plan.fps),'-c:v','libx264','-preset','fast','-crf','19','-pix_fmt','yuv420p','-c:a','copy','-t',String(audio.duration),'-movflags','+faststart',video],{stdio:['pipe','ignore','pipe']});let errors='';ff.stderr.on('data',d=>errors+=d);const done=once(ff,'close');
 for(let i=0;i<Math.ceil(audio.duration*renderFPS);i++){R.frame(ctx,plan,i/renderFPS,{production:true,scale:W/plan.W});if(!ff.stdin.write(Buffer.from(ctx.getImageData(0,0,W,H).data)))await once(ff.stdin,'drain');if(i%150===0)console.log('render',i,'/',Math.ceil(audio.duration*renderFPS));}
 ff.stdin.end();const [exit]=await done;R.disposeAssets();if(exit)throw Error(errors);
 const probe=JSON.parse(spawnSync('ffprobe',['-v','error','-count_frames','-show_streams','-show_format','-of','json',video],{encoding:'utf8'}).stdout),vs=probe.streams.find(s=>s.codec_type==='video'),as=probe.streams.find(s=>s.codec_type==='audio');
 if(vs.codec_tag_string!=='avc1'||as.codec_tag_string!=='mp4a'||vs.width!==W||vs.height!==H||Math.abs(+probe.format.duration-plan.duration)>.1||+vs.nb_read_frames!==Math.ceil(plan.duration*plan.fps))throw Error('Native MP4 structure failed');
 const width=96,height=Math.round(width*plan.H/plan.W),decoded=spawnSync('ffmpeg',['-v','error','-i',video,'-vf',`fps=10,scale=${width}:${height}`,'-pix_fmt','rgba','-f','rawvideo','pipe:1'],{maxBuffer:128*1024*1024});if(decoded.status)throw Error(decoded.stderr.toString());
 const frames=[],size=width*height*4;for(let i=0;i<Math.floor(decoded.stdout.length/size);i++)frames.push({time:i/10,features:J.observePixelFrame(decoded.stdout.subarray(i*size,(i+1)*size),width,height)});
 const observer=J.observeVisualPeaks(frames),alignment=J.alignObservedPeaks(observer,J.musicalTargets(plan)),exportPixel={...pixel,metrics:{...pixel.metrics,observer,observedVisualHitAlignment:alignment,alignmentDomains:J.alignmentDomains8(observer,J.musicalTargets(plan)),audienceImpact:J.audienceImpact7(observer,plan)}};
 const validation={container:'mp4',videoCodec:vs.codec_tag_string,audioCodec:as.codec_tag_string,audioSamples:+as.nb_read_frames,width:vs.width,height:vs.height,duration:+probe.format.duration,bytes:fs.statSync(video).size,certification:{passed:false,status:'NATIVE_FFMPEG_VERIFIED_BROWSER_WEBCODECS_UNTESTED'}};
 const r=J.checkMVQuality(p,plan,audio,null,exportPixel,{h264:true,aac:true,webCodecs:false,recorder:true},validation),audioSource=spawnSync('ffmpeg',['-v','error','-i',path.join(dir,'audio.m4a'),'-f','hash','-hash','sha256','-'],{encoding:'utf8'}).stdout,audioExport=spawnSync('ffmpeg',['-v','error','-i',video,'-map','0:a','-f','hash','-hash','sha256','-'],{encoding:'utf8'}).stdout;if(audioSource!==audioExport)throw Error('Audio PCM hash changed');
 const result={method:'Native Canvas full export; H.264/AAC; ffmpeg decoded export pixels; unchanged KAMEN scorer',limitation:'Original supplied PNG and saved browser selections restored; audio features recomputed from source PCM. Native fallback fonts; browser export not verified.',duration:plan.duration,frames:+vs.nb_read_frames,sourceAudioPCM:audioSource.trim(),exportAudioPCM:audioExport.trim(),videoSHA256:await J.sha256(new Uint8Array(fs.readFileSync(video))),quality:r.quality,issues:r.issues,alignment,validation,musicalPhoto:plan.musicalPhoto,refinementAttempt,metrics:exportPixel.metrics};fs.writeFileSync(path.join(out,'decoded-score.json'),JSON.stringify(result,null,2));console.log(JSON.stringify({total:r.quality.overallScore,creative:r.quality.creativeScore,domains:r.quality.productionDomains,issues:r.issues.map(i=>i.code),sameAudio:true}));
})().catch(e=>{console.error(e);process.exitCode=1;});
