'use strict';const assert=require('node:assert/strict'),{engine}=require('./custom_test_support.cjs');const {J}=engine();
// Final-pixel low contrast must fail even when every glyph exists.
const w=12,h=12,mask=Array(w*h).fill(0),bg=Array(w*h).fill(.05),good=bg.slice(),bad=Array(w*h).fill(.95);for(let y=4;y<8;y++)for(let x=4;x<8;x++){mask[y*w+x]=1;good[y*w+x]=.95;}
assert.equal(J.decodedGlyphContrast(good,bg,mask,w,h).score,100);assert.equal(J.decodedGlyphContrast(bad,bad,mask,w,h).score,0);assert.equal(J.decodedGlyphContrast(good,bg,Array(w*h).fill(0),w,h).score,null);
const channels=[Array(960).fill(.2),Array(960).fill(.1)],endpoint={head:{channels,sampleRate:48000},tail:{channels,sampleRate:48000},source:'decoded test AAC'};assert.equal(J.measureAudioEndpointSeam(endpoint).score,100);const broken=JSON.parse(JSON.stringify(endpoint));broken.tail.channels[1].fill(-.8);assert(J.measureAudioEndpointSeam(broken).score<20,'worst stereo channel governs audio seam');broken.tail.channels[1]=[0];assert.equal(J.measureAudioEndpointSeam(broken),null,'incomplete endpoint coverage never scores');
assert.equal(J.decodedTextSeam(bg,bg,mask,mask).score,100);assert.equal(J.decodedTextSeam(bg,bg,mask,Array(w*h).fill(0)).score,0,'text discontinuity cannot be hidden by identical backgrounds');assert.equal(J.decodedTextSeam(bg,bg,Array(w*h).fill(0),Array(w*h).fill(0)).score,100);
const grammar={field:'hero',mode:'hero',side:0,temporal:{role:'identity',level:.5},safeDerived:true,derivedLayer:'frame'},cut=(line)=>({line,start:line*3,end:line*3+3,grammar:JSON.parse(JSON.stringify(grammar)),params:{},cinema:{}}),p={W:1280,H:720,cuts:[cut(0),cut(1)],storyboard:[],musicalPhoto:{cinema:{architecture:{opening:0},grammar:{}}},lastPixelQA:{metrics:{decodedCinema:{completed:true,metrics:{lyricForegroundNovelty:100,hookNovelty:100},samples:[],techniqueCoverage:[{line:0,coverage:.2,minimumPixelDelta:.0001}],layerPresence:{primaryText:{samples:[]}}}}}};const original=JSON.stringify(p.cuts[1]),r=J.repairPhotoBottlenecks(p,{hardFailures:[],failures:[]},2);assert(r.some(s=>s.startsWith('layer-contract:0')));assert.equal(JSON.stringify(p.cuts[1]),original,'successful cuts remain unchanged by targeted repairs');assert.equal(p.cuts[0].grammar.derivedLayer,'contour');assert(p.cuts[0].grammar.layerStrength>1);assert(p.musicalPhoto.cinema.targetedRepair.noGenericBackgroundAdjustment);
assert.equal(J.cinemaWeakTypographyLines({layerPresence:{primaryText:{samples:[{line:0,structure:[1,0]},{line:1,structure:[1,0]},{line:2,structure:[0,1]}]}}}).join(','),'1','repeated typography architecture is repaired even when text already moves');
const d={completed:true,metrics:{motionRealization:82,impactBeatSync:91,localContrast:80,loopQuality:null,foregroundNovelty:null}};const v=J.qualityScoreStages({metrics:{}},d).verifiedScore;assert.equal(v.metrics.motionRealization,82);assert.equal(v.metrics.impactBeatSync,91);assert(v.unmeasuredPrimary.includes('loopQuality'));assert.equal(v.metrics.semanticDirection,null);assert.equal(v.overall,null);assert(!v.certified100);
const motionPlan={W:1280,H:720,fps:30,duration:3,cuts:[{line:0,start:0,end:3,dur:3,grammar:{temporal:{role:'identity',level:.7,hit:1}},cinema:{}}],beatHierarchy:[{time:1,beatSalience:.9}],musicalPhoto:{cinema:{architecture:{}},songProfile:{energy:.8}},musicalStructure:{sections:[{from:0,to:3,energy:.8}]}};const frameSet=pulse=>Array.from({length:31},(_,i)=>({time:i/10,features:{luma:Array(144).fill(i===pulse?.8:.1),edge:Array(144).fill(0)}}));const aligned=J.measureDecodedCinemaFrames(frameSet(10),motionPlan,null,16,9),late=J.measureDecodedCinemaFrames(frameSet(20),motionPlan,null,16,9);assert.equal(aligned.metrics.impactBeatSync,100);assert.equal(late.metrics.impactBeatSync,0,'a large peak at an unintended time cannot pass beat intent');assert.equal(aligned.beatIntent.targets.length,1,'only selected beats are evaluated');
console.log('Decoded glyph contrast, worst-channel AAC seam, text-only seam, incomplete evidence rejection, failure-specific repair isolation and honest verified score PASS');
// Exercise the browser inspection orchestration with explicit decoder stubs.
// Real H.264/AAC pixel and PCM evidence is checked separately by the native fixture.
(async()=>{const vm=require('node:vm'),fs=require('node:fs');let requested=[],width=0;const base=()=>({decodedCinema:{completed:true,metrics:{loopQuality:97},layerPresence:null}}),A={clamp:(v,a=0,b=1)=>Math.min(b,Math.max(a,v)),observeExportedMP4:async()=>base(),applyDecodedCinemaEvidence:d=>d,observePixelFrame:()=>({luma:[]}),waitExportStep:f=>f(),verifyDecodedCinemaLayers:async(frames,p,r,opts)=>{width=opts.width;assert.equal(frames.length,requested.length);return {samples:[],primaryText:{samples:[]},textLoop:{score:100}};},cinemaDecodeTimes7:()=>[0,2.99999]};const media={sampleMP4:async(blob,times,opts)=>{requested=times;assert.equal(opts.signal.aborted,false);times.forEach(t=>opts.onSample(t,new Uint8Array(4)));},audioEndpoints:async()=>endpoint};const win={J:A,JIZURAMedia:media},ctx=vm.createContext({window:win,AbortController,setTimeout,clearTimeout});vm.runInContext(fs.readFileSync(require('node:path').join(__dirname,'../src/11zzy_closed_loop.js'),'utf8'),ctx);const plan={W:1280,H:720,duration:3,fps:30,cuts:[{start:0,end:3,dur:3,grammar:{temporal:{hit:1}}}]};const r=await A.observeExportedMP4(new Blob(),plan,null);assert.equal(width,384);assert.equal(requested.at(-1),2.99999,'inspect the same true final-frame request as the primary decoder');assert(requested.every((t,i)=>!i||t>=requested[i-1]));assert.equal(r.decodedCinema.loopComponents.audio,100);assert.equal(r.decodedCinema.metrics.loopQuality,97);media.audioEndpoints=async()=>null;const missing=await A.observeExportedMP4(new Blob(),plan,null);assert.equal(missing.decodedCinema.metrics.loopQuality,null,'missing encoded audio cannot inherit the visual loop score');console.log('384-pixel phase decode, true final-frame request, encoded audio loop composition and unsupported decoder rejection PASS');})().catch(e=>{console.error(e);process.exitCode=1;});
