'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{engine,root}=require('./custom_test_support.cjs');
const input=process.argv[2],output=process.argv[3];
if(!input||!output)throw Error('Usage: node dev/kamen_attachment_quality.cjs inputDirectory report.json');
(async()=>{
 const {J,createCanvas}=engine(),c=JSON.parse(fs.readFileSync(path.join(input,'DIRECTOR_CONTEXT.json'))),bg='data:image/webp;base64,'+fs.readFileSync(path.join(input,'background.webp')).toString('base64');
 const p=J.defaultProject();Object.assign(p,{title:fs.readFileSync(path.join(input,'PROJECT_SUMMARY.md'),'utf8').split('\n')[0].replace(/^# /,''),artist:'@Arijigoku_GMB',lyrics:fs.readFileSync(path.join(input,'lyrics.lrc'),'utf8'),style:'noir',autoDirection:true,seed:777,res:720,fps:30});p.customBg={...p.customBg,enabled:true,dataUrl:bg};p.visualAssets=c.assets.map(a=>({...a,dataUrl:bg}));
 const audio={duration:c.duration,beats:c.beats,features:c.audioFeatures},proposal=J.proposeDirection(p,audio,c.imageFeatures);Object.assign(p,{style:proposal.style,mood:proposal.mood,fx:proposal.fx,enabled:proposal.enabled,seed:proposal.seed});p.artDirection=J.makeArtDirection(p,audio,proposal);J.enableSingleBackgroundMode();if(process.argv[4])Object.assign(p,JSON.parse(fs.readFileSync(process.argv[4])));const original=JSON.stringify(p),results=[];
 for(const aspect of ['16:9','9:16','1:1','4:5']){
  let maxCenterError=0;const q={...p,aspect},plan=J.plan(q,audio),r=new J.Renderer(),canvas=createCanvas(480,Math.round(480*plan.H/plan.W)),mask=createCanvas(canvas.width,canvas.height);
  await r.loadCustomBackground(bg);await r.loadAssetDeck(plan);
  try{if(aspect==='16:9'){const full=createCanvas(1280,720);for(const t of [15,28.5,32,40]){r.frame(full.getContext('2d'),plan,t,{scale:1280/plan.W,production:true});fs.writeFileSync(path.join(path.dirname(output),'full-'+t+'.png'),full.toBuffer('image/png'));}const contact=createCanvas(1440,540),cc=contact.getContext('2d');for(const [i,time] of [15,28.5,38,40,43,50.5].entries()){r.frame(canvas.getContext('2d'),plan,time,{scale:480/plan.W,production:true});cc.drawImage(canvas,(i%3)*480,Math.floor(i/3)*270);cc.fillStyle='#fff';cc.font='16px sans-serif';cc.fillText(time+'s',(i%3)*480+8,Math.floor(i/3)*270+22);}fs.writeFileSync(path.join(path.dirname(output),'revised-contact.png'),contact.toBuffer('image/png'));}
  for(const line of plan.lines){for(const u of [.2,.5,.8]){const time=line.start+(line.end-line.start)*u,items=[];r.frame(canvas.getContext('2d'),plan,time,{scale:480/plan.W,production:true,lyricAuditCtx:mask.getContext('2d'),lyricAuditItems:items});const bytes=mask.getContext('2d').getImageData(0,0,mask.width,mask.height).data;let ink=0;for(let i=3;i<bytes.length;i+=4)if(bytes[i]>24)ink++;assert(ink>8,`${aspect} ${line.text} ${u}: no lyric ink`);assert(items.some(it=>it.bounds),`${aspect} ${line.text}: no glyph audit`);for(const it of items.filter(it=>it.bounds)){const b=it.bounds,cut=J.cutAt(plan,time);if(plan.photoCompositionPolicy&&time>=cut.start+cut.inDur&&time<=cut.end-cut.outDur){const error=Math.max(Math.abs((b.x0+b.x1)/2/plan.W-.5),Math.abs((b.y0+b.y1)/2/plan.H-.5));maxCenterError=Math.max(maxCenterError,error);assert(error<.005,`${aspect} ${line.text}: centred glyph error ${error}`);}assert(b.x0>=plan.W*.11-1&&b.x1<=plan.W*.89+1&&b.y0>=plan.H*.08-1&&b.y1<=plan.H*.92+1,`${aspect} ${line.text} ${u}: `+JSON.stringify(b));}}}
   const presentationVariation=await J.measurePresentationVariation(plan);assert(presentationVariation.measured);assert(presentationVariation.observedChangedPairs>=3,'repeated lyric presentation must change in actual masks');
   results.push({aspect,lines:plan.lines.length,samples:plan.lines.length*3,maxNormalizedCenterError:maxCenterError,localCues:plan.localLyricDirection?.count||0,presentationVariation,status:'PASS'});
  }finally{r.disposeAssets();}
 }
 assert.equal(JSON.stringify(p),original);
 const report={source:'Attached background / audio feature context / original LRC lines reconstructed local project',results,sourceProjectMutated:false,limitations:['Original complete project JSON was not attached. This does not recreate the original manual editing state.','Native Canvas glyph integrity and safe-area checks do not establish subjective perfection or singing alignment.','No audio decode or export quality setting was changed by offline cues.']};
 fs.mkdirSync(path.dirname(path.resolve(output)),{recursive:true});fs.writeFileSync(output,JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2));
})().catch(e=>{console.error(e);process.exitCode=1;});
