'use strict';
const assert=require('node:assert/strict'),crypto=require('node:crypto'),{engine}=require('./custom_test_support.cjs');
(async()=>{const {J,createCanvas}=engine();J.enableSingleBackgroundMode();
const q={metrics:{typographyDiversity:144,structuralDiversity:100,visualStagnationSeconds:144},productionDomains:{semanticDirection:null}},d={completed:true,metrics:{perceptualNovelty:75,motion:100,foregroundNovelty:null}};
const stages=J.qualityScoreStages(q,d);assert.equal(stages.previewScore.metrics.typographyDiversity,100);assert.equal(stages.verifiedScore.metrics.perceptualNovelty,75);assert.equal(stages.verifiedScore.metrics.structuralDiversity,null);assert.equal(stages.verifiedScore.overall,null);assert(!stages.verifiedScore.certified100);assert.equal(q.metrics.visualStagnationSeconds,144,'seconds are not clamped as scores');
assert(!J.cinemaTechniqueSupported('subjectParallax',{W:720,H:1280}));assert(J.cinemaTechniqueSupported('contour',{W:720,H:1280}));
const sequences=new Set(),pixels=new Set(),phrases=['今ここに集いし','荒れ狂い暴れまわる','声が聞こえるだろ','今日もここにいるぜ','光と共に輝く','いつもの道を歩く','ラララーラララー','オオオーオオオー'];let example;
for(let i=0;i<20;i++){const bg=createCanvas(320,180),x=bg.getContext('2d');x.fillStyle=['#163661','#403b26','#113b2f','#472a3e'][i%4];x.fillRect(0,0,320,180);x.fillStyle='#aabbd1';x.fillRect(25+i*3,20,70,140);x.fillStyle='#257bce';x.fillRect(170,40+i,80,100);
const source=J.defaultProject();Object.assign(source,{autoDirection:true,res:720,fps:30,lyrics:phrases.map((_,k)=>'[00:'+String(1+k*2).padStart(2,'0')+']'+phrases[(k+i)%phrases.length]).join('\n')});source.customBg={...source.customBg,enabled:true,dataUrl:bg.toDataURL()};const calm=i%4===0,audio={duration:18,energyRate:10,energy:Float32Array.from({length:180},(_,k)=>.2+.7*((Math.floor(k/20)+i)%4)/3),features:{energy:calm?.2:.8,bpm:60+i*7,beatStrength:calm?.2:.9,percussive:calm?.1:.8,smoothness:calm?.9:.15},beats:Array.from({length:40},(_,k)=>k*(60/(60+i*7)))};
const proposal=J.proposeDirection(source,audio,{});Object.assign(source,{style:proposal.style,mood:proposal.mood,fx:proposal.fx,enabled:proposal.enabled,seed:proposal.seed});source.artDirection=J.makeArtDirection(source,audio,proposal);const initial=J.plan(source,audio);proposal.registrySelection={style:source.style,font:'embedded_bold',audioKey:J.registrySelectionAudioKey(audio),backgroundKey:J.registrySelectionBackgroundKey(source),lyricsKey:J.registrySelectionLyricsKey(initial),virtualShots:J.virtualShotCandidates(bg),entries:Object.fromEntries(initial.cuts.filter(c=>c.line>=0).map(c=>[c.line,{layout:'photoStatement',params:{font:'embedded_bold',displayText:c.lineText},enter:'cut',hold:'still',inDur:0}]))};source.artDirection=J.makeArtDirection(source,audio,proposal);const p=J.plan(source,audio);example=p;
sequences.add(p.cuts.filter(c=>c.grammar).map(c=>[c.grammar.subWorld,c.grammar.phraseMotion,c.grammar.field].join('/')).join('>'));assert(p.cuts.filter(c=>c.grammar?.derivedLayer).every(c=>J.cinemaTechniqueSupported(c.grammar.derivedLayer,p)));assert(p.musicalPhoto.localMusic.every(m=>m.source.startsWith('decoded audio')));const R=new J.Renderer(),cv=createCanvas(128,72),cx=cv.getContext('2d');await R.loadCustomBackground(source.customBg.dataUrl);const bytes=[];for(const t of [2,6,12]){R.frame(cx,p,t,{scale:128/p.W,production:true});bytes.push(Buffer.from(cx.getImageData(0,0,128,72).data));}pixels.add(crypto.createHash('sha256').update(Buffer.concat(bytes)).digest('hex'));R.disposeAssets();}
assert(sequences.size>=6,'20 different inputs must not collapse to one world/phrase sequence');assert.equal(pixels.size,20);const profiles=await J.measureSocialProfilePreviews(example);assert.equal(profiles.profiles.length,3);assert(profiles.profiles.every(p=>p.shortScore===null&&p.windows.length===4));const measured=await J.measureCinemaSequence(example);assert(measured.techniqueEvidence.contracts.every(c=>Number.isFinite(c.pixelDelta)&&Number.isFinite(c.visibleArea)));console.log(JSON.stringify({songs:20,distinctSequences:sequences.size,distinctRasterOutputs:pixels.size,profilePreviews:3}));console.log('Score units and stage isolation, unsupported-mask rejection, local-audio decisions, 20-song real-pixel diversity and separate aspect previews PASS');})().catch(e=>{console.error(e);process.exitCode=1;});
