'use strict';
const assert=require('node:assert/strict'),{engine}=require('./custom_test_support.cjs');
(async()=>{
 const {J,createCanvas}=engine();J.enableSingleBackgroundMode();const bg=createCanvas(640,640),x=bg.getContext('2d');
 const g=x.createLinearGradient(0,0,640,640);g.addColorStop(0,'#245eff');g.addColorStop(1,'#0c0915');x.fillStyle=g;x.fillRect(0,0,640,640);x.fillStyle='#d3c49f';x.fillRect(100,180,130,370);x.fillRect(390,80,190,200);
 const p=J.defaultProject();Object.assign(p,{autoDirection:true,res:720,fps:30,title:'俺らにできること',artist:'作者',lyrics:'[00:02.88]今ここに集いし\n[00:05.04]青と黒の戦士たち\n[00:07.86]我らの誇りと共に輝き\n[00:10.76]荒れ狂い暴れまわる\n[00:13.79]声が聞こえるだろ\n[00:16.52]今日もここにいるぜ\n[00:19.57]ラララーラララーラララー\n[00:22.46]ラララーラララーラララー\n[00:25.63]ラララーラララーラララー\n[00:28.48]ラララーラララーラララー\n[00:31.38]オオオーオオオーオオオ\n[00:34.45]オオオーオオオーオオオ\n[00:37.37]オオオーオオオーオオオ\n[00:40.22]オオオーオオオーオオオ'});p.customBg={...p.customBg,enabled:true,dataUrl:bg.toDataURL()};
 const pcm=new Float32Array(44*48000),audio={duration:44,buffer:{sampleRate:48000,length:pcm.length,duration:44,numberOfChannels:1,getChannelData:()=>pcm},beats:Array.from({length:120},(_,i)=>i*.372),features:{energy:.8,bpm:161,beatStrength:.8}};
 const d=J.proposeDirection(p,audio,{});Object.assign(p,{style:d.style,mood:d.mood,fx:d.fx,enabled:d.enabled,seed:d.seed});p.artDirection=J.makeArtDirection(p,audio,d);const base=J.plan(p,audio);
 d.registrySelection={style:p.style,font:'embedded_bold',lyricsKey:J.registrySelectionLyricsKey(base),backgroundKey:J.registrySelectionBackgroundKey(p),virtualShots:J.virtualShotCandidates(bg),entries:Object.fromEntries(base.cuts.filter(c=>c.line>=0).map(c=>[c.line,{layout:'photoStatement',params:{font:'embedded_bold',displayText:c.lineText},enter:'cut',hold:'still',inDur:0,family:'statement'}]))};p.artDirection=J.makeArtDirection(p,audio,d);
 const snapshot=JSON.stringify(p),plan=J.plan(p,audio);assert.equal(JSON.stringify(p),snapshot);assert.equal(plan.musicalPhoto.cinema.pool.length,9);assert.equal(J.lyricCinemaMeaning('声が聞こえるだろ'),'call');assert(plan.cuts.find(c=>c.line===4).cinema.quiet);
 assert.equal(J.vocaliseUnits('ラララーラララーラララー').join(''),'ラララーラララーラララー');
 const group=plan.cuts.filter(c=>c.story?.group==='la');assert.deepEqual(Array.from(group,c=>c.layout),['cinemaGrammarsolo','cinemaGrammarduo','cinemaGrammarstands','cinemaGrammarstadium']);
 const final=plan.musicalPhoto.cinema.climax,stop=plan.musicalPhoto.cinema.loop.from;let scale=0;for(let t=final;t<stop;t+=.1){const s=J.cameraAt(plan,t).s;assert(s>=scale-1e-8,'climax zoom must not regress before loop');scale=s;}
 assert(plan.musicalPhoto.cinema.hook.length>=3);assert(new Set(plan.cuts.filter(c=>c.virtualShot).map(c=>c.virtualShot.id)).size>=6);
 const R=new J.Renderer(),cv=createCanvas(480,270);await R.loadCustomBackground(p.customBg.dataUrl);await R.loadAssetDeck(plan);const ctx=cv.getContext('2d'),render=(time,range)=>{R.frame(ctx,plan,time,{scale:480/plan.W,range,production:true});return Buffer.from(ctx.getImageData(0,0,480,270).data);};
 const stored=JSON.stringify({cuts:plan.cuts,cinema:plan.musicalPhoto.cinema,events:plan.events});const background=time=>{ctx.setTransform(480/plan.W,0,0,480/plan.W,0,0);ctx.clearRect(0,0,plan.W,plan.H);R.renderRange=null;R.drawCustomBackground(ctx,plan,time);return Buffer.from(ctx.getImageData(0,0,480,270).data);};assert(background(43.9666666667).equals(background(0)),'last background must match opening');assert(J.creditStateAt(plan,43.9666666667).hidden,'no title over final lyric');assert(render(0).equals(render(0)),'deterministic seeking');assert.equal(JSON.stringify({cuts:plan.cuts,cinema:plan.musicalPhoto.cinema,events:plan.events}),stored);
 assert(!render(5.5).equals(render(11.5)),'meaning selects a distinct rendered shot');
 const noPhoto={...plan,cuts:plan.cuts.map(c=>c.line===3?{...c,photoExit:true}:c)};R.frame(ctx,noPhoto,11.5,{scale:480/plan.W,production:true});assert(!Buffer.from(ctx.getImageData(0,0,480,270).data).equals(render(11.5)),'photo-off counterfactual must suppress the supplied image');
 const range={start:19.57,end:31.38},lastFrame=Math.floor((range.end-1e-7)*30)/30;assert(!render(lastFrame,range).equals(render(range.start,range)),'range keeps its last lyric until the intentional text exchange');
 const short=J.createSocialHookPlan(plan,{start:19.57,end:34.45});for(const c of short.cuts.filter(c=>c.line>=0&&c.start>=19.57&&c.start<34.45)){const original=plan.cuts.find(v=>v.line===c.line);assert.equal(c.lineText,original.lineText);assert.equal(c.layout,original.layout,'social re-edit must retain cinema chant staging');}
 const evidence=await J.measureCinemaEvidence(plan,null,audio);assert(evidence.loop.visualScore>=99);assert(evidence.loop.audio);assert(evidence.hook.hasNewInformation.some(Boolean));
 const onset=await J.measureDisplayOnsets(plan,null);assert.equal(onset.score,100);
 const manual=J.plan({...p,overrides:{2:{layout:'photoStatement',enter:'pop',hold:'breathe',cam:'panL'}}},audio),cut=manual.cuts.find(c=>c.line===2);assert(J.photoChoreographyLocked(manual,cut));assert(!cut.cinema);assert.equal(cut.enter,'pop');
 for(const aspect of ['9:16','1:1','16:9','4:5']){const q=J.plan({...p,aspect},audio),r=new J.Renderer(),c=createCanvas(240,Math.round(240*q.H/q.W)),mc=createCanvas(c.width,c.height);await r.loadCustomBackground(p.customBg.dataUrl);await r.loadAssetDeck(q);for(const time of [3.1,6,11,20,26,32,41]){const items=[];r.frame(c.getContext('2d'),q,time,{scale:240/q.W,production:true,lyricAuditCtx:mc.getContext('2d'),lyricAuditItems:items});assert(items.length);for(const item of items){const b=item.bounds;assert(b.x0>=q.W*.065&&b.x1<=q.W*.935&&b.y0>=q.H*.04&&b.y1<=q.H*.96,aspect+' lyric safe area');}}r.disposeAssets();}
 R.disposeAssets();console.log('9 edge-sampled shots, semantic roles, exact chant text, monotonic climax, full-frame/range loop, counterfactual, glyph onsets, manual locks and 4 aspect ratios PASS');
})().catch(e=>{console.error(e);process.exitCode=1;});
