const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{fixture,J,draw,createCanvas}=require('./phase4_fixture.cjs');
const fakeFrames=(flash=false)=>Array.from({length:41},(_,i)=>{const c=createCanvas(48,27),ctx=c.getContext('2d');ctx.fillStyle=flash&&i===20?'#fff':'#111';ctx.fillRect(0,0,48,27);ctx.fillStyle='#fff';ctx.fillRect(4+(i>=10&&i<20?15:0),9,7,8);return {time:i*.1,features:J.observePixelFrame(ctx.getImageData(0,0,48,27).data,48,27)};});
module.exports=async name=>{const {p,a,plan}=fixture();
 switch(name){
 case 'observer_visual_peak_test':{const o=J.observeVisualPeaks(fakeFrames(true));assert(o.independent);assert(o.peaks.some(x=>Math.abs(x.time-2)<.11));const f=fakeFrames().map(x=>({...x,features:fakeFrames()[0].features}));assert.equal(J.observeVisualPeaks(f).peaks.length,0);assert(!J.observeVisualPeaks.toString().includes('p.events'));break;}
 case 'event_target_type_test':{const aligned=J.plannedEventAlignment({...plan,events:[{t:1,amp:.8,targetType:'BEAT'},{t:1,amp:.8,targetType:'LYRIC_ONSET'}],hypeTimeline:[],beatHierarchy:[{time:1.4,beatSalience:1}],lines:[{start:1}],musicalStructure:{sections:[]}});assert.equal(aligned.samples[0].pass,false);assert.equal(aligned.samples[1].pass,true);assert.equal(aligned.beatSync,0);break;}
 case 'observed_hit_alignment_test':{const q=J.alignObservedPeaks({peaks:[{time:1,tier:'Major'}],sampleCount:20},{BEAT:[1.4],LYRIC_ONSET:[1],PHRASE_ONSET:[],SECTION:[]});assert.equal(q.score,100);assert.equal(q.beatOnlyScore,0);assert.equal(q.peaks[0].targetType,'LYRIC_ONSET');break;}
 case 'visual_world_intelligence_test':{const low=J.chapterIntent({role:'verse',energy:.1},null,{}),high=J.chapterIntent({role:'verse',energy:.9},{energy:.2},{});assert.notEqual(low,high);for(const w of plan.visualWorld.chapters)for(const k of ['backgroundWorld','typographyArchitecture','paletteTreatment','texture','motifState','motionPhysics','cameraLanguage','transitionLanguage','layerDensity'])assert(k in w);assert(plan.visualWorld.chapters.some(w=>w.photoExit));break;}
 case 'world_distance_realization_test':{const frames=fakeFrames();const identical=frames.map(f=>({...f,features:frames[0].features}));const pp={...plan,duration:4,visualWorld:{chapters:[{from:0,to:2,targetWorldDistance:0},{from:2,to:4,targetWorldDistance:.8}]}};const q=J.measureWorldDistance7(pp,identical);assert.equal(q.pairs[0].actual,0);assert(q.weakChapters.length);break;}
 case 'motif_physics_v2_test':assert.notDeepEqual(J.motifPhysicsAt(plan,1),J.motifPhysicsAt(plan,45));assert(J.motifPhysicsAt(plan,1).envelope!==undefined);break;
 case 'motif_reality_test':{const still=J.observeVisualPeaks(fakeFrames().map(f=>({...f,features:fakeFrames()[0].features})));assert.equal(J.motifReality7(plan,still).score,0);assert(J.motifReality7(plan,J.observeVisualPeaks(fakeFrames())).score>0);const q=await J.measureMotifReality7({...plan,suppressMotif7:true});assert.equal(q.score,0);assert(q.causal);break;}
 case 'semantic_reality_test':{const c=plan.cuts.find(c=>c.line>=0);c.semanticIntent={visualVerb:'rise',importance:1};c.semanticResolved=J.resolveVisualVerb('rise');const q=await J.measureSemanticReality7(plan);assert(q.measured);assert(q.results[0].rendered.centroid.length===3);assert(Number.isFinite(q.score));assert.equal(q.results[0].verb,'rise');break;}
 case 'semantic_verb_family_test':for(const v of ['fall','rush','contract','surround','collide','reveal','dominate','celebrate','endure','ignite','break','resolve']){const r=J.resolveVisualVerb(v);assert.equal(r.verb,v);assert(J.LAYOUTS[r.layout]);assert(J.CAMERA[r.motion]);}assert(J.resolveVisualVerb('untrusted').fallback);break;
 case 'typography_semantic_motion_test':{assert(J.semanticTypographyState('expand',.8).width>J.semanticTypographyState('expand',.1).width);assert(J.semanticTypographyState('rise',.8).y<J.semanticTypographyState('rise',.1).y);assert(J.semanticTypographyState('freeze',.5).still);const c=plan.cuts.find(c=>c.line>=0);c.semanticIntent={visualVerb:'expand',importance:1};assert(draw(plan,c.start+.3).ink>0);break;}
 case 'audience_impact_test':{const q=J.audienceImpact7(J.observeVisualPeaks(fakeFrames(true)),{musicalStructure:{sections:[{role:'climax',from:1.9,to:2.2}]}});assert(q.climaxDominance>1);assert(q.heroCount<=3);assert(q.method.includes('proxy'));break;}
 case 'climax_dominance_test':{const q=J.audienceImpact7({signals:[{time:1,perceivedImpact:1},{time:3,perceivedImpact:1}],peaks:[]},{musicalStructure:{sections:[{role:'climax',from:2,to:4}]}});assert(!q.climaxPass);assert.equal(q.climaxDominance,1);break;}
 case 'negative_space_test':{const climax=plan.musicalStructure.sections.find(s=>s.role==='climax');assert(climax);assert(J.negativeSpaceAt(plan,climax.from-.2).typeScale<1);assert.equal(J.negativeSpaceAt(plan,climax.from+.2).typeScale,1);break;}
 case 'repetition_intelligence_test':{assert(plan.repetitionIntelligence.some(r=>r.role==='establish'));assert(plan.repetitionIntelligence.some(r=>r.role==='develop'));assert(plan.repetitionIntelligence.some(r=>['variation','payoff'].includes(r.role)));assert.equal(p.lyrics.split('\n').length,20);break;}
 case 'layout_fatigue_v2_test':{const pp=structuredClone(plan);for(const w of pp.visualWorld.chapters)w.intent='identity';pp.cuts=Array.from({length:8},(_,i)=>({line:i,start:i,layout:'huge',architecture:'giant',params:{}}));assert(J.auditLayoutFatigue7(pp).penalties.length>0);break;}
 case 'director_context_v5_test':{const c=J.directorContext(p,plan,a);assert.equal(c.schema,'jizura-director-context-v7');for(const k of ['chapterIntent','currentVisualWorlds','observedVisualPeaks','weakWorldChapters','weakSemanticLines','motifFatigue','layoutFatigue','currentQualityScores','currentQAFailures','socialTarget'])assert(k in c);break;}
 case 'director_revision_v2_test':{const blob=await J.createDirectorRevisionPack({project:p,plan,audio:a}),b=Buffer.from(await blob.arrayBuffer());for(const n of ['VISUAL_REFERENCE_SHEET.jpg','CURRENT_QA.json','CURRENT_DRAFT_CONTACT.jpg','DIRECTOR_CONTEXT.json'])assert(b.includes(Buffer.from(n)));break;}
 case 'director_observer_tournament_test':{const w=J.directorWindows(plan.duration,plan);assert.equal(w.length,6);assert(w.some(x=>x.name==='weakest chapter'));assert(J.compareDirectorCandidates.toString().includes('observedVisualHitAlignment'));break;}
 case 'social_director_v5_test':{const c=J.socialHookCandidates(plan,a)[0],s=J.createSocialHookPlan(plan,c);assert.equal(s.socialHook.version,5);assert(s.socialDirector.independent);assert.equal(s.socialDirector.aspect,'9:16');assert(s.socialDirector.phases[0].to-s.socialDirector.phases[0].from<=.5);assert(s.H>s.W);assert(draw(s,c.start+.2,[180,320]).ink>0);break;}
 case 'adaptive_fps_test':{assert.equal(J.chooseAdaptiveFPS({fps:60}).fps,60);assert.equal(J.chooseAdaptiveFPS({exportSettings:{fpsMode:'auto'},fx:{koma:12}}).fps,24);assert.equal(J.chooseAdaptiveFPS({exportSettings:{fpsMode:'auto'},artDirection:{visualDNA:{motionAmount:.9}}},{maxFPS:30}).fps,30);break;}
 case 'platform_policy_test':for(const v of Object.values(J.exportPolicies))for(const k of ['platform','checkedAt','source','aspect','resolution','fps','codec','bitrate','duration'])assert(k in v);assert.equal(J.exportPolicies.x.duration,140);break;
 case 'export_provenance_test':{assert.equal(await J.sha256('abc'),'ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad');const blob=new Blob(['videoA']),hash=await J.sha256(await blob.arrayBuffer());assert(await J.verifyExportProvenance(blob,{videoSHA256:hash}));assert(!await J.verifyExportProvenance(new Blob(['videoB']),{videoSHA256:hash}));const old=J.canonicalJSON(plan);plan.currentQualityScores={technical:100};assert.equal(J.canonicalJSON(plan),old);plan.cuts[0].params.size=123;assert.notEqual(J.canonicalJSON(plan),old);break;}
 case 'quality_bottleneck_test':{const q=J.bottleneckCreative7({musicalDirection:100,typography:100,visualWorld:60,motionRealization:100,audienceImpact:100,semanticDirection:null});assert(q.score<90);assert(q.penalty>0);break;}
 default:throw Error('Unknown '+name);
 }
 console.log(name+' PASS');
};
