const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{fixture,J,draw}=require('./phase4_fixture.cjs');
module.exports=async name=>{const {p,a,plan}=fixture();
 if(['event_realization_test','strong_event_repair_test','musical_salience_alignment_test'].includes(name)){
  plan.events=[{t:.85,type:'chroma',amp:.8,plannedImpact:.8,dur:.22}];plan.hypeTimeline=[];plan.fx.chroma=0;const before=await J.measureEventRealization(plan);assert.equal(before.samples.length,1);assert(before.samples[0].channels);const after=await J.repairStrongEvents(plan);assert(after.samples[0].actualImpact>before.samples[0].actualImpact);assert(after.strongEventVisibleRate>=95);assert(plan.perceptualRepair.attempts<=3);assert(after.samples.every(s=>Number.isFinite(s.timingErrorMs)&&s.actualImpact>=0&&s.actualImpact<=1));
 }else if(name==='visual_verb_resolver_test'){for(const verb of ['pierce','explode','unite','rise','flow','freeze','collapse','expand','echo']){const r=J.resolveVisualVerb(verb);assert(J.LAYOUTS[r.layout]);assert(J.CAMERA[r.motion]);}assert.equal(J.resolveVisualVerb('unknown').verb,'flow');}
 else if(['semantic_direction_test','director_revision_roundtrip_test'].includes(name)){
  const chapters=plan.musicalStructure.sections.map(s=>({from:s.from,to:s.to,role:s.role,styleIntent:'sports'})),raw={schema:'jizura-director-v4',projectHash:J.directorProjectHash(p,a.duration,a),chapters,lineSemantics:[{line:0,emotion:'pride',importance:.9,visualVerb:'unite'}],constraints:{preserveLyrics:true,safeArea:true}};const v=J.validateDirectorPlan(raw,p,plan,a);assert(v.valid,JSON.stringify(v.errors));const applied=J.applyDirectorPlan(p,v.candidates[0].plan,a),render=J.plan(applied,a);assert.equal(render.cuts.find(c=>c.line===0).semanticResolved.family,'gather');assert.equal(applied.lyrics,p.lyrics);raw.lineSemantics[0].text='歌詞改変';assert(!J.validateDirectorPlan(raw,p,plan,a).valid);
 }else if(name==='director_context_v4_test'){const c=J.directorContext(p,plan,a);assert(['jizura-director-context-v4','jizura-director-context-v5','jizura-director-context-v7'].includes(c.schema));for(const key of ['currentQualityScores','currentQAFailures','visualWorldSummary','socialTarget','macroSections','beatSalienceSummary'])assert(key in c);}
 else if(name==='director_revision_pack_test'){
  const zip=await J.createDirectorRevisionPack({project:p,plan,audio:a});const bytes=Buffer.from(await zip.arrayBuffer()),text=bytes.toString();for(const n of ['DIRECTOR_CONTEXT.json','CURRENT_QA.json','CURRENT_DRAFT_CONTACT.jpg','lyrics.lrc','CHATGPT_REVISION_PROMPT.md','PROJECT_SUMMARY.md'])assert(text.includes(n));
 }else if(['portrait_saliency_test','social_subject_avoidance_test'].includes(name)){const {plan:q}=fixture('9:16');q.autoPalette={localMap:{width:6,height:8,values:Array.from({length:48},(_,i)=>[.3,i>=18&&i<30?.9:.02]).flat()}};const result=J.portraitSaliency(q);assert(result.checked);assert.equal(result.warnings,0);assert(result.resolutions.some(r=>r.after<r.before));assert(draw(q,1,[180,320]).ink>10);}
 else if(['motif_physics_test','motif_development_test'].includes(name)){assert.notDeepEqual(J.motifPhysicsAt(plan,.1),J.motifPhysicsAt(plan,2));assert(J.motifStateAt(plan,plan.duration*.8).density>=J.motifStateAt(plan,1).density);}
 else if(name==='visual_world_distinctness_test'){assert(plan.visualWorld.version>=3);for(const w of plan.visualWorld.chapters)assert(w.motionPhysics&&w.paletteTreatment&&w.texture&&w.layerDensity);}
 else if(name==='director_tournament_test'){assert.equal(J.directorWindows(61).length,5);assert(J.directorPrompt().includes('lineSemantics'));assert(J.directorPrompt().includes('jizura-director-v4'));}
 else if(name==='export_certification_test'){assert(J.certifyExport);assert(J.EXPORT_POLICY.x.maxDuration===140);const source=fs.readFileSync(path.join(__dirname,'../src/12_ui.js'),'utf8');assert(source.includes('EXPORT VERIFIED'));assert(source.includes('certification?.passed'));}
 else if(['browser_export_e2e_test','variable_font_browser_test'].includes(name)){
  const report=process.env.JIZURA_BROWSER_QA_REPORT;if(!report||!fs.existsSync(report)){console.log(name+' SKIPPED_ENVIRONMENT_MISSING (run dev/browser_export_e2e.cjs with Chrome/Edge)');return 'SKIP';}const r=JSON.parse(fs.readFileSync(report));assert.equal(r.status,'PASS');assert(r.validation.certification.passed);if(name==='variable_font_browser_test')assert(r.variableFont?.tested);
 }
 console.log(name+' PASS');};
