const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{chromium}=require('playwright-core');
(async()=>{const C=fs.existsSync('/tmp/jizura-browser/node_modules/@sparticuz/chromium/build/index.js')?(await import('/tmp/jizura-browser/node_modules/@sparticuz/chromium/build/index.js')).default:{args:['--no-sandbox','--disable-dev-shm-usage','--allow-file-access-from-files']},browser=await chromium.launch({executablePath:process.env.JIZURA_CHROME_PATH||'/tmp/chromium',headless:true,args:C.args,timeout:60000});const page=await browser.newPage({acceptDownloads:true,viewport:{width:1365,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));const out=path.resolve('../deliverables');fs.mkdirSync(out,{recursive:true});await page.goto('file://'+path.resolve('dist/index.html'));await page.waitForFunction(()=>window.J?.ui?.project&&document.querySelector('#visualAssetFiles'));const fixture=await page.evaluate(()=>{const images=[];for(let i=0;i<12;i++){const c=document.createElement('canvas');c.width=1280;c.height=720;const x=c.getContext('2d'),g=x.createLinearGradient(0,0,1280,720);g.addColorStop(0,['#0e3358','#28494d','#50325d'][i%3]);g.addColorStop(1,['#437fab','#609c76','#a86259'][i%3]);x.fillStyle=g;x.fillRect(0,0,1280,720);x.fillStyle='#b9cee0';for(let j=0;j<20+i;j++){x.fillRect((j*137+i*50)%1000,400+(j%4)*50,25+i*3,20);}images.push(c.toDataURL('image/png'));}return images;});
for(let i=0;i<12;i++)fs.writeFileSync(path.join(out,'qa-image-'+i+'.png'),Buffer.from(fixture[i].split(',')[1],'base64'));
await page.locator('#visualAssetFiles').setInputFiles([0,1,2].map(i=>path.join(out,'qa-image-'+i+'.png')));await page.waitForFunction(()=>J.ui.project.visualAssets?.length===3&&document.querySelector('#visualAssetStatus').textContent.includes('/ 3枚'));
await page.evaluate(async()=>{const p=J.ui.project;window.fixtureAssets=structuredClone(p.visualAssets);p.title='Motion Director 検証';p.artist='JIZURA';p.lyrics='[00:00.00]光をつなぐ\n[00:02.00]未来へ進む\n[00:04.00]声を重ねる\n[00:06.00]ここから始まる\n[00:08.00]光をつなぐ\n[00:10.00]未来へ進む';p.aspect='16:9';p.res=720;p.fps=24;p.autoDirection=true;p.timing.bpm=120;const ac=new AudioContext(),buffer=ac.createBuffer(1,ac.sampleRate*12,ac.sampleRate),samples=buffer.getChannelData(0);for(let i=0;i<samples.length;i++){const t=i/ac.sampleRate,beat=t%.5,envelope=Math.exp(-beat*18);samples[i]=Math.sin(t*2*Math.PI*220)*.13+Math.sin(t*2*Math.PI*70)*envelope*.28;}J.ui.audio={buffer,duration:12,beats:Array.from({length:24},(_,i)=>i*.5),features:{bpm:120,energy:.7,beatStrength:.8,density:.7,timeline:Array.from({length:24},(_,i)=>({time:i*.5,energy:.3+i/40,density:.7,spectralFlux:.6,bass:.5}))}};const proposal=J.proposeDirection(p,J.ui.audio,{median:.3,detail:.4,chroma:.5});Object.assign(p,{style:proposal.style,mood:proposal.mood,fx:proposal.fx,enabled:proposal.enabled,seed:proposal.seed});p.artDirection=J.makeArtDirection(p,J.ui.audio,proposal);J.uiApi.replan();await J.ui.renderer.loadAssetDeck(J.ui.plan);});
const reports=[];for(const count of [1,3,12]){console.log('START CASE',count);await page.evaluate(async count=>{const p=J.ui.project;p.visualAssets=count<=3?structuredClone(window.fixtureAssets.slice(0,count)):Array.from({length:12},(_,i)=>({...structuredClone(window.fixtureAssets[i%3]),id:'stress_'+i,name:'stress '+i}));J.uiApi.replan();await J.ui.renderer.loadAssetDeck(J.ui.plan);},count);
const report=await page.evaluate(async count=>{const {project,plan,audio}=J.ui;const pixels=await J.analyzeRenderedFrames(plan,{start:0,end:12},audio),quality=J.checkMVQuality(project,plan,audio,null,pixels,{h264:true,aac:true,webCodecs:true});const R=new J.Renderer();await R.loadCustomBackground(project.customBg.dataUrl);await R.loadAssetDeck(plan);const memory=R.visualMemory;R.disposeAssets();const result=await J.exportMP4({project,plan,audio,range:{start:0,end:12},quality:'high'});const data=async blob=>{const bytes=new Uint8Array(await blob.arrayBuffer());let s='';for(let i=0;i<bytes.length;i+=8192)s+=String.fromCharCode(...bytes.subarray(i,i+8192));return btoa(s);};return {count,mp4:await data(result.blob),validation:result.validation,provenance:result.provenance,quality:J.checkMVQuality(project,plan,audio,null,plan.lastPixelQA,{h264:true,aac:true,webCodecs:true},result.validation).quality,memory,storyboard:plan.storyboard,usage:plan.assetUsage,pixelMetrics:pixels.metrics,project};},count);assert(report.validation.certification.passed);assert(report.validation.provenanceMatch);assert(report.memory.retainedBytes<=report.memory.budgetBytes);const name=count===1?'FULL_MV_SAMPLE':count===3?'MULTI_IMAGE_FULL_SAMPLE':'STRESS_12_IMAGE_SAMPLE';fs.writeFileSync(path.join(out,name+'.mp4'),Buffer.from(report.mp4,'base64'));delete report.mp4;fs.writeFileSync(path.join(out,name+'.json'),JSON.stringify(report,null,2));reports.push(report);console.log('MP4 PASS',count,report.validation.duration,report.quality.productionDomains);}
// Undo/redo and persistence through real editor controls.
await page.evaluate(()=>J.uiApi.flushSave());await page.reload();await page.waitForFunction(()=>J.ui?.project?.visualAssets?.length===12);assert(await page.locator('#visualAssetFiles').count());
await page.screenshot({path:path.join(out,'JIZURA_8_UI.png'),fullPage:true});
await page.evaluate(async()=>{const p=J.ui.project;p.visualAssets=structuredClone(window.fixtureAssets||p.visualAssets.slice(0,3));p.autoDirection=true;J.uiApi.replan();});
fs.writeFileSync(path.join(out,'browser_qa.json'),JSON.stringify({status:'PASS',browser:await browser.version(),errors,cases:reports.map(r=>({count:r.count,validation:r.validation,quality:r.quality,memory:r.memory,usage:r.usage})),variableFont:{tested:false,status:'UNVERIFIED_FONT'}},null,2));assert.equal(errors.length,0,errors.join('\n'));await browser.close();})().catch(e=>{console.error(e);process.exitCode=1});
