const assert=require('node:assert/strict'),{J,createCanvas,fixture}=require('./phase4_fixture.cjs');
const image=createCanvas(960,640),ctx=image.getContext('2d');ctx.fillStyle='#18314a';ctx.fillRect(0,0,960,640);ctx.fillStyle='#5085bd';ctx.fillRect(30,150,330,320);const analysis=J.analyzeVisualAsset(image),dataUrl=image.toDataURL('image/png');
const assets=Array.from({length:12},(_,i)=>({id:'img_'+i,name:'test '+i,dataUrl,analysis:{...analysis,autoRole:i%3?'CROWD':'HERO',quality:.8,textCompatibility:.8,portraitFit:.8},role:'AUTO',pin:'auto'}));
const {p,a}=fixture();p.customBg={...p.customBg,enabled:true,dataUrl};p.visualAssets=assets;
let count=0;function test(name,fn){fn();count++;console.log(name+' PASS');}
test('legacy_single_image_migration_test',()=>{const m=J.migrateProject({customBg:p.customBg});assert.equal(m.visualAssets.length,1);assert.equal(m.visualAssets[0].dataUrl,dataUrl);assert.equal(m.schemaVersion,3);});
test('multi_image_import_test',()=>{assert.equal(J.normalizeVisualAssets([...assets,...assets]).length,12);});
test('asset_analysis_test',()=>{for(const k of ['brightness','chroma','negativeSpace','safeTextRegions','fingerprint','quality','portraitFit'])assert(k in analysis);assert.equal(analysis.width,960);});
test('asset_role_test',()=>{assert.equal(J.normalizeVisualAssets([{role:'unknown'}])[0].role,'AUTO');});
test('duplicate_image_test',()=>{assert.equal(J.detectAssetDuplicates(assets)[0].type,'exact duplicate');});
let plan=J.plan(p,a);
test('asset_chapter_fit_test',()=>{const f=J.assetChapterFit(assets[0],{intent:'climax'});assert(f>=0&&f<=1);});
test('asset_beam_search_test',()=>{assert(plan.assetCandidateSearch.every(s=>s.candidates.length<=12));assert(plan.storyboard.length>0);});
test('asset_fatigue_test',()=>{assert(J.assetChapterFit(assets[0],{intent:'identity'},null,6)<J.assetChapterFit(assets[0],{intent:'identity'},null,0));});
test('asset_reuse_variant_test',()=>{const m=J.plan({...p,visualAssets:[assets[0]]},a);const used=m.storyboard.filter(s=>s.assetId);assert(used.some(s=>s.variant==='DETAIL'||s.variant==='HERO'));});
test('palette_harmonization_test',()=>{assert(plan.globalVisualPalette.accent);assert(plan.cuts.some(c=>c.backgroundScene?.tint));});
test('image_transition_test',()=>{assert(plan.storyboard.every(s=>['cut','match-cut','color-bridge'].includes(s.transition)));});
test('visual_match_cut_test',()=>{assert(plan.storyboard.some(s=>s.transition==='match-cut'));});
test('multi_image_world_test',()=>{assert(plan.cuts.some(c=>c.assetId));assert(plan.storyboard.some(s=>s.variant==='TYPE_ONLY'));});
test('portrait_asset_fit_test',()=>{assert(analysis.portraitFit>=0&&analysis.portraitFit<=1);});
test('portrait_crop_test',()=>{const q=J.plan({...p,aspect:'9:16'},a);assert(q.storyboard.every(s=>s.crop.x>=0&&s.crop.x<=100));});
test('director_multi_image_context_test',()=>{const c=J.directorContext(p,plan,a);assert.equal(c.schema,'jizura-director-context-v7');assert.equal(c.assets.length,12);assert(!c.assets[0].dataUrl);});
test('director_asset_semantics_test',()=>{const d={schema:'jizura-director-v4',projectHash:J.directorProjectHash(p,plan.duration,a),chapters:[{from:0,to:20,role:'hook'},{from:20,to:40,role:'build'},{from:40,to:61,role:'climax'}],assetSemantics:[{assetId:'bad',meaning:['unity']}],constraints:{safeArea:true,preserveLyrics:true}};assert(!J.validateDirectorPlan(d,p,plan,a).valid);d.assetSemantics[0].assetId='img_0';assert(J.validateDirectorPlan(d,p,plan,a).valid);});
test('asset_missing_recovery_test',()=>{const q=J.plan({...p,visualAssets:[{...assets[0],dataUrl:''}]},a);assert.equal(q.assetUsage.used,0);});
test('asset_quality_gate_test',()=>{const q=J.plan({...p,visualAssets:[{...assets[0],analysis:{...analysis,quality:.1}}]},a);assert.equal(q.assetUsage.used,0);});
test('manual_asset_pin_test',()=>{const q=J.plan({...p,scenePins:[{from:plan.storyboard[0].from,assetId:'img_5'}]},a);assert.equal(q.storyboard[0].assetId,'img_5');assert(q.storyboard[0].locked);});
test('excluded_asset_test',()=>{const q=J.plan({...p,visualAssets:assets.map(x=>({...x,pin:'excluded'}))},a);assert.equal(q.assetUsage.used,0);});
test('alignment_domain_separation_test',()=>{const d=J.alignmentDomains8({peaks:[{time:1,tier:'Major'}],sampleStep:.1,sampleCount:20},{BEAT:[1.4],LYRIC_ONSET:[1]});assert.equal(d.beatSync.score,null);assert.equal(d.beatSync.status,'UNMEASURED_EXPECTED_BEAT_CUES');assert.equal(d.lyricSync.score,100);assert.equal(J.alignmentDomains8(null,{BEAT:[],LYRIC_ONSET:[]}).beatSync.score,null);});
test('semantic_registry_test',()=>{for(const [v,s] of Object.entries(J.SEMANTIC_REGISTRY)){assert.equal(J.resolveVisualVerb(v).verb,v);assert(J.LAYOUTS[s.layout]);}});
test('multi_image_social_test',()=>{const c=J.socialHookCandidates(plan,a)[0],q=J.createSocialHookPlan(plan,{...c,assetStrategy:'HERO_FOCUSED'});assert.equal(q.visualAssets.length,1);assert(q.H>q.W);});
console.log(`${count}/${count} multi-image regression cases PASS`);
