'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const window={},document={getElementById(){return null},createElement(){return {getContext(){return {measureText(s){return {width:String(s).length*20}}}}}},fonts:{load:async()=>[],ready:Promise.resolve()},head:{appendChild(){}}};
const J=window.J,ctx=vm.createContext({window,document,console,Blob,TextEncoder,URL,setTimeout,clearTimeout,performance,requestAnimationFrame(){}});
for(const name of fs.readdirSync(path.join(__dirname,'../src')).filter(x=>x.endsWith('.js')).sort())vm.runInContext(fs.readFileSync(path.join(__dirname,'../src',name),'utf8'),ctx,{filename:name});
const engine=window.J;
const image={median:.25,chroma:.3,warmth:.3,detail:.35,spaceLeft:.7,spaceRight:.3,spaceCenter:.5};
const makeAudio=duration=>({duration,buffer:{},bpm:124,beats:Array.from({length:Math.ceil(duration*2)},(_,i)=>i*.5),features:{bpm:124,energy:.6,beatStrength:.55,onsetDensity:.46,sectionContrast:.58,brightness:.45,bass:.5,timeline:Array.from({length:Math.ceil(duration/3)},(_,i)=>({time:i*3,energy:i>25&&i<46?.91:.25,density:i>25&&i<46?.7:.2,spectralFlux:i>25&&i<46?.7:.1,bass:.5}))}});
const p=engine.defaultProject();p.lyrics=Array.from({length:48},(_,i)=>`[${String(Math.floor(i*3/60)).padStart(2,'0')}:${String(i*3%60).padStart(2,'0')}.00]${i%4===0?'フォルツァ中谷ー':i%4===1?'進之介アレー':i%4===2?'ラララララー':'アレガンバエー'}`).join('\n');
const audio=makeAudio(144),versions=[];
for(let i=0;i<3;i++){
  const proposal=engine.proposeDirection(p,audio,image,i);
  versions.push(proposal);
  assert.equal(proposal.visualDNA.type,versions[0].visualDNA.type);
  assert.equal(proposal.mood,versions[0].mood);
  assert.deepEqual(JSON.stringify(proposal),JSON.stringify(engine.proposeDirection(p,audio,image,i)));
}
assert.equal(new Set(versions.map(v=>v.seed)).size,3);
assert.notEqual(versions[0].style,versions[1].style);
const optimized=engine.optimizeDirectionCandidates(p,audio,image,3),optimizedAgain=engine.optimizeDirectionCandidates(p,audio,image,3);
assert.equal(optimized.candidates.length,3);
assert.equal(optimized.recommended,optimized.candidates[0]);
assert.deepEqual(optimized.candidates.map(c=>[c.variant,c.score,c.proposal.seed]),optimizedAgain.candidates.map(c=>[c.variant,c.score,c.proposal.seed]),'candidate optimization must be deterministic');
assert(optimized.candidates.every(c=>c.audit.ok&&c.proposal.visualDNA.type===optimized.recommended.proposal.visualDNA.type),'alternatives preserve a realized direction and classification');
Object.assign(p,{style:versions[0].style,mood:versions[0].mood,enabled:versions[0].enabled,fx:versions[0].fx,seed:versions[0].seed,autoDirection:true});p.artDirection=engine.makeArtDirection(p,audio,versions[0]);
let plan=engine.plan(p,audio),highlights=engine.highlightCandidates(plan,audio);
assert.equal(highlights.length,3);assert(highlights[0].start>0);assert(highlights.every(c=>c.end-c.start<=60.1));
assert(highlights.every(c=>plan.lines.some(l=>Math.abs(l.start-c.start)<.01)||c.start===0));
const short=makeAudio(28),shortPlan=engine.plan(Object.assign(engine.defaultProject(),{lyrics:'[00:01.00]アレガンバエー\n[00:09.00]アレガンバエー'}),short);
assert.equal(engine.highlightCandidates(shortPlan,short)[0].end,28);
assert.throws(()=>engine.highlightCandidates(engine.plan(Object.assign(engine.defaultProject(),{lyrics:'時刻なしの歌詞'}),audio),audio));
p.customBg.blur=22;p.customBg.darkness=.72;p.fx.motion=.95;
let q=engine.preflightMV(p,audio,{start:highlights[0].start,end:highlights[0].end},()=>engine.plan(p,audio));
assert(q.fixes>=3);assert(p.customBg.blur<=8&&p.customBg.darkness<=.32&&p.fx.motion<=.75);
assert(!q.report.issues.some(i=>i.code==='blur'||i.code==='darkness'||i.code==='motion'));
const bad=engine.checkMVQuality(p,plan,{duration:0,buffer:null},{start:0,end:0});assert(bad.errors.length>0);
assert(bad.issues.some(i=>i.code==='audio_missing'&&i.severity==='ERROR'));
const invalid=engine.defaultProject();invalid.lyrics='[00:04.00]一行目\n[00:04.00]同時刻\n[03:00.00]音源の外';
const invalidPlan=engine.plan(invalid,makeAudio(30));
const invalidReport=engine.checkMVQuality(invalid,invalidPlan,makeAudio(30),{start:0,end:30});
assert(invalidReport.issues.some(i=>i.code==='lrc_outside'));
assert(invalidReport.issues.some(i=>i.code==='timing_duplicate'));
const clipped=engine.checkMVQuality(p,plan,{...audio,clipFraction:.04,peakAmplitude:1},{start:0,end:30});
assert(clipped.issues.some(i=>i.code==='audio_clip'));
const clean=engine.defaultProject();clean.autoDirection=false;clean.fx.motion=.45;clean.fx.glitch=0;clean.lyrics='[00:02.00]最初の歌詞\n[00:12.00]次の歌詞\n[00:22.00]最後の歌詞';
const cleanAudio={duration:30,buffer:{numberOfChannels:2}},cleanPlan=engine.plan(clean,cleanAudio),bounds=engine.outputSize(clean);
const cleanCaps={webCodecs:true,h264:true,aac:true,recorder:null},pixels={completed:true,issues:[]};
const pending=engine.checkMVQuality(clean,cleanPlan,cleanAudio,{start:0,end:30},pixels,cleanCaps);
assert.equal(pending.quality.score,98,'quality score reserves two points until the actual MP4 is inspected');
const validMP4={container:'mp4',videoCodec:'avc1',audioCodec:'mp4a',audioSamples:12,bytes:2048,duration:30,width:bounds[0],height:bounds[1]};
const finalReport=engine.checkMVQuality(clean,cleanPlan,cleanAudio,{start:0,end:30},pixels,cleanCaps,validMP4);
assert(finalReport.quality.score<100,'synthetic pixel pass alone cannot award 100');assert.equal(finalReport.checked.exportValidation,true);
const badMP4=engine.checkMVQuality(clean,cleanPlan,cleanAudio,{start:0,end:30},pixels,cleanCaps,{...validMP4,bytes:0});
assert(badMP4.errors.some(i=>i.code==='export_validation'));
const exportProject=engine.defaultProject();engine.applyExportPreset(exportProject,'xStandard');
assert.equal(exportProject.res,720);assert.equal(exportProject.fps,30);assert.equal(exportProject.aspect,'16:9');
const estimate=engine.estimateExport(exportProject,60,true);assert(estimate.bytes>0&&estimate.videoBitrate===6000000&&estimate.audioBitrate===192000);
console.log('Highlights, alternate DNA and preflight convergence passed.');
