'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const {engine,root}=require('./custom_test_support.cjs');
const previous=process.argv[2]||root,input=process.argv[3],output=process.argv[4];
const e=engine(),J=e.J,old=engine(previous),tests=[],measurements=[];
async function test(name,fn){await fn();tests.push({name,status:'PASS'});console.log(name,'PASS');}
(async()=>{
 const canvas=e.createCanvas(320,180),x=canvas.getContext('2d');x.fillStyle='#295782';x.fillRect(0,0,320,180);const url=canvas.toDataURL('image/png');
 const p=J.defaultProject();Object.assign(p,{title:'検証',lyrics:'[00:00.00]青黒大阪\n[00:03.11]青黒大阪',autoDirection:true});p.customBg={...p.customBg,enabled:true,dataUrl:url,filename:'背景.png'};
 p.visualAssets=Array.from({length:3},(_,i)=>({id:'image_'+i,name:'保存済み'+i,dataUrl:url,analysis:J.analyzeVisualAsset(canvas),pin:i===0?'excluded':'required'}));p.scenePins=[{from:0,assetId:'image_2'}];p.proAssets=[{id:'logo',dataUrl:url,role:'logo'}];
 const serialized=JSON.stringify(p),a={duration:7,bpm:120,beats:[0,.5,1,1.5,2,2.5,3,3.5,4,4.5,5,5.5,6,6.5],features:{energy:.7,beatStrength:.8,density:.7}};
 const direction=J.proposeDirection(p,a,{median:.3,detail:.4,chroma:.7});Object.assign(p,{style:direction.style,mood:direction.mood,fx:direction.fx,enabled:direction.enabled,seed:direction.seed});p.artDirection=J.makeArtDirection(p,a,direction);
 const original=JSON.stringify(p);
 J.enableSingleBackgroundMode();
 await test('single_background_rendering_preserves_archive_assets',()=>{const plan=J.plan(p,a);assert.equal(plan.visualAssets.length,1);assert.equal(plan.visualAssets[0].dataUrl,url);assert(!plan.assetDeck.some(a=>a.id==='logo'||a.id==='image_2'));assert(plan.storyboard.every(s=>s.assetId===null||s.assetId==='image_0'));assert.deepEqual(Object.keys(p).filter(k=>JSON.stringify(p[k])!==JSON.stringify(JSON.parse(original)[k])),[]);const disabled=J.plan({...p,customBg:{...p.customBg,enabled:false}},a);assert.equal(disabled.visualAssets.length,0);});
 await test('replacement_is_selected_even_when_old_assets_exist',()=>{const changed=canvas.toDataURL('image/webp');const plan=J.plan({...p,customBg:{...p.customBg,dataUrl:changed}},a);assert.equal(plan.visualAssets.length,1);assert.equal(plan.visualAssets[0].dataUrl,changed);assert(!plan.assetDeck.some(a=>a.dataUrl===url));assert.deepEqual(Object.keys(p).filter(k=>JSON.stringify(p[k])!==JSON.stringify(JSON.parse(original)[k])),[]);});
 await test('legacy_project_migration_and_storage_schema_preserved',()=>{const restored=J.migrateProject(JSON.parse(serialized));assert.equal(restored.visualAssets.length,3);assert.equal(restored.proAssets.length,1);assert.equal(restored.scenePins.length,1);assert.equal(J.PROJECT_SCHEMA_VERSION,3);for(const f of ['src/11_export.js'])assert.equal(fs.readFileSync(path.join(root,f),'utf8'),fs.readFileSync(path.join(previous,f),'utf8'));for(const aspect of ['16:9','9:16','1:1','4:5'])assert.equal(JSON.stringify(J.resolveExportSettings({...p,aspect})),JSON.stringify(old.J.resolveExportSettings({...p,aspect})));});
 await test('single_background_crop_does_not_double_manual_zoom',()=>{const q=J.singleBackgroundProject({...p,customBg:{...p.customBg,x:70,y:60,zoom:2}});assert.equal(q.customBg.zoom,2);assert.equal(q.visualAssets[0].crop.x,50);assert.equal(q.visualAssets[0].crop.y,50);assert(!q.visualAssets[0].crop.zoom);const info=J.backgroundResolutionInfo({...p,res:1080},{width:1254,height:1254});assert(info.scale>1.5);const video=J.singleBackgroundProject({...p,proAssets:[...p.proAssets,{id:'video',dataUrl:'data:video/mp4;base64,AAAA',role:'video'}]});assert.equal(video.proAssets.length,1);assert.equal(video.proAssets[0].id,'video');});
 await test('diagnostics_hidden_but_coordinate_lyrics_preserved',()=>{const plan=J.plan(p,a),R=new J.Renderer(),ctx=canvas.getContext('2d'),cut={line:0,lineText:'青黒大阪',text:'青黒大阪',dur:3,inDur:0};const env=R.makeEnv(ctx,plan,cut,{fg:'#fff'},{pass:'main',t:1,lt:1,scale:1});const draw=J.drawItem;let labels=[];J.drawItem=(env,it)=>labels.push(it.text);try{env.draw({debug:true,text:'X494 Y406'});env.draw({text:'X494 Y406'});assert.equal(labels.length,0);cut.lineText=cut.text='X494 Y406';env.draw({text:'X494 Y406'});assert.equal(labels.length,1);R._productionFrame=true;const prod=R.makeEnv(ctx,plan,cut,{fg:'#fff'},{pass:'main',t:1,lt:1,scale:1});prod.draw({debug:true,text:'X494 Y406'});assert.equal(labels.length,1);}finally{J.drawItem=draw;R.disposeAssets();}});
 await test('graphic_field_contrast_includes_character_colors',()=>{const env={plan:{customBg:{enabled:true},motionDirector7:true,visualWorld:{chapters:[{from:0,to:5,photoExit:true,fieldColor:'#E9AA31'}]}},cut:{line:0,text:'青黒大阪'},t:1,pass:'main',sc:{fg:'#fff'}};const it=J.adjustLocalReadability(env,{text:'青黒大阪',size:100,color:'#fff',charFn:()=>({color:'#fff',dy:2})});assert.equal(it.color,'#10151e');assert.equal(it.charFn(0).color,it.color);assert.equal(it.charFn(0).dy,2);const l=J.paletteLuma('#E9AA31');assert((l+.05)/.055>4.5);});
 await test('photographic_main_lyrics_receive_separation_edge',()=>{const env={plan:{customBg:{enabled:true}},cut:{line:0,text:'青黒大阪'},t:1,pass:'main',sc:{fg:'#fff'}};const it=J.adjustLocalReadability(env,{text:'青黒大阪',size:100,color:'#fff'});assert(it.stroke>=1);assert(it.strokeUnder);assert(it.shadow.blur>=2);});
 await test('vertical_rise_has_motion_headroom_and_safe_bounds',()=>{const env={plan:{directionOverrides7:{}},cut:{line:0,start:0,end:4,semanticIntent:{visualVerb:'rise'}},W:1920,H:1080,t:0,scale:1,ctx:e.createCanvas(1920,1080).getContext('2d')};const item={text:'青黒大阪',font:'gothic_black',size:230,x:960,y:540,vertical:true};const start=J.safeLyricItem(env,item);env.t=4;const end=J.safeLyricItem(env,item);const b=J.measureLyricItemBounds(env,end);assert(end.y<start.y-30);assert(b.y0>=1080*.08-1&&b.y1<=1080*.92+1);});
 await test('validated_image_input_preserves_original_bytes_and_dimensions',async()=>{const ui=engine(root),context=ui.context,code=fs.readFileSync(path.join(root,'src/12_ui.js'),'utf8');const handler=code.slice(code.indexOf('async function prepareBackgroundFile(file) {'),code.indexOf("window.addEventListener('pagehide'",code.indexOf('async function prepareBackgroundFile(file) {')));const bytes=canvas.toBuffer('image/png');context.file=new Blob([bytes],{type:'image/png'});context.file.name='原画.png';context.decodeImageFile=async()=>({width:6000,height:4000,close(){}});context.fileAsDataUrl=async b=>'data:'+b.type+';base64,'+Buffer.from(await b.arrayBuffer()).toString('base64');vm.runInContext(handler,context);const encoded=await vm.runInContext('prepareBackgroundFile(file)',context);assert(Buffer.from(encoded.split(',')[1],'base64').equals(bytes));assert(encoded.startsWith('data:image/png;base64,'));});
 await test('actual_background_handler_replaces_one_image_and_keeps_failed_inputs_atomic',async()=>{
  const ui=engine(root),context=ui.context;const source=fs.readFileSync(path.join(root,'src/12_ui.js'),'utf8');
  const handler=source.slice(source.indexOf('async function importVisualAssets(files){'),source.indexOf('function refreshVisualAssetsUI()',source.indexOf('async function importVisualAssets(files){')));
  const project=JSON.parse(original);context.S={project,renderer:new ui.J.Renderer(),plan:null};context.url=url;context.audio=a;context.error=null;context.imported=[];
  context.document.querySelector=()=>({click(){}});
  vm.runInContext(`let visualBusy=false,directionBusy=false,paletteBusy=false,exportPreflightBusy=false;
   function syncDirectionUI(){}function showMsg(){}function remember(){}function syncUI(){}function invalidateVisualDirection(){}function commit(){}function restartPreview(){}function toast(){}
   async function flushSave(){return true;}async function prepareBackgroundFile(file){if(file.invalid)throw Error('画像を読み込めません');imported.push(file.name);return url;}
   function replan(){S.plan=J.plan(S.project,audio);}
   ${handler}`,context);
  const snapshot=JSON.stringify(context.S.project);
  await vm.runInContext(`importVisualAssets([{name:'破損.png',size:32,invalid:true}])`,context);assert.equal(JSON.stringify(context.S.project),snapshot);
  await vm.runInContext(`importVisualAssets([{name:'新しい背景.png',size:32},{name:'追加しない.png',size:32}])`,context);
  assert.equal(context.S.project.customBg.filename,'新しい背景.png');assert.equal(context.S.project.visualAssets.length,3);assert.deepEqual(context.imported,['新しい背景.png']);
  await vm.runInContext(`directionBusy=true;importVisualAssets([{name:'処理中.png',size:32}])`,context);assert.deepEqual(context.imported,['新しい背景.png']);
  context.S.renderer.customBgBitmap?.close?.();context.S.renderer.disposeAssets();
 });
 if(input&&output){fs.mkdirSync(output,{recursive:true});const c=JSON.parse(fs.readFileSync(path.join(input,'DIRECTOR_CONTEXT.json'))),bg='data:image/webp;base64,'+fs.readFileSync(path.join(input,'background.webp')).toString('base64');
  const q=J.defaultProject();Object.assign(q,{title:'オオサカスタイル',artist:'@Arijigoku_GMB',lyrics:fs.readFileSync(path.join(input,'lyrics.lrc'),'utf8'),style:'noir',autoDirection:true,seed:777,res:720,fps:30});q.customBg={...q.customBg,enabled:true,dataUrl:bg};q.visualAssets=c.assets.map(a=>({...a,dataUrl:bg}));
  const audio={duration:c.duration,beats:c.beats,features:c.audioFeatures};const proposal=J.proposeDirection(q,audio,c.imageFeatures);Object.assign(q,{style:proposal.style,mood:proposal.mood,fx:proposal.fx,enabled:proposal.enabled,seed:proposal.seed});q.artDirection=J.makeArtDirection(q,audio,proposal);
  const plans=[old.J.plan(JSON.parse(JSON.stringify(q)),audio),J.plan(JSON.parse(JSON.stringify(q)),audio)],rs=[new old.J.Renderer(),new J.Renderer()];for(let i=0;i<2;i++){await rs[i].loadCustomBackground(bg);await rs[i].loadAssetDeck(plans[i]);}
  await test('attached_lyrics_and_all_aspect_output_settings_unchanged',()=>{assert.equal(JSON.stringify(plans[0].lines.map(l=>({text:l.text,start:l.start}))),JSON.stringify(plans[1].lines.map(l=>({text:l.text,start:l.start}))));assert.equal(plans[1].visualAssets.length,1);for(const aspect of ['16:9','9:16','1:1','4:5'])assert.equal(JSON.stringify(J.resolveExportSettings({...q,aspect})),JSON.stringify(old.J.resolveExportSettings({...q,aspect})));});
  const sheet=e.createCanvas(960,25*180),sx=sheet.getContext('2d'),snap=e.createCanvas(480,270),mask=e.createCanvas(480,270);const metrics=[];
  for(const [i,line]of c.lyrics.entries()){const time=line.start+Math.min(.6,(line.end-line.start)*.45);for(let n=0;n<2;n++){rs[n].frame(snap.getContext('2d'),plans[n],time,{scale:480/plans[n].W,production:true,lyricAuditCtx:mask.getContext('2d'),lyricAuditItems:[]});sx.drawImage(snap,n*480,i*180,480,180);if(n===1){const pixels=mask.getContext('2d').getImageData(0,0,480,270).data;let ink=0;for(let k=3;k<pixels.length;k+=4)if(pixels[k]>16)ink++;assert(ink>100,'lyric '+i+' has no visible pixels');metrics.push({line:i,time,inkPixels:ink});}}}
  fs.writeFileSync(path.join(output,'before-after.png'),sheet.toBuffer('image/png'));fs.writeFileSync(path.join(output,'sample-project.json'),JSON.stringify(q));measurements.push({case:'provided materials, reconstructed test project',exactOriginalProject:false,lyrics:metrics,priorAssets:plans[0].visualAssets.length,currentAssets:plans[1].visualAssets.length});for(const r of rs){r.customBgBitmap?.close?.();r.disposeAssets();}
 }
 fs.writeFileSync(path.join(root,'dev/single-background-quality-results.json'),JSON.stringify({tests,measurements,browser:'NOT_TESTED'},null,2));
})().catch(e=>{console.error(e);process.exitCode=1});
