/* Motion Director 6: causal raster realization, semantic intent and export certification. */
(()=>{'use strict';
const J=window.J,C=(x,a=0,b=1)=>Math.max(a,Math.min(b,+x||0)),avg=a=>a.length?a.reduce((s,v)=>s+v,0)/a.length:0;
// Platform policy and its legacy alias are centralized in Motion Director 7.
const verbs={pierce:{family:'directional',layout:'diag',motion:'push'},explode:{family:'impact',layout:'huge',motion:'beatPunch'},unite:{family:'gather',layout:'stack',motion:'push'},rise:{family:'directional',layout:'vcols',motion:'push'},flow:{family:'fluid',layout:'type',motion:'driftDiag'},freeze:{family:'still',layout:'type',motion:'stillCamera'},collapse:{family:'contract',layout:'stack',motion:'driftDiag'},expand:{family:'expand',layout:'huge',motion:'push'},echo:{family:'repeat',layout:'stack',motion:'driftDiag'}};
J.resolveVisualVerb=verb=>({...verbs[String(verb||'').toLowerCase()]||verbs.flow,verb:verbs[String(verb||'').toLowerCase()]?String(verb).toLowerCase():'flow',fallback:!verbs[String(verb||'').toLowerCase()]});
const baseValidate=J.validateDirectorPlan;
J.validateDirectorPlan=(input,project,plan,audio)=>{
 const copied=JSON.parse(JSON.stringify(input));for(const c of copied.candidates||[copied])if(c.schema==='jizura-director-v4')c.schema='jizura-director-v3';
 const r=baseValidate(copied,project,plan,audio);for(const c of r.candidates){const raw=(input.candidates||[input])[c.index];c.plan.lineSemantics=[];
  for(const s of (raw.lineSemantics||[]).slice(0,500)){if(!Number.isInteger(s.line)||!plan.lines[s.line]){r.warnings.push('意味情報の歌詞番号を無視しました');continue;}if(s.text!==undefined&&s.text!==plan.lines[s.line].text){r.errors.push('意味情報で歌詞を変更できません');r.valid=false;continue;}
   c.plan.lineSemantics.push({line:s.line,role:String(s.role||'phrase').slice(0,32),emotion:String(s.emotion||'neutral').slice(0,32),importance:C(s.importance),visualVerb:J.resolveVisualVerb(s.visualVerb).verb});}
  if(raw.schema==='jizura-director-v4')c.plan.semanticVersion=4;
 }return r;
};
const baseApply=J.applyDirectorPlan;J.applyDirectorPlan=(p,d,a)=>baseApply(p,{...d,schema:d.schema==='jizura-director-v4'?'jizura-director-v3':d.schema},a);
J.portraitSaliency=(plan)=>{
 if(plan.H<=plan.W)return {warnings:0,resolutions:[],checked:false};const map=plan.autoPalette?.localMap,values=map?.values||[],mw=map?.width||0,mh=map?.height||0;
 // Local-map pair is luminance/salience. Search actual image coordinates, never assume a subject box.
 const risk=(x,y)=>{if(!mw||!mh)return 0;let sum=0,n=0;for(let gy=0;gy<mh;gy++)for(let gx=0;gx<mw;gx++)if(Math.abs((gx+.5)/mw-x)<.24&&Math.abs((gy+.5)/mh-y)<.15){sum+=+values[(gy*mw+gx)*2+1]||0;n++;}return n?sum/n:0;};
 const resolutions=[];for(const c of plan.cuts.filter(c=>c.line>=0)){const points=[{x:.5,y:.46},{x:.5,y:.28},{x:.5,y:.68},{x:.34,y:.48},{x:.66,y:.48}],chosen=points.sort((a,b)=>risk(a.x,a.y)-risk(b.x,b.y))[0];c.portraitAnchor=chosen;const before=risk(.5,.46),after=risk(chosen.x,chosen.y);c.subjectScrim=after>.28?.52:after>.14?.25:0;
  if(after>.38){c.backgroundScene={...c.backgroundScene,blur:8,darkness:.48};c.portraitAbstract=true;}resolutions.push({line:c.line,before,after,method:after<before?'reposition':c.portraitAbstract?'blurred-scene':c.subjectScrim?'local-scrim':'clear',warning:after>.58&&!c.portraitAbstract});}
 if(plan.lyricPlacement&&mw)plan.lyricPlacement.subjectOverlap=Math.max(0,...resolutions.map(r=>r.warning?r.after:Math.min(.5,r.after)));
 return {checked:!!mw,warnings:resolutions.filter(r=>r.warning).length,resolutions};
};
J.mergeCoincidentStrongEvents=p=>{const all=[...p.events||[],...p.hypeTimeline||[]].filter(e=>(e.plannedImpact??e.amp)>=.25).sort((a,b)=>b.plannedImpact-a.plannedImpact||b.amp-a.amp),keep=[];for(const e of all)if(!keep.some(k=>Math.abs(k.t-e.t)<.11))keep.push(e);for(const e of all)if(!keep.includes(e)){const k=keep.find(k=>Math.abs(k.t-e.t)<.11);if(k){k.realizedReasons=[...new Set([...(k.realizedReasons||[]),k.reason,e.reason].filter(Boolean))];}}p.events=(p.events||[]).filter(e=>(e.plannedImpact??e.amp)<.25||keep.includes(e));p.hypeTimeline=(p.hypeTimeline||[]).filter(e=>(e.plannedImpact??e.amp)<.25||keep.includes(e));};
const makePlan=J.plan;J.plan=(project,audio)=>{const p=makePlan(project,audio);if(!p.motionDirector5)return p;p.motionDirector6=true;p.perceptualRepair={version:1,maxAttempts:3,attempts:0};
 p.musicalEvents=(p.beatHierarchy||[]).map(b=>({...b,musicalSalience:b.beatSalience}));
 for(const s of p.musicalStructure.sections)p.musicalEvents.push({time:s.from,musicalSalience:C(.6+s.energy*.35),source:'macro'});
 for(const l of p.lines)p.musicalEvents.push({time:l.start,musicalSalience:.6,source:'phrase'});
 p.musicalEvents.sort((a,b)=>a.time-b.time);p.lineSemantics=project.directorPlan?.lineSemantics||[];
 for(const c of p.cuts){const semantic=p.lineSemantics.find(s=>s.line===c.line);if(!semantic)continue;c.semanticIntent=semantic;const resolved=J.resolveVisualVerb(semantic.visualVerb);c.semanticResolved=resolved;const layout=p.H>p.W?J.resolvePortraitLayout(resolved.layout):resolved.layout;if(!project.overrides?.[c.line]?.layout&&J.LAYOUTS[layout]){c.layout=layout;c.params={...c.params,...J.LAYOUTS[layout].plan(J.rng(c.seed),c,c.style||p.style),font:c.params.font};}c.cam=resolved.motion;c.camP=J.CAMERA[c.cam]?.plan?.(J.rng(c.seed),c.style||p.style)||{};}
 for(const e of [...p.events,...p.hypeTimeline||[]]){e.plannedImpact=C(e.plannedImpact??e.amp);if(e.plannedImpact<.25)continue;const near=p.musicalEvents.filter(b=>Math.abs(b.time-e.t)<.42).sort((a,b)=>(Math.abs(a.time-e.t)-.2*a.musicalSalience)-(Math.abs(b.time-e.t)-.2*b.musicalSalience))[0];if(near){e.t=near.time;e.musicalSalience=near.musicalSalience;}e.semanticFamily=e.type==='chroma'?'accent':e.type==='shake'?'impact':e.type==='zoom'?'expand':'impact';}
 J.mergeCoincidentStrongEvents(p);p.events.sort((a,b)=>a.t-b.t);p.hypeTimeline?.sort((a,b)=>a.t-b.t);p.visualWorld.version=3;for(const [i,w] of p.visualWorld.chapters.entries())Object.assign(w,{paletteTreatment:i%2?'contrast':'club',texture:i%2?'grain':'clean',motionPhysics:p.visualWorld.motifs[0],layerDensity:.2+i*.12,transitionLanguage:w.transition||'wipe'});
 for(const c of p.cuts){const aliases={pulse:'beatPunch',drift:'driftDiag',hold:'stillCamera'};c.cam=aliases[c.cam]||c.cam;if(J.CAMERA[c.cam])c.camP=J.CAMERA[c.cam].plan?.(J.rng(c.seed),c.style||p.style)||{};}p.artDirection.vocabulary.cam=[...new Set(p.cuts.map(c=>c.cam).filter(Boolean))];p.portraitSaliency=J.portraitSaliency(p);return p;
};
const social=J.createSocialHookPlan;J.createSocialHookPlan=(p,c)=>{const s=social(p,c);s.motionDirector6=p.motionDirector6;s.socialHook.version=4;s.perceptualRepair={version:1,maxAttempts:3,attempts:0};for(const c of s.cuts)c.cam=({pulse:'beatPunch',drift:'driftDiag',hold:'stillCamera'}[c.cam]||c.cam);s.artDirection.vocabulary.cam=[...new Set(s.cuts.map(c=>c.cam).filter(Boolean))];s.portraitSaliency=J.portraitSaliency(s);J.mergeCoincidentStrongEvents(s);return s;};
J.motifPhysicsAt=(p,t)=>{const m=J.motifStateAt(p,t),wave=Math.sin(t*2.4);return {motif:m.id,x:wave*(m.id==='wave'?.007:.002),y:Math.cos(t*1.2)*.003,skew:m.id==='stripe'?wave*.9:0,rotation:m.id==='grid'?0:wave*.35,scale:1+Math.abs(wave)*.004};};
const eventsFor=p=>[...p.events||[],...p.hypeTimeline||[]].filter(e=>e.plannedImpact>=.25||e.amp>=.25);
const pulse=(e,t)=>{const dt=t-e.t;return dt>=0&&dt<Math.max(.14,e.dur||.2)?Math.exp(-dt*11):0;};
const type5=J.applyTypography5;J.applyTypography5=(env,it)=>{type5(env,it);const p=env.plan;if(!p.motionDirector6)return;const physics=J.motifPhysicsAt(p,env.t);it.skew=(it.skew||0)+physics.skew;it.rot=(it.rot||0)+physics.rotation;
 const semantic=env.cut.semanticIntent;if(semantic){const b=p.musicalEvents.reduce((best,b)=>Math.abs(b.time-env.t)<Math.abs(best.time-env.t)?b:best,{time:-10,musicalSalience:0}),hit=pulse({t:b.time,dur:.3},env.t)*semantic.importance;if(semantic.visualVerb==='rise')it.y-=env.H*.025*hit;if(semantic.visualVerb==='pierce')it.skew+=3*hit;if(semantic.visualVerb==='expand'||semantic.visualVerb==='explode')it.size*=1+.08*hit;if(semantic.visualVerb==='freeze')it.rot=0;}
 for(const e of eventsFor(p)){const k=pulse(e,env.t);if(!k||(e.repairStage||0)<2)continue;it.size*=1+.12*k;it.sx=(it.sx||1)*(1+.065*k);it.stroke=Math.max(it.stroke||0,it.size*.018*k);}
 if(env.cut.portraitAnchor){it.x=env.W*env.cut.portraitAnchor.x;it.y+=env.H*(env.cut.portraitAnchor.y-.49);}
 // Unverified variable interpolation never enters production; use geometry fallback.
 if(J.fontCapabilities(it.font).variable&&!p.variableFontVerified){it.fontWeight=null;it.fontAxes=null;}
};
const camera6=J.cameraAt;J.cameraAt=(p,t,range)=>{const a=camera6(p,t,range);if(!p.motionDirector6||!a)return a;const chapter=p.musicalStructure.sections.find(s=>t>=s.from&&t<s.to);if(!chapter)return a;const u=C((t-chapter.from)/Math.max(.1,chapter.to-chapter.from)),k=Math.sin(Math.PI*u)*(range?Math.sin(Math.PI*C((t-range.start)/Math.max(.1,range.end-range.start)))**2:1),ph=J.motifPhysicsAt(p,t),mode=chapter.role==='climax'?'beatPunch':chapter.role==='break'?'driftDiag':chapter.role==='build'?'push':'driftDiag';return {...a,s:a.s+k*(mode==='beatPunch'?.025:mode==='push'?.04:.01),x:a.x+p.W*ph.x*k,y:a.y+p.H*ph.y*k};};
const bg=J.Renderer.prototype.drawCustomBackground;J.Renderer.prototype.drawCustomBackground=function(ctx,p,t,...args){if(!p.motionDirector6)return bg.call(this,ctx,p,t,...args);const ph=J.motifPhysicsAt(p,t),k=Math.max(0,...eventsFor(p).map(e=>e.repairStage>=3?pulse(e,t):0));ctx.save();ctx.translate(p.W*ph.x,p.H*ph.y);ctx.translate(p.W/2,p.H/2);ctx.scale(ph.scale+k*.07,ph.scale+k*.07);ctx.translate(-p.W/2,-p.H/2);const v=bg.call(this,ctx,p,t,...args);ctx.restore();return v;};
const main=J.Renderer.prototype.drawCut; // Scrim is drawn in the typography pass before mainDraw via the core hook below.
const oldMain=J.mainDraw;J.mainDraw=(env,it)=>{if(env.cut?.subjectScrim&&env.pass==='main'){const c=env.ctx;c.save();c.fillStyle='#000';c.globalAlpha=env.cut.subjectScrim;c.fillRect(env.W*.06,env.H*(env.cut.portraitAnchor.y-.18),env.W*.88,env.H*.36);c.restore();}return oldMain(env,it);};
const baseFrame6=J.Renderer.prototype.frame;J.Renderer.prototype.frame=function(ctx,p,t,opt={}){const result=baseFrame6.call(this,ctx,p,t,opt);if(!p.motionDirector6||opt.backgroundOnly||opt.transparent)return result;const k=Math.max(0,...eventsFor(p).map(e=>e.repairStage>=3?pulse(e,t):0));if(k>.001){const w=ctx.canvas.width,h=ctx.canvas.height;ctx.save();ctx.setTransform(1,0,0,1,0,0);ctx.globalAlpha=k*.9;const edgePixel=ctx.getImageData(Math.floor(w/2),Math.min(4,h-1),1,1).data;ctx.strokeStyle=(edgePixel[0]+edgePixel[1]+edgePixel[2])/3>128?'#10151e':'#f6f3ea';ctx.lineWidth=Math.min(w,h)*.09;ctx.strokeRect(0,0,w,h);ctx.restore();}return result;};
const raster=(data,w,h)=>{const edge=[];let r=0,g=0,b=0,ink=0,x0=w,y0=h,x1=0,y1=0;for(let y=0;y<h;y++)for(let x=0;x<w;x++){const i=(y*w+x)*4,lum=(data[i]+data[i+1]+data[i+2])/765;r+=data[i]/255;g+=data[i+1]/255;b+=data[i+2]/255;if(data[i+3]>24){ink++;x0=Math.min(x0,x);y0=Math.min(y0,y);x1=Math.max(x1,x);y1=Math.max(y1,y);}edge.push(x&&y?Math.abs(lum-(data[i-4]+data[i-3]+data[i-2])/765):0);}return {data:Array.from(data),edge,palette:[r/(w*h),g/(w*h),b/(w*h)],bbox:ink?[x0/w,y0/h,x1/w,y1/h]:[0,0,0,0],ink};};
const diff=(a,b)=>avg(a.map((x,i)=>Math.abs(x-(b[i]||0))));
J.measureEventRealization=async(p,range=null,telemetry={})=>{
 const R=new J.Renderer(),w=128,h=Math.round(w*p.H/p.W),c=document.createElement('canvas'),mask=document.createElement('canvas');c.width=mask.width=w;c.height=mask.height=h;const ctx=c.getContext('2d'),mc=mask.getContext('2d');if(p.customBg?.enabled)await R.loadCustomBackground(p.customBg.dataUrl);await R.loadAssetDeck?.(p);
 const from=range?.start??0,to=range?.end??p.duration,events=eventsFor(p).filter(e=>e.t>=from&&e.t<to),samples=[];
 const snap=(plan,t)=>{const items=[];R.frame(ctx,plan,Math.max(from,Math.min(to-.001,t)),{scale:w/p.W,production:true,range,lyricAuditCtx:mc,lyricAuditItems:items});return {frame:raster(ctx.getImageData(0,0,w,h).data,w,h),foreground:raster(mc.getImageData(0,0,w,h).data,w,h),items};};
 try{for(const [index,e] of events.entries()){const control={...p,events:(p.events||[]).filter(x=>x!==e),hypeTimeline:(p.hypeTimeline||[]).filter(x=>x!==e)},pre=snap(p,e.t-.05),post=snap(p,e.t+Math.max(e.dur||.2,.15)+.05),peaks=[];
  for(const delay of [0,.033,.067,.1]){const time=Math.min(to-.001,e.t+delay),real=snap(p,time),without=snap(control,time),fg=diff(real.foreground.data,without.foreground.data)/255,edge=diff(real.foreground.edge,without.foreground.edge),bbox=diff(real.foreground.bbox,without.foreground.bbox),palette=diff(real.frame.palette,without.frame.palette),frame=diff(real.frame.data,without.frame.data)/255;
   const actualImpact=C(fg*32+edge*8+bbox*3+frame*9+palette*2);peaks.push({time,actualImpact,channels:{foreground:fg,edge,bbox,palette,frame},ink:real.foreground.ink});}
  const peak=peaks.sort((a,b)=>b.actualImpact-a.actualImpact)[0],musical=(p.musicalEvents||[]).reduce((a,b)=>Math.abs(b.time-peak.time)<Math.abs(a.time-peak.time)?b:a,{time:-10,musicalSalience:0}),planned=C(e.plannedImpact??e.amp),required=Math.max(.12,planned*.45);
  samples.push({index,type:e.type,time:e.t,peakTime:peak.time,preTime:Math.max(from,e.t-.05),postTime:Math.min(to,e.t+Math.max(e.dur||.2,.15)+.05),plannedImpact:planned,actualImpact:peak.actualImpact,realizationRatio:peak.actualImpact/Math.max(.01,planned),visible:peak.actualImpact>=required,major:planned>=.5,timingErrorMs:Math.abs(musical.time-peak.time)*1000,musicalSalience:musical.musicalSalience||0,channels:peak.channels,prePostForeground:diff(pre.foreground.data,post.foreground.data)/255,repairStage:e.repairStage||0});if(telemetry.onProgress){telemetry.onProgress({label:'音楽に合わせた演出の強さ・タイミングを検査しています',current:index+1,total:events.length});await new Promise(r=>setTimeout(r,0));}}
 }finally{R.customBgBitmap?.close?.();R.disposeAssets?.();}
 const major=samples.filter(s=>s.major),visibleRate=samples.length?100*samples.filter(s=>s.visible).length/samples.length:0,alignment=major.length?100*major.filter(s=>s.timingErrorMs<=100&&s.visible).length/major.length:0;
 const xs=samples.map(s=>s.actualImpact),ys=samples.map(s=>s.musicalSalience),mx=avg(xs),my=avg(ys),cov=avg(xs.map((x,i)=>(x-mx)*(ys[i]-my))),variance=Math.sqrt(avg(xs.map(x=>(x-mx)**2))*avg(ys.map(x=>(x-my)**2)));
 return {measured:true,samples,strongEventVisibleRate:Math.round(visibleRate),majorHit100ms:Math.round(alignment),impactAlignment:Math.round(avg(samples.map(s=>s.visible?(1-C(s.timingErrorMs/200))*s.musicalSalience:0))*100),timingErrorMs:Math.round(avg(samples.map(s=>s.timingErrorMs))),salienceCorrelation:variance?cov/variance:0,score:Math.round(avg(samples.map(s=>C(s.realizationRatio)))*100),majorFailures:major.filter(s=>!s.visible).length};
};
J.repairStrongEvents=async(p,range=null,telemetry={})=>{let measured=await J.measureEventRealization(p,range,telemetry),attempts=0;while(measured.samples.some(s=>!s.visible)&&attempts<3){attempts++;const all=eventsFor(p).filter(e=>e.t>=(range?.start??0)&&e.t<(range?.end??p.duration));for(const s of measured.samples.filter(s=>!s.visible)){const e=all[s.index];if(!e)continue;e.repairStage=attempts;e.amp=C(e.amp*1.35,.1,1);e.repairSemanticFamily=e.semanticFamily||'impact';}measured=await J.measureEventRealization(p,range,telemetry);}p.perceptualRepair={version:1,maxAttempts:3,attempts};p.eventRealization=measured;return measured;};
const analyze=J.analyzeRenderedFrames;J.analyzeRenderedFrames=async(p,range,audio,telemetry={})=>{if(p.motionDirector6)await J.repairStrongEvents(p,range,telemetry);const r=await analyze(p,range,audio,telemetry);if(!r.completed||!p.motionDirector6)return r;r.metrics.eventRealization=p.eventRealization;
 const R=new J.Renderer(),c=document.createElement('canvas');c.width=128;c.height=Math.round(128*p.H/p.W);const ctx=c.getContext('2d');if(p.customBg?.enabled)await R.loadCustomBackground(p.customBg.dataUrl);const shots=[];for(const s of p.musicalStructure.sections.filter(s=>s.to>(range?.start??0)&&s.from<(range?.end??p.duration))){const t=(s.from+s.to)/2;R.frame(ctx,p,t,{scale:128/p.W,production:true,range});shots.push(raster(ctx.getImageData(0,0,c.width,c.height).data,c.width,c.height));}R.customBgBitmap?.close?.();R.disposeAssets?.();r.metrics.worldDistinctness={measured:shots.length>1,comparisons:shots.slice(1).map((s,i)=>Math.round(C(diff(s.edge,shots[i].edge)*5+diff(s.palette,shots[i].palette)*2+diff(s.data,shots[i].data)/255*2)*100))};p.lastPixelQA=r;return r;};
const context=J.directorContext;J.directorContext=(p,plan,audio,image)=>({...context(p,plan,audio,image),schema:'jizura-director-context-v4',currentQualityScores:plan.currentQualityScores||null,currentQAFailures:plan.lastQAFailures||[],visualWorldSummary:plan.visualWorld,eventRealization:plan.eventRealization||{measured:false},semanticVocabulary:Object.keys(verbs),lineSemanticsOptional:true});
const prompt=J.directorPrompt;J.directorPrompt=()=>prompt().replace('jizura-director-v3','jizura-director-v4')+' 任意のlineSemanticsにline/role/emotion/importance(0..1)/visualVerbを指定。visualVerbはpierce/explode/unite/rise/flow/freeze/collapse/expand/echo。歌詞本文は変更禁止。';
J.createDirectorRevisionPack=async({project,plan,audio,audioFile,pixelQA})=>{
 const zip=new J.ZipWriter(),add=(n,v)=>zip.add(n,new TextEncoder().encode(v)),ctx=J.directorContext(project,plan,audio);add('DIRECTOR_CONTEXT.json',JSON.stringify(ctx,null,2));add('CURRENT_QA.json',JSON.stringify({quality:plan.currentQualityScores||null,pixels:(pixelQA||plan.lastPixelQA)?.metrics||null,eventRealization:plan.eventRealization},null,2));add('lyrics.lrc',project.lyrics||'');add('CHATGPT_REVISION_PROMPT.md',J.directorPrompt()+' CURRENT_QAとコンタクトシートから弱い実現度、意味、章間差、SNS可読性を修正。最大3候補をJSONのみで返してください。');add('PROJECT_SUMMARY.md',`# ${project.title||'JIZURA'}\nArtist: ${project.artist||''}\nHash: ${ctx.projectHash}\n`);
 const contact=document.createElement('canvas');contact.width=1200;contact.height=plan.H>plan.W?440:230;const cc=contact.getContext('2d'),R=new J.Renderer();if(plan.customBg?.enabled)await R.loadCustomBackground(plan.customBg.dataUrl);await R.loadAssetDeck?.(plan);for(const [i,w] of J.directorWindows(plan.duration).entries()){const frame=document.createElement('canvas');frame.width=240;frame.height=contact.height-28;R.frame(frame.getContext('2d'),plan,w.start+.1,{scale:240/plan.W,production:true});cc.drawImage(frame,i*240,28);cc.fillStyle='#fff';cc.font='14px sans-serif';cc.fillText(w.name,i*240+8,18);}R.customBgBitmap?.close?.();R.disposeAssets?.();const jpg=await new Promise(r=>contact.toBlob(r,'image/jpeg',.82));zip.add('CURRENT_DRAFT_CONTACT.jpg',new Uint8Array(await jpg.arrayBuffer()));
 if(project.customBg?.dataUrl){const source=await(await fetch(project.customBg.dataUrl)).blob();let bg=source;if(source.type!=='image/webp'){const bitmap=await createImageBitmap(source),bc=document.createElement('canvas');bc.width=bitmap.width;bc.height=bitmap.height;bc.getContext('2d').drawImage(bitmap,0,0);bitmap.close?.();bg=await new Promise(r=>bc.toBlob(r,'image/webp',.92));if(!bg||bg.type!=='image/webp')throw new Error('WebP conversion unavailable');}zip.add('background.webp',new Uint8Array(await bg.arrayBuffer()));}if(audioFile instanceof Blob)zip.add('audio.'+(/\.(m4a|wav|mp3|ogg)$/i.exec(audioFile.name||'')?.[1]||'bin'),new Uint8Array(await audioFile.arrayBuffer()));else add('README.txt','元音源もChatGPTへ手動添付してください。');return zip.finish();
};
const compare6=J.compareDirectorCandidates;J.compareDirectorCandidates=async(...args)=>{const r=await compare6(...args);for(const c of r){const q=c.renderPlan.currentQualityScores||{};c.quality.musicalDirection=q.musicalDirection??c.quality.direction;c.quality.semanticDirection=q.semanticDirection??null;c.quality.typography=q.typography??0;c.quality.visualWorld=q.visualWorld??0;c.quality.eventRealization=q.eventRealization??0;}return r;};
const quality=J.checkMVQuality;J.checkMVQuality=(p,plan,audio,range,pixel,caps,validation)=>{const r=quality(p,plan,audio,range,pixel,caps,validation);if(!plan.motionDirector6)return r;const q=r.quality,event=pixel?.metrics?.eventRealization,semantic=plan.lineSemantics?.length?Math.round(100*plan.cuts.filter(c=>c.semanticResolved).length/Math.max(1,plan.cuts.filter(c=>c.lineSemantics||plan.lineSemantics.some(s=>s.line===c.line)).length)):null;
 q.musicalDirectionScore=event?Math.round(q.directionScore*.5+event.impactAlignment*.5):q.directionScore;q.semanticDirectionScore=semantic;q.eventRealizationScore=event?.score??null;q.worldDistinctness=pixel?.metrics?.worldDistinctness;q.productionDomains={technical:q.technicalScore,musicalDirection:q.musicalDirectionScore,semanticDirection:semantic,typography:q.typographyScore,visualWorld:q.visualWorldScore,eventRealization:q.eventRealizationScore,social:q.socialScore};
 q.creativeScore=Math.round(avg([q.musicalDirectionScore,q.typographyScore,q.visualWorldScore,q.eventRealizationScore??0,...semantic===null?[]:[semantic]]));
 const fail=(code,message)=>{if(!r.issues.some(i=>i.code===code))r.issues.push({code,severity:'ERROR',message,exportBlocking:false});};if(event&&event.applicable!==false&&(event.strongEventVisibleRate<95||event.majorFailures))fail('EVENT_NOT_REALIZED','強い演出の実画素への実現率が不足しています');if(plan.portraitSaliency?.warnings)fail('SUBJECT_CRITICAL_OVERLAP','主要被写体への文字の重なりがあります');if(semantic!==null&&semantic<95)fail('BROKEN_DIRECTOR_INTENT','歌詞意味の演出が一部実現していません');
 for(const [old,code] of [['lyric_small','UNREADABLE_TEXT'],['contrast','UNREADABLE_TEXT'],['audio_missing','MISSING_AUDIO'],['black_frame','BLACK_FRAME'],['export_validation','EXPORT_INVALID']])if(r.issues.some(i=>i.code===old))fail(code,'品質条件: '+code);if(q.worldDistinctness?.measured&&q.worldDistinctness.comparisons.some(v=>v<8))fail('BROKEN_STYLE_ARC','章の画素差が不足しています');q.exportVerified=validation?.certification?.passed===true;q.certified100=!!q.exportVerified&&q.technicalScore>=99&&q.musicalDirectionScore>=95&&q.typographyScore>=95&&q.visualWorldScore>=95&&q.eventRealizationScore>=95&&q.creativeScore>=95&&(!plan.socialHook||q.socialScore>=95&&plan.portraitSaliency?.warnings===0&&(pixel?.metrics?.loopQuality||0)>=85)&&!r.issues.some(i=>i.severity==='ERROR');
 if(event?.applicable!==false&&(event?.strongEventVisibleRate<95||event?.majorFailures))q.creativeScore=Math.min(94,q.creativeScore);q.overallScore=q.certified100?100:Math.min(99,Math.round(q.technicalScore*.3+q.creativeScore*.45+q.socialScore*.25));q.domains=[{key:'technical',score:q.technicalScore,max:100},{key:'creative',score:q.creativeScore,max:100},{key:'social',score:q.socialScore,max:100}];q.score=q.overallScore;q.perfectEligible=q.certified100;q.hardGates.passed=!r.issues.some(i=>i.severity==='ERROR');r.errors=r.issues.filter(i=>i.severity==='ERROR');r.ready=!r.errors.some(i=>i.exportBlocking!==false);plan.currentQualityScores=q.productionDomains;plan.lastQAFailures=r.errors.map(i=>({code:i.code,message:i.message}));return r;};
J.verifyVariableFontRaster=async key=>{const cap=J.fontCapabilities(key),axis=cap.axes.find(a=>a.tag==='wght');if(!cap.variable||!axis)return {verified:false,status:'STATIC_FALLBACK'};const font=J.FONTS[key],family=String(font.family).replace(/^"|"$/g,''),c=document.createElement('canvas');c.width=400;c.height=100;const ctx=c.getContext('2d'),samples=[];for(const weight of [axis.min,axis.max]){await document.fonts.load(`${weight} 48px "${family}"`);ctx.clearRect(0,0,400,100);ctx.font=`${weight} 48px "${family}"`;ctx.fillText('日本語ABC',8,70);const data=ctx.getImageData(0,0,400,100).data;samples.push({data:Array.from(data),width:ctx.measureText('日本語ABC').width});}const delta=diff(samples[0].data,samples[1].data)/255;return {verified:delta>.002,status:delta>.002?'BROWSER_AXIS_VISIBLE':'VARIABLE_FALLBACK',axis:'wght',difference:delta,widths:samples.map(s=>s.width),exportVerified:false};};
J.certifyExport=async(blob,expected)=>{
 const inspection=J.inspectMP4Buffer(await blob.arrayBuffer(),{requireAudio:expected.audio}),video=document.createElement('video'),url=URL.createObjectURL(blob),checks={container:inspection.container==='mp4',video:inspection.videoCodec==='avc1',audio:!expected.audio||inspection.audioCodec==='mp4a',resolution:inspection.width===expected.width&&inspection.height===expected.height,duration:Math.abs(inspection.duration-expected.duration)<.2,frames:Math.abs(inspection.videoSamples-expected.duration*expected.fps)<2};
 const wait=name=>J.waitMediaEvent(video,name,{signal:expected.signal});
 try{video.muted=true;video.preload='auto';const loaded=wait('loadeddata');video.src=url;await loaded;checks.fps=Math.abs(inspection.videoSamples/(inspection.videoDuration||inspection.duration)-expected.fps)<.2;checks.avSync=!expected.audio||Math.abs(inspection.videoDuration-inspection.audioDuration)<.12;checks.reloaded=true;checks.avDuration=Math.abs(video.duration-inspection.duration)<.2;const c=document.createElement('canvas');c.width=96;c.height=54;const ctx=c.getContext('2d'),frames=[];
  for(const t of [0,Math.min(video.duration-.08,.25),video.duration*.5,Math.max(0,video.duration-.08)]){if(Math.abs(video.currentTime-t)>.001){const seek=wait('seeked');video.currentTime=t;await seek;}ctx.drawImage(video,0,0,96,54);const pixels=ctx.getImageData(0,0,96,54).data;frames.push({time:t,nonBlack:J.nonBlackRGBFraction(pixels)});}checks.seek=true;checks.blackFrames=frames.every(f=>f.nonBlack>.01);checks.firstLast=frames[0].nonBlack>.01&&frames.at(-1).nonBlack>.01;
  const nativeFrames=frames.slice(),nativeChecks={blackFrames:checks.blackFrames,firstLast:checks.firstLast};let independentPixels=checks.blackFrames&&checks.firstLast?{status:'NOT_APPLICABLE',reason:'native probe passed; independent recovery unnecessary'}:{status:'UNMEASURED',reason:'independent recovery disabled or unavailable'};
  if(J.cinemaV3?.enabled&&(!checks.blackFrames||!checks.firstLast)&&window.JIZURAMedia?.sampleMP4){const control=new AbortController(),abort=()=>control.abort(),decoded=[];expected.signal?.addEventListener('abort',abort,{once:true});if(expected.signal?.aborted)abort();try{await J.waitExportStep(()=>window.JIZURAMedia.sampleMP4(blob,nativeFrames.map(f=>f.time),{width:96,height:54,signal:control.signal,onSample:(time,pixels)=>decoded.push({time,nonBlack:J.nonBlackRGBFraction(pixels)})}),{signal:control.signal,onTimeout:abort,timeout:15000,label:'MP4黒フレームの独立デコード検査'});if(decoded.length===nativeFrames.length){independentPixels={status:'MEASURED',source:'independent encoded MP4 decoder; same RGB threshold and timestamps',frames:decoded};checks.blackFrames=decoded.every(f=>f.nonBlack>.01);checks.firstLast=decoded[0].nonBlack>.01&&decoded.at(-1).nonBlack>.01;frames.splice(0,frames.length,...decoded);}else independentPixels={status:'UNMEASURED',reason:'incomplete independent frame coverage',sampleCount:decoded.length};}catch(error){if(expected.signal?.aborted)throw error;independentPixels={status:'UNMEASURED',reason:error.message};}finally{control.abort();expected.signal?.removeEventListener('abort',abort);}}
  return {...inspection,certification:{passed:Object.values(checks).every(Boolean),checks,frames,nativeFrames,nativeChecks,independentPixels,path:'Browser WebCodecs → MP4 Blob → HTMLVideoElement reload/decode',fps:inspection.videoSamples/(inspection.videoDuration||inspection.duration),avSync:'track timestamp/duration; no perceptual sync claim'}};
 }finally{video.removeAttribute('src');video.load();URL.revokeObjectURL(url);}
};
const exportMP4=J.exportMP4;J.exportMP4=async args=>{const out=await exportMP4(args);args.onProgress?.(.995,'生成済みMP4のフレーム・音声・タイミングを検査中…',{stage:'verify',indeterminate:true});out.validation=await J.certifyExport(out.blob,{width:out.width,height:out.height,fps:args.plan.fps,duration:(args.range?.end??args.plan.duration)-(args.range?.start??0),audio:!!out.audio,signal:args.signal});if(!out.validation.certification.passed)throw Object.assign(Error('EXPORT_INVALID: MP4再読込検査に失敗しました '+JSON.stringify(out.validation.certification.checks)),{inspection:out.validation});return out;};
})();
