/* Motion Director 7. Independent pixel observer never receives a render plan or event list. */
(()=>{'use strict';
const J=window.J,clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,Number(v)||0)),mean=a=>a.length?a.reduce((x,y)=>x+y,0)/a.length:0,quantile=(a,p)=>{const s=[...a].sort((x,y)=>x-y);return s.length?s[Math.floor((s.length-1)*p)]:0;},delta=(a,b)=>mean(a.map((v,i)=>Math.abs(v-(b[i]||0))));
J.MOTION_DIRECTOR_VERSION='7.1';
const clean=value=>{if(Array.isArray(value))return value.map(clean);if(value&&typeof value==='object')return Object.fromEntries(Object.keys(value).sort().filter(k=>!['lastPixelQA','currentQualityScores','lastQAFailures','exportProvenance','observerQA','worldQA','semanticQA','lastQualityTarget','provenance','pixelQA'].includes(k)&&typeof value[k]!=='function').map(k=>[k,clean(value[k])]));return value;};
J.canonicalJSON=v=>JSON.stringify(clean(v));
J.sha256=async data=>{
 const bytes=typeof data==='string'?new TextEncoder().encode(data):data instanceof Uint8Array?data:new Uint8Array(data);
 if(globalThis.crypto?.subtle)return [...new Uint8Array(await globalThis.crypto.subtle.digest('SHA-256',bytes))].map(v=>v.toString(16).padStart(2,'0')).join('');
 // Portable fallback for non-secure local pages. SHA-256, not the legacy Director compatibility hash.
 const K=[],H=[],prime=n=>{for(let d=2;d*d<=n;d++)if(n%d===0)return false;return true;};for(let n=2;K.length<64;n++)if(prime(n)){if(H.length<8)H.push((Math.sqrt(n)%1*4294967296)|0);K.push((Math.cbrt(n)%1*4294967296)|0);}const length=Math.ceil((bytes.length+9)/64)*64,padded=new Uint8Array(length);padded.set(bytes);padded[bytes.length]=128;const view=new DataView(padded.buffer);view.setUint32(length-8,Math.floor(bytes.length/536870912));view.setUint32(length-4,bytes.length*8);const rot=(x,n)=>(x>>>n)|(x<<(32-n));
 for(let off=0;off<length;off+=64){const w=new Int32Array(64);for(let i=0;i<16;i++)w[i]=view.getInt32(off+i*4);for(let i=16;i<64;i++){const a=w[i-15],b=w[i-2];w[i]=(w[i-16]+(rot(a,7)^rot(a,18)^(a>>>3))+w[i-7]+(rot(b,17)^rot(b,19)^(b>>>10)))|0;}let [a,b,c,d,e,f,g,h]=H;for(let i=0;i<64;i++){const s1=rot(e,6)^rot(e,11)^rot(e,25),t1=(h+s1+((e&f)^(~e&g))+K[i]+w[i])|0,t2=((rot(a,2)^rot(a,13)^rot(a,22))+((a&b)^(a&c)^(b&c)))|0;h=g;g=f;f=e;e=(d+t1)|0;d=c;c=b;b=a;a=(t1+t2)|0;}[a,b,c,d,e,f,g,h].forEach((v,i)=>H[i]=(H[i]+v)|0);}return H.map(v=>(v>>>0).toString(16).padStart(8,'0')).join('');
};
J.exportPolicies={x:{platform:'X free',checkedAt:'2026-09-30',source:'https://help.x.com/en/using-x/x-videos',aspect:['16:9','9:16','1:1','4:5'],resolution:[720,1080],fps:[24,30,60],codec:['avc1','mp4a'],bitrate:[6e6,20e6],duration:140,maxBytes:512*1024*1024},youtube:{platform:'YouTube',checkedAt:'2026-09-30',source:'https://support.google.com/youtube/answer/1722171',aspect:['16:9','9:16'],resolution:[720,1080,1440,2160],fps:[24,30,60],codec:['avc1','mp4a'],bitrate:[8e6,53e6],duration:null},master:{platform:'Master',checkedAt:'2026-09-30',source:'JIZURA local production policy',aspect:['16:9','9:16','1:1','4:5'],resolution:[720,1080,1440,2160],fps:[24,30,60],codec:['avc1','mp4a'],bitrate:[12e6,60e6],duration:null}};
J.EXPORT_POLICY={checkedAt:J.exportPolicies.x.checkedAt,source:J.exportPolicies.x.source,x:{maxDuration:J.exportPolicies.x.duration,maxBytes:J.exportPolicies.x.maxBytes,video:'avc1',audio:'mp4a',fps:30},youtube:{fps:30},master:{fps:30}};
J.chooseAdaptiveFPS=(p,caps={})=>{if(p.exportSettings?.fpsMode!=='auto')return {fps:p.fps||30,reason:'manual override'};const energy=p.artDirection?.visualDNA?.motionAmount??p.analysis?.energy??.5,stepped=(p.fx?.koma||0)>0,platform=p.exportSettings?.preset?.startsWith('x')?'x':p.exportSettings?.preset==='youtube1080'?'youtube':'master',allowed=J.exportPolicies[platform].fps;const wanted=stepped||energy<.28?24:energy>.68?60:30;const fps=caps.maxFPS?wanted<=caps.maxFPS?wanted:30:wanted;return {fps:allowed.includes(fps)?fps:30,reason:stepped?'stepped':energy>.68?'rapid typography':energy<.28?'cinematic':'standard',capabilityVerified:!!caps.maxFPS};};
// Observer features are derived solely from pixels. A supplied raster mask is optional; MP4 uses inferred edges.
J.observePixelFrame=(rgba,width,height,foreground=null)=>{
 const n=width*height,luma=new Float32Array(n),edge=new Float32Array(n),palette=[0,0,0],fg=new Float32Array(n),sum=[0,0],bbox=[width,height,-1,-1];let area=0,edgeArea=0,mxy=0,mxx=0,myy=0;
 for(let i=0;i<n;i++){const j=i*4;luma[i]=(rgba[j]*.2126+rgba[j+1]*.7152+rgba[j+2]*.0722)/255;for(let c=0;c<3;c++)palette[c]+=rgba[j+c]/255/n;}
 for(let y=1;y<height-1;y++)for(let x=1;x<width-1;x++){const i=y*width+x,dx=luma[i+1]-luma[i-1],dy=luma[i+width]-luma[i-width];edge[i]=Math.hypot(dx,dy);edgeArea+=edge[i];fg[i]=foreground?foreground[i*4+3]/255:edge[i]>.23&&Math.abs(luma[i]-mean(palette))>.18?1:0;if(fg[i]>.12){area++;sum[0]+=x;sum[1]+=y;bbox[0]=Math.min(bbox[0],x);bbox[1]=Math.min(bbox[1],y);bbox[2]=Math.max(bbox[2],x);bbox[3]=Math.max(bbox[3],y);mxy+=x*y;mxx+=x*x;myy+=y*y;}}
 const center=area?[sum[0]/area/width,sum[1]/area/height]:[.5,.5],spread=area?Math.max(0,(mxx/area-(center[0]*width)**2)/width**2+(myy/area-(center[1]*height)**2)/height**2):0;
 return {luma:Array.from(luma),edge:Array.from(edge),fg:Array.from(fg),palette,area:area/n,bbox:area?[bbox[0]/width,bbox[1]/height,bbox[2]/width,bbox[3]/height]:[0,0,0,0],center,spread,texture:edgeArea/n,angle:area?Math.atan2(2*(mxy/area-center[0]*width*center[1]*height),(mxx/area-(center[0]*width)**2)-(myy/area-(center[1]*height)**2)):0,foregroundSource:foreground?'raster-mask':'inferred-edge-contrast'};
};
J.observeVisualPeaks=frames=>{
 const signals=[];for(let i=1;i<frames.length;i++){const a=frames[i-1].features,b=frames[i].features,dt=Math.max(.001,frames[i].time-frames[i-1].time),d={frame:delta(a.luma,b.luma),foreground:delta(a.fg,b.fg),edge:delta(a.edge,b.edge),bbox:delta(a.bbox,b.bbox),palette:delta(a.palette,b.palette),camera:Math.hypot(b.center[0]-a.center[0],b.center[1]-a.center[1]),crop:delta(a.edge,b.edge),areaChange:Math.abs(b.area-a.area),typographyDominance:b.area};const pre=mean(signals.slice(-3).map(s=>s.velocity)),velocity=(d.foreground*.5+d.edge*.2+d.camera*.3)/dt,stillness=1/(1+pre*4),raw=d.frame*1.4+d.foreground*2.2+d.edge*1.1+d.bbox*.55+d.palette*.75+d.camera*.45+d.areaChange*.8;signals.push({time:frames[i].time-dt/2,observationInterval:[frames[i-1].time,frames[i].time],channels:d,raw,velocity,preEventStillness:stillness,perceivedImpact:raw*(.8+stillness*.4),features:b});}
 const scores=signals.map(s=>s.perceivedImpact),threshold=Math.max(.007,quantile(scores,.85)),peaks=[];for(let i=0;i<signals.length;i++){const s=signals[i];if(s.perceivedImpact<threshold||s.perceivedImpact<(signals[i-1]?.perceivedImpact??-Infinity)||s.perceivedImpact<(signals[i+1]?.perceivedImpact??-Infinity))continue;const prev=peaks.at(-1);if(prev&&s.time-prev.time<.22){if(prev.perceivedImpact<s.perceivedImpact)peaks[peaks.length-1]=s;}else peaks.push(s);}
 const hero=quantile(peaks.map(s=>s.perceivedImpact),.96),major=quantile(scores,.96);for(const p of peaks){p.percentile=100*scores.filter(s=>s<=p.perceivedImpact).length/Math.max(1,scores.length);p.tier=p.perceivedImpact>=hero?'Hero':p.perceivedImpact>=major?'Major':'Medium';}const heroes=peaks.filter(p=>p.tier==='Hero').sort((a,b)=>b.perceivedImpact-a.perceivedImpact);for(const p of heroes.slice(3))p.tier='Major';
 return {independent:true,source:'rendered pixels only; no planner/events input',threshold,sampleCount:frames.length,sampleStep:frames.length>1?frames[1].time-frames[0].time:null,peaks:peaks.map(({features,...s})=>s),signals:signals.map(({features,...s})=>s),frameSummaries:frames.map(f=>({time:f.time,area:f.features.area,bbox:f.features.bbox,center:f.features.center,palette:f.features.palette,spread:f.features.spread,texture:f.features.texture,angle:f.features.angle})),foregroundSource:frames[0]?.features.foregroundSource||'unknown'};
};
J.musicalTargets=p=>({BEAT:(p.beatHierarchy||[]).map(b=>b.time),SALIENT_BEAT:(p.beatHierarchy||[]).filter(b=>b.beatSalience>=.45).map(b=>b.time),LYRIC_ONSET:p.lines.map(l=>l.start),PHRASE_ONSET:p.lines.filter((l,i)=>!i||l.start-p.lines[i-1].end>.15||i%4===0).map(l=>l.start),SECTION:p.musicalStructure?.sections.map(s=>s.from)||[],BREAK:p.musicalStructure?.sections.filter(s=>s.role==='break').map(s=>s.from)||[],FREE:[]});
const nearest=(times,t)=>times.length?times.reduce((a,b)=>Math.abs(b-t)<Math.abs(a-t)?b:a):null;
J.alignObservedPeaks=(observer,targets)=>{const peaks=observer.peaks.map(p=>{const distances=Object.fromEntries(['BEAT','LYRIC_ONSET','PHRASE_ONSET','SECTION'].map(type=>{const time=nearest(type==='BEAT'?(targets.SALIENT_BEAT||targets.BEAT||[]):targets[type]||[],p.time);return [type,time===null?null:Math.abs(time-p.time)*1000];}));const values=Object.entries(distances).filter(([,d])=>d!==null).sort((a,b)=>a[1]-b[1]);return {...p,distances,targetType:values[0]?.[0]||'FREE',timingErrorMs:values[0]?.[1]??null,aligned:values.length>0&&values[0][1]<=100+1e-6};});const strong=peaks.filter(p=>['Hero','Major'].includes(p.tier));return {independent:true,peaks,score:strong.length?Math.round(100*strong.filter(p=>p.aligned).length/strong.length):0,beatOnlyScore:strong.length?Math.round(100*strong.filter(p=>p.distances.BEAT!==null&&p.distances.BEAT<=100+1e-6).length/strong.length):0,target:'JIZURA internal target: observed strong peaks ±100ms >=85%; not an industry standard',sampleCount:observer.sampleCount};};
J.plannedEventAlignment=(p,range)=>{const targets=J.musicalTargets(p),events=[...p.events||[],...p.hypeTimeline||[]].filter(e=>(e.amp||0)>=.25&&(!range||e.t>=range.start&&e.t<range.end)),samples=events.map(e=>{const type=e.targetType||'FREE',target=nearest(targets[type]||[],e.t),error=target===null?null:Math.abs(target-e.t)*1000;return {time:e.t,targetType:type,timingErrorMs:error,pass:type==='FREE'?null:error!==null&&error<=100+1e-6};}),timed=samples.filter(s=>s.pass!==null),beats=samples.filter(s=>s.targetType==='BEAT');return {score:timed.length?Math.round(100*timed.filter(s=>s.pass).length/timed.length):null,beatSync:beats.length?Math.round(100*beats.filter(s=>s.pass).length/beats.length):null,samples};};
const worldAt=(p,t)=>p.visualWorld?.chapters.find(w=>t>=w.from&&t<w.to)||p.visualWorld?.chapters.at(-1);
J.chapterIntent=(s,previous,context)=>{const energy=clamp(s.energy),deltaEnergy=energy-(previous?.energy??energy),repeat=context.repetition||0,semantic=context.semantic||'';return /climax|celebrat|payoff/.test(semantic)||s.role==='climax'?'climax':/command|aggress|conflict/.test(semantic)?'conflict':s.role==='break'||deltaEnergy<-.23?'break':/resolv|calm/.test(semantic)||['outro','finale'].includes(s.role)?'resolution':s.role==='hook'?'identity':s.role==='build'||deltaEnergy>.13?'build':repeat>1&&Math.abs(deltaEnergy)<.1?'reprise':energy<.35?'tension':deltaEnergy<-.09?'release':'identity';};
// Keep serializable preferences in the plan so raster repairs and social clones retain them.
J.captureDirectionPreferences7=(p,project)=>{
 p.directionOverrides7=JSON.parse(JSON.stringify(project?.overrides||p.directionOverrides7||{}));
 p.directorLyricDirectives7=JSON.parse(JSON.stringify(project?.directorPlan?.lyricDirectives||p.directorLyricDirectives7||[]));
 p.directorSections7=JSON.parse(JSON.stringify(project?.directorPlan?.sections||p.directorSections7||[]));
};
const layoutParams7=(p,c,id)=>({...c.params,...J.LAYOUTS[id].plan(J.rng(c.seed),{...c,W:p.W,H:p.H,text:c.text||p.lines[c.line]?.text||'',n:[...(c.text||p.lines[c.line]?.text||'')].length,dur:c.end-c.start},c.style||p.style),font:c.params.font});
J.applyExplicitOverrides7=p=>{
 for(const c of p.cuts){const o=p.directionOverrides7?.[c.line];if(!o||c.line<0)continue;
  if(o.layout&&J.LAYOUTS[o.layout]){c.layout=o.layout;c.params=layoutParams7(p,c,c.layout);c.kineticGrouped=false;}
  for(const [key,registry,param] of [['cam',J.CAMERA,'camP'],['trans',J.TRANS,'transP'],['hold',J.HOLD,'holdP'],['enter',J.ENTER,'enterP'],['exit',J.EXIT,'exitP']])if(o[key]&&registry[o[key]]){c[key]=o[key];if(registry[o[key]].plan)c[param]=registry[o[key]].plan(J.rng(c.seed),c.style||p.style)||{};}
 }
 for(const key of ['layout','cam','trans','hold'])p.artDirection.vocabulary[key]=[...new Set([...(p.artDirection.vocabulary[key]||[]),...p.cuts.map(c=>c[key]).filter(Boolean)])];
};
J.buildVisualWorld7=(p,project)=>{
 J.captureDirectionPreferences7(p,project);
 const chapters=[],sections=p.musicalStructure?.sections||[];let prev=null;const scheme=p.style.schemes[0],identity=['primary-font','accent-palette'];
 for(const section of sections){
  const cuts=p.cuts.filter(c=>c.line>=0&&c.start>=section.from&&c.start<section.to),sem=cuts.map(c=>c.semanticIntent?.role||'').join(' '),texts=cuts.map(c=>p.lines[c.line]?.text||''),repetition=texts.length-new Set(texts).size,director=p.directorSections7.find(d=>section.from>=d.from&&section.from<d.to);
  const intent=J.chapterIntent(section,prev,{repetition,semantic:sem+' '+(director?.motionIntent||'')}),energy=clamp(section.energy),type=String(director?.typographyIntent||'').toLowerCase(),sceneIntent=String(director?.sceneIntent||'').toLowerCase(),motion=[].concat(director?.cameraIntent||[],director?.motionIntent||[]).join(' ').toLowerCase();
  const architecture=/vertical/.test(type)?'vertical':/giant|hero|impact/.test(type)?'giant':/split/.test(type)?'split':/diag/.test(type)?'diagonal':/stack/.test(type)?'stacked':intent==='climax'?'giant':intent==='break'?'vertical':['build','conflict'].includes(intent)?'diagonal':intent==='reprise'?'stacked':p.H>p.W?'stacked':'signage';
  const explicitScene=/detail/.test(sceneIntent)?'DETAIL':/mono/.test(sceneIntent)?'MONO':/tight|subject/.test(sceneIntent)?'TIGHT':/blur/.test(sceneIntent)?'BLURRED_TYPE':/wide/.test(sceneIntent)?'WIDE':/graphic/.test(sceneIntent)?'GRAPHIC_HEAVY':null;
  const photoExit=explicitScene?explicitScene==='GRAPHIC_HEAVY':['break','tension','climax'].includes(intent),treatment=['climax','conflict'].includes(intent)?'accent-field':['break','tension'].includes(intent)?'mono-negative':'photo-color';
  const w={...section,intent,chapterIntent:intent,backgroundWorld:photoExit?intent==='climax'?'graphic-field':'typography-only':'photo',photoExit,typographyArchitecture:architecture,architecture,paletteTreatment:treatment,texture:energy>.7?'speed-grain':energy<.35?'clean':'fine-grid',motifState:intent==='climax'?'expand':intent==='break'?'break':intent==='resolution'?'resolve':intent==='build'?'develop':'introduce',motionPhysics:p.visualWorld.motifs[0],cameraLanguage:/still|calm|lock|freeze/.test(motion)?'locked':/push|rush/.test(motion)?'push':intent==='break'?'locked':intent==='climax'?'impact':intent==='build'?'push':'float',transitionLanguage:intent==='break'?'cut':intent==='climax'?'wipe':'crossfade',layerDensity:clamp(.15+energy*.55+(intent==='climax'?.15:0),.1,.85),identity,energy,energyDelta:energy-(prev?.energy??energy),repetition,targetWorldDistance:prev?clamp(.22+Math.abs(energy-prev.energy)*.45+(intent!==prev.intent?.22:0)+(intent==='climax'?.18:0),.2,.95):0,scene:explicitScene||(photoExit?'GRAPHIC_HEAVY':energy>.6?'TIGHT':energy<.4?'DETAIL':'WIDE'),fieldColor:treatment==='accent-field'?scheme.accent:treatment==='mono-negative'?'#0b1020':scheme.bg,directorConstraints:{scene:!!explicitScene,typography:!!type,camera:!!motion}};
  chapters.push(w);prev=w;
 }
 p.visualWorld={...p.visualWorld,version:4,identity,chapters};J.applyVisualWorld7(p,project);return p.visualWorld;
};
J.applyVisualWorld7=(p,project)=>{
 if(project)J.captureDirectionPreferences7(p,project);
 for(const c of p.cuts){const w=worldAt(p,c.start);if(!w||c.line<0)continue;const override=p.directionOverrides7?.[c.line]||{};c.worldIntent=w.intent;c.architecture=w.typographyArchitecture;c.photoExit=w.photoExit;
  const scene=p.sceneCandidates.find(s=>s.id===w.scene)||p.sceneCandidates[0];c.backgroundScene={...scene,x:scene.x-50,y:scene.y-50,sceneFocal:{x:scene.x,y:scene.y}};
  if(!override.layout&&!c.semanticIntent&&!p.directorLyricDirectives7?.some(d=>d.line===c.line)){let id=w.architecture==='giant'?'huge':w.architecture==='vertical'?(w.directorConstraints?.typography||p.H>p.W?'vcols':'type'):w.architecture==='diagonal'?'diag':w.architecture==='stacked'?'stack':w.architecture==='split'?'splitScreen':'type';if(p.H>p.W&&w.architecture!=='vertical')id=J.resolvePortraitLayout(id);if(J.LAYOUTS[id]){c.layout=id;c.params=layoutParams7(p,c,id);c.kineticGrouped=false;}}
  if(!override.cam){c.cam=c.semanticResolved?.motion||(w.cameraLanguage==='locked'?'stillCamera':w.cameraLanguage==='impact'?'beatPunch':w.cameraLanguage==='push'?'push':'driftDiag');c.camP=J.CAMERA[c.cam]?.plan?.(J.rng(c.seed),c.style||p.style)||{};}
  if(!c.semanticIntent&&!override.hold)c.hold='still';
  if(!override.trans){c.trans=J.TRANS[w.transitionLanguage]?w.transitionLanguage:'wipe';c.transP=J.TRANS[c.trans]?.plan?.(J.rng(c.seed),c.style||p.style)||{};}
 }
 J.applyExplicitOverrides7(p);
};
const extra={fall:['directional','vcols','push'],rush:['directional','diag','push'],contract:['contract','stack','driftDiag'],surround:['surround','stack','driftDiag'],collide:['gather','splitScreen','beatPunch'],reveal:['reveal','type','push'],dominate:['impact','huge','push'],celebrate:['expand','huge','beatPunch'],endure:['still','type','stillCamera'],ignite:['impact','diag','beatPunch'],break:['contract','splitScreen','beatPunch'],resolve:['still','type','stillCamera']},oldVerb=J.resolveVisualVerb;
J.resolveVisualVerb=v=>{const x=extra[String(v).toLowerCase()];return x?{verb:String(v).toLowerCase(),family:x[0],layout:x[1],motion:x[2],fallback:false}:oldVerb(v);};
const oldPlan=J.plan;J.plan=(project,audio)=>{const p=oldPlan(project,audio);if(!p.motionDirector6)return p;p.motionDirector7=true;J.buildVisualWorld7(p,project);const targets=J.musicalTargets(p);for(const e of [...p.events,...p.hypeTimeline||[]]){e.targetType=/section|style-arc|chapter/.test(e.reason||'')?'SECTION':/lyric|phrase/.test(e.reason||'')?'LYRIC_ONSET':e.t<.32?'FREE':targets.BEAT.length?'BEAT':'FREE';if(e.targetType!=='FREE'){const time=nearest(targets[e.targetType],e.t);if(time!==null&&(e.targetType==='SECTION'||Math.abs(time-e.t)<.42))e.t=time;}}J.mergeCoincidentStrongEvents(p);p.events.sort((a,b)=>a.t-b.t);p.hypeTimeline?.sort((a,b)=>a.t-b.t);p.plannedEventAlignment=J.plannedEventAlignment(p);p.repetitionIntelligence=[];const counts=new Map();for(const c of p.cuts.filter(c=>c.line>=0)){const text=p.lines[c.line]?.text||'',n=(counts.get(text)||0)+1;counts.set(text,n);c.repetitionRole=n===1?'establish':worldAt(p,c.start)?.intent==='climax'?'payoff':n===2?'develop':'variation';if(!project.overrides?.[c.line]?.layout&&!c.semanticIntent&&!worldAt(p,c.start)?.directorConstraints?.typography&&n>2&&p.H<=p.W){const id=c.repetitionRole==='payoff'?'huge':n===3?'diag':null;if(id&&J.LAYOUTS[id]){c.layout=id;c.params={...c.params,...J.LAYOUTS[id].plan(J.rng(c.seed),c,c.style||p.style),font:c.params.font};}}if(!project.overrides?.[c.line]?.lock){c.inDur=c.inDur>0?Math.min(c.inDur,.07):0;c.outDur=c.outDur>0?Math.min(c.outDur,.07):0;c.transDur=.07;}p.repetitionIntelligence.push({line:c.line,occurrence:n,role:c.repetitionRole});}for(const key of ['layout','cam','trans','hold'])p.artDirection.vocabulary[key]=[...new Set([...(p.artDirection.vocabulary[key]||[]),...p.cuts.map(c=>c[key]).filter(Boolean)])];J.applyExplicitOverrides7(p);p.layoutFatigue=J.auditLayoutFatigue7(p);return p;};
J.auditLayoutFatigue7=p=>{const history=[],penalties=[];for(const c of p.cuts.filter(c=>c.line>=0)){const signature=[c.layout,c.architecture,c.params?.plate||'',c.params?.banner||''].join('|'),recent=history.filter(x=>c.start-x.time<14),count=recent.filter(x=>x.signature===signature).length;if(count>=3&&!['reprise','climax'].includes(worldAt(p,c.start)?.intent))penalties.push({line:c.line,time:c.start,signature,count});history.push({signature,time:c.start});}return {penalties,score:Math.max(0,100-penalties.length*8)};};
const motif6=J.motifPhysicsAt;J.motifPhysicsAt=(p,t)=>{const v=motif6(p,t);if(p.suppressMotif7)return {...v,x:0,y:0,skew:0,rotation:0,scale:1,envelope:0};if(!p.motionDirector7)return v;const w=worldAt(p,t),u=clamp((t-(w?.from||0))/Math.max(.1,(w?.to||p.duration)-(w?.from||0))),envelope=w?.intent==='climax'?1.8:w?.intent==='break'?.12:w?.intent==='build'?.3+u*.8:w?.intent==='resolution'?.5*(1-u):.35+u*.3,m=String(v.motif).toLowerCase(),wave=Math.sin(t*2.4);return {...v,envelope,x:(m==='stripe'?wave*.005:m==='grid'?Math.round(wave*3)*.0015:wave*.008)*envelope,y:(m==='grid'?Math.round(Math.cos(t)*3)*.0015:Math.cos(t*1.7)*.006)*envelope,skew:m==='stripe'?wave*2.5*envelope:0,rotation:m==='grid'?0:wave*.5*envelope,scale:1+Math.abs(wave)*.006*envelope};};
J.semanticTypographyState=(verb,u)=>{u=clamp(u);const hit=Math.sin(Math.PI*u);return {width:['expand','celebrate'].includes(verb)?.8+.38*u:['contract','collapse','break'].includes(verb)?1.18-.35*u:1,scale:['explode','ignite','dominate'].includes(verb)?.85+.3*u:1,y:['rise','celebrate'].includes(verb)?-.075*u:verb==='fall'?.075*u:0,x:['pierce','rush'].includes(verb)?.065*u:0,skew:['pierce','rush'].includes(verb)?5+hit*6:0,tracking:verb==='unite'?.09*(1-u):verb==='echo'?.015+hit*.03:0,still:['freeze','endure','resolve'].includes(verb),reveal:verb==='reveal',dispersion:verb==='explode'?hit*.05:verb==='unite'?.035*(1-u):0};};
J.negativeSpaceAt=(p,t)=>{const peak=p.musicalStructure.sections.find(s=>s.role==='climax'),rest=!p.suppressNegativeSpace7&&peak&&t>peak.from-.65&&t<peak.from,u=rest?(t-peak.from+.65)/.65:0,k=rest?Math.sin(Math.PI*u)**2:0;return {typeScale:1-k*.15,motionScale:1-k*.85,graphicScale:1-k*.8};};
const cameraBefore71=J.cameraAt;
J.cameraAt=(p,t,range)=>{
 const cut=J.cutAt(p,t),override=p.directionOverrides7?.[cut?.line]?.cam;
 let a=cameraBefore71(p,t,range);
 if(override&&J.CAMERA[override]){try{a=J.CAMERA[override].get({W:p.W,H:p.H,t,lt:t-cut.start,cut,plan:p,st:cut.style||p.style,energy:.5,beat:{pulse:0}},cut.camP||{});}catch{a={s:1,x:0,y:0,rot:0};}}
 if(!p.motionDirector7||!a)return a;
 const k=J.negativeSpaceAt(p,t).motionScale;
 return {...a,s:1+((a.s??1)-1)*k,x:(a.x||0)*k,y:(a.y||0)*k,rot:(a.rot||0)*k,skx:(a.skx||0)*k};
};
const localReadability=J.adjustLocalReadability;J.adjustLocalReadability=(env,it)=>{const w=worldAt(env.plan,env.t);if(env.plan.motionDirector7&&w?.photoExit){const field=w.fieldColor||'#0b1020',color=J.paletteLuma(field)>.38?'#10151e':'#f8f8f2';return {...it,color,strokeColor:color};}return localReadability(env,it);};
const typo=J.applyTypography5;J.applyTypography5=(env,it)=>{typo(env,it);if(!env.plan.motionDirector7)return;const p=env.plan,c=env.cut,w=worldAt(p,env.t),u=clamp((env.t-c.start)/Math.max(.2,c.end-c.start)),sem=c.semanticIntent,st=J.semanticTypographyState(sem?.visualVerb||'',u),law=J.motifPhysicsAt(p,env.t);it.sx=(it.sx||1)*st.width;it.size*=st.scale;it.y+=env.H*st.y;it.x+=env.W*st.x;it.skew=(it.skew||0)+st.skew;it.track=(it.track||0)+st.tracking;if(st.still){it.rot=0;it.skew=0;it.charFns=[];}if(law.motif==='grid'){it.x=Math.round(it.x/(env.W/24))*(env.W/24);it.y=Math.round(it.y/(env.H/24))*(env.H/24);}if(['wave','flag'].includes(law.motif))it.sx*=1+Math.sin(env.t*2.4)*.018*law.envelope;if(!st.still)it.charFns.push(i=>({dy:Math.sin(i*.6+env.t*2)*it.size*.012*law.envelope,dx:Math.sin(i*1.8)*env.W*st.dispersion,a:st.reveal?clamp((u-i*.016)*5):1}));if(sem?.role==='command')it.stroke=Math.max(it.stroke||0,it.size*.025);if(w?.intent==='climax'){it.sx*=1.1;it.stroke=Math.max(it.stroke||0,it.size*.018);}if(w?.intent==='tension')it.sx*=.87;
 const rest=J.negativeSpaceAt(p,env.t);it.size*=rest.typeScale;if(rest.motionScale<1)it.charFns=[];if(rest.motionScale>=1&&c.repetitionRole==='variation'){it.track=(it.track||0)+.008;it.charFns.push(i=>({dy:Math.sin(i*.8+u*3)*it.size*.01}));}if(c.repetitionRole==='payoff')it.stroke=Math.max(it.stroke||0,it.size*.025);
};
const bg=J.Renderer.prototype.drawCustomBackground;J.Renderer.prototype.drawCustomBackground=function(ctx,p,t,...args){const w=worldAt(p,t);if(!p.motionDirector7||!w?.photoExit)return bg.call(this,ctx,p,t,...args);ctx.save();ctx.fillStyle=w.fieldColor||'#0b1020';ctx.fillRect(0,0,p.W,p.H);const ph=J.motifPhysicsAt(p,t),accent=p.style.schemes[0].accent;ctx.strokeStyle=accent;ctx.globalAlpha=(w.texture==='clean'?.1:.22)*J.negativeSpaceAt(p,t).graphicScale;ctx.lineWidth=Math.max(1,p.W*.0015);if(w.backgroundWorld==='graphic-field'){for(let i=0;i<6;i++){const y=p.H*(i/6+ph.y);ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(p.W,y+p.H*.12);ctx.stroke();}}else if(w.texture==='fine-grid'){for(let x=0;x<p.W;x+=p.W/12){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,p.H);ctx.stroke();}}ctx.restore();};
J.collectCanvasObserver=async(p,range,telemetry={})=>{const from=range?.start??0,to=range?.end??p.duration,width=96,height=Math.round(width*p.H/p.W),R=new J.Renderer(),c=document.createElement('canvas'),m=document.createElement('canvas');c.width=m.width=width;c.height=m.height=height;const ctx=c.getContext('2d'),mc=m.getContext('2d'),frames=[];if(p.customBg?.enabled)await R.loadCustomBackground(p.customBg.dataUrl);await R.loadAssetDeck?.(p);try{for(let i=0;i<Math.ceil((to-from)/.1);i++){const time=from+i*.1;R.frame(ctx,p,time,{scale:width/p.W,production:true,range,lyricAuditCtx:mc,lyricAuditItems:[]});frames.push({time,features:J.observePixelFrame(ctx.getImageData(0,0,width,height).data,width,height,mc.getImageData(0,0,width,height).data)});if(i%8===0){telemetry.onProgress?.({label:'映像の動きと音楽の一致を検査しています',current:i+1,total:Math.ceil((to-from)/.1)});await new Promise(r=>setTimeout(r,0));}}}finally{R.customBgBitmap?.close?.();R.disposeAssets?.();}const observer=J.observeVisualPeaks(frames);observer.media='actual Canvas';return {observer,frames,width,height};};
J.measureWorldDistance7=(p,frames,range)=>{const chapters=p.visualWorld.chapters.filter(w=>w.to>(range?.start??0)&&w.from<(range?.end??p.duration)),shots=chapters.map(w=>{const start=Math.max(w.from,range?.start??0),end=Math.min(w.to,range?.end??p.duration),t=(start+end)/2,f=frames.reduce((a,b)=>Math.abs(b.time-t)<Math.abs(a.time-t)?b:a);return {w,f:f.features};}),pairs=shots.slice(1).map((s,i)=>{const a=shots[i].f,b=s.f,channels={crop:delta(a.edge,b.edge),luminance:delta(a.luma,b.luma),palette:delta(a.palette,b.palette),architecture:delta(a.bbox,b.bbox),geometry:Math.abs(a.spread-b.spread),texture:Math.abs(a.texture-b.texture),foreground:delta(a.fg,b.fg)},actual=clamp(channels.crop*.8+channels.luminance*1.2+channels.palette*.9+channels.architecture*.4+channels.foreground*.9+channels.geometry*1.2+channels.texture*.6);return {from:s.w.from,intent:s.w.intent,target:s.w.targetWorldDistance,actual,channels,pass:actual>=s.w.targetWorldDistance*.65};});return {measured:pairs.length>0,pairs,weakChapters:pairs.filter(s=>!s.pass),score:pairs.length?Math.round(mean(pairs.map(s=>clamp(s.actual/Math.max(.1,s.target))))*100):null};};
J.measureSemanticReality7=async(p,range)=>{const sem=p.cuts.filter(c=>c.semanticIntent&&c.line>=0&&(!range||c.start<range.end&&c.end>range.start)),R=new J.Renderer(),c=document.createElement('canvas'),m=document.createElement('canvas');c.width=m.width=128;c.height=m.height=Math.round(128*p.H/p.W);const ctx=c.getContext('2d'),mc=m.getContext('2d'),results=[];if(p.customBg?.enabled)await R.loadCustomBackground(p.customBg.dataUrl);await R.loadAssetDeck?.(p);try{for(const cut of sem){const states=[];for(const u of [.12,.5,.8]){const t=cut.start+(cut.end-cut.start)*u;R.frame(ctx,p,t,{scale:128/p.W,production:true,range,lyricAuditCtx:mc,lyricAuditItems:[]});states.push(J.observePixelFrame(ctx.getImageData(0,0,c.width,c.height).data,c.width,c.height,mc.getImageData(0,0,c.width,c.height).data));}const [a,b,z]=states,v=cut.semanticIntent.visualVerb,width=s=>s.bbox[2]-s.bbox[0],movement=Math.hypot(z.center[0]-a.center[0],z.center[1]-a.center[1]),valid=a.area>0&&z.area>0;let ratio=['expand','celebrate','explode','dominate','ignite'].includes(v)?Math.max(z.area/Math.max(.0001,a.area),width(z)/Math.max(.001,width(a))):['contract','collapse','break'].includes(v)?a.area/Math.max(.0001,z.area):['rise','fall'].includes(v)?(v==='rise'?a.center[1]-z.center[1]:z.center[1]-a.center[1])/.035:['freeze','endure','resolve'].includes(v)?clamp(1-movement/.045):['unite','collide'].includes(v)?a.spread/Math.max(.0001,z.spread):['pierce','rush'].includes(v)?Math.max(movement/.035,Math.abs(z.angle-a.angle)/.12):v==='reveal'?z.area/Math.max(.0001,a.area):movement/.012;const score=valid?Math.round(clamp(ratio/(['expand','celebrate','explode','dominate','ignite','contract','collapse','break','unite','collide','reveal'].includes(v)?1.15:1))*100):0;results.push({line:cut.line,verb:v,resolved:cut.semanticResolved?.family||J.resolveVisualVerb(v).family,rendered:{area:states.map(s=>s.area),bbox:states.map(s=>s.bbox),centroid:states.map(s=>s.center),dispersion:states.map(s=>s.spread)},score,pass:score>=85});}}finally{R.customBgBitmap?.close?.();R.disposeAssets?.();}return {measured:results.length>0,results,weakLines:results.filter(r=>!r.pass),score:results.length?Math.round(mean(results.map(r=>r.score))):null};};
J.audienceImpact7=(observer,p)=>{const all=observer.signals,climax=p.musicalStructure?.sections.find(s=>s.role==='climax'),inside=all.filter(s=>climax&&s.time>=climax.from&&s.time<climax.to),normal=all.filter(s=>!climax||s.time<climax.from||s.time>=climax.to),normalP90=quantile(normal.map(s=>s.perceivedImpact),.9),climaxPeak=Math.max(0,...inside.map(s=>s.perceivedImpact)),dominance=climaxPeak/Math.max(.007,normalP90),peakContrast=mean(observer.peaks.map(s=>s.preEventStillness)),score=all.length?Math.round(clamp((dominance/2)*.6+peakContrast*.4)*100):0;return {score,climaxDominance:dominance,normalP90,climaxPeak,climaxPass:!!climax&&dominance>=1.15,heroCount:observer.peaks.filter(s=>s.tier==='Hero').length,method:'track percentile and local motion contrast; engineering proxy, not calibrated audience research'};};
J.motifReality7=(p,observer)=>{const f=observer.frameSummaries,changes=f.slice(1).map((s,i)=>({x:s.center[0]-f[i].center[0],y:s.center[1]-f[i].center[1],angle:s.angle-f[i].angle})),motion=mean(changes.map(d=>Math.hypot(d.x,d.y))),geometry=quantile(f.map(x=>x.spread),.9)-quantile(f.map(x=>x.spread),.1),score=Math.round(clamp(motion/.007*.45+geometry/.05*.4+mean(changes.map(d=>Math.abs(d.angle)))/.1*.15)*100);return {measured:true,motion,geometry,score,motif:p.visualWorld?.motifs[0],method:'observed foreground vector/dispersion/orientation; no plan-presence credit'};};
const unifiedMotif=J.drawUnifiedMotif;J.drawUnifiedMotif=(ctx,p,t)=>p.suppressMotif7?undefined:unifiedMotif(ctx,p,t);
J.measureMotifReality7=async(p,range)=>{const R=new J.Renderer(),c=document.createElement('canvas'),mask=document.createElement('canvas'),w=96,h=Math.round(w*p.H/p.W);c.width=mask.width=w;c.height=mask.height=h;const ctx=c.getContext('2d'),mc=mask.getContext('2d'),from=range?.start??0,to=range?.end??p.duration,control={...p,suppressMotif7:true},samples=[];if(p.customBg?.enabled)await R.loadCustomBackground(p.customBg.dataUrl);await R.loadAssetDeck?.(p);const snap=(plan,t)=>{R.frame(ctx,plan,t,{scale:w/p.W,production:true,range,lyricAuditCtx:mc,lyricAuditItems:[]});return J.observePixelFrame(ctx.getImageData(0,0,w,h).data,w,h,mc.getImageData(0,0,w,h).data);};try{for(const u of [.08,.23,.42,.6,.77,.92]){const t=from+(to-from)*u,a=snap(p,t),b=snap(control,t);samples.push({time:t,foreground:delta(a.fg,b.fg),background:delta(a.luma,b.luma),geometry:delta(a.bbox,b.bbox),orientation:Math.abs(a.angle-b.angle)});}}finally{R.customBgBitmap?.close?.();R.disposeAssets?.();}const foreground=mean(samples.map(s=>s.foreground)),background=mean(samples.map(s=>s.background)),score=Math.round(clamp(foreground/.018*.5+background/.015*.5)*100);return {measured:true,causal:true,motif:p.visualWorld?.motifs[0],foreground,background,samples,score,visible:foreground>.001&&background>.001,method:'same-renderer motif-law on/off raster comparison; independent Observer remains pixel-only'};};
const analyze6=J.analyzeRenderedFrames;J.analyzeRenderedFrames=async(p,range,audio,telemetry={})=>{const r=await analyze6(p,range,audio,telemetry);if(!r.completed||!p.motionDirector7)return r;let sampled=await J.collectCanvasObserver(p,range,telemetry),world=J.measureWorldDistance7(p,sampled.frames,range),attempts=0,repairAllowed=!(p.singleBackground&&p.customBg?.enabled)&&!Object.keys(p.directionOverrides7||{}).length&&!p.directorLyricDirectives7?.length&&!p.directorSections7?.length;while(repairAllowed&&!range&&world.weakChapters.length&&attempts<3){attempts++;for(const weak of world.weakChapters){const w=p.visualWorld.chapters.find(w=>w.from===weak.from);if(attempts===1&&!w.directorConstraints?.scene)w.scene=w.scene==='DETAIL'?'TIGHT':'DETAIL';if(attempts===2&&!w.directorConstraints?.typography){w.typographyArchitecture=w.architecture=w.architecture==='giant'?'vertical':'giant';}if(attempts===3&&!w.directorConstraints?.scene){w.photoExit=true;w.backgroundWorld='typography-only';w.fieldColor=w.paletteTreatment==='accent-field'?'#0b1020':p.style.schemes[0].accent;w.paletteTreatment='repaired-contrast';}}J.applyVisualWorld7(p);sampled=await J.collectCanvasObserver(p,range,telemetry);world=J.measureWorldDistance7(p,sampled.frames,range);}
 // Repairs alter layout: rerun glyph integrity rather than reuse pre-repair masks.
 const final=attempts?await analyze6(p,range,audio,telemetry):r;if(attempts){sampled=await J.collectCanvasObserver(p,range,telemetry);world=J.measureWorldDistance7(p,sampled.frames,range);}final.metrics.observer=sampled.observer;final.metrics.observedVisualHitAlignment=J.alignObservedPeaks(sampled.observer,J.musicalTargets(p));final.metrics.plannedEventAlignment=J.plannedEventAlignment(p,range);final.metrics.worldRealization={...world,repairAttempts:attempts,maxAttempts:repairAllowed?3:0,repairPolicy:repairAllowed?'LEGACY_GRAPHIC_REPAIR':'PRESERVE_BACKGROUND_AND_MANUAL_DIRECTION'};final.metrics.semanticReality=await J.measureSemanticReality7(p,range);final.metrics.audienceImpact=J.audienceImpact7(sampled.observer,p);final.metrics.motifReality=await J.measureMotifReality7(p,range);p.lastPixelQA=final;p.worldQA=final.metrics.worldRealization;p.semanticQA=final.metrics.semanticReality;p.observerQA=final.metrics.observer;return final;};
J.bottleneckCreative7=domains=>{const weights={musicalDirection:.2,semanticDirection:.15,typography:.15,visualWorld:.2,motionRealization:.15,audienceImpact:.15},entries=Object.entries(weights).filter(([k])=>Number.isFinite(domains[k])),sum=entries.reduce((s,[,w])=>s+w,0),weighted=entries.reduce((s,[k,w])=>s+domains[k]*w,0)/Math.max(.01,sum),weakest=Math.min(...entries.map(([k])=>domains[k])),penalty=Math.max(0,weighted-weakest)*.35;return {score:Math.round(clamp((weighted-penalty)/100)*100),weightedMean:weighted,weakest,penalty};};
J.normalizeQARange7=(p,range)=>range&&Math.abs(range.start||0)<.001&&Math.abs((range.end??p.duration)-p.duration)<.001?null:range||null;
J.certificationEligibility7=({domains:d,creative,exportVerified,provenanceMatch,pixelComplete,lyricSampleCount,requiredLyricSamples,semanticRequired,socialHook,loopQuality,portraitWarnings,issues})=>!!(exportVerified&&provenanceMatch&&pixelComplete&&lyricSampleCount>=requiredLyricSamples&&d.technical>=99&&['musicalDirection','typography','visualWorld','motionRealization','audienceImpact','social'].every(k=>d[k]>=95)&&(!semanticRequired||d.semanticDirection>=95)&&creative>=95&&(!socialHook||loopQuality>=85&&portraitWarnings===0)&&!issues.some(x=>['ERROR','WARNING'].includes(x.severity)));
const quality6=J.checkMVQuality;J.checkMVQuality=(project,p,audio,range,pixel,caps,validation)=>{range=J.normalizeQARange7(p,range);const r=quality6(project,p,audio,range,pixel,caps,validation);if(!p.motionDirector7)return r;const m=pixel?.metrics||{},q=r.quality,observed=m.observedVisualHitAlignment,world=m.worldRealization,sem=m.semanticReality,impact=m.audienceImpact,motif=m.motifReality;const d={technical:q.technicalScore,musicalDirection:observed?.score??null,semanticDirection:sem?.score??null,typography:q.typographyScore,visualWorld:world?.score===null?null:world?(motif?.applicable===false?world.score:Math.round((world.score*.8+(motif?.score||0)*.2))):null,motionRealization:m.eventRealization?.score??null,audienceImpact:impact?.score??null,social:q.socialScore};q.productionDomains=d;const inheritedCap=q.creativeScore;const bottleneck=J.bottleneckCreative7(d);q.creativeBottleneck=bottleneck;q.creativeScore=bottleneck.score;if(q.hardGates?.visualStagnationCap||p.attentionBudget?.withinBudget===false)q.creativeScore=Math.min(q.creativeScore,inheritedCap);q.plannedEventAlignment=m.plannedEventAlignment;q.observedVisualHitAlignment=observed;q.audienceImpact=impact;
 const fail=(code,message)=>{if(!r.issues.some(i=>i.code===code))r.issues.push({code,severity:'ERROR',message,exportBlocking:false});};if(world?.weakChapters.length)fail('BROKEN_VISUAL_WORLD','章の実画素差が意図した距離に届いていません');if(sem?.weakLines.length)fail('SEMANTIC_NOT_REALIZED','意味の動作が実画素で不足しています');if(impact&&impact.climaxApplicable!==false&&!impact.climaxPass)fail('CLIMAX_TOO_WEAK','クライマックスの実Impactが通常場面p90を十分に上回っていません');if(validation?.provenanceMatch===false)fail('PROVENANCE_MISMATCH','動画とQAのハッシュが一致しません');if((m.stagnationSeconds||0)>=8){fail('VISUAL_STAGNATION','実画素の変化が8秒以上停滞しています');q.creativeScore=Math.min(q.creativeScore,72);}if(!J.auditAttentionBudget(p).withinBudget)q.creativeScore=Math.min(q.creativeScore,74);if(impact?.climaxApplicable!==false&&!impact?.climaxPass)q.creativeScore=Math.min(94,q.creativeScore);if(motif&&motif.applicable!==false&&motif.score<85)q.creativeScore=Math.min(94,q.creativeScore);q.provenanceMatch=validation?.provenanceMatch===true&&validation?.provenancePlanHash===p._provenancePlanHash;q.exportVerified=validation?.certification?.passed===true;q.certified100=J.certificationEligibility7({domains:d,creative:q.creativeScore,exportVerified:q.exportVerified,provenanceMatch:q.provenanceMatch,pixelComplete:pixel?.completed,lyricSampleCount:m.lyricPoints?.length||0,requiredLyricSamples:p.lines.filter(l=>l.start>=(range?.start??0)&&l.start<(range?.end??p.duration)).length*3,semanticRequired:!!p.lineSemantics?.length,socialHook:!!p.socialHook,loopQuality:m.loopQuality||0,portraitWarnings:p.portraitSaliency?.warnings,issues:r.issues});q.overallScore=q.certified100?100:Math.min(99,Math.round(d.technical*.3+q.creativeScore*.45+d.social*.25));q.score=q.overallScore;q.perfectEligible=q.certified100;q.hardGates={...q.hardGates,passed:!r.issues.some(x=>x.severity==='ERROR'),total:r.issues.filter(x=>x.severity==='ERROR').length};q.domains=[{key:'technical',score:d.technical,max:100},{key:'creative',score:q.creativeScore,max:100},{key:'social',score:d.social,max:100}];r.errors=r.issues.filter(x=>x.severity==='ERROR');r.ready=!r.errors.some(x=>x.exportBlocking!==false);p.currentQualityScores=d;p.lastQAFailures=r.errors.map(x=>({code:x.code,message:x.message}));return r;};
const social6=J.createSocialHookPlan;J.createSocialHookPlan=(p,candidate)=>{const s=social6(p,candidate);if(!s.motionDirector6)return s;s.motionDirector7=true;s.W=Math.min(p.W,p.H);s.H=Math.round(s.W*16/9);s.socialHook.version=5;s.socialDirector={version:5,aspect:'9:16',independent:true,phases:[['shock',0,.5],['identity',.5,1],['hook',1,3],['rhythm',3,7],['escalation',7,11],['climax',11,14],['loop',14,15]].map(([intent,from,to])=>({intent,from:candidate.start+from*(candidate.end-candidate.start)/15,to:Math.min(candidate.end,candidate.start+to*(candidate.end-candidate.start)/15)})).filter(x=>x.to>x.from)};s.musicalStructure.sections=s.socialDirector.phases.map(f=>({...f,role:f.intent==='climax'?'climax':f.intent==='escalation'?'build':f.intent==='loop'?'finale':['shock','identity','hook'].includes(f.intent)?'hook':'verse',energy:f.intent==='climax'?.95:f.intent==='escalation'?.78:f.intent==='rhythm'?.55:.35}));const cuts=[];for(const cut of s.cuts){const boundaries=[cut.start,...s.socialDirector.phases.flatMap(f=>[f.from,f.to]).filter(t=>t>cut.start+.001&&t<cut.end-.001),cut.end].sort((a,b)=>a-b).filter((t,i,a)=>!i||t!==a[i-1]);for(let i=0;i<boundaries.length-1;i++)cuts.push({...cut,params:{...cut.params},start:boundaries[i],end:boundaries[i+1],dur:boundaries[i+1]-boundaries[i],transDur:.07});}s.cuts=cuts.sort((a,b)=>a.start-b.start);s.cuts.forEach((c,i)=>c.index=i);J.buildVisualWorld7(s,{});for(const w of s.visualWorld.chapters){const phase=s.socialDirector.phases.find(f=>w.from>=f.from&&w.from<f.to);if(phase?.intent==='shock'){w.photoExit=true;w.backgroundWorld='typography-only';w.intent='identity';}if(phase?.intent==='loop'){const first=s.visualWorld.chapters[0];Object.assign(w,{photoExit:first.photoExit,backgroundWorld:first.backgroundWorld,fieldColor:first.fieldColor,paletteTreatment:first.paletteTreatment,typographyArchitecture:first.typographyArchitecture,architecture:first.architecture,cameraLanguage:first.cameraLanguage,motionPhysics:first.motionPhysics});}}J.applyVisualWorld7(s);s.portraitSaliency=J.portraitSaliency(s);return s;};
const context4=J.directorContext;J.directorContext=(project,p,audio,image)=>({...context4(project,p,audio,image),schema:'jizura-director-context-v5',chapterIntent:p.visualWorld?.chapters.map(w=>({from:w.from,to:w.to,intent:w.intent})),currentVisualWorlds:p.visualWorld?.chapters,observedVisualPeaks:p.observerQA?.peaks||[],weakWorldChapters:p.worldQA?.weakChapters||[],weakSemanticLines:p.semanticQA?.weakLines||[],motifFatigue:p.motifFatigue,layoutFatigue:p.layoutFatigue,currentQualityScores:p.currentQualityScores||null,currentQAFailures:p.lastQAFailures||[],observerTarget:'internal ±100ms >=85%, not industry standard'});
const prompt4=J.directorPrompt;J.directorPrompt=()=>prompt4()+' Context v5のobservedVisualPeaks/weakWorldChapters/weakSemanticLines/layoutFatigueを読み、弱い実画素結果を改善してください。追加visualVerb: fall/rush/contract/surround/collide/reveal/dominate/celebrate/endure/ignite/break/resolve。';
const windows5=J.directorWindows;J.directorWindows=(duration,p)=>{const windows=windows5(duration);if(!p)return windows;const weak=p.worldQA?.weakChapters?.[0],chapter=weak?p.visualWorld.chapters.find(w=>w.from===weak.from):p.visualWorld.chapters.reduce((a,b)=>b.energy<a.energy?b:a),start=Math.max(0,Math.min(duration-1,chapter?.from||duration*.4));return [...windows.slice(0,3),{name:'weakest chapter',start,end:Math.min(duration,start+Math.min(3,duration/10))},...windows.slice(3)];};
J.compareDirectorCandidates=async(project,audio,candidates)=>{const result=[];for(const [i,item] of (candidates||[]).slice(0,3).entries()){const candidate=item.plan||item,variant=J.applyDirectorPlan(project,candidate,audio),p=J.plan(variant,audio),samples=[];for(const range of J.directorWindows(p.duration,p)){const pixel=await J.analyzeRenderedFrames(p,range,audio),q=J.checkMVQuality(variant,p,audio,range,pixel,null,null);samples.push({window:range.name,quality:q.quality,observer:pixel.metrics.observedVisualHitAlignment,issues:q.errors.map(e=>e.code)});}const domains=['technical','musicalDirection','semanticDirection','typography','visualWorld','motionRealization','audienceImpact','social'],quality=Object.fromEntries(domains.map(k=>{const v=samples.map(s=>s.quality.productionDomains[k]).filter(Number.isFinite);return [k,v.length?Math.round(mean(v)):null];}));quality.score=J.bottleneckCreative7(quality).score;quality.creative=quality.score;quality.direction=quality.musicalDirection??0;quality.directorReality=quality.motionRealization;result.push({index:item.index??i,plan:candidate,project:variant,renderPlan:p,quality,pixelQA:p.lastPixelQA,windows:samples.map(s=>s.window),observerWindows:samples.map(s=>({window:s.window,...s.observer})),warnings:[...new Set(samples.flatMap(s=>s.issues))]});}result.sort((a,b)=>b.quality.score-a.quality.score);result.forEach((r,i)=>r.recommended=i===0);return result;};
const revision1=J.createDirectorRevisionPack;J.createDirectorRevisionPack=async args=>{const original=await revision1(args),bytes=new Uint8Array(await original.arrayBuffer()),zip=new J.ZipWriter(); // Existing ZipWriter stores uncompressed local entries; preserve every entry.
 const view=new DataView(bytes.buffer);let pos=0;while(pos+30<bytes.length&&view.getUint32(pos,true)===0x04034b50){const size=view.getUint32(pos+18,true),nl=view.getUint16(pos+26,true),el=view.getUint16(pos+28,true),name=new TextDecoder().decode(bytes.slice(pos+30,pos+30+nl)),start=pos+30+nl+el;if(view.getUint16(pos+8,true)!==0)throw Error('Unsupported Director ZIP compression');zip.add(name,bytes.slice(start,start+size));pos=start+size;}
 const p=args.plan,c=document.createElement('canvas');c.width=1200;c.height=400;const ctx=c.getContext('2d'),R=new J.Renderer();if(p.customBg?.enabled)await R.loadCustomBackground(p.customBg.dataUrl);await R.loadAssetDeck?.(p);for(const [i,w] of J.directorWindows(p.duration,p).entries()){const f=document.createElement('canvas');f.width=200;f.height=Math.round(200*p.H/p.W);R.frame(f.getContext('2d'),p,w.start+.1,{scale:200/p.W,production:true});ctx.fillStyle='#10151e';ctx.fillRect(i*200,0,200,400);ctx.drawImage(f,i*200,30,200,Math.min(355,f.height));ctx.fillStyle='#fff';ctx.font='12px sans-serif';ctx.fillText(w.name,i*200+5,18);}R.customBgBitmap?.close?.();R.disposeAssets?.();const image=await new Promise(r=>c.toBlob(r,'image/jpeg',.84));zip.add('VISUAL_REFERENCE_SHEET.jpg',new Uint8Array(await image.arrayBuffer()));return zip.finish();};
J.observerTimeOrigin7=(p,range)=>range?.start??p.socialHook?.start??0;
J.cinemaDecodeTimes7=(p,duration)=>{const times=Array.from({length:Math.ceil(duration/.1)},(_,i)=>Math.min(duration-.02,i*.1));if(p.musicalPhoto?.cinema?.architecture){const last=Math.max(0,duration-.5/(p.fps||30));if(last>times.at(-1)+.001)times.push(last);}return times;};
const observeMP4BySeeking=async(blob,p,range,signal,onProgress)=>{const v=document.createElement('video'),url=URL.createObjectURL(blob),c=document.createElement('canvas'),width=96,height=Math.round(width*p.H/p.W);c.width=width;c.height=height;const ctx=c.getContext('2d'),frames=[],wait=event=>J.waitMediaEvent(v,event,{signal});try{v.muted=true;const loaded=wait('loadeddata');v.src=url;await loaded;const from=J.observerTimeOrigin7(p,range),duration=(range?.end??p.socialHook?.end??p.duration)-from;const timestamps=J.cinemaDecodeTimes7(p,duration);for(let i=0;i<timestamps.length;i++){if(signal?.aborted)throw Object.assign(Error('Cancelled'),{name:'AbortError'});const relative=Math.min(v.duration-1e-5,timestamps[i]);if(Math.abs(v.currentTime-relative)>.001){const seek=wait('seeked');v.currentTime=relative;await seek;}ctx.drawImage(v,0,0,width,height);frames.push({time:from+relative,features:J.observePixelFrame(ctx.getImageData(0,0,width,height).data,width,height)});onProgress?.(.995,'完成したMP4を検査中 '+(i+1)+'/'+Math.ceil(duration/.1)+'フレーム',{stage:'verify',current:i+1,total:Math.ceil(duration/.1)});}const observer=J.observeVisualPeaks(frames);observer.media='exported MP4 decoded in browser';const decodedCinema=J.measureDecodedCinemaFrames?.(frames,p,range,width,height);if(decodedCinema?.completed){decodedCinema.layerPresence=await J.verifyDecodedCinemaLayers?.(frames,p,range);J.applyDecodedCinemaEvidence?.(decodedCinema);}return {observer,alignment:J.alignObservedPeaks(observer,J.musicalTargets(p)),audienceImpact:J.audienceImpact7(observer,p),decodedCinema};}finally{v.removeAttribute('src');v.load();URL.revokeObjectURL(url);}};
J.observeExportedMP4=async(blob,p,range,signal,onProgress)=>{
 if(window.JIZURAMedia&&typeof VideoDecoder!=='undefined'){
  const from=J.observerTimeOrigin7(p,range),duration=(range?.end??p.socialHook?.end??p.duration)-from,width=96,height=Math.round(width*p.H/p.W),frames=[];
  const timestamps=J.cinemaDecodeTimes7(p,duration);
  try{
   const decode=new AbortController(),abort=()=>decode.abort();signal?.addEventListener('abort',abort,{once:true});if(signal?.aborted)decode.abort();
   let watchdog;const idle=()=>{clearTimeout(watchdog);watchdog=setTimeout(()=>decode.abort(),45000);};idle();
   try{await J.waitExportStep(()=>window.JIZURAMedia.sampleMP4(blob,timestamps,{width,height,signal:decode.signal,onSample:(time,pixels)=>{idle();frames.push({time:from+time,features:J.observePixelFrame(pixels,width,height)});onProgress?.(.995,'完成したMP4を検査中 '+frames.length+'/'+timestamps.length+'フレーム',{stage:'verify',current:frames.length,total:timestamps.length});}}),{signal:decode.signal,label:'MP4の連続デコード',timeout:Math.max(60000,duration*3000)});}finally{clearTimeout(watchdog);decode.abort();signal?.removeEventListener('abort',abort);}
   const observer=J.observeVisualPeaks(frames);observer.media='exported MP4 decoded sequentially in browser';
   const decodedCinema=J.measureDecodedCinemaFrames?.(frames,p,range,width,height);if(decodedCinema?.completed){decodedCinema.layerPresence=await J.verifyDecodedCinemaLayers?.(frames,p,range);J.applyDecodedCinemaEvidence?.(decodedCinema);}return {observer,alignment:J.alignObservedPeaks(observer,J.musicalTargets(p)),audienceImpact:J.audienceImpact7(observer,p),decodedCinema};
  }catch(error){if(signal?.aborted)throw error;console.warn('Sequential MP4 inspection unavailable; using browser seeking',error);}
 }
 const seeking=new AbortController(),abort=()=>seeking.abort();signal?.addEventListener('abort',abort,{once:true});if(signal?.aborted)seeking.abort();try{return await J.waitExportStep(()=>observeMP4BySeeking(blob,p,range,seeking.signal,onProgress),{signal:seeking.signal,label:'MP4の再生検査',onTimeout:abort,timeout:Math.max(60000,((range?.end??p.duration)-(range?.start??0))*3000)});}finally{seeking.abort();signal?.removeEventListener('abort',abort);}
};
J.createExportProvenance=async(args,result,report)=>{
 const audioDigest=async()=>{
  const buffer=args.audio?.buffer,parts=[];if(buffer?.getChannelData)for(let ch=0;ch<buffer.numberOfChannels;ch++){const pcm=buffer.getChannelData(ch);parts.push(new Uint8Array(pcm.buffer,pcm.byteOffset,pcm.byteLength));}
  if(!parts.length)return null;
  const all=new Uint8Array(parts.reduce((n,p)=>n+p.length,0)+8),view=new DataView(all.buffer);view.setUint32(0,buffer.sampleRate,true);view.setUint32(4,buffer.numberOfChannels,true);let n=8;for(const part of parts){all.set(part,n);n+=part.length;}return J.sha256(all);
 };
 const bg=args.project.customBg?.dataUrl;
 const [audioHash,backgroundHash,projectHash,planHash,videoSHA256]=await Promise.all([
  audioDigest(),bg?(async()=>J.sha256(await(await fetch(bg)).arrayBuffer()))():null,
  J.sha256(J.canonicalJSON(args.project)),J.sha256(J.canonicalJSON(args.plan)),(async()=>J.sha256(await result.blob.arrayBuffer()))()
 ]);
 return {schema:'jizura-export-qa-v1',projectHash,planHash,audioHash,audioHashFormat:'sample-rate u32LE, channel-count u32LE, channel-major decoded Float32 PCM',backgroundHash,videoSHA256,jizuraVersion:J.MOTION_DIRECTOR_VERSION,browser:globalThis.navigator?.userAgent||'unknown',exportSettings:{width:result.width,height:result.height,fps:args.plan.fps,range:args.range||{start:0,end:args.plan.duration},videoCodec:result.validation.videoCodec,audioCodec:result.validation.audioCodec},qualityScores:report.quality.productionDomains||{technical:report.quality.technicalScore,creative:report.quality.creativeScore,social:report.quality.socialScore},creative:report.quality.creativeScore,hardGates:report.errors.map(x=>x.code),certified100:report.quality.certified100,timestamp:new Date().toISOString(),observerQA:result.validation.observerQA||null};
};
J.verifyExportProvenance=async(blob,sidecar,args=null)=>!!sidecar&&sidecar.videoSHA256===await J.sha256(await blob.arrayBuffer())&&(!args||sidecar.projectHash===await J.sha256(J.canonicalJSON(args.project))&&sidecar.planHash===await J.sha256(J.canonicalJSON(args.plan)));
const export6=J.exportMP4,fallback6=J.exportMP4Fallback;const finalize7=async(args,result)=>{args.onProgress?.(.995,'生成済みMP4の演出・出所情報を検査中…',{stage:'verify',indeterminate:true});const decoded=await J.observeExportedMP4(result.blob,args.plan,args.range,args.signal,args.onProgress);result.validation.observerQA=decoded;const pixel=args.plan.lastPixelQA||{completed:false,metrics:{}},exportPixel={...pixel,metrics:{...pixel.metrics,observer:decoded.observer,observedVisualHitAlignment:decoded.alignment,audienceImpact:decoded.audienceImpact,decodedCinema:decoded.decodedCinema}};let report=J.checkMVQuality(args.project,args.plan,args.audio,args.range,exportPixel,{h264:true,aac:!!result.audio,webCodecs:true},result.validation);result.provenance=await J.createExportProvenance(args,result,report);result.validation.provenanceMatch=await J.verifyExportProvenance(result.blob,result.provenance,args);result.validation.provenancePlanHash=result.provenance.planHash;Object.defineProperty(args.plan,'_provenancePlanHash',{value:result.provenance.planHash,configurable:true});if(!result.validation.provenanceMatch)throw Error('PROVENANCE_MISMATCH');report=J.checkMVQuality(args.project,args.plan,args.audio,args.range,exportPixel,{h264:true,aac:!!result.audio,webCodecs:true},result.validation);result.provenance.diagnosticQualityScores=report.quality.productionDomains;result.provenance.qualityScores=report.quality.verifiedScore?.metrics||report.quality.productionDomains||result.provenance.qualityScores;if(!args.plan.motionDirector7)report.quality.certified100=false;result.provenance.diagnosticCreative=report.quality.creativeScore;result.provenance.creative=report.quality.verifiedScore?null:report.quality.creativeScore;result.provenance.certified100=report.quality.certified100;result.provenance.hardGates=report.errors.map(x=>x.code);result.provenance.validation={certification:result.validation.certification,provenanceMatch:true};result.sidecar=new Blob([JSON.stringify(result.provenance,null,2)],{type:'application/json'});args.plan.lastPixelQA=exportPixel;args.onProgress?.(.995,'MP4検査完了',{stage:'verify',indeterminate:true});return result;};
J.exportMP4=async args=>{if(args.project.exportSettings?.fpsMode==='auto'){const wanted=J.chooseAdaptiveFPS(args.project).fps,[w,h]=J.outputSize(args.project);const estimate=J.estimateExport(args.project,(args.range?.end??args.plan.duration)-(args.range?.start??0),!!args.audio);if(!await J.pickVideoCodec(w,h,wanted,Math.round(estimate.videoBitrate)))throw Error('この端末は指定FPSでのMP4書き出しに対応していません。別の対応ブラウザでお試しください。');args.plan.fps=wanted;args.plan.adaptiveFPS={wanted,chosen:wanted,capabilityVerified:true};}return finalize7(args,await export6(args));};
J.exportMP4Fallback=async args=>{const result=await fallback6(args);const [w,h]=J.outputSize(args.project);result.width=w;result.height=h;result.validation=await J.certifyExport(result.blob,{width:w,height:h,fps:args.plan.fps,duration:(args.range?.end??args.plan.duration)-(args.range?.start??0),audio:!!result.audio});if(!result.validation.certification.passed)throw Error('EXPORT_INVALID');return finalize7(args,result);};
})();
