/* Motion Director 8: local visual descriptors, bounded scene search and evidence-only metrics. */
(()=>{'use strict';
const J=window.J,C=(v,a=0,b=1)=>Math.max(a,Math.min(b,Number(v)||0)),avg=a=>a.length?a.reduce((s,v)=>s+v,0)/a.length:0;
J.MOTION_DIRECTOR_VERSION='8.0';
J.ASSET_ROLES=['AUTO','HERO','ESTABLISHING','SUPPORT','DETAIL','PORTRAIT','CROWD','SYMBOL','TEXTURE','LOGO','ABSTRACT'];
const migrate=J.migrateProject;J.migrateProject=input=>{const p=migrate(input);p.visualAssets=J.normalizeVisualAssets(p.visualAssets?.length?p.visualAssets:p.customBg?.dataUrl?[{id:'img_01',name:p.customBg.filename||'背景画像',dataUrl:p.customBg.dataUrl,role:'AUTO'}]:[]);p.scenePins=Array.isArray(p.scenePins)?p.scenePins:[];p.schemaVersion=3;return p;};J.PROJECT_SCHEMA_VERSION=3;
J.normalizeVisualAssets=assets=>(Array.isArray(assets)?assets:[]).slice(0,12).map((a,i)=>({...a,id:typeof a.id==='string'?a.id:'img_'+String(i+1).padStart(2,'0'),name:String(a.name||'画像 '+(i+1)).slice(0,150),role:J.ASSET_ROLES.includes(a.role)?a.role:'AUTO',pin:['required','excluded','climax'].includes(a.pin)?a.pin:'auto',dataUrl:/^data:image\/(png|jpeg|webp);base64,/i.test(a.dataUrl||'')?a.dataUrl:'',status:a.dataUrl?'READY':'MISSING_ASSET'})).filter((a,i,all)=>all.findIndex(b=>b.id===a.id)===i);
J.analyzeVisualAsset=(image,original={})=>{const canvas=document.createElement('canvas'),w=64,h=64;canvas.width=w;canvas.height=h;const ctx=canvas.getContext('2d',{willReadFrequently:true});ctx.drawImage(image,0,0,w,h);const rgba=ctx.getImageData(0,0,w,h).data,features=J.observePixelFrame(rgba,w,h),l=features.luma,hist=Array(12).fill(0),colors=Array(27).fill(0),edgeCells=Array(16).fill(0),lumaCells=Array(16).fill(0);let chroma=0,warmth=0,alpha=0,lap=0;
for(let i=0;i<w*h;i++){const r=rgba[i*4]/255,g=rgba[i*4+1]/255,b=rgba[i*4+2]/255,max=Math.max(r,g,b),min=Math.min(r,g,b),d=max-min;chroma+=d/(w*h);warmth+=(r-b)/(w*h);alpha+=rgba[i*4+3]/255/(w*h);let hue=d===0?0:max===r?((g-b)/d+6)%6:max===g?(b-r)/d+2:(r-g)/d+4;hist[Math.min(11,Math.floor(hue*2))]++;colors[Math.min(2,Math.floor(r*3))*9+Math.min(2,Math.floor(g*3))*3+Math.min(2,Math.floor(b*3))]++;const x=i%w,y=Math.floor(i/w),cell=Math.floor(y/16)*4+Math.floor(x/16);edgeCells[cell]+=features.edge[i]/256;lumaCells[cell]+=l[i]/256;if(x>0&&x<w-1&&y>0&&y<h-1)lap+=(l[i-1]+l[i+1]+l[i-w]+l[i+w]-4*l[i])**2/(w*h);}
const brightness=avg(l),contrast=Math.sqrt(avg(l.map(v=>(v-brightness)**2))),negativeSpace=edgeCells.map((v,i)=>({x:(i%4+.5)/4,y:(Math.floor(i/4)+.5)/4,risk:C(v*3),brightness:lumaCells[i]})).sort((a,b)=>a.risk-b.risk),rank=colors.map((n,i)=>({n,color:'#'+[Math.floor(i/9),Math.floor(i/3)%3,i%3].map(v=>Math.round((v+.5)/3*255).toString(16).padStart(2,'0')).join('')})).sort((a,b)=>b.n-a.n),hash=[];
for(let y=0;y<8;y++)for(let x=0;x<8;x++)hash.push(l[y*8*w+x*8]>l[y*8*w+Math.min(63,x*8+7)]?1:0);
const width=original.width||image.width,height=original.height||image.height,aspect=width/height,resolution=C(Math.min(width,height)/720),blur=C(lap/.012),quality=C(resolution*.5+blur*.3+(brightness>.06&&brightness<.94?.2:0)),focus=features.center,role=alpha<.8?'LOGO':features.texture>.13?'CROWD':chroma<.08&&contrast>.2?'SYMBOL':features.texture<.035?'ABSTRACT':aspect<.85?'PORTRAIT':aspect>1.5?'ESTABLISHING':'SUPPORT';
return {width,height,aspect,brightness,contrast,chroma,warmth,dominantColors:rank.slice(0,4).map(c=>c.color),hueDistribution:hist.map(n=>n/(w*h)),edgeDensity:features.texture,detailDensity:C(features.texture*5),negativeSpace,safeTextRegions:negativeSpace.slice(0,4),visualCenter:focus,subjectSaliencyProxy:{center:focus,confidence:'heuristic',personRecognition:false},facePersonLikeRegion:{center:focus,confidence:'unverified; no face recognition'},logoLikeRegion:{center:focus,confidence:role==='LOGO'?'alpha/contrast proxy':'unverified'},crowdTexture:C(features.texture*5),blurProxy:blur,compressionAssessment:'unverified',cropFlexibility:C(1-Math.abs(aspect-1)*.25),portraitFit:C(resolution*.4+(1-Math.abs(focus[0]-.5))*.3+Math.min(1,1/aspect)*.3),quality,autoRole:role,category:['LOGO','TEXTURE','ABSTRACT'].includes(role)?'Utility':quality>=.55?'Primary':'Secondary',heroScore:quality,textCompatibility:1-negativeSpace[0].risk,motionCompatibility:C(quality*.7+.3),fingerprint:{perceptualHash:hash.join(''),colorSignature:features.palette,edgeSignature:edgeCells,layoutSignature:lumaCells,method:'local descriptor; no semantic embedding'}};};
J.assetSimilarity=(a,b)=>{const x=a.analysis?.fingerprint,y=b.analysis?.fingerprint;if(!x||!y)return {similarity:0,type:'unverified'};const h=avg([...x.perceptualHash].map((v,i)=>v===y.perceptualHash[i]?1:0)),color=1-avg(x.colorSignature.map((v,i)=>Math.abs(v-y.colorSignature[i]))),layout=1-avg(x.layoutSignature.map((v,i)=>Math.abs(v-y.layoutSignature[i])));return {similarity:C(h*.5+color*.2+layout*.3),type:a.dataUrl&&a.dataUrl===b.dataUrl?'exact duplicate':h>.92&&layout>.94?'near duplicate':layout>.95?'same composition':'distinct'};};
J.detectAssetDuplicates=assets=>assets.flatMap((a,i)=>assets.slice(0,i).map(b=>({assetId:a.id,otherId:b.id,...J.assetSimilarity(a,b)})).filter(d=>d.type!=='distinct'&&d.type!=='unverified'));
J.assetChapterFit=(asset,chapter,previous=null,uses=0,portrait=false)=>{const a=asset.analysis||{},role=asset.role==='AUTO'?a.autoRole:asset.role,intent=chapter.assetIntent||chapter.intent||chapter.role||'',semantic=asset.meaning||[],fit=/unity|build|climax/.test(intent)?['CROWD','HERO','SYMBOL'].includes(role):/identity|hook/.test(intent)?['ESTABLISHING','LOGO','SYMBOL','HERO'].includes(role):/break|tension/.test(intent)?['DETAIL','TEXTURE','ABSTRACT'].includes(role):['SUPPORT','ESTABLISHING','PORTRAIT'].includes(role),preference=chapter.preferredAssets?.includes(asset.id)?.15:0,duplicate=previous?J.assetSimilarity(asset,previous).similarity:0;
return C((a.quality??.5)*.28+(a.textCompatibility??.5)*.2+(portrait?a.portraitFit??.4:a.cropFlexibility??.5)*.17+(fit?.2:.08)+(semantic.some(s=>intent.includes(s))?.1:0)+preference-(uses*.06)-(duplicate>.9?.12:0)+(asset.pin==='climax'&&intent==='climax'?.35:0));};
J.buildAssetStoryboard=(p,project)=>{const assets=J.normalizeVisualAssets(project.visualAssets),available=assets.filter(a=>a.dataUrl&&a.pin!=='excluded'),uses=new Map(),story=[],duplicate=J.detectAssetDuplicates(assets);p.visualAssets=assets;p.scenePins=project.scenePins||[];p.assetDuplicates=duplicate;p.assetDeck=(p.assetDeck||[]).filter(a=>!assets.some(b=>a.id===b.id));if(!assets.length)return [];
let previous=null;const worlds=p.visualWorld?.chapters||[{from:0,to:p.duration,intent:'identity',energy:.5}];for(const [i,w] of worlds.entries()){const directive=project.directorPlan?.sections?.find(d=>w.from>=d.from&&w.from<d.to)||{};const chapter={...w,...directive},pinned=project.scenePins?.find(s=>Math.abs(s.from-w.from)<.01),eligible=available.filter(a=>a.pin==='required'||a.pin==='climax'||(a.analysis?.quality??.5)>=.35),pool=eligible.length?eligible:available.filter(a=>a.role==='TEXTURE'),ranked=pool.map(a=>({a,fit:J.assetChapterFit(a,chapter,previous,uses.get(a.id)||0,p.H>p.W)})).sort((a,b)=>b.fit-a.fit),locked=available.find(a=>a.id===pinned?.assetId),required=available.find(a=>a.pin==='required'&&!uses.has(a.id)),choice=locked?{a:locked,fit:J.assetChapterFit(locked,chapter,previous,0,p.H>p.W)}:required&&worlds.length-i<=available.filter(a=>a.pin==='required'&&!uses.has(a.id)).length?{a:required,fit:J.assetChapterFit(required,chapter,previous,0,p.H>p.W)}:ranked[0];
p.assetCandidateSearch=p.assetCandidateSearch||[];const beam=[];for(const item of ranked.slice(0,3))for(const variant of ['WIDE','DETAIL'])for(const treatment of ['photo-color','mono'])beam.push({assetId:item.a.id,variant,treatment,jointScore:C(item.fit+(variant==='WIDE'?(item.a.analysis?.cropFlexibility||.5)*.04:0)+(treatment==='mono'&&w.intent==='break'?.04:0))});p.assetCandidateSearch.push({chapter:i,candidates:beam.sort((a,b)=>b.jointScore-a.jointScore)});
let asset=choice?.a,variant=w.photoExit&&!locked&&!required?'TYPE_ONLY':w.intent==='climax'?'HERO':w.intent==='break'?'MONO':(uses.get(asset?.id)||0)>0?'DETAIL':'WIDE';if(locked&&pinned.variant)variant=pinned.variant;if(asset?.pin==='climax'&&w.intent==='climax')variant='HERO';const focus=asset?.crop?[C(asset.crop.x/100),C(asset.crop.y/100)]:asset?.analysis?.visualCenter||[.5,.5],safe=asset?.analysis?.safeTextRegions?.[0]||{x:.5,y:.46},same=previous&&asset?J.assetSimilarity(asset,previous):null,transition=!previous||same?.similarity<.65?'cut':same?.similarity>.9?'match-cut':'color-bridge';const scene={from:w.from,to:w.to,chapter:i,assetId:variant==='TYPE_ONLY'?null:asset?.id||null,variant,role:w.intent,style:w.style||p.styleId,typography:w.architecture,motif:w.motifState,camera:w.cameraLanguage,transition,semanticIntent:chapter.assetIntent||w.intent,fit:choice?.fit??0,locked:!!locked,crop:{x:focus[0]*100,y:focus[1]*100,zoom:asset?.crop?.zoom?C(asset.crop.zoom,.5,3):variant==='DETAIL'?1.35:1},textAnchor:{x:safe.x,y:C(safe.y,.22,.72)},reason:asset?`${w.intent}: ${asset.role==='AUTO'?asset.analysis?.autoRole||'AUTO':asset.role}; 構図・文字領域・品質の適合 ${Math.round((choice?.fit||0)*100)}%; ${variant}`:'文字主体の場面',usageState:!uses.has(asset?.id)?'introduced':w.intent==='climax'?'climax':'revisited'};
story.push(scene);if(scene.assetId){uses.set(asset.id,(uses.get(asset.id)||0)+1);previous=asset;}w.assetId=scene.assetId;}
p.storyboard=story;p.assetUsage={used:uses.size,total:assets.length,unused:assets.filter(a=>!uses.has(a.id)).map(a=>({id:a.id,reason:a.pin==='excluded'?'手動で除外':!a.dataUrl?'MISSING_ASSET':(a.analysis?.quality||0)<.35?'画質が主背景の基準未満':'章への適合順位／文字主体の場面を優先'})),counts:Object.fromEntries(uses)};p.assetShortlistLimit={assets:3,variants:2,treatments:2};p.globalVisualPalette=p.style?.schemes?.[0]||{};
p.assetDeck.push(...available.filter(a=>uses.has(a.id)).map(a=>({...a,role:'visual'})));J.applyAssetStoryboard(p);return story;};
J.applyAssetStoryboard=p=>{const boundaries=(p.storyboard||[]).map(s=>s.from);p.cuts=p.cuts.flatMap(c=>{const times=[c.start,...boundaries.filter(t=>t>c.start+.001&&t<c.end-.001),c.end].sort((a,b)=>a-b);return times.slice(0,-1).map((from,i)=>({...c,start:from,end:times[i+1],dur:times[i+1]-from,inDur:i?0:c.inDur,params:{...c.params}}));});p.cuts.forEach((c,i)=>c.index=i);for(const w of p.visualWorld?.chapters||[]){const s=p.storyboard?.find(s=>w.from>=s.from&&w.from<s.to);if(s){w.photoExit=!s.assetId;w.backgroundWorld=s.assetId?'photo':'typography-only';}}for(const c of p.cuts){const scene=p.storyboard?.find(s=>c.start>=s.from&&c.start<s.to);if(!scene)continue;c.visualAssetId=scene.assetId;c.assetId=scene.assetId;c.assetScene=scene;if(scene.assetId){c.photoExit=false;c.backgroundScene={...c.backgroundScene,id:scene.variant,x:scene.crop.x-50,y:scene.crop.y-50,zoom:scene.crop.zoom,blur:scene.variant==='MONO'?1:0,darkness:.12,filter:scene.variant==='MONO'?'grayscale(1) contrast(1.08)':'saturate(.92) contrast(1.04)',tint:p.globalVisualPalette?.accent};if(p.H>p.W)c.portraitAnchor=scene.textAnchor;}else c.photoExit=true;}};
const make=J.plan;J.plan=(project,audio)=>{const p=make(project,audio);if(p.motionDirector7){p.motionDirector8=true;J.buildAssetStoryboard(p,project);}return p;};
const applyWorld=J.applyVisualWorld7;J.applyVisualWorld7=(p,project)=>{applyWorld(p,project);if(p.storyboard)J.applyAssetStoryboard(p);};
const social=J.createSocialHookPlan;J.createSocialHookPlan=(p,candidate)=>{const s=social(p,candidate);if(p.visualAssets?.length){s.motionDirector8=true;const strategy=candidate.assetStrategy||'CLIMAX_FOCUSED',max=strategy==='HERO_FOCUSED'?1:strategy==='RAPID_MULTI_IMAGE'?4:3,chosen=p.visualAssets.filter(a=>a.dataUrl&&a.pin!=='excluded').sort((a,b)=>(b.analysis?.heroScore||0)-(a.analysis?.heroScore||0)).slice(0,max);J.buildAssetStoryboard(s,{visualAssets:chosen,scenePins:p.scenePins});s.socialAssetStrategy=strategy;}return s;};
// Decode sequentially, bound total retained pixels; originals remain in portable projects/IndexedDB.
const loadDeck=J.Renderer.prototype.loadAssetDeck;
J.Renderer.prototype.loadAssetDeck=function(p){
 const task=(this._deckQueue||Promise.resolve()).catch(()=>{}).then(async()=>{
  if(this._assetsDisposed)return;
  const visuals=(p.assetDeck||[]).filter(a=>a.role==='visual'),other=(p.assetDeck||[]).filter(a=>a.role!=='visual');
  await loadDeck.call(this,{...p,assetDeck:[...other,...visuals.filter(a=>this.assetBitmaps?.has(a.id)).map(a=>({...a,dataUrl:this.assetBitmaps.get(a.id).source}))]});
  if(this._assetsDisposed){this.disposeAssets();return;}
  this.assetBitmaps=this.assetBitmaps||new Map();
  const max=Math.min(2048,Math.floor(Math.sqrt(48*1024*1024/4/Math.max(1,visuals.length))));
  for(const a of visuals){
   const cached=this.assetBitmaps.get(a.id);if(cached?.source===a.dataUrl)continue;
   let base=null,bitmap=null;
   try{
    const response=await fetch(a.dataUrl);if(!response.ok)throw Error('画像素材を読み込めません');
    base=await createImageBitmap(await response.blob());bitmap=base;
    const r=Math.min(1,max/Math.max(base.width,base.height));
    if(r<1){bitmap=await createImageBitmap(base,{resizeWidth:Math.max(1,Math.round(base.width*r)),resizeHeight:Math.max(1,Math.round(base.height*r)),resizeQuality:'high'});base.close?.();base=null;}
    if(this._assetsDisposed){bitmap.close?.();return;}
    this.assetBitmaps.set(a.id,{bitmap,source:a.dataUrl,role:'visual'});cached?.bitmap?.close?.();
   }catch(e){bitmap?.close?.();if(base&&base!==bitmap)base.close?.();throw e;}
  }
  this.visualMemory={budgetBytes:48*1024*1024,retainedBytes:[...this.assetBitmaps.values()].filter(a=>a.role==='visual').reduce((s,a)=>s+a.bitmap.width*a.bitmap.height*4,0),maxDimension:max};
 });
 this._deckQueue=task;return task;
};
J.Renderer.prototype.disposeAssets=function(){this._assetsDisposed=true;for(const b of this.assetBitmaps?.values()||[]){b.bitmap?.close?.();b.video?.pause?.();if(b.video){b.video.removeAttribute?.('src');b.video.load?.();}}this.assetBitmaps?.clear();if(this.visualMemory)this.visualMemory.retainedBytes=0;for(const c of [this.scratch,this.small,this.tiny,this.transA,this.transB,this.transC,this.scan,...this.grain||[],...this.paperCache?.values()||[]])if(c&&typeof c.getContext==='function')c.width=c.height=1;this.grain=[];this.paperCache?.clear();};
const frame=J.Renderer.prototype.frame;J.Renderer.prototype.frame=function(ctx,p,t,opt){const c=J.cutAt(p,t),asset=this.assetBitmaps?.get(c?.visualAssetId),old=this.customBgBitmap;if(asset?.bitmap&&!p.singleBackground)this.customBgBitmap=asset.bitmap;try{return frame.call(this,ctx,p,t,opt);}finally{this.customBgBitmap=old;}};
// Semantic vocabulary is shared by context, resolver and renderer; no silent unknown verb substitution.
J.SEMANTIC_REGISTRY=Object.freeze(Object.fromEntries(['pierce','explode','unite','rise','flow','freeze','collapse','expand','echo','fall','rush','contract','surround','collide','reveal','dominate','celebrate','endure','ignite','break','resolve'].map(v=>[v,Object.freeze({...J.resolveVisualVerb(v),verb:v})])));
const resolve=J.resolveVisualVerb;J.resolveVisualVerb=v=>J.SEMANTIC_REGISTRY[String(v||'').toLowerCase()]?{...J.SEMANTIC_REGISTRY[String(v).toLowerCase()]}:{...resolve(v),fallback:true};
J.alignmentDomains8=(observer,targets)=>{const strong=(observer?.peaks||[]).filter(p=>['Hero','Major'].includes(p.tier)),score=times=>{if(!times?.length||!strong.length)return {score:null,samples:[],status:'UNMEASURED'};const samples=strong.map(p=>({time:p.time,errorMs:Math.min(...times.map(t=>Math.abs(t-p.time)))*1000,uncertaintyMs:(observer.sampleStep||.1)*500}));return {score:Math.round(100*samples.filter(s=>s.errorMs<=100).length/samples.length),samples,status:'PIXEL_PROXY',toleranceMs:100};};return {beatSync:score(targets.BEAT),lyricSync:score(targets.LYRIC_ONSET),note:'歌詞同期はLRC開始時刻と実画素ピークの一致。歌唱との知覚的同期は未検証。'};};
const context=J.directorContext;J.directorContext=(project,p,audio,image)=>({...context(project,p,audio,image),schema:'jizura-director-context-v7',semanticVocabulary:Object.keys(J.SEMANTIC_REGISTRY),assets:(p.visualAssets||J.normalizeVisualAssets(project.visualAssets)).map(({dataUrl,...a})=>a),currentStoryboard:p.storyboard||[],assetUsage:p.assetUsage,assetDuplicates:p.assetDuplicates,alignmentDomains:p.lastPixelQA?.metrics?.alignmentDomains||null,metricPolicy:'Observed pixels only. Missing measurements are null. Engineering proxies are not aesthetic certification.'});
const prompt=J.directorPrompt;J.directorPrompt=()=>prompt()+' Context v7のassetsとCURRENT_STORYBOARDを読み、chaptersにpreferredAssets（既存Asset IDのみ）とassetIntent、assetSemanticsにassetId/role/meaning/recommendedUseを指定できます。品質上不要なら画像を使わなくてよい。画像の意味は画像自体で確認し、ローカルdescriptorを認識結果と誤解しないでください。';
const validate=J.validateDirectorPlan;J.validateDirectorPlan=(input,project,p,audio)=>{const r=validate(input,project,p,audio),ids=new Set(J.normalizeVisualAssets(project.visualAssets).map(a=>a.id));for(const c of r.candidates){const raw=(input.candidates||[input])[c.index];c.plan.assetSemantics=[];for(const s of (Array.isArray(raw.assetSemantics)?raw.assetSemantics:[]).slice(0,12)){if(!ids.has(s.assetId)){r.errors.push('未知のAsset ID: '+String(s.assetId));r.valid=false;continue;}c.plan.assetSemantics.push({assetId:s.assetId,role:String(s.role||'').slice(0,32),meaning:(Array.isArray(s.meaning)?s.meaning:[]).filter(x=>typeof x==='string').slice(0,12).map(x=>x.replace(/[<>]/g,'').slice(0,40)),recommendedUse:(Array.isArray(s.recommendedUse)?s.recommendedUse:[]).filter(x=>typeof x==='string').slice(0,8)});}for(const s of c.plan.sections){const source=(raw.chapters||raw.sections||[]).find(d=>+d.from===s.from&&+d.to===s.to);s.preferredAssets=(Array.isArray(source?.preferredAssets)?source.preferredAssets:[]).filter(id=>{if(ids.has(id))return true;r.errors.push('未知のAsset ID: '+String(id));r.valid=false;return false;}).slice(0,3);s.assetIntent=String(source?.assetIntent||'').replace(/[<>]/g,'').slice(0,80);}}return r;};
const apply=J.applyDirectorPlan;J.applyDirectorPlan=(project,d,audio)=>{const copy=apply(project,d,audio);for(const s of copy.directorPlan?.assetSemantics||[]){const a=copy.visualAssets?.find(a=>a.id===s.assetId);if(a){a.meaning=s.meaning;a.semanticRole=s.role;}}return copy;};
J.assetContactSheet=async project=>{const assets=J.normalizeVisualAssets(project.visualAssets),c=document.createElement('canvas');c.width=1200;c.height=Math.max(230,Math.ceil(assets.length/4)*230);const ctx=c.getContext('2d');ctx.fillStyle='#111827';ctx.fillRect(0,0,c.width,c.height);for(const [i,a] of assets.entries()){const x=(i%4)*300,y=Math.floor(i/4)*230;if(a.dataUrl){const b=await createImageBitmap(await(await fetch(a.dataUrl)).blob());const r=Math.min(280/b.width,165/b.height);ctx.drawImage(b,x+10,y+10,b.width*r,b.height*r);b.close();}ctx.fillStyle='#fff';ctx.font='14px sans-serif';ctx.fillText(a.id+' '+(a.role==='AUTO'?a.analysis?.autoRole||'AUTO':a.role),x+10,y+193);ctx.fillText((a.analysis?.width||'?')+' × '+(a.analysis?.height||'?')+' '+(a.analysis?.dominantColors||[]).slice(0,2).join(' '),x+10,y+214);}return new Promise(r=>c.toBlob(r,'image/jpeg',.86));};
const extendZip=async(blob,project,p)=>{const bytes=new Uint8Array(await blob.arrayBuffer()),view=new DataView(bytes.buffer),zip=new J.ZipWriter();let pos=0;while(pos+30<bytes.length&&view.getUint32(pos,true)===0x04034b50){const size=view.getUint32(pos+18,true),nl=view.getUint16(pos+26,true),el=view.getUint16(pos+28,true),name=new TextDecoder().decode(bytes.slice(pos+30,pos+30+nl)),start=pos+30+nl+el;zip.add(name,bytes.slice(start,start+size));pos=start+size;}const add=(n,v)=>zip.add(n,new TextEncoder().encode(JSON.stringify(v,null,2)));for(const a of J.normalizeVisualAssets(project.visualAssets))if(a.dataUrl){const ext=a.dataUrl.includes('image/png')?'png':a.dataUrl.includes('image/jpeg')?'jpg':'webp';zip.add('assets/'+a.id+'.'+ext,new Uint8Array(await(await fetch(a.dataUrl)).arrayBuffer()));}if(project.visualAssets?.length)zip.add('ASSET_CONTACT_SHEET.jpg',new Uint8Array(await(await J.assetContactSheet(project)).arrayBuffer()));add('CURRENT_STORYBOARD.json',p?.storyboard||[]);add('UNUSED_ASSETS.json',p?.assetUsage?.unused||[]);add('OVERUSED_ASSETS.json',Object.entries(p?.assetUsage?.counts||{}).filter(([,n])=>n>3));add('WEAK_ASSET_TRANSITIONS.json',p?.lastPixelQA?.metrics?.assetReality?.weakTransitions||[]);return zip.finish();};
const pack=J.createDirectorPack;J.createDirectorPack=async args=>extendZip(await pack(args),args.project,args.context?.currentStoryboard?{storyboard:args.context.currentStoryboard,assetUsage:args.context.assetUsage}:null);
const revision=J.createDirectorRevisionPack;J.createDirectorRevisionPack=async args=>extendZip(await revision(args),args.project,args.plan);
const quality=J.checkMVQuality;J.checkMVQuality=(project,p,audio,range,pixel,caps,validation)=>{const r=quality(project,p,audio,range,pixel,caps,validation);if(!p.motionDirector8)return r;const q=r.quality,alignment=J.alignmentDomains8(pixel?.metrics?.observer,J.musicalTargets(p));q.productionDomains.beatSync=alignment.beatSync.score;q.productionDomains.lyricSync=alignment.lyricSync.score;q.metricCaveat=alignment.note;if(pixel?.metrics)pixel.metrics.alignmentDomains=alignment;const assets=p.visualAssets||[],measured=pixel?.metrics?.assetReality;const failed=(code,message,severity='WARNING')=>{if(!r.issues.some(i=>i.code===code))r.issues.push({code,message,severity,exportBlocking:false});};for(const a of assets){if(!a.dataUrl)failed('BROKEN_ASSET',a.name+' の画像が不足しています');if(p.storyboard?.some(s=>s.assetId===a.id)&&(a.analysis?.quality??1)<.35)failed('IMAGE_TOO_LOW_RES',a.name+' は主背景として画質が不足しています');}q.productionDomains.assetDirection=measured?.score??null;q.productionDomains.multiImageCoherence=measured?.coherence??null;if(measured?.criticalFailures)failed('BROKEN_IMAGE_TRANSITION','画像切替または実画素への表示が不足しています','ERROR');for(const scene of p.storyboard||[]){const directive=project.directorPlan?.sections?.find(d=>scene.from>=d.from&&scene.from<d.to);if(directive?.preferredAssets?.length&&scene.assetId&&!directive.preferredAssets.includes(scene.assetId))failed('ASSET_SEMANTIC_MISMATCH','Directorの画像候補と実使用画像が一致しません');}if(Object.values(p.assetUsage?.counts||{}).some(n=>n>4))failed('ASSET_OVERUSE','同一画像の使用が多いため、再利用の意図を確認してください');if(assets.length>1){q.certified100=!!q.certified100&&measured?.score>=95&&measured?.coherence>=95&&!measured?.criticalFailures;q.creativeScore=Math.min(q.creativeScore,measured?.score??94);}if(alignment.beatSync.score===null||alignment.lyricSync.score===null)q.certified100=false;if(r.issues.some(i=>['ERROR','WARNING'].includes(i.severity)))q.certified100=false;q.perfectEligible=q.certified100;q.overallScore=q.score=q.certified100?100:Math.min(99,q.score);r.errors=r.issues.filter(i=>i.severity==='ERROR');r.warnings=r.issues.filter(i=>i.severity==='WARNING');q.hardGates={...q.hardGates,passed:r.errors.length===0,total:r.errors.length};p.currentQualityScores=q.productionDomains;return r;};
})();
/* Pixel audit keeps measurement evidence separate from descriptor/selection scores. */
(()=>{'use strict';const J=window.J,mean=a=>a.length?a.reduce((s,v)=>s+v,0)/a.length:0;
J.measureAssetReality8=async(p,range,telemetry={})=>{if(!p.visualAssets?.length)return {measured:false,score:null,coherence:null,criticalFailures:0,weakTransitions:[]};telemetry.onProgress?.({label:'画像の選定・切り替えを画素で検査しています'});await new Promise(r=>setTimeout(r,0));const R=new J.Renderer(),c=document.createElement('canvas'),m=document.createElement('canvas'),W=160,H=Math.round(W*p.H/p.W);c.width=m.width=W;c.height=m.height=H;const ctx=c.getContext('2d'),mc=m.getContext('2d'),samples=[],transitions=[];let critical=0;try{if(p.customBg?.enabled)await R.loadCustomBackground(p.customBg.dataUrl);await R.loadAssetDeck(p);const snap=(plan,t)=>{ctx.clearRect(0,0,W,H);mc.clearRect(0,0,W,H);R.frame(ctx,plan,t,{scale:W/p.W,production:true,range,lyricAuditCtx:mc,lyricAuditItems:[]});return J.observePixelFrame(ctx.getImageData(0,0,W,H).data,W,H,mc.getImageData(0,0,W,H).data);};
for(const scene of p.storyboard||[]){if(telemetry.onProgress)await new Promise(r=>setTimeout(r,0));if(range&&(scene.to<=range.start||scene.from>=range.end))continue;const from=Math.max(scene.from,range?.start??0),to=Math.min(scene.to,range?.end??p.duration),t=from+(to-from)*.45,a=snap(p,t),cut=J.cutAt(p,t),asset=p.visualAssets.find(a=>a.id===scene.assetId),cached=R.assetBitmaps.get(scene.assetId);let visible=null;if(scene.assetId&&cut&&cached?.bitmap){const control={...p,visualWorld:{...p.visualWorld,chapters:p.visualWorld.chapters.map(w=>t>=w.from&&t<w.to?{...w,photoExit:true,backgroundWorld:'typography-only'}:w)},cuts:p.cuts.map(c=>c===cut?{...c,assetId:null,visualAssetId:null,photoExit:true}:c)},b=snap(control,t);const delta=mean(a.luma.map((v,i)=>Math.abs(v-b.luma[i])));visible=delta>.004;samples.push({assetId:scene.assetId,time:t,backgroundPixelDelta:delta,visible,meanLuma:mean(a.luma),assignmentMatches:cut.assetId===scene.assetId,fitProxy:scene.fit,semanticConfidence:asset?.meaning?.length?'manual-director':'role-proxy',subjectRecognition:false});if(!visible)critical++;}
if(scene.from>0&&(!range||scene.from>range.start)){const before=snap(p,Math.max(range?.start??0,scene.from-.06)),peak=snap(p,scene.from+.02),after=snap(p,Math.min(to-.01,scene.from+.12));const black=[before,peak,after].some(f=>mean(f.luma)<.002),paletteDelta=mean(before.palette.map((v,i)=>Math.abs(v-after.palette[i])));transitions.push({time:scene.from,before:mean(before.luma),peak:mean(peak.luma),after:mean(after.luma),blackFrame:black,paletteDelta,transition:scene.transition});if(black)critical++;}}
const measured=samples.length>0,visibility=measured?100*samples.filter(s=>s.visible&&s.assignmentMatches).length/samples.length:null,fit=measured?mean(samples.map(s=>s.fitProxy))*100:null,weakTransitions=transitions.filter(t=>t.blackFrame);return {measured,score:measured?Math.round(Math.min(visibility,visibility*.7+fit*.3)-Math.max(0,visibility-fit)*.15):null,coherence:transitions.length?Math.round(Math.max(0,100-mean(transitions.map(t=>t.paletteDelta))*100-weakTransitions.length*25)):null,criticalFailures:critical,samples,transitions,weakTransitions,method:'same renderer photo-on/type-only control and transition before/peak/after; composition/semantic fit remains a local proxy, not human subject recognition'};}finally{R.customBgBitmap?.close?.();R.disposeAssets();}};
const analyze=J.analyzeRenderedFrames;J.analyzeRenderedFrames=async(p,range,audio,telemetry={})=>{const r=await analyze(p,range,audio,telemetry);if(r.completed&&p.motionDirector8){r.metrics.assetReality=await J.measureAssetReality8(p,range,telemetry);r.metrics.alignmentDomains=J.alignmentDomains8(r.metrics.observer,J.musicalTargets(p));p.lastPixelQA=r;}return r;};
const provenance=J.createExportProvenance;J.createExportProvenance=async(args,result,report)=>({...await provenance(args,result,report),visualAssetHashes:await Promise.all((args.plan.visualAssets||[]).map(async a=>({id:a.id,sha256:a.dataUrl?await J.sha256(await(await fetch(a.dataUrl)).arrayBuffer()):null}))),assetReality:args.plan.lastPixelQA?.metrics?.assetReality||null});
// Release temporary decodes created by observer and revision work without touching preview renderers.
const collect=J.collectCanvasObserver;J.collectCanvasObserver=async(...args)=>collect(...args);
})();
(()=>{'use strict';const J=window.J,hash=J.directorProjectHash;J.directorProjectHash=(p,d,a)=>{const base=hash(p,d,a);if((p.visualAssets?.length||0)<2)return base;let h=2166136261;const value=JSON.stringify(p.visualAssets.map(x=>({id:x.id,role:x.role,pin:x.pin,crop:x.crop,dataUrl:x.dataUrl||''})));for(let i=0;i<value.length;i++)h=Math.imul(h^value.charCodeAt(i),16777619)>>>0;return base+'-'+h.toString(16).padStart(8,'0');};})();
