/* Cinema V3 contracts and adapters. Existing renderer and save formats stay authoritative. */
(()=>{
'use strict';
const J=window.J, V=J.cinemaV3={version:'3.0.3',enabled:true}, finite=Number.isFinite;
/** @typedef {'MEASURED'|'UNMEASURED'|'NOT_APPLICABLE'|'FAILED'} EvidenceStatus */
/** @typedef {{value:*,confidence:number,source:string,status:EvidenceStatus,limitations?:string[]}} Feature */
/** @typedef {{inputHash:string,audioHash:?string,imageHashes:string[],lyricsHash:string,projectHash:string,rendererVersion:string,outputProfile:Object,userLocks:Object}} ImmutableInputSnapshot */
/** @typedef {{from:number,to:number,energy:Feature,beatSalience:Feature,onsetDensity:Feature,lyricDensity:Feature,repetition:Feature,role:Feature}} SectionFeatures */
/** @typedef {{mode:string,stageRole:string,motionBudget:number,attentionBudget:number,typographyBudget:number,desiredChange:number,confidence:number,quietIntent:boolean}} DirectionPolicy */
/** @typedef {{line:number,from:number,to:number,role:string,grammarId:string,typographyId:string,motionId:string,safeArea:Object,minReadableFrames:number,maxOcclusionRatio:number,reasonCodes:string[],featureSources:string[],userLocked:boolean}} ShotContract */
/** @typedef {{id:string,value:?number,unit:string,source:string,status:EvidenceStatus,sampleCount:number,affectedLineIds:number[],confidence:number,profileId:string,thresholdId:string,method:string,planHash:string,inputHash:string,rendererVersion:string,outputProfile:Object}} MetricEvidence */
/** @typedef {{id:string,planHash:string,candidateSeed:number,hardFailures:string[],measurements:MetricEvidence[],objectives:Object,lowerTail:?number,constraintViolations:number,memoryBudgetBytes:number,timeCostMs:number}} CandidateEvaluation */
/** @typedef {{previousPlanHash:string,nextPlanHash:string,failuresAddressed:string[],operatorId:string,changedLines:number[],unchangedLines:number[],before:CandidateEvaluation,after:CandidateEvaluation,accepted:boolean,reason:string,artifacts:string[]}} RepairResult */
const statuses=['MEASURED','UNMEASURED','NOT_APPLICABLE','FAILED'], roles=['introduce','develop','contrast','resolve','sustain'];
const str=v=>typeof v==='string'&&v.length>0, number=v=>finite(v), nonnegative=v=>finite(v)&&v>=0, integer=v=>Number.isInteger(v)&&v>=0, unit=v=>finite(v)&&v>=0&&v<=1, bool=v=>typeof v==='boolean', arrayOf=f=>v=>Array.isArray(v)&&v.every(f), nullable=f=>v=>v===null||f(v), oneOf=a=>v=>a.includes(v), object=v=>v!==null&&typeof v==='object'&&!Array.isArray(v);
const profile=p=>object(p)&&oneOf(['FULL_MV','SHORT','LOOP_SHORT','SQUARE'])(p.purpose)&&str(p.aspect)&&number(p.fps)&&p.fps>0&&Array.isArray(p.range)&&p.range.length===2&&p.range.every(nonnegative)&&p.range[1]>p.range[0]&&bool(p.loopRequired);
const fields=(v,schema)=>object(v)&&Object.entries(schema).every(([k,f])=>f(v[k]));
const feature=v=>fields(v,{value:x=>x!==undefined,confidence:unit,source:str,status:oneOf(statuses)})&&(v.status==='MEASURED'?v.value!==null:v.value===null&&v.confidence===0)&&(v.limitations===undefined||arrayOf(str)(v.limitations));
const snapshot=v=>fields(v,{inputHash:str,audioHash:nullable(str),imageHashes:arrayOf(str),lyricsHash:str,projectHash:str,rendererVersion:str,outputProfile:profile,userLocks:x=>fields(x,{lockedLines:arrayOf(integer),manualTypography:arrayOf(integer),manualCamera:arrayOf(integer)})});
const metric=v=>fields(v,{id:str,value:nullable(number),unit:str,source:oneOf(['PLAN','CANVAS','ENCODED_MP4','HUMAN']),status:oneOf(statuses),sampleCount:integer,affectedLineIds:arrayOf(integer),confidence:unit,profileId:str,thresholdId:str,method:str,planHash:str,inputHash:str,rendererVersion:str,outputProfile:profile})&&(v.status==='MEASURED'?v.value!==null&&v.sampleCount>0&&v.confidence>0:v.value===null&&v.confidence===0)&&(v.status!=='NOT_APPLICABLE'||str(v.reason));
const evaluation=v=>fields(v,{id:str,planHash:str,candidateSeed:integer,hardFailures:arrayOf(str),measurements:arrayOf(metric),objectives:x=>object(x)&&Object.values(x).every(nullable(number)),lowerTail:nullable(number),constraintViolations:integer,memoryBudgetBytes:nonnegative,timeCostMs:nonnegative})&&new Set(v.measurements.map(m=>m.id)).size===v.measurements.length;
const validators={EvidenceStatus:oneOf(statuses),Feature:feature,ImmutableInputSnapshot:snapshot,SectionFeatures:v=>fields(v,{from:nonnegative,to:nonnegative,energy:feature,beatSalience:feature,onsetDensity:feature,lyricDensity:feature,repetition:feature,role:x=>feature(x)&&(x.value===null||oneOf(['intro','verse','chorus','bridge','climax','outro','unknown'])(x.value))})&&v.to>v.from,DirectionPolicy:v=>fields(v,{mode:oneOf(['cinematic','energetic','minimal','lyric_first','mixed']),stageRole:oneOf(roles),motionBudget:unit,attentionBudget:unit,typographyBudget:unit,desiredChange:unit,confidence:unit,quietIntent:bool}),ShotContract:v=>fields(v,{line:integer,from:nonnegative,to:nonnegative,role:oneOf(roles),grammarId:str,typographyId:str,motionId:str,safeArea:x=>fields(x,{left:unit,right:unit,top:unit,bottom:unit})&&x.left<x.right&&x.top<x.bottom,minReadableFrames:integer,maxOcclusionRatio:unit,reasonCodes:arrayOf(str),featureSources:arrayOf(str),userLocked:bool})&&v.to>v.from,MetricEvidence:metric,CandidateEvaluation:evaluation,RepairResult:v=>fields(v,{previousPlanHash:str,nextPlanHash:str,failuresAddressed:arrayOf(str),operatorId:str,changedLines:arrayOf(integer),unchangedLines:arrayOf(integer),before:evaluation,after:evaluation,accepted:bool,reason:str,artifacts:arrayOf(str)})};
V.validate=(type,value)=>{if(!validators[type])throw new TypeError('Unknown Cinema V3 contract: '+type);if(!validators[type](value))throw new TypeError('Invalid Cinema V3 '+type);return value;};
V.feature=(value,source,confidence=1,status=value===null?'UNMEASURED':'MEASURED')=>V.validate('Feature',{value,status,source,confidence:status==='MEASURED'?confidence:0});
V.legacyPlanningStates=new WeakMap();
V.clone=value=>{const copy=J.clonePhotoRenderPlan(value),legacy=value&&typeof value==='object'?V.legacyPlanningStates.get(value):null;if(legacy)V.legacyPlanningStates.set(copy,legacy);return copy;};
V.captureLegacyPlan=p=>{if(p.cinemaCandidateMode!=='legacy'&&!V.legacyPlanningStates.has(p))V.legacyPlanningStates.set(p,J.clonePhotoRenderPlan(p));};
// Freeze only owned JSON metadata; never freeze PCM buffers, DOM or codec objects.
V.freezeMetadata=value=>{if(value&&typeof value==='object'){Object.values(value).forEach(V.freezeMetadata);Object.freeze(value);}return value;};
// The design canvas (e.g. 1920×1080) is not the requested delivery raster.
V.bindDelivery=(p,project)=>{const [width,height]=J.outputSize(project);if(p.cinemaDelivery?.width!==width||p.cinemaDelivery?.height!==height){delete p.musicalPhoto?.cinema?.architectureSearch;delete p.musicalPhoto?.preparation;}p.cinemaDelivery={width,height};return p;};
const deliveryPlan=J.plan;J.plan=(project,...args)=>V.bindDelivery(deliveryPlan(project,...args),project);
V.outputProfile=(p,range=null)=>{const loop=p.exportSettings?.loopRequired===true,short=!!p.socialHook,aspect=(()=>{const gcd=(a,b)=>b?gcd(b,a%b):a,d=gcd(p.W,p.H);return p.W/d+':'+p.H/d;})();return V.validateProfile({purpose:loop?'LOOP_SHORT':short?'SHORT':aspect==='1:1'?'SQUARE':'FULL_MV',aspect,fps:p.fps,range:[range?.start??p.socialHook?.start??0,range?.end??p.socialHook?.end??p.duration],loopRequired:loop,...(p.cinemaDelivery?{resolution:[p.cinemaDelivery.width,p.cinemaDelivery.height]}:{})});};
V.validateProfile=p=>{if(!profile(p))throw new TypeError('Invalid Cinema V3 output profile');return p;};
V.profileId=p=>J.canonicalJSON(p);
V.audioHash=async audio=>{const b=audio?.buffer;if(!b?.getChannelData)return null;const parts=[];for(let c=0;c<b.numberOfChannels;c++){const pcm=b.getChannelData(c);parts.push(await J.sha256(new Uint8Array(pcm.buffer,pcm.byteOffset,pcm.byteLength)));}return J.sha256(J.canonicalJSON({sampleRate:b.sampleRate,channels:b.numberOfChannels,length:b.length,parts}));};
V.snapshot=async(project,audio,p,range=null)=>{
 const images=[project.customBg?.dataUrl,...(project.visualAssets||[]).map(a=>a.dataUrl)].filter(Boolean),outputProfile=V.outputProfile(p,range),locked=(p.cuts||[]).filter(c=>c.line>=0&&(c.locked||J.photoChoreographyLocked?.(p,c))).map(c=>c.line);
 const [audioHash,imageHashes,lyricsHash,projectHash]=await Promise.all([V.audioHash(audio),Promise.all(images.map(src=>J.sha256(src))),J.sha256(J.canonicalJSON({lyrics:project.lyrics,timing:project.timing,lines:p.lines})),J.sha256(J.canonicalJSON(project))]);
 const state={audioHash,imageHashes,lyricsHash,projectHash,rendererVersion:V.version,proceduralTextureVersion:J.proceduralTextureVersion,outputProfile,userLocks:{lockedLines:[...new Set(locked)].sort((a,b)=>a-b),manualTypography:locked.slice(),manualCamera:locked.slice()}};
 state.inputHash=await J.sha256(J.canonicalJSON(state));return V.freezeMetadata(V.validate('ImmutableInputSnapshot',state));
};
V.planHash=p=>J.sha256(J.canonicalJSON(p));
V.assertSnapshot=async(expected,project,audio,p,range)=>{const next=await V.snapshot(project,audio,p,range);if(next.inputHash!==expected.inputHash){V.invalidate(p);throw new Error('INPUT_CHANGED');}return next;};
V.invalidate=p=>{p.lastPixelQA=null;delete p.lastQualityTarget;delete p._provenancePlanHash;J.clearPhotoComposition?.(p);};
V.createPlan=async(project,audio,options={})=>{const workingProject=V.clone(project),working=J.plan(workingProject,audio),input=await V.snapshot(project,audio,working,options.range);return {input,working,confirmed:null,planHash:await V.planHash(working)};};
V.evaluate=(...args)=>J.checkMVQuality(...args);
V.repair=(p,acceptance,attempt=1)=>J.repairPhotoBottlenecks(p,acceptance,attempt);
V.confirm=async(session,project,audio,range)=>{await V.assertSnapshot(session.input,project,audio,session.working,range);session.confirmed=V.clone(session.working);session.planHash=await V.planHash(session.confirmed);return session.confirmed;};
})();
/* Hierarchical ranking: values retain their units and missing evidence remains null. */
(()=>{
'use strict';const J=window.J,V=J.cinemaV3,finite=Number.isFinite;
V.metric=(id,value,metadata={})=>{
 const status=metadata.status||(finite(value)&&metadata.sampleCount>0?'MEASURED':'UNMEASURED');
 return V.validate('MetricEvidence',{id,value:status==='MEASURED'?value:null,unit:'score/100',source:'CANVAS',sampleCount:0,affectedLineIds:[],confidence:status==='MEASURED'?1:0,profileId:V.profileId(metadata.outputProfile),thresholdId:'existing-kamen-v2.0.26',method:'existing renderer observation',planHash:'unbound',inputHash:'unbound',rendererVersion:V.version,...metadata,status,...(status==='MEASURED'?{}:{value:null,confidence:0})});
};
V.requiredMetrics=(stage,{allIntentionalHolds=false}={})=>stage==='A'?['rasterSafety']:stage==='B'?['rasterSafety',...allIntentionalHolds?[]:['holdMotion']]:stage==='C'?['rasterSafety','localContrast','outputReadability','frameAlignedOutputReadability','lowerTail']:['rasterSafety','localContrast','lowerTail','videoStructure','audioEndpoint'];
V.comparable=(a,b)=>a.unit===b.unit&&a.source===b.source&&a.method===b.method&&a.profileId===b.profileId&&a.inputHash===b.inputHash&&a.rendererVersion===b.rendererVersion;
J.rankCinemaCandidateV2=(candidate,profile,baseline=null)=>{
 V.validate('CandidateEvaluation',candidate);const fail=(reason,extra={})=>({eligible:false,reason,...extra,rankVector:null});
 if(candidate.measurements.some(m=>m.planHash!==candidate.planHash)||new Set(candidate.measurements.map(m=>m.inputHash)).size>1||new Set(candidate.measurements.map(m=>m.rendererVersion)).size>1)return fail('STALE_EVIDENCE');
 if(candidate.measurements.some(m=>m.rendererVersion!==V.version))return fail('STALE_RENDERER');if(candidate.hardFailures.length)return fail('HARD_FAILURE',{failures:candidate.hardFailures});const technical=candidate.measurements.filter(m=>['rasterSafety','videoStructure','audioEndpoint'].includes(m.id)&&m.status==='MEASURED'&&m.value!==100);if(technical.length)return fail('HARD_FAILURE',{failures:technical.map(m=>m.id)});
 const measurements=new Map(candidate.measurements.map(m=>[m.id,m])),required=profile.requiredMetrics||V.requiredMetrics(profile.stage,profile),missing=required.filter(id=>{const m=measurements.get(id);return !m||m.status!=='MEASURED'||m.confidence<=0||m.sampleCount<=0;});
 const failed=required.filter(id=>measurements.get(id)?.status==='FAILED');if(failed.length)return fail('REQUIRED_FAILED',{failed});if(missing.length)return fail('REQUIRED_UNMEASURED',{missing});
 if(candidate.measurements.some(m=>m.profileId!==profile.profileId))return fail('PROFILE_MISMATCH');
 const regressions=[],incomparable=[];
 if(baseline)for(const prior of baseline.measurements){const m=measurements.get(prior.id),protectedMetric=prior.id.startsWith('decodedPhysicalContrast@')||prior.id.startsWith('decodedFrameAlignedContrast@')||prior.id.startsWith('decodedLocalContrast@')||prior.id==='rasterSafety'||prior.id==='localContrast'||prior.id==='outputReadability'||prior.id==='frameAlignedOutputReadability'||(prior.status==='MEASURED'&&prior.value>=(profile.protectionThresholds?.[prior.id]??90));
  if(!protectedMetric||prior.status!=='MEASURED')continue;if(!m||m.status!=='MEASURED'){regressions.push(prior.id);continue;}if(!V.comparable(m,prior)){incomparable.push(prior.id);continue;}if(m.value<prior.value)regressions.push(prior.id);
 }
 if(incomparable.length)return fail('INCOMPARABLE_EVIDENCE',{incomparable});if(regressions.length)return fail('PROTECTED_REGRESSION',{regressions});
 const confidence=Math.min(...required.map(id=>measurements.get(id).confidence)),n=v=>finite(v)?v:-Infinity,o=candidate.objectives;
 return {eligible:true,reason:'MEASURED_COMPARABLE',missing:[],rankVector:[-candidate.constraintViolations,confidence,n(candidate.lowerTail),n(o.readability),n(o.musicFit),n(o.visualCoherence),n(o.contextualVariation),candidate.timeCostStatus==='UNMEASURED'?-Infinity:-candidate.timeCostMs],artistic100Established:false};
};
V.compareRanks=(a,b)=>{for(let i=0;i<a.length;i++)if(a[i]!==b[i])return a[i]>b[i]?-1:1;return 0;};
V.select=(candidates,profile,baseline=null)=>{
 const ranked=candidates.map(c=>({candidate:c,...J.rankCinemaCandidateV2(c,profile,baseline)}));
 const eligible=ranked.filter(c=>c.eligible),dominates=(a,b)=>a.rankVector.every((v,i)=>v>=b.rankVector[i])&&a.rankVector.some((v,i)=>v>b.rankVector[i]);
 const frontier=eligible.filter(b=>!eligible.some(a=>a!==b&&dominates(a,b))).sort((a,b)=>V.compareRanks(a.rankVector,b.rankVector)||(String(a.candidate.id)<String(b.candidate.id)?-1:String(a.candidate.id)>String(b.candidate.id)?1:0));
 return {selected:frontier[0]?.candidate??null,ranked,paretoIds:frontier.map(c=>c.candidate.id),status:frontier.length?'SELECTED':'NO_ELIGIBLE_CANDIDATE'};
};
V.searchEvaluation=(item,p,stage,inputHash='search-local',range=null)=>{
 const profile=V.outputProfile(p,range),r=item.raster,encoded=item.encoded,rows=r?.samples||[],d=encoded?.completed?encoded:null,holds=item.video?.samples||[],allIntentionalHolds=holds.length>0&&holds.every(s=>s.intentionalHold),hardFailures=[];
 if(rows.some(s=>!s.safe))hardFailures.push('RASTER_LYRIC_OR_SAFE_AREA');
 if(d?.layerPresence?.primaryText?.samples?.some(s=>s.visibleSamples<s.samples.length))hardFailures.push('ENCODED_LYRIC_MISSING');
 const base={outputProfile:profile,profileId:V.profileId(profile),planHash:item.planHash||'search-'+item.id,inputHash,sampleCount:rows.length,affectedLineIds:rows.map(s=>s.line),method:'128px production glyph presence and safe area'},measurements=[V.metric('rasterSafety',rows.length?(rows.every(s=>s.safe)?100:0):null,base)];
 measurements.push(V.metric('rasterRank',r?.rank??null,{...base,unit:'legacy-raster-rank'}));
 if(stage!=='A')measurements.push(V.metric('holdMotion',item.video?.score??null,{...base,sampleCount:holds.filter(s=>!s.intentionalHold).length,method:'320px 10fps production HOLD block-flow',...(allIntentionalHolds?{status:'NOT_APPLICABLE',reason:'Every sampled HOLD is intentional'}:{})}));
 if(stage==='C')for(const [id,value,count]of [['localContrast',d?.metrics?.localContrast??null,d?.readability?.sampleCount||0],['lowerTail',d?.lowerTailQuality??null,d?.sceneQuality?.length||0]])measurements.push(V.metric(id,value,{...base,source:'ENCODED_MP4',method:'640px 10fps H264 decode / '+id,sampleCount:count,status:finite(value)&&count?'MEASURED':encoded?.status==='FAILED'?'FAILED':'UNMEASURED'}));
 if(stage==='C'){const native={...base,source:'CANVAS',method:'requested raster/FPS with unchanged final observer cadence'};measurements.push(V.metric('outputReadability',item.outputReadability?.score??null,{...native,sampleCount:item.outputReadability?.samples?.length||0}));
 measurements.push(V.metric('frameAlignedOutputReadability',item.outputReadability?.frameAlignedScore??null,{...native,method:'requested delivered frame image and glyph/background at identical actual frame time',sampleCount:item.outputReadability?.samples?.length||0}));
 // Preserve already-readable phrase intervals, not only the video's weakest point.
 for(const sample of item.outputReadability?.samples||[])if(finite(sample.time))measurements.push(V.metric('outputReadability@'+sample.time,sample.contrast?.score??null,{...native,sampleCount:finite(sample.contrast?.score)?1:0,affectedLineIds:sample.line==null?[]:[sample.line]}));
 for(const sample of item.outputReadability?.samples||[])if(finite(sample.time))measurements.push(V.metric('frameAlignedOutputReadability@'+sample.time,sample.alignedContrast?.score??null,{...native,method:'requested delivered frame image and glyph/background at identical actual frame time',sampleCount:finite(sample.alignedContrast?.score)?1:0,affectedLineIds:sample.line==null?[]:[sample.line]}));
 }
 const lower=stage==='C'?d?.lowerTailQuality??null:stage==='B'?item.video?.score??null:null;
 return {evaluation:V.validate('CandidateEvaluation',{id:String(item.id),planHash:base.planHash,candidateSeed:J.cinemaContentSeed(p),hardFailures,measurements,objectives:{readability:stage==='C'?(finite(d?.metrics?.localContrast)&&finite(item.outputReadability?.score)?Math.min(d.metrics.localContrast,item.outputReadability.score):null):rows.length?Math.min(...rows.map(s=>s.safe?100:0)):null,musicFit:d?.metrics?.impactBeatSync??null,visualCoherence:null,contextualVariation:null},lowerTail:lower,constraintViolations:hardFailures.length,memoryBudgetBytes:0,timeCostMs:item.timeCostMs??0,timeCostStatus:finite(item.timeCostMs)?'MEASURED':'UNMEASURED',memoryBudgetStatus:'UNMEASURED'}),profile:{stage,profileId:base.profileId,allIntentionalHolds,requiredMetrics:V.requiredMetrics(stage,{allIntentionalHolds}),protectionThresholds:{rasterRank:-Infinity}}};
};
// Do not spend native-raster work on a proxy that already cannot be promoted.
// Encoded proxy and final MP4 QA remain mandatory; this removes only irrelevant extra work.
V.proxyEligibility=(item,p,range=null,inputHash='unbound')=>{const evidence=V.searchEvaluation(item,p,'C',inputHash,range);return J.rankCinemaCandidateV2(evidence.evaluation,{...evidence.profile,requiredMetrics:evidence.profile.requiredMetrics.filter(id=>!['outputReadability','frameAlignedOutputReadability'].includes(id))});};
// An ineligible incumbent can still supply readable-interval protection for another candidate.
V.needsOutputReadability=(items,item)=>items.some(s=>s.proxyEligibility?.eligible)&&(item.id==='baseline'||item.proxyEligibility?.eligible===true);
V.searchInputHash=async(p,range,audio)=>J.sha256(J.canonicalJSON({audioHash:await V.audioHash(audio),lyrics:p.lines,image:p.customBg,assets:p.visualAssets,locks:p.directionOverrides7,directives:p.directorLyricDirectives7,profile:V.outputProfile(p,range),rendererVersion:V.version}));
V.selectSearch=(items,p,stage,range=null,inputHash='unbound')=>{const values=items.map(item=>({...V.searchEvaluation(item,p,stage,inputHash,range),item})),baseline=values.find(v=>v.item.id==='baseline'),profile=values[0]?.profile;if(!profile)return {item:null,status:'NO_CANDIDATES',ranked:[]};
 // Applicability is determined once for the output and shared by every candidate.
 profile.allIntentionalHolds=values.every(v=>v.profile.allIntentionalHolds);profile.requiredMetrics=V.requiredMetrics(stage,profile);
 const selection=V.select(values.map(v=>v.evaluation),profile,baseline?.evaluation);
 // A proxy tie is not evidence that a changed composition improves the output.
 // Preserve the incumbent when its complete measured rank equals the winner.
 const incumbent=baseline&&selection.ranked.find(v=>v.candidate===baseline.evaluation),winner=selection.ranked.find(v=>v.candidate===selection.selected);
 if(stage==='C'&&incumbent?.eligible&&winner&&V.compareRanks(incumbent.rankVector,winner.rankVector)===0){selection.selected=baseline.evaluation;selection.reason='BASELINE_EQUAL_MEASURED_EVIDENCE';}
 return {...selection,item:values.find(v=>v.evaluation===selection.selected)?.item??null};
};
})();

/* Verified repair orchestration around the existing encoder, observer and repair operators. */
(()=>{
'use strict';const J=window.J,V=J.cinemaV3;
const edges={CREATED:['PROXY_MEASURED'],PROXY_MEASURED:['SELECTED'],SELECTED:['FULL_ENCODED'],FULL_ENCODED:['DECODED_QA'],DECODED_QA:['ACCEPTED','REPAIRABLE','UNREPAIRABLE','BUDGET_EXHAUSTED'],REPAIRABLE:['CREATED','BUDGET_EXHAUSTED','UNREPAIRABLE'],ACCEPTED:[],UNREPAIRABLE:[],BUDGET_EXHAUSTED:[]};
V.createState=(inputHash,planHash)=>({state:'CREATED',inputHash,planHash,confirmedPlanHash:null,videoHash:null,history:[{state:'CREATED',planHash}],outcome:null});
V.transition=(state,next,data={})=>{if(!edges[state.state]?.includes(next))throw new Error('INVALID_TRANSITION:'+state.state+'→'+next);Object.assign(state,data,{state:next});state.history.push({state:next,planHash:state.planHash,videoHash:state.videoHash,outcome:state.outcome});return state;};
V.interruptState=(state,reason)=>{if(['ACCEPTED','UNREPAIRABLE','BUDGET_EXHAUSTED'].includes(state.state))return state;state.state='UNREPAIRABLE';state.outcome=reason;state.history.push({state:'UNREPAIRABLE',outcome:reason,planHash:state.confirmedPlanHash});return state;};
V.createResourceScope=()=>{const owned=[],closed={value:false};return {own(resource,dispose){if(closed.value)throw new Error('RESOURCE_SCOPE_CLOSED');owned.push(()=>dispose?dispose(resource):resource?.close?.());return resource;},async dispose(){if(closed.value)return;closed.value=true;const failures=[];for(const close of owned.splice(0).reverse())try{await close();}catch(error){failures.push(String(error));}return failures;}};};
V.restorePlan=(p,snapshot,provenanceHash)=>{for(const key of Object.keys(p))delete p[key];Object.assign(p,V.clone(snapshot));delete p._provenancePlanHash;if(provenanceHash!==undefined)Object.defineProperty(p,'_provenancePlanHash',{value:provenanceHash,configurable:true});J.clearPhotoComposition?.(p);};
V.lockSignature=p=>J.canonicalJSON((p.cuts||[]).filter(c=>c.line>=0&&(c.locked||J.photoChoreographyLocked?.(p,c))).map(c=>({line:c.line,start:c.start,end:c.end,lineText:c.lineText,layout:c.layout,params:c.params,enter:c.enter,exit:c.exit,hold:c.hold,cam:c.cam,decor:c.decor,grammar:c.grammar,assetScene:c.assetScene,semanticIntent:c.semanticIntent})));
V.budgetPolicy=(settings={},memoryGB=typeof navigator!=='undefined'?navigator.deviceMemory:null)=>{const low=Number.isFinite(memoryGB)&&memoryGB<=2;return {stageB:low?4:8,stageC:low?2:3,maxFullEncodes:low?2:5,budgetMs:low?120000:300000,memoryHintGB:memoryGB??null,memoryHintSource:memoryGB==null?'UNMEASURED':'browser coarse deviceMemory estimate',configuredMemoryBudgetBytes:low?134217728:268435456,hardProcessMemoryLimitEnforced:false};};
V.beginRepair=async args=>{const [width,height]=J.outputSize(args.project);if(args.plan.cinemaDelivery?.width!==width||args.plan.cinemaDelivery?.height!==height){V.bindDelivery(args.plan,args.project);V.invalidate(args.plan);await J.analyzeRenderedFrames(args.plan,args.range,args.audio,{signal:args.signal});}if(args.project.exportSettings?.fpsMode==='auto'){const fps=J.chooseAdaptiveFPS(args.project).fps;if(args.plan.fps!==fps){args.plan.fps=fps;delete args.plan.musicalPhoto?.cinema?.architectureSearch;V.adaptGrammar?.(args.plan);V.invalidate(args.plan);await J.analyzeRenderedFrames(args.plan,args.range,args.audio,{signal:args.signal});}}const budgetPolicy=V.budgetPolicy(args.project.exportSettings);return {budgetPolicy,input:await V.snapshot(args.project,args.audio,args.plan,args.range),original:V.clone(args.plan),originalProvenanceHash:args.plan._provenancePlanHash,locks:V.lockSignature(args.plan),started:performance.now(),budgetMs:args.cinemaBudgetMs??Math.min(budgetPolicy.budgetMs,Math.max(120000,Math.min(300000,args.plan.duration*15000))),state:null,evaluations:[],resourceScope:V.createResourceScope()};};
V.finalEvaluation=async(result,p,args,session)=>{
 await V.assertSnapshot(session.input,args.project,args.audio,p,args.range);if(V.lockSignature(p)!==session.locks)throw Error('LOCK_CHANGED');
 const planHash=await V.planHash(p),videoHash=await J.sha256(await result.blob.arrayBuffer()),d=p.lastPixelQA?.metrics?.decodedCinema,r=p.lastPixelQA?.metrics?.cinemaFeedback,profile=V.outputProfile(p,args.range),base={outputProfile:profile,profileId:V.profileId(profile),planHash,inputHash:session.input.inputHash,source:'ENCODED_MP4',method:'final-resolution MP4 independent decode',sampleCount:d?.sceneQuality?.length||0},hardFailures=[];
 if(result.provenance?.videoSHA256&&result.provenance.videoSHA256!==videoHash)hardFailures.push('VIDEO_HASH_MISMATCH');
 if(result.validation?.certification?.passed===false)hardFailures.push('VIDEO_STRUCTURE');
 if(d?.protectedIntervalReadability?.videoHash&&d.protectedIntervalReadability.videoHash!==videoHash)hardFailures.push('PROTECTED_QA_VIDEO_HASH_MISMATCH');
 if(d?.loop?.lastFrameIncluded===false)hardFailures.push('MISSING_FINAL_FRAME');if(d?.endingClosure?.sourceAudioEndAligned===false)hardFailures.push('AUDIO_END_MISMATCH');
 if(r?.samples?.some(s=>!s.safe))hardFailures.push('LYRIC_OR_SAFE_AREA');
 if(d?.layerPresence?.primaryText?.samples?.some(s=>s.visibleSamples<s.samples.length))hardFailures.push('ENCODED_LYRIC_MISSING');
 const measurements=[V.metric('rasterSafety',r?.samples?.length?(r.samples.every(s=>s.safe)?100:0):null,{...base,source:'CANVAS',method:'128px production glyph presence and safe area',sampleCount:r?.samples?.length||0}),V.metric('localContrast',d?.metrics?.localContrast??null,{...base,sampleCount:d?.readability?.sampleCount||0}),V.metric('lowerTail',d?.lowerTailQuality??null,base),V.metric('videoStructure',result.validation?.certification?.passed===true?100:null,{...base,method:'MP4 track structure and frame count certification',sampleCount:result.validation?.certification?.passed?1:0,status:result.validation?.certification?.passed===false?'FAILED':undefined})];
 for(const sample of d?.alignedReadability?.samples||[])measurements.push(V.metric('decodedFrameAlignedContrast@'+sample.line+':'+sample.time,sample.visible?sample.contrast?.score??null:null,{...base,sampleCount:sample.visible&&Number.isFinite(sample.contrast?.score)?1:0,affectedLineIds:[sample.line],method:'final MP4 production glyph/background at actual decoder timestamp / all lyric cuts'}));
 for(const sample of d?.protectedIntervalReadability?.backgroundConsistentReadability?.samples||[])measurements.push(V.metric('decodedPhysicalContrast@'+sample.line+':'+sample.time,sample.visible?sample.contrast?.score??null:null,{...base,sampleCount:sample.visible&&Number.isFinite(sample.contrast?.score)?1:0,affectedLineIds:[sample.line],method:'final MP4 actual decoder clock / primary-associated background retained / original plus protected timestamps'}));
 for(const phrase of d?.layerPresence?.primaryText?.samples||[])for(const sample of phrase.samples||[])measurements.push(V.metric('decodedLocalContrast@'+phrase.line+':'+sample.time,sample.visible?sample.contrast?.score??null:null,{...base,sampleCount:sample.visible&&Number.isFinite(sample.contrast?.score)?1:0,affectedLineIds:[phrase.line],method:'final MP4 existing-cadence primary mask / phrase-time contrast'}));
 if(args.audio?.buffer)measurements.push(V.metric('audioEndpoint',d?.endingClosure?.sourceAudioEndAligned===true?100:d?.endingClosure?.sourceAudioEndAligned===false?0:null,{...base,method:'decoded AAC duration versus authoritative output range',sampleCount:Number.isFinite(d?.endingClosure?.encodedAudioDuration)?1:0}));
 for(const [id,value]of Object.entries(d?.metrics||{}))if(!measurements.some(m=>m.id===id)&&(Number.isFinite(value)||value===null))measurements.push(V.metric(id,value,base));
 const evaluation={id:videoHash,planHash,candidateSeed:J.cinemaContentSeed(p),hardFailures,measurements,objectives:{readability:d?.metrics?.localContrast??null,musicFit:d?.metrics?.impactBeatSync??null,visualCoherence:null,contextualVariation:null},lowerTail:d?.lowerTailQuality??null,constraintViolations:hardFailures.length,memoryBudgetBytes:V.budgetPolicy(p.exportSettings).configuredMemoryBudgetBytes,timeCostMs:0,timeCostStatus:'UNMEASURED',memoryBudgetStatus:'CONFIGURED_SOFT_BUDGET'};
 V.validate('CandidateEvaluation',evaluation);return {evaluation,videoHash,profile:{stage:'FINAL',profileId:base.profileId,requiredMetrics:['rasterSafety','localContrast','lowerTail','videoStructure',...args.audio?.buffer?['audioEndpoint']:[],...(profile.loopRequired?['loopQuality']:[])]},decodedCompleted:!!d?.completed};
};
J.acceptOrRevertRepair=({before,after,profile,targets=['lowerTail','localContrast'],sameInputs=true,sameLocks=true})=>{
 if(!sameInputs||!sameLocks)return {accepted:false,reason:!sameInputs?'INPUT_CHANGED':'LOCK_CHANGED'};
 const rank=J.rankCinemaCandidateV2(after,profile,before);if(!rank.eligible)return {accepted:false,reason:rank.reason,details:rank};
 const old=new Map(before.measurements.map(m=>[m.id,m]));const improved=after.measurements.filter(m=>targets.includes(m.id)&&m.status==='MEASURED'&&old.get(m.id)?.status==='MEASURED'&&V.comparable(m,old.get(m.id))&&m.value>old.get(m.id).value);
 // Readability and every previously verified high-quality metric are protected by the ranker.
 if(!improved.length)return {accepted:false,reason:'NO_MEASURED_TARGET_IMPROVEMENT'};return {accepted:true,reason:'VERIFIED_TARGET_IMPROVEMENT',improved:improved.map(m=>m.id)};
};
J.proposeTargetedRepairs=(p,acceptance)=>{
 if(!p.lastPixelQA?.metrics?.decodedCinema?.completed)return [];
 return (J.classifyCinemaRepairFailures(p,acceptance)||[]).map(task=>({...task,lines:task.lines.filter(line=>{const c=p.cuts.find(c=>c.line===line);return c&&!c.locked&&!J.photoChoreographyLocked(p,c)&&!(c.grammar?.intentionalHold&&/HOLD|STAGNATION|MOTION|NOVELTY|TYPOGRAPHY_DIVERSITY/.test(task.code));}),stage:(p.musicalPhoto?.cinema?.repairEscalation?.[task.code]?.occurrences||0)===0?'MICRO':(p.musicalPhoto?.cinema?.repairEscalation?.[task.code]?.occurrences||0)===1?'ARCHITECTURE':'GRAMMAR_RESET'})).filter(task=>task.lines.length);
};
V.rebuildAfterRepair=p=>{const f=p.musicalPhoto?.cinema;if(!f)return;const shifted=new Map((f.beatTimingRepair?.records||[]).map(r=>[r.line,p.cuts.find(c=>c.line===r.line)?.grammar?.temporal?.hit]));J.rebuildCinemaBeatIntent?.(p);for(const [line,hit]of shifted)if(Number.isFinite(hit))p.cuts.find(c=>c.line===line).grammar.temporal.hit=hit;if(f.grammar)f.grammar.shots=(p.cuts||[]).filter(c=>c.grammar).map(c=>({line:c.line,from:c.start,to:c.end,...V.clone(c.grammar)}));for(const s of p.storyboard||[]){const c=p.cuts.find(c=>c.start===s.from);if(c?.grammar&&!s.locked)s.shotGrammar=V.clone(c.grammar);}V.invalidate(p);};
V.applyRepair=(p,acceptance,attempt)=>{const tasks=J.proposeTargetedRepairs(p,acceptance),allowed=new Set(tasks.flatMap(t=>t.lines)),before=V.clone(p),hash=p._provenancePlanHash;if(!allowed.size)return {changes:[],reason:'NO_MEASURED_REPAIRABLE_LINES'};const locks=V.lockSignature(p),changes=J.repairPhotoBottlenecks(p,acceptance,attempt,{tasks}),changed=(p.cuts||[]).filter((c,i)=>J.canonicalJSON(c)!==J.canonicalJSON(before.cuts[i])).map(c=>c.line),master=J.canonicalJSON(before.musicalPhoto?.cinema?.visualDNA?.master??null);if(changed.some(line=>!allowed.has(line))||locks!==V.lockSignature(p)||master!==J.canonicalJSON(p.musicalPhoto?.cinema?.visualDNA?.master??null)){V.restorePlan(p,before,hash);return {changes:[],reason:'OUT_OF_SCOPE_OR_LOCKED_REPAIR_REVERTED'};}V.rebuildAfterRepair(p);return {changes,tasks,changedLines:changed,unchangedLines:(p.cuts||[]).map(c=>c.line).filter(line=>!changed.includes(line)),reason:'TARGETED_RENDER_CHANGE'};};
V.observeRepair=async(session,args,result,best)=>{
 const evidence=await V.finalEvaluation(result,args.plan,args,session),state=V.createState(session.input.inputHash,evidence.evaluation.planHash);
 if(args.plan.lastPixelQA?.completed)V.transition(state,'PROXY_MEASURED',{proxyStatus:'MEASURED'});else{V.interruptState(state,'PROXY_UNMEASURED');session.state=state;return {...evidence,accepted:false,reason:'PROXY_UNMEASURED'};}
 V.transition(state,'SELECTED');V.transition(state,'FULL_ENCODED',{videoHash:evidence.videoHash});
 if(!evidence.decodedCompleted){V.interruptState(state,'DECODED_QA_UNMEASURED');session.state=state;return {...evidence,accepted:false,reason:'DECODED_QA_UNMEASURED'};}
 V.transition(state,'DECODED_QA');const decision=best?J.acceptOrRevertRepair({before:best.v3.evaluation,after:evidence.evaluation,profile:evidence.profile}):{accepted:true,reason:'INITIAL_ARTIFACT_RETAINED_AS_DRAFT'};
 const eligible=J.rankCinemaCandidateV2(evidence.evaluation,evidence.profile).eligible;session.state=state;session.evaluations.push({planHash:state.planHash,videoHash:state.videoHash,eligible,decision,stateHistory:state.history});return {...evidence,...decision,eligible};
};
J.generateCinemaCandidates=(p)=>[{id:'baseline',plan:V.clone(p)},...(p.musicalPhoto?.cinema?.architecture?J.cinemaArchitectureCandidates(p).map(candidate=>{const plan=V.clone(p);J.applyCinemaArchitecture(plan,candidate);return {id:String(candidate.id),plan};}):[])];
J.assessCandidatePreview=async(candidate,range,signal)=>{const p=candidate.plan,raster=await J.measureCinemaSequence(p,range),video=await J.measureCinemaVideoProxy(p,range,signal);return {...candidate,raster,video};};
J.exportAndObserveCandidate=args=>J.exportMP4({...args,cinemaV3:true});
V.repair=args=>J.exportAndObserveCandidate(args);
})();

/* Confidence-aware grammar extension. The authoritative lyric/audio ranges never move. */
(()=>{
'use strict';const J=window.J,V=J.cinemaV3,C=J.clamp,mean=a=>a.length?a.reduce((x,y)=>x+y,0)/a.length:null;
V.sectionFeatures=(p,audio)=>{
 const energy=Array.from(audio?.energy||[]),peak=energy.length?energy.reduce((m,v)=>Number.isFinite(v)?Math.max(m,v):m,0):0,rate=audio?.energyRate||energy.length/(audio?.duration||p.duration),tempo=audio?.tempoConfidence??audio?.features?.tempoConfidence,energyConfidence=audio?.features?.statistics?.energy?.confidence;
 const sections=p.musicalStructure?.sections?.length?p.musicalStructure.sections:[{from:0,to:p.duration}];
 return sections.map(s=>{const values=rate?energy.slice(Math.floor(s.from*rate),Math.ceil(s.to*rate)).filter(Number.isFinite):[],beats=(p.beatHierarchy||[]).filter(b=>b.time>=s.from&&b.time<s.to),lyrics=(p.lines||[]).filter(l=>l.start>=s.from&&l.start<s.to),texts=lyrics.map(l=>String(l.text).trim()),duration=s.to-s.from,onsets=Array.from(audio?.onset||[]).slice(Math.floor(s.from*rate),Math.ceil(s.to*rate)),confidence=values.length?(Number.isFinite(energyConfidence)?C(energyConfidence):Math.min(.85,values.length/(values.length+20))):0;
 const result={from:s.from,to:s.to,energy:V.feature(values.length?(peak?mean(values)/peak:0):null,'decodedPCM normalized envelope',confidence),beatSalience:V.feature(beats.length&&Number.isFinite(tempo)&&tempo>0?mean(beats.map(b=>b.beatSalience).filter(Number.isFinite)):null,'existing beat hierarchy; tempo autocorrelation confidence',Number.isFinite(tempo)?C(tempo):0),onsetDensity:V.feature(onsets.length?onsets.filter(x=>x>0).length/Math.max(.001,duration):null,'decodedPCM positive onset bins / seconds',onsets.length?confidence:0),lyricDensity:V.feature(texts.reduce((n,t)=>n+Array.from(t).length,0)/Math.max(.001,duration),'authoritative lyric characters / seconds',1),repetition:V.feature(texts.length?1-new Set(texts).size/texts.length:0,'exact authoritative phrase repetition',1),role:V.feature(Number.isFinite(s.confidence)&&s.confidence>0&&['intro','verse','chorus','bridge','climax','outro'].includes(s.role)?s.role:null,'existing section analysis; uncertain role remains unknown',Number.isFinite(s.confidence)?C(s.confidence):0)};
 result.energy.limitations=['Envelope confidence is sampling coverage / existing analysis confidence, not genre or perceptual certainty'];return V.validate('SectionFeatures',result);
 });
};
V.directionPolicy=(features,index,count)=>{
 const e=features.energy.value,beat=features.beatSalience,density=features.lyricDensity.value,quiet=e!==null&&e<.3&&density<8,confidence=features.energy.confidence,knownBeat=beat.status==='MEASURED'&&beat.confidence>=.35;
 const stageRole=quiet?'sustain':index===0?'introduce':index===count-1?'resolve':features.role.value==='bridge'?'contrast':'develop';
 return V.validate('DirectionPolicy',{mode:e===null||!knownBeat?'lyric_first':quiet?'minimal':e>.7?'energetic':'cinematic',stageRole,motionBudget:C((e??.25)*.65*(knownBeat?1:.5)),attentionBudget:C(1-density/30),typographyBudget:C(1-density/40),desiredChange:quiet?0:C((e??.25)*.5),confidence,quietIntent:quiet});
};
V.phases=(c,fps)=>{const from=c.start,to=c.end,dur=Math.max(0,to-from),frame=1/fps,enter=Math.min(dur*.12,.12),settle=Math.min(dur*.15,Math.max(frame,.05+Array.from(c.lineText||'').length*.002)),release=Math.min(dur*.12,.2),exit=Math.min(dur*.06,frame);return {PREPARE:[Math.max(0,from-Math.min(.15,dur*.1)),from],ENTER:[from,from+enter],SETTLE:[from+enter,Math.min(to-release-exit,from+enter+settle)],HOLD:[Math.min(to-release-exit,from+enter+settle),to-release-exit],RELEASE:[to-release-exit,to-exit],EXIT:[to-exit,to]};};
V.phaseAt=(phases,t)=>Object.keys(phases).find(key=>t>=phases[key][0]&&t<phases[key][1])||(t<phases.ENTER[0]?'PREPARE':'EXIT');
V.typographyPreflight=(p,c)=>{
 const text=J.composeLyricPhrase(String(c.lineText||c.text||'')),font=c.params?.font||'embedded_bold',cv=document.createElement('canvas'),ctx=cv.getContext?.('2d');
 try{if(typeof ctx?.measureText!=='function')return {text,font,size:null,lineCount:text.split('\n').length,widths:null,widthStatus:'UNMEASURED',safeArea:{left:.11,right:.89,top:.08,bottom:.92},minReadableFrames:Math.ceil(Math.min(2,Math.max(.15,Array.from(text).length/20))*p.fps),availableFrames:Math.max(0,Math.floor((c.end-c.start)*p.fps)),constraintFailures:['CANVAS_TEXT_MEASUREMENT_UNAVAILABLE'],fontCoverage:V.feature(null,'Canvas text measurement unavailable',0),rubyPresent:/[《》｜]|<ruby\b/i.test(text),source:'UNMEASURED: no Canvas text measurement capability'};const safeArea={left:.11,right:.89,top:.08,bottom:.92},width=p.W*(safeArea.right-safeArea.left),height=p.H*(safeArea.bottom-safeArea.top),size=J.fitSize(text,font,width,height,{lead:1.12,track:.015});ctx.font=J.fontCSS(font,size);const rows=text.split('\n'),widths=rows.map(row=>ctx.measureText(row).width),chars=Array.from(text.replace(/\s/g,'')).length,minSeconds=Math.min(2,Math.max(.15,chars/20)),minReadableFrames=Math.ceil(minSeconds*p.fps),availableFrames=Math.max(0,Math.floor((c.end-c.start)*p.fps)),fontKnown=!!J.FONTS[font];
 return {text,font,size,lineCount:rows.length,widths,safeArea,minReadableFrames,availableFrames,constraintFailures:[...widths.some(w=>w>width+1)?['TEXT_WIDTH']:[],...availableFrames<minReadableFrames?['READ_DURATION_UNMET']:[],...!fontKnown?['FONT_UNKNOWN']:[]],fontCoverage:V.feature(null,'Font availability is not per-character cmap coverage; final glyph raster required',0),rubyPresent:/[《》｜]|<ruby\b/i.test(text),source:'existing composeLyricPhrase / fitSize / browser text measurement; no input rewrite'};
 }finally{cv.width=cv.height=1;}
};
// Motion adaptation can move a brighter source patch under unchanged lyrics.
// Compare its initial grammar to the internal pre-adaptation grammar before search.
V.initialGrammarAcceptable=(adapted,legacy)=>{if(!Number.isFinite(adapted?.score)||!Number.isFinite(legacy?.score)||adapted.score<legacy.score)return false;const values=new Map((adapted.samples||[]).map(s=>[s.time,s.contrast?.score]));return (legacy.samples||[]).every(s=>!Number.isFinite(s.contrast?.score)||s.contrast.score<90||Number.isFinite(values.get(s.time))&&values.get(s.time)>=s.contrast.score);};
V.protectInitialGrammar=async(p,range,signal)=>{
 const cuts=(p.cuts||[]).filter(c=>c.grammar?.temporal&&c.cinemaV3LegacyGrammar?.temporal&&!c.locked&&!J.photoChoreographyLocked?.(p,c)&&c.grammar.temporal.level<c.cinemaV3LegacyGrammar.temporal.level);
 if(!cuts.length)return null;const adapted=cuts.map(c=>V.clone(c.grammar));let keepLegacy=false;
 try{const after=await J.measureCinemaOutputReadability(p,range,signal);cuts.forEach(c=>c.grammar=V.clone(c.cinemaV3LegacyGrammar));const before=await J.measureCinemaOutputReadability(p,range,signal);keepLegacy=!V.initialGrammarAcceptable(after,before);p.musicalPhoto.cinema.initialGrammarProtection={status:Number.isFinite(before.score)&&Number.isFinite(after.score)?'MEASURED':'UNMEASURED',decision:keepLegacy?'KEEP_INTERNAL_LEGACY_GRAMMAR':'KEEP_MEASURED_ADAPTATION',legacy:before,adapted:after,source:'CANVAS requested delivery raster; final decoded QA remains mandatory'};return p.musicalPhoto.cinema.initialGrammarProtection;
 }finally{if(!keepLegacy)cuts.forEach((c,i)=>c.grammar=adapted[i]);const f=p.musicalPhoto?.cinema;if(f?.grammar)f.grammar.shots=p.cuts.filter(c=>c.grammar).map(c=>({line:c.line,from:c.start,to:c.end,...V.clone(c.grammar)}));for(const s of p.storyboard||[]){const c=p.cuts.find(c=>c.start===s.from);if(c?.grammar&&!s.locked)s.shotGrammar=V.clone(c.grammar);}}
};
V.adaptPlan=(p,audio,project)=>{if(!V.enabled||p.cinemaCandidateMode==='legacy')return p;V.captureLegacyPlan(p);const features=V.sectionFeatures(p,audio);p.cinemaV3Features={sections:features,imageSaliency:V.feature(null,'No verified subject segmentation or calibrated saliency confidence',0),inputMode:!project.customBg?.enabled?'no-image':(p.visualAssets||[]).filter(a=>a.dataUrl).length>1?'multi-image':'single-image',vocalSynchronization:V.feature(null,'No vocal separation or sung onset detector',0)};return V.adaptGrammar(p);};
V.adaptGrammar=p=>{
 if(!V.enabled||!p.cinemaV3Features||p.cinemaCandidateMode==='legacy')return p;const sections=p.cinemaV3Features.sections,policies=sections.map((s,i)=>V.directionPolicy(s,i,sections.length));
 for(const c of p.cuts||[]){if(c.line<0||c.locked||c.cinemaV3LegacyFinalist||J.photoChoreographyLocked?.(p,c))continue;const i=Math.max(0,sections.findIndex(s=>c.start>=s.from&&c.start<s.to)),policy=policies[i],preflight=V.typographyPreflight(p,c),g=c.grammar;
 c.cinemaV3Shot=V.validate('ShotContract',{line:c.line,from:c.start,to:c.end,role:policy.stageRole,grammarId:g?.field||c.layout||'legacy',typographyId:preflight.font,motionId:g?.temporal?.motionPrinciple||c.hold||'still',safeArea:preflight.safeArea,minReadableFrames:preflight.minReadableFrames,maxOcclusionRatio:0,reasonCodes:[policy.mode,...preflight.constraintFailures],featureSources:['authoritative LRC','normalized PCM envelope'],userLocked:false});c.cinemaV3Typography=preflight;
 if(!g)continue;c.cinemaV3LegacyGrammar??=V.clone(g);g.directionPolicy=policy;g.scenePhases=V.phases(c,p.fps);g.intentionalHold=g.intentionalHold===true||g.quiet===true||g.temporal?.motionPrinciple==='weighted-hold'||policy.quietIntent;
 if(g.temporal&&policy.mode==='lyric_first'){g.temporal.level=Math.min(g.temporal.level,Math.max(.15,policy.motionBudget));g.motion=g.temporal.level;}
 }
 const f=p.musicalPhoto?.cinema;if(f?.grammar)f.grammar.shots=p.cuts.filter(c=>c.grammar).map(c=>({line:c.line,from:c.start,to:c.end,...V.clone(c.grammar)}));for(const s of p.storyboard||[]){const c=p.cuts.find(c=>c.start===s.from);if(c?.grammar&&!s.locked)s.shotGrammar=V.clone(c.grammar);}return p;
};
})();

/* Measured, unlocked phrase-local readability trial; not a certification. */
(()=>{'use strict';const J=window.J,V=J.cinemaV3,prior=J.adjustLocalReadability;
V.reuseReadabilityEvidence=async(p,range,inputHash,evidence,options={})=>{
 const identity=evidence?.cacheIdentity;
 if(!inputHash||!identity?.unchanged||identity.textureVersion!==J.proceduralTextureVersion||identity.inputHash!==inputHash||identity.method!==(options.physicalOnly?'CANVAS actual-frame output and background-consistent glyph reference':'CANVAS requested-output raster / historical and actual-time glyph references'))return null;
 if(!!identity.backgroundConsistency!==!!options.backgroundConsistency||J.canonicalJSON(identity.additionalTimes||[])!==J.canonicalJSON([...new Set(options.additionalTimes||[])].sort((a,b)=>a-b)))return null;
 if(identity.profileId!==V.profileId(V.outputProfile(p,range))||identity.planHash!==await V.planHash(p))return null;
 return evidence;
};
J.adjustLocalReadability=(env,it)=>{
 let out=prior(env,it);const repair=env.cut?.params?.cinemaReadabilityRepair;
 if(!V.enabled||!repair||env.cut?.line<0||env.cut?.locked||J.photoChoreographyLocked(env.plan,env.cut)||env.pass!=='main'||out.fill===false||out.ghost===false)return out;
 const label=String(out.text||'').replace(/\s/g,''),phrase=String(env.cut.lineText||'').replace(/\s/g,'');if(!label||!phrase.includes(label))return out;
 const amount=typeof repair==='number'?repair:repair.shadow||0,edge=typeof repair==='number'?repair:0;
 if(repair.scrim&&env.ctx){const box=J.measureLyricItemBounds(env,out);if(box){const ctx=env.ctx,k=env.scale||1,cx=(box.x0+box.x1)/2,cy=(box.y0+box.y1)/2,rx=Math.max(env.W*.06,(box.x1-box.x0)*.9),ry=Math.max(env.H*.04,(box.y1-box.y0)*1.2);ctx.save();ctx.setTransform(k,0,0,k,0,0);ctx.translate(cx,cy);ctx.scale(rx,ry);const gradient=ctx.createRadialGradient(0,0,0,0,0,1);gradient.addColorStop(0,'rgba(0,0,0,'+repair.scrim+')');gradient.addColorStop(.8,'rgba(0,0,0,'+repair.scrim+')');gradient.addColorStop(1,'rgba(0,0,0,0)');ctx.fillStyle=gradient;ctx.fillRect(-1,-1,2,2);ctx.restore();}}
 if(!amount)return out;
 return {...out,...(edge?{stroke:Math.max(out.stroke||0,Math.min(3*env.H/1080,out.size*.01*edge)),strokeUnder:true,strokeColor:'rgba(0,0,0,.88)'}:{}),shadow:{...out.shadow,color:'rgba(0,0,0,.78)',blur:Math.max(out.shadow?.blur||0,out.size*.04*amount),dx:0,dy:1}};
};
V.physicalReadabilityDominates=(next,prior)=>{
 if(!next?.cacheIdentity?.backgroundConsistency||!prior?.cacheIdentity?.backgroundConsistency||!next.cacheIdentity.inputHash||next.cacheIdentity.inputHash!==prior.cacheIdentity.inputHash||next.cacheIdentity.profileId!==prior.cacheIdentity.profileId)return false;
 if(!next.cacheIdentity.unchanged||!prior.cacheIdentity.unchanged||next.cacheIdentity.textureVersion!==J.proceduralTextureVersion||prior.cacheIdentity.textureVersion!==J.proceduralTextureVersion||!['CANVAS requested-output raster / historical and actual-time glyph references','CANVAS actual-frame output and background-consistent glyph reference'].includes(next.cacheIdentity.method)||prior.cacheIdentity.method!==next.cacheIdentity.method||!Number.isFinite(next.fps)||!Array.isArray(next.outputResolution)||!Array.isArray(next.observerResolution))return false;
 for(const key of ['outputResolution','observerResolution','fps'])if(J.canonicalJSON(next[key])!==J.canonicalJSON(prior[key]))return false;
 const points=new Map(next.samples.map(s=>[s.time,s]));let measured=0;
 for(const old of prior.samples){const score=old.backgroundConsistentAlignedContrast?.score;if(!Number.isFinite(score))continue;measured++;const current=points.get(old.time);if(!current||current.line!==old.line||!Number.isFinite(old.actualTime)||!Number.isFinite(current.actualTime)||Math.abs(current.actualTime-old.actualTime)>1e-7||!Number.isFinite(current.backgroundConsistentAlignedContrast?.score)||current.backgroundConsistentAlignedContrast.score<score)return false;}
 return measured>0;
};
V.repairReadabilityPreview=async(p,range,signal,options={})=>{
 const originalRepairs=p.cuts.map(c=>c.params?.cinemaReadabilityRepair),scope=options.scope||{renderer:new J.Renderer(),ready:false};
 try{
  const cached=await V.reuseReadabilityEvidence(p,range,options.inputHash,options.cached,options),measureOptions={scope,physicalOnly:options.physicalOnly,inputHash:options.inputHash,backgroundConsistency:options.backgroundConsistency,additionalTimes:options.additionalTimes},before=cached||await J.measureCinemaOutputReadability(p,range,signal,measureOptions),physical=!!options.backgroundConsistency;
  const value=s=>physical?s.backgroundConsistentAlignedContrast?.score:s.contrast?.score,weakValue=s=>physical?s.backgroundConsistentAlignedContrast?.score:s.alignedContrast?.score,weak=new Set(before.samples.filter(s=>Number.isFinite(weakValue(s))&&weakValue(s)<90).map(s=>s.line)),cuts=p.cuts.filter(c=>weak.has(c.line)&&!c.locked&&!J.photoChoreographyLocked(p,c)),trials=[];
  let current=before,accepted=false;const protectedTimes=new Set(before.samples.filter(s=>Number.isFinite(value(s))).map(s=>s.time)),vector=r=>r.samples.filter(s=>protectedTimes.has(s.time)).map(value).filter(Number.isFinite).sort((a,b)=>a-b);
  for(const cut of cuts){const original=cut.params.cinemaReadabilityRepair;let keep=false,best=current,chosen=original;
   try{for(const amount of [2,{shadow:2},{scrim:.24}]){
    cut.params.cinemaReadabilityRepair=amount;const partial=await J.measureCinemaOutputReadability(p,range,signal,{...measureOptions,lines:[cut.line]}),changed=new Map(partial.samples.map(s=>[s.time,s])),samples=current.samples.map(s=>changed.get(s.time)||s),regular=samples.filter(s=>!s.supplemental),after={...current,samples,cacheIdentity:partial.cacheIdentity,frameAlignedScore:regular.length&&regular.every(s=>Number.isFinite(s.alignedContrast?.score))?Math.min(...regular.map(s=>s.alignedContrast.score)):null,score:regular.length&&regular.every(s=>Number.isFinite(s.contrast?.score))?Math.min(...regular.map(s=>s.contrast.score)):null};
    if(signal?.aborted)throw new DOMException('Aborted','AbortError');
    const map=new Map(after.samples.map(s=>[s.time,s.contrast?.score])),historicalNoLoss=Number.isFinite(after.score)&&after.score>=current.score&&current.samples.every(s=>!Number.isFinite(s.contrast?.score)||Number.isFinite(map.get(s.time))&&map.get(s.time)>=s.contrast.score),aligned=new Map(after.samples.map(s=>[s.time,s.alignedContrast?.score])),alignedProtected=current.samples.every(s=>!Number.isFinite(s.alignedContrast?.score)||Number.isFinite(aligned.get(s.time))&&aligned.get(s.time)>=s.alignedContrast.score),noLoss=physical?V.physicalReadabilityDominates(after,current):historicalNoLoss&&alignedProtected,points=new Map(after.samples.map(s=>[s.time,value(s)])),improved=current.samples.some(s=>Number.isFinite(value(s))&&points.get(s.time)>value(s));
    trials.push({line:cut.line,amount,after,noLoss,historicalNoLoss,alignedProtected,improved,selectionEvidence:physical?'SAME_ACTUAL_FRAME_BACKGROUND_CONSISTENT_NATIVE_PIXELS':'HISTORICAL_AND_ALIGNED_NATIVE_REFERENCES',historicalProxyValuesRetained:true});
    if(noLoss&&improved&&V.compareRanks(vector(after),vector(best))<0){keep=true;best=after;chosen=amount;}
   }if(keep){cut.params.cinemaReadabilityRepair=chosen;accepted=true;current=best;}}
   finally{if(!keep){if(original===undefined)delete cut.params.cinemaReadabilityRepair;else cut.params.cinemaReadabilityRepair=original;}}
  }
  if(signal?.aborted)throw new DOMException('Aborted','AbortError');
  return {before,after:current,accepted,trials,beforeSource:cached?'REUSED_IDENTICAL_PLAN_INPUT_PROFILE_NATIVE_EVIDENCE':'FRESH_NATIVE_MEASUREMENT'};
 }catch(error){p.cuts.forEach((c,i)=>{if(originalRepairs[i]===undefined)delete c.params.cinemaReadabilityRepair;else c.params.cinemaReadabilityRepair=originalRepairs[i];});throw error;}
 finally{if(!options.scope){scope.renderer.customBgBitmap?.close?.();scope.renderer.disposeAssets?.();}}
};
})();

/* Reuse generated geometry; empty HOLDs retain null and the legacy raster tie break. */
(()=>{'use strict';const J=window.J,V=J.cinemaV3;
V.captureLegacyGrammar=p=>{if(!V.enabled||p.cinemaCandidateMode==='legacy')return;for(const c of p.cuts||[])if(c.grammar&&!J.photoChoreographyLocked(p,c)){const g=V.clone(c.grammar);delete g.scenePhases;delete g.directionPolicy;delete g.intentionalHold;c.cinemaV3LegacyCandidateGrammar=g;}};
V.readabilityDominates=(next,prior)=>{for(const key of ['outputResolution','observerResolution','fps'])if((next?.[key]!==undefined||prior?.[key]!==undefined)&&J.canonicalJSON(next?.[key]??null)!==J.canonicalJSON(prior?.[key]??null))return false;if(!Number.isFinite(next?.score)||!Number.isFinite(prior?.score)||next.score<prior.score)return false;const map=new Map(next.samples.map(s=>[s.time,s.contrast?.score]));const aligned=new Map(next.samples.map(s=>[s.time,s.alignedContrast?.score]));const clocks=new Map(next.samples.map(s=>[s.time,s.actualTime]));return prior.samples.every(s=>(!Number.isFinite(s.actualTime)||Number.isFinite(clocks.get(s.time))&&Math.abs(clocks.get(s.time)-s.actualTime)<1e-7)&&(!Number.isFinite(s.contrast?.score)||Number.isFinite(map.get(s.time))&&map.get(s.time)>=s.contrast.score)&&(!Number.isFinite(s.alignedContrast?.score)||Number.isFinite(aligned.get(s.time))&&aligned.get(s.time)>=s.alignedContrast.score));};
V.compareLegacyFinalist=async(p,range,signal,shared,incumbent,options={})=>{
 if(!Number.isFinite(incumbent?.score))return {status:'UNMEASURED',reason:'INCUMBENT_DELIVERY_READABILITY_UNMEASURED'};

 const rasterScope=options.scope||{renderer:new J.Renderer(),ready:false};try{
 const seen=[],pool=[],attempts=[],legacyBase=V.legacyPlanningStates.get(p),distance=(a,b)=>a.length===b.length?a.reduce((n,v,i)=>n+Math.abs(v-b[i]),0)/a.length:1;
 if(!legacyBase)return {status:'UNMEASURED',reason:'NO_PRE_ADAPTATION_LEGACY_PLANNING_SOURCE'};
 const working=V.clone(legacyBase);working.cinemaCandidateMode='legacy';working.cinemaDelivery=V.clone(p.cinemaDelivery);working.exportSettings=V.clone(p.exportSettings);
 for(const c of working.cuts){const live=p.cuts.find(x=>x.line===c.line&&x.start===c.start&&x.end===c.end);if(live&&J.photoChoreographyLocked(p,live)){for(const key of Object.keys(c))delete c[key];Object.assign(c,V.clone(live));}}
 const save=()=>({cuts:V.clone(working.cuts),cinema:V.clone(working.musicalPhoto.cinema),storyboard:V.clone(working.storyboard)}),restore=state=>{working.cuts.forEach((c,i)=>{for(const key of Object.keys(c))delete c[key];Object.assign(c,V.clone(state.cuts[i]));});const f=working.musicalPhoto.cinema;for(const key of Object.keys(f))delete f[key];Object.assign(f,V.clone(state.cinema));working.storyboard=V.clone(state.storyboard);},baseline=save();
 for(const item of shared){
  if(signal?.aborted)throw new DOMException('Aborted','AbortError');restore(baseline);if(item.candidate)J.applyCinemaArchitecture(working,item.candidate);J.rebuildCinemaBeatIntent(working);
  const activeCuts=working.cuts.filter(c=>c.grammar&&!J.photoChoreographyLocked(working,c)&&c.start<(range?.end??p.duration)&&c.end>(range?.start??0)),indices=[0,Math.floor(activeCuts.length/2),activeCuts.length-1],raster=await J.measureCinemaSequence(working,range,{scope:rasterScope,...(item.id==='baseline'?{}:{lines:[...new Set(indices.map(i=>activeCuts[i]?.line).filter(Number.isFinite))]})}),sig=raster.samples.flatMap(s=>[...s.signature,...s.primarySignature]),duplicate=item.id!=='baseline'&&seen.some(v=>distance(v,sig)<.012);if(item.id!=='baseline')seen.push(sig);const safe=raster.samples.every(s=>s.safe);attempts.push({id:item.id,rank:raster.rank,duplicate,safe,safetySamples:raster.samples.map(s=>({line:s.line,safe:s.safe,readabilityFailures:s.readabilityFailures}))});
  if(item.id==='baseline'||!duplicate&&safe){pool.push({id:item.id,state:save(),raster});pool.sort((a,b)=>b.raster.rank-a.raster.rank);const top=[pool.find(x=>x.id==='baseline'),...pool.filter(x=>x.id!=='baseline').slice(0,7)].filter(Boolean);pool.length=0;pool.push(...top);}await new Promise(resolve=>setTimeout(resolve,0));
 }
 if(!pool.length)return {status:'UNMEASURED',reason:'NO_LEGACY_RASTER',attempts};
 const stages=await J.selectCinemaProxyStages(working,range,{signal},pool,restore,V.budgetPolicy(working.exportSettings),false,{scope:rasterScope});restore(stages.chosen.state);
 const selected={id:stages.chosen.id,plan:working,raster:stages.chosen.raster},legacyStages={selectedCandidate:selected.id,stageA:attempts.length-1,stageB:stages.stageB.map(x=>({candidate:x.id,score:x.score,safe:x.raster.samples.every(s=>s.safe)})),stageC:stages.stageC.map(x=>({candidate:x.id,completed:x.encoded.completed,score:x.encoded.score??null})),source:'shared generated specifications; same existing local B/C selection and fallback, no V3 evidence privileges'};
 if(selected.raster.samples.some(s=>!s.safe))return {status:'UNMEASURED',reason:'LEGACY_FINALIST_UNSAFE',attempts,legacyStages};const selectedProxyPlanHash=await V.planHash(selected.plan);
 const inputHash=incumbent.cacheIdentity?.inputHash,additionalTimes=[...new Set([...incumbent.samples.map(s=>s.time),...stages.stageC.flatMap(item=>(item.state.cuts||[]).flatMap(c=>[c.start+.04,c.start+c.dur*.25,c.start+c.dur*.5,c.start+c.dur*.75,c.end-.2,c.grammar?.temporal?.hit])).filter(Number.isFinite)])],measurementOptions={scope:rasterScope,inputHash,backgroundConsistency:true,physicalOnly:true,additionalTimes};
 // Keep requested-time proxy values for audit. Decisions use background and
 // glyph references at the very same actual frame clock, input and profile.
 incumbent=await J.measureCinemaOutputReadability(p,range,signal,measurementOptions);
 const rawLegacy=await J.measureCinemaOutputReadability(selected.plan,range,signal,measurementOptions),legacyTrial=await V.repairReadabilityPreview(selected.plan,range,signal,{...measurementOptions,cached:rawLegacy}),legacyReadability=legacyTrial.after,repairedSelected=V.clone(selected.plan),finalistComparisons=[],components=[{id:'INCUMBENT',plan:V.clone(p),readability:incumbent},{id:'LEGACY_FINALIST',plan:repairedSelected,readability:legacyReadability}];
 for(const finalist of stages.stageC){
  if(finalist.id===selected.id||!finalist.encoded?.completed||finalist.raster.samples.some(s=>!s.safe))continue;
  if(signal?.aborted)throw new DOMException('Aborted','AbortError');restore(finalist.state);const alternativePlan=V.clone(working),trial=await V.repairReadabilityPreview(alternativePlan,range,signal,measurementOptions);components.push({id:finalist.id,plan:alternativePlan,readability:trial.after});finalistComparisons.push({candidate:finalist.id,planHash:await V.planHash(alternativePlan),readability:trial.after,creativeLowerTail:finalist.encoded.lowerTailQuality??null,source:'already encoded Stage C finalist; actual-time native pixels are not final MP4 certification'});
 }
 const perLine=(measurement,line)=>({...measurement,samples:measurement.samples.filter(s=>s.line===line)}),value=s=>s.backgroundConsistentAlignedContrast?.score,improves=(next,prior)=>{const map=new Map(prior.samples.map(s=>[s.time,value(s)]));return next.samples.some(s=>Number.isFinite(value(s))&&Number.isFinite(map.get(s.time))&&value(s)>map.get(s.time));},protectedTimes=new Set([...legacyReadability.samples,...incumbent.samples].filter(s=>Number.isFinite(value(s))).map(s=>s.time)),vector=e=>e.samples.filter(s=>protectedTimes.has(s.time)).map(value).filter(Number.isFinite).sort((a,b)=>a-b),proposals=[];
 for(const root of [components[1],components[0]]){
  const plan=V.clone(root.plan),lines=[];
  for(const target of plan.cuts){if(J.photoChoreographyLocked(plan,target))continue;let current=perLine(root.readability,target.line);
   for(const component of components){const source=component.plan.cuts.find(c=>c.line===target.line&&c.start===target.start&&c.end===target.end);if(!source)continue;const next=perLine(component.readability,target.line);if(!V.physicalReadabilityDominates(next,current)||!improves(next,current))continue;for(const key of Object.keys(target))delete target[key];Object.assign(target,V.clone(source));if(component.plan.cinemaCandidateMode==='legacy'&&plan.cinemaCandidateMode!=='legacy')target.cinemaV3Legacy=true;target.cinemaV3LegacyFinalist=true;current=next;lines.push({line:target.line,component:component.id});}
  }
  J.rebuildCinemaBeatIntent(plan);const raw=await J.measureCinemaOutputReadability(plan,range,signal,measurementOptions),repair=V.physicalReadabilityDominates(raw,legacyReadability)&&V.physicalReadabilityDominates(raw,incumbent)?null:await V.repairReadabilityPreview(plan,range,signal,{...measurementOptions,cached:raw}),readability=repair?.after||raw,legacyProtected=V.physicalReadabilityDominates(readability,legacyReadability),incumbentProtected=V.physicalReadabilityDominates(readability,incumbent);
  proposals.push({root:root.id,plan,lines,readability,repair,legacyProtected,incumbentProtected});
 }
 const viable=proposals.filter(x=>x.legacyProtected&&x.incumbentProtected).sort((a,b)=>V.compareRanks(vector(a.readability),vector(b.readability))||String(a.root).localeCompare(String(b.root))),proposal=viable[0],plan=proposal?.plan||p,readability=proposal?.readability||incumbent,lines=proposal?.lines||[],raster=proposal?await J.measureCinemaSequence(plan,range,{scope:rasterScope}):null,encoded=proposal?(!legacyTrial.accepted&&!lines.length&&stages.chosen.encoded&&selectedProxyPlanHash===await V.planHash(plan)?stages.chosen.encoded:await J.measureCinemaEncodedProxy(plan,range,signal,{scope:rasterScope})):null,safe=!!encoded?.completed&&raster.samples.every(s=>s.safe)&&!(encoded.layerPresence?.primaryText?.samples||[]).some(s=>s.visibleSamples<s.samples.length),accepted=!!proposal&&safe;
 const evidence={status:inputHash?'LEGACY_DRAFT_FINALIST_COMPARED':'UNMEASURED',candidate:selected.id,selectedComposition:proposal?'physical-phrase-protected-hybrid':'incumbent-retained',compositionRoot:proposal?.root??null,v3Lines:lines.map(x=>x.line),components:lines,compositionRejected:!proposal,planHash:await V.planHash(plan),profile:V.outputProfile(plan,range),attempts,legacyStages,supplementalFinalistsNeeded:true,finalistComparisons,legacyTrial,legacyReadability,readability,encoded,accepted,physicalLowerTailProtected:proposal?.incumbentProtected??false,incumbentIntervalsProtected:proposal?.incumbentProtected??false,legacyIntervalsProtected:proposal?.legacyProtected??false,proposals:proposals.map(x=>({root:x.root,components:x.lines,readability:x.readability,repair:x.repair,legacyProtected:x.legacyProtected,incumbentProtected:x.incumbentProtected})),reason:!inputHash?'NATIVE_COMPARISON_INPUT_HASH_UNMEASURED':accepted?'ACTUAL_FRAME_PHRASE_BASELINES_PROTECTED_FINAL_QA_REQUIRED':!proposal?'NO_COMPOSITION_PROTECTS_BOTH_ACTUAL_FRAME_BASELINES':'LEGACY_ENCODED_LYRIC_OR_DECODE_FAILURE',lowerTailMissingReason:'Contrast never substitutes for missing creative lower-tail evidence',selectionEvidence:'SAME_ACTUAL_FRAME_BACKGROUND_CONSISTENT_NATIVE_PIXELS',historicalProxyValuesRetained:true,candidateGenerationReused:true,additional32CandidateGeneration:false,finalMP4Certified:false};
 if(signal?.aborted)throw new DOMException('Aborted','AbortError');
 p.cinemaProtectedIntervalTimes=[...new Set([...incumbent.samples,...legacyReadability.samples].map(s=>s.time))].sort((a,b)=>a-b);
 if(accepted){for(const c of plan.cuts){const target=p.cuts.find(x=>x.line===c.line&&x.start===c.start&&x.end===c.end);if(target&&!J.photoChoreographyLocked(p,target)){for(const k of Object.keys(target))delete target[k];Object.assign(target,V.clone(c));}}p.cinemaCandidateMode=plan.cinemaCandidateMode;const f=p.musicalPhoto.cinema;for(const key of Object.keys(f))delete f[key];Object.assign(f,V.clone(plan.musicalPhoto.cinema));p.storyboard=V.clone(plan.storyboard);J.rebuildCinemaBeatIntent(p);}

 return evidence;
 }finally{if(!options.scope){rasterScope.renderer.customBgBitmap?.close?.();rasterScope.renderer.disposeAssets?.();}}
};
})();
