/* Compare inexpensive actual lyric renders, then persist one coherent selection. */
(()=>{'use strict';const J=window.J,C=J.clamp,norm=s=>String(s||'').replace(/\s/g,''),yieldUI=()=>new Promise(r=>setTimeout(r,0));
const photo=p=>p?.photoCompositionPolicy&&p.customBg?.enabled;
J.registrySelectionLyricsKey=p=>JSON.stringify((p.lines||[]).map(l=>({text:l.text,start:l.start})));
const backgroundKeys=new Map();J.registrySelectionBackgroundKey=p=>{const src=p.customBg?.dataUrl||'';let hash=backgroundKeys.get(src);if(!hash){let h=2166136261;for(let i=0;i<src.length;i++)h=Math.imul(h^src.charCodeAt(i),16777619)>>>0;hash=src.length+':'+h;backgroundKeys.set(src,hash);if(backgroundKeys.size>2)backgroundKeys.delete(backgroundKeys.keys().next().value);}return hash+':'+JSON.stringify({...p.customBg,dataUrl:undefined});};
const cleanLayouts=new Set(['center','condensed','huge','circle','bubble','edgeFrame','perspective','depthStack','curtain','shadowPlay','origami','sliceStack','halftoneBig','portraitStack','portraitDiag','photoStatement','photoPhrase','photoChant','photoBanner','photoFocus','photoCondensed']);
const families={center:'statement',condensed:'condensed',huge:'hero',circle:'radial',bubble:'plate',edgeFrame:'frame',perspective:'perspective',depthStack:'depth',curtain:'reveal',shadowPlay:'shadow',origami:'fold',sliceStack:'split',halftoneBig:'pattern',portraitStack:'phrase',portraitDiag:'diagonal',photoStatement:'statement',photoPhrase:'phrase',photoChant:'hero',photoBanner:'banner',photoFocus:'frame',photoCondensed:'condensed'};
for(const [id,name,family] of [['photoBanner','歌詞の横帯','banner'],['photoFocus','余白のフレーム','frame'],['photoCondensed','凝縮した見出し','condensed']])J.LAYOUTS[id]={name,special:true,plan:()=>({font:'gothic_bold',readablePhoto:true}),render(env){
 const {W,H,cut}=env,P=cut.params,text=P.displayText||cut.lineText||cut.text,font=P.font||'gothic_bold',rows=text.split('\n').length,sx=family==='condensed'?.82:1,track=family==='condensed'?.04:.018,lead=1.23;
 const cap=family==='condensed'?Math.min(H*(H>W?.115:.18),W*.27):H*(H>W?.087:.14),size=Math.min(cap,J.fitSize(text,font,W*.72/sx,H*.36,{track,lead}));
 const mw=Math.min(W*.78,J.measure({text,font,size,track,lead,sx}).w+size*.48),mh=size*(1+(rows-1)*lead)+size*.45;
 if(env.pass==='main'){const x=(W-mw)/2,y=(H-mh)/2,ctx=env.ctx;ctx.save();if(family==='banner'){ctx.fillStyle='rgba(5,12,24,.48)';ctx.fillRect(x,y,mw,mh);ctx.fillStyle=env.sc.accent;ctx.globalAlpha=.7;ctx.fillRect(x,y,Math.max(2,W*.005),mh);}else if(family==='frame'){ctx.strokeStyle=env.sc.accent;ctx.globalAlpha=.75;ctx.lineWidth=Math.max(1,H*.002);const arm=Math.min(mw*.12,size*.8);ctx.beginPath();for(const [X,Y,dx,dy] of [[x,y,1,1],[x+mw,y,-1,1],[x,y+mh,1,-1],[x+mw,y+mh,-1,-1]]){ctx.moveTo(X+dx*arm,Y);ctx.lineTo(X,Y);ctx.lineTo(X,Y+dy*arm);}ctx.stroke();}ctx.restore();}
 return J.mainDraw(env,{text,font,size,sx,x:W/2,y:H/2,track,lead,color:env.sc.fg});
}};
J.registrySelectionCatalog=()=>Object.fromEntries(['style',...J.GROUP_KEYS].map(g=>{const reg=g==='style'?J.STYLES:J.registry(g),entries=Object.keys(reg).map(id=>({id,status:g==='style'?'STYLE_RENDER_COMPARISON':g==='layout'?(cleanLayouts.has(id)?'LYRIC_RENDER_CANDIDATE':'MANUAL_OR_THEMATIC_ONLY'):g==='enter'||g==='hold'?'MOTION_COMPATIBILITY':g==='fx'?'LYRIC_FREE_ONLY':g==='bg'?'RETAIN_SUPPLIED_BACKGROUND':g==='exit'||g==='trans'?'RETAIN_FULL_LYRIC_UNTIL_CUE':'MANUAL_OR_INTENT_ONLY'}));return [g,entries];}));
const intersects=(e,c)=>e.t<c.end&&e.t+Math.max(.04,e.dur||.2)>c.start;
J.sanitizePhotoEvents=p=>{if(!photo(p))return p;const cuts=p.cuts.filter(c=>c.line>=0&&!J.photoChoreographyLocked(p,c));for(const key of ['events','hypeTimeline'])p[key]=(p[key]||[]).filter(e=>e.manual||e.directorIntent||e.musicalPhotoCue||!cuts.some(c=>intersects(e,c)));p.plannedEventAlignment=J.plannedEventAlignment?.(p);return p;};
// The guard also applies to effects inserted by a repair after planning. The
// original arrays are restored before returning; a render never edits a plan.
const frame=J.Renderer.prototype.frame;J.Renderer.prototype.frame=function(ctx,p,t,opt={}){const c=J.cutAt(p,t);if(!photo(p)||c?.line<0||!c||J.photoChoreographyLocked(p,c))return frame.call(this,ctx,p,t,opt);const events=p.events,hype=p.hypeTimeline;p.events=(events||[]).filter(e=>e.manual||e.directorIntent||e.musicalPhotoCue||!intersects(e,c));p.hypeTimeline=(hype||[]).filter(e=>e.manual||e.directorIntent||e.musicalPhotoCue||!intersects(e,c));try{return frame.call(this,ctx,p,t,{...opt,noHype:opt.noHype||!p.hypeTimeline.length});}finally{p.events=events;p.hypeTimeline=hype;}};
const credit=J.Renderer.prototype.drawTitleCredit;J.Renderer.prototype.drawTitleCredit=function(ctx,p,t,scale){return credit.call(this,ctx,photo(p)?{...p,visualEnergyDensity:{...p.visualEnergyDensity,tier:'STANDARD'}}:p,t,scale);};
const eventMeasure=J.measureEventRealization;J.measureEventRealization=async(p,range,...args)=>{const r=await eventMeasure(p,range,...args);return photo(p)&&!r.samples.length?{...r,score:null,strongEventVisibleRate:null,majorHit100ms:null,impactAlignment:null,measured:false,applicable:false,status:'NOT_APPLICABLE_NO_AUTHORED_EVENTS'}:r;};
const repair=J.repairStrongEvents;if(repair)J.repairStrongEvents=async(p,...args)=>{J.sanitizePhotoEvents(p);return repair(p,...args);};
// A photographic composition deliberately omits the legacy style's ornament.
// Keep the original cue score (e.g. font + accent = 65), without requiring an
// omitted ornament or letting the old fixer replace measured selections.
const reality=J.auditDirectionReality;J.auditDirectionReality=(p,pixel)=>{const r=reality(p,pixel);if(!photo(p)||!p.artDirection?.registrySelection)return r;const checks=r.checks.map(c=>c.intent==='style core cues'?{...c,actual:{...c.actual,decorRequired:false,policy:'retain supplied photographic world'},status:c.actual.font&&(!pixel?.metrics?.styleCues||pixel.metrics.styleCues.font>.0001)?'match':'mismatch'}:c),mismatches=checks.filter(c=>c.status==='mismatch');return {...r,checks,mismatches,ok:!mismatches.length,score:Math.round(100*(1-mismatches.length/Math.max(1,checks.length)))};};
// Registry choices are pixel-measured. A direction finding requests the production
// raster search; the finding stays in QA. Generic metadata regeneration must not
// discard the measured selection before that search can run.
const qualityFix=J.fixMVQuality;J.fixMVQuality=(p,r,a)=>{if(!p.artDirection?.registrySelection)return qualityFix(p,r,a);if(r.issues.some(i=>i.code==='direction_realization'))p.renderFeedbackRequested=true;return qualityFix(p,{...r,issues:r.issues.filter(i=>!['dna_mismatch','direction_realization'].includes(i.code))},a);};
// The selected visual identity must survive the legacy automatic style arc.
// Explicit director arcs remain authoritative.
const buildArc=J.buildStyleArc;J.buildStyleArc=(p,project,audio)=>{const arc=buildArc(p,project,audio),selection=p.artDirection?.registrySelection;if(!selection||project.directorPlan?.styleArc?.length)return arc;return {...arc,base:selection.style,segments:arc.segments.map(s=>({...s,style:selection.style})),candidates:[selection.style],shares:{base:1,accent:0,peak:0},source:'measured-photographic-identity'};};
const makeDirection=J.makeArtDirection;J.makeArtDirection=(p,a,proposal)=>{const d=makeDirection(p,a,proposal);if(proposal.registrySelection){d.registrySelection=JSON.parse(JSON.stringify(proposal.registrySelection));d.typography.display=proposal.registrySelection.font;}return d;};
const makePlan=J.plan;J.plan=(p,a)=>{const plan=makePlan(p,a);if(plan.artDirection&&Object.keys(plan.directionOverrides7||{}).length)J.applyExplicitOverrides7(plan);return J.sanitizePhotoEvents(plan);};
const makeSocial=J.createSocialHookPlan;if(makeSocial)J.createSocialHookPlan=(p,c)=>J.sanitizePhotoEvents(makeSocial(p,c));
const analyze=J.analyzeRenderedFrames;J.analyzeRenderedFrames=async(p,...args)=>{J.sanitizePhotoEvents(p);return analyze(p,...args);};
const fontFor=key=>J.STYLES[key].fonts.display.find(k=>J.FONTS[k])||'gothic_bold';
const candidateCut=(p,c,id,font,enter='photoSettle',hold='still')=>{const original=p.lines[c.line].text,family=families[id]||id,params={...J.LAYOUTS[id].plan?.(J.rng(c.seed),{...c,text:original,lineText:original,n:[...norm(original)].length,W:p.W,H:p.H,dur:c.dur},p.style),font,align:'center',prompt:false,label:false,readablePhoto:true,readableHero:true,directionAngle:0,composition:family};
 if(id.startsWith('photo'))params.displayText=['phrase','banner','frame'].includes(family)?J.composeLyricPhrase(original):p.H>p.W?J.splitLines(original,10):J.splitLines(original,18);
 return {...c,layout:id,text:original,lineText:original,params,enter,hold,inDur:.12,outDur:0,exit:'cut',trans:'cut',transDur:0,decor:p.registrySignatureProbe&&J.styleSignature(p.styleKey).decor?[{id:J.styleSignature(p.styleKey).decor,photoSignature:true,seed:c.seed,n:1,r:.35,low:true,big:false}]:[],treat:null,photoChoreography:true,registrySelected:true,kineticGrouped:false,architecture:family};};
J.selectionPixelEvidence=(rgba,mask,w,h,bounds,W,H)=>{let ink=0,near=0,outside=0,inside=0;for(let i=0;i<w*h;i++){const j=i*4;if(mask[j+3]>24){ink++;if(Math.max(rgba[j],rgba[j+1],rgba[j+2])-Math.min(rgba[j],rgba[j+1],rgba[j+2])<55&&rgba[j]>180)near++;}if(mask[j+3]>150)inside++;}
 const b=bounds.length?{x0:Math.min(...bounds.map(b=>b.x0)),x1:Math.max(...bounds.map(b=>b.x1)),y0:Math.min(...bounds.map(b=>b.y0)),y1:Math.max(...bounds.map(b=>b.y1))}:null;
 const safe=!!b&&b.x0>=W*.105&&b.x1<=W*.895&&b.y0>=H*.075&&b.y1<=H*.925,center=b?Math.max(Math.abs((b.x0+b.x1)/2/W-.5),Math.abs((b.y0+b.y1)/2/H-.5)):1;
 return {ink,opaqueInk:inside,nearWhite:ink?near/ink:0,bounds:b,safe,centerError:center,height:b?(b.y1-b.y0)/H:0};};
// Measure individual ink boxes, not just the enclosing phrase rectangle.
J.selectionGlyphEvidence=(env,it)=>{
 const ctx=env.ctx,lay=J.layoutText(it),boxes=[];let distortion=false,maxHeight=0,minAlpha=1;
 ctx.save();ctx.font=J.fontCSS(it.font,it.size,it.fontWeight);ctx.textAlign='center';ctx.textBaseline='middle';
 for(const g of lay){if(!g.ch.trim())continue;const c=it.charFn?.(g.i,g,lay.N)||{},sx=(it.sx??1)*(c.s??1)*(c.sx??1),sy=(it.sy??1)*(c.s??1)*(c.sy??1),ratio=Math.abs(sx/sy),alpha=(it.alpha??1)*(c.a??1);minAlpha=Math.min(minAlpha,c.hide?0:alpha);if(ratio<.68||ratio>1.5)distortion=true;
 const m=ctx.measureText(c.ch||g.ch),pad=(it.stroke||0)/2,x=(g.x+g.vx)*(it.sx??1)+(c.dx||0),y=(g.y+g.vy)*(it.sy??1)+(c.dy||0),b={x0:x+(-m.actualBoundingBoxLeft-pad)*sx,x1:x+(m.actualBoundingBoxRight+pad)*sx,y0:y+(-m.actualBoundingBoxAscent-pad)*sy,y1:y+(m.actualBoundingBoxDescent+pad)*sy};maxHeight=Math.max(maxHeight,(b.y1-b.y0)/env.H);boxes.push(b);}
 ctx.restore();let collisions=0;for(let i=0;i<boxes.length;i++)for(let j=i+1;j<boxes.length;j++){const a=boxes[i],b=boxes[j],intersection=Math.max(0,Math.min(a.x1,b.x1)-Math.max(a.x0,b.x0))*Math.max(0,Math.min(a.y1,b.y1)-Math.max(a.y0,b.y0)),area=Math.min((a.x1-a.x0)*(a.y1-a.y0),(b.x1-b.x0)*(b.y1-b.y0));if(intersection>area*.12)collisions++;}
 const short=norm(env.cut.lineText).length<=4,cap=env.H>env.W?(short?.25:.145):(short?.29:.195);return {collisions,distortion,maxGlyphHeight:maxHeight,minAlpha,readable:!distortion&&!collisions&&maxHeight<=cap&&minAlpha>=.55};
};
J.compareRegistryCandidates=async(project,audio,image,options={})=>{
 const musicProfile=J.songDirectionProfile(audio);
 const initial={...J.proposeDirection(project,audio,image),overrides:JSON.parse(JSON.stringify(project.overrides||{}))},probeProject={...project,style:initial.style,mood:initial.mood,fx:initial.fx,enabled:initial.enabled,seed:initial.seed,overrides:initial.overrides,autoDirection:true};probeProject.artDirection=J.makeArtDirection(probeProject,audio,initial);const p=J.plan(probeProject,audio);
 if(!photo(p)||p.manualLyricColor)return null;
 const unlocked=p.cuts.filter(c=>c.line>=0&&!J.photoChoreographyLocked(p,c));if(!unlocked.length)return null;
 const representatives=[...new Map([unlocked.slice().sort((a,b)=>norm(b.lineText).length-norm(a.lineText).length)[0],unlocked.find(c=>/[A-Za-z]{2}/.test(c.lineText)),unlocked.slice().sort((a,b)=>norm(a.lineText).length-norm(b.lineText).length)[0]].filter(Boolean).map(c=>[c.line,c])).values()];
 const fonts=Object.keys(J.FONTS);if(options.ensureFonts!==false)await J.ensureFonts(p.lines.map(l=>l.text).join(''),fonts);
 const canvas=document.createElement('canvas'),mask=document.createElement('canvas'),w=256,h=Math.min(512,Math.round(w*p.H/p.W));canvas.width=mask.width=w;canvas.height=mask.height=h;const ctx=canvas.getContext('2d'),mc=mask.getContext('2d'),R=new J.Renderer(),styles=[],fontResults=[],layoutResults=[],motionResults=[],backgroundPlans=new Map();let frames=0,lastEnter='',workDone=0;const workTotal=fonts.length+J.STYLE_ORDER.length+Object.keys(J.LAYOUTS).length+Object.keys(J.ENTER).length+Object.keys(J.HOLD).length+unlocked.length,progress=label=>options.onProgress?.({label,current:++workDone,total:workTotal});
 const sample=(plan,c,dt)=>{const records=[],items=[],draw=J.drawItem,fill=ctx.fillText,directLabels=[];let unstable=false,primary=false,glyphBackdrop=null;const geometry=[];ctx.fillText=function(text,...args){if(!primary&&String(text).trim())directLabels.push(String(text));return fill.call(this,text,...args);};J.drawItem=(env,it)=>{if(env.pass==='main'&&env.ctx===ctx&&it.text){if(!glyphBackdrop)glyphBackdrop=new Uint8ClampedArray(ctx.getImageData(0,0,w,h).data);geometry.push(J.selectionGlyphEvidence(env,it));if(it.pieceFn||it.clip||it.clipY||it.clipFn||it.bands||it.vbands||(it.blur||0)>.5||it.streak?.a>.01||it.echo?.n>0)unstable=true;const glyphs=J.layoutText(it).filter(g=>{const ch=it.charFn?.(g.i,g);if(Math.abs((it.rot||0)+(ch?.rot||0)+(g.r90?90:0))>6)unstable=true;return !ch?.hide&&(it.alpha??1)*(ch?.a??1)>.06;}).map(g=>it.charFn?.(g.i,g)?.ch||g.ch).join('');records.push(glyphs);}const before=primary;primary=env.pass==='main'&&env.ctx===ctx;try{return draw(env,it);}finally{primary=before;}};try{const cp={...plan,cuts:plan.cuts.map(old=>old.line===c.line?c:old),events:[],hypeTimeline:[],titleDisplay:null};const reference=backgroundPlans.get(plan.styleKey);if(reference)J.sharePhotoComposition(reference,cp);else backgroundPlans.set(plan.styleKey,cp);R.frame(ctx,cp,Math.min(c.end-.04,Math.ceil((c.start+dt)*plan.fps)/plan.fps),{scale:w/plan.W,production:true,noHud:true,noPost:true,noGhost:true,noHype:true,noTrans:true,lyricAuditCtx:mc,lyricAuditItems:items});frames++;const rendered=ctx.getImageData(0,0,w,h).data,bytes=mc.getImageData(0,0,w,h).data,ev=J.selectionPixelEvidence(rendered,bytes,w,h,items.map(it=>it.bounds).filter(Boolean),plan.W,plan.H),actual=norm(records.join('')),expected=norm(c.lineText),full=actual===expected,extra=actual!==expected||directLabels.length>0;
 const contrast=glyphBackdrop?{...J.glyphFootprintContrast(glyphBackdrop,rendered,bytes,w,h),control:'COMPOSITE_BEFORE_FIRST_PRIMARY_GLYPH; includes lyric scrim and backplates'}:{measured:false,status:'NO_PRIMARY_GLYPH_CONTROL'},contrastFit=contrast.measured?C(contrast.renderedVsBackgroundContrastP10/4.5):null;
 return {...ev,contrast,contrastFit,full,extra,directLabels,unstable,geometry,eligible:full&&!extra&&!unstable&&contrast.measured&&contrast.renderedVsBackgroundContrastP10>=3&&geometry.length>0&&geometry.every(g=>g.readable)&&ev.ink>8&&ev.safe&&(c.params.photoAnchor||ev.centerError<.025)&&ev.height>.035,mask:new Uint8ClampedArray(bytes)};}finally{J.drawItem=draw;ctx.fillText=fill;}};
 const metrics=({mask,...ev})=>ev;
 try{
  await R.loadCustomBackground(p.customBg.dataUrl);await R.loadAssetDeck?.(p);
  // Each catalogue face gets its own phrase render. Do not call a loaded fallback
  // the requested decorative font. Native Canvas remains explicitly unverified.
  for(const font of fonts){const loading=options.ensureFonts===false?{status:'NATIVE_FONT_NOT_BROWSER_VERIFIED'}:J.fontLoadEvidence?.get(font)||{status:'REQUESTED_FACE_UNAVAILABLE'},fallback=font==='embedded_bold'&&loading.status!=='LOADED',available=options.ensureFonts===false||loading.status==='LOADED'||fallback;
   const evidence=representatives.map(c=>sample(p,candidateCut(p,c,norm(c.lineText).length<=4?'photoChant':'photoStatement',font),.6));
   const eligible=available&&evidence.every(e=>e.eligible),reading=evidence.reduce((sum,e)=>sum+(e.contrastFit??0)*.45+C(e.height/.15)*.35+C(e.opaqueInk/Math.max(1,e.ink))*.2,0)/evidence.length;
   fontResults.push({id:font,kind:J.FONTS[font].kind,loading:{...loading,...(fallback?{effectiveFace:'JIZURA Noto CJK JP',fallback:true}:{})},eligible,rank:eligible?reading:-1,evidence:evidence.map(metrics)});progress('全フォントの字形と背景上の読みやすさを比較しています');await yieldUI();
  }
  for(const key of J.STYLE_ORDER){const style=J.STYLES[key],sp={...p,style,styleKey:key,registrySignatureProbe:true},font=fontResults.filter(f=>f.eligible).sort((a,b)=>{const fit=f=>(style.fonts.display.includes(f.id)?.16:0)+(J.FONTS[fontFor(key)]?.kind===f.kind?.07:0);return (b.rank+fit(b))-(a.rank+fit(a))||a.id.localeCompare(b.id);})[0]?.id||'embedded_bold',evidence=representatives.map(c=>sample(sp,{...candidateCut(sp,c,norm(c.lineText).length<=4?'photoChant':'photoStatement',font),style,styleKey:key},.6));const scored=initial.debug.styleDecision.candidates.find(c=>c.style===key)||J.scoreStyleProfiles(initial.debug.styleDecision.input,[key])[0],parts=scored?.components,fit=parts?parts.image*.28+parts.audio*.30+parts.lyrics*.26+parts.direction*.16:scored?.score??0,valid=evidence.every(e=>e.eligible),reading=evidence.reduce((s,e)=>s+(e.contrastFit??0)*.45+C(e.height/.15)*.35+C(e.opaqueInk/Math.max(1,e.ink))*.2,0)/evidence.length;styles.push({id:key,font,eligible:valid,profileFit:fit,renderFit:reading,rank:valid?fit*.78+reading*.22:-1,evidence:evidence.map(metrics)});progress('全スタイルを実際の歌詞で比較しています');await yieldUI();}
  styles.sort((a,b)=>b.rank-a.rank||a.id.localeCompare(b.id));const winner=styles.find(s=>s.eligible);if(!winner)throw Error('読みやすいスタイル候補を描画できませんでした');
  const font=winner.font,style=J.STYLES[winner.id],sp={...p,style,styleKey:winner.id,registrySignatureProbe:true};
  for(const id of Object.keys(J.LAYOUTS)){if(['title','interlude'].includes(id)){layoutResults.push({id,status:'CREDIT_OR_INSTRUMENTAL_ONLY'});progress('歌詞の全文・大きさ・余白を比較しています');continue;}const probes=[];for(const c of cleanLayouts.has(id)?representatives:[representatives[0]]){try{const cut={...candidateCut(sp,c,id,font),style,styleKey:winner.id},ev=sample(sp,cut,.6);probes.push({line:c.line,...metrics(ev),_mask:ev.mask,params:cut.params});}catch(error){probes.push({line:c.line,eligible:false,reason:error.message});}}layoutResults.push({id,family:families[id],status:!cleanLayouts.has(id)?'MANUAL_OR_THEMATIC_ONLY':probes.some(e=>e.eligible)?'ELIGIBLE_FOR_MEASURED_PHRASES':'REJECTED_RENDER',probes});progress('歌詞の全文・大きさ・余白を比較しています');await yieldUI();}
  const motionCut={...candidateCut(sp,representatives[0],'photoStatement',font),style,styleKey:winner.id,start:0,end:2,dur:2},motionPlan={...sp,cuts:[motionCut],duration:2};
  for(const id of Object.keys(J.ENTER)){try{const probes=[0,.025,.06,.11,.2].map(dt=>sample(motionPlan,{...motionCut,enter:id},dt));motionResults.push({group:'enter',id,eligible:probes.every(ev=>ev.eligible&&ev.height<.35),evidence:probes.map(metrics)});}catch(error){motionResults.push({group:'enter',id,eligible:false,reason:error.message});}progress('文字が消えない導入を比較しています');if(motionResults.length%8===0)await yieldUI();}
  for(const id of Object.keys(J.HOLD)){try{const early=sample(motionPlan,{...motionCut,hold:id},.6),late=sample(motionPlan,{...motionCut,hold:id},1.1),delta=J.comparePresentationMasks(early.mask,late.mask,w,h).rasterDifference,controlEarly=sample(motionPlan,{...motionCut,hold:'still'},.6),controlLate=sample(motionPlan,{...motionCut,hold:'still'},1.1),contribution=(J.comparePresentationMasks(early.mask,controlEarly.mask,w,h).rasterDifference+J.comparePresentationMasks(late.mask,controlLate.mask,w,h).rasterDifference)/2;motionResults.push({group:'hold',id,eligible:early.eligible&&late.eligible&&delta<.35,evidence:[metrics(early),metrics(late)],delta,contribution});}catch(error){motionResults.push({group:'hold',id,eligible:false,reason:error.message});}progress('保持中の読みやすさを比較しています');if(motionResults.length%8===0)await yieldUI();}
  const entries={},history=[],holdHistory=[],seen=new Map(),available=layoutResults.filter(x=>x.status==='ELIGIBLE_FOR_MEASURED_PHRASES');
  for(const c of unlocked){const text=norm(c.lineText),repeatKey=J.vocaliseGroup?.(c.lineText)||text,rep=seen.get(repeatKey)||0,previous=seen.get(repeatKey+'|choice'),nearest=representatives.slice().sort((a,b)=>Math.abs(norm(a.lineText).length-text.length)-Math.abs(norm(b.lineText).length-text.length))[0],short=text.length<=4,role=p.musicalStructure?.sections?.find(s=>c.start>=s.from&&c.start<s.to)?.role;
   const section=p.musicalStructure?.sections?.find(s=>c.start>=s.from&&c.start<s.to),energy=section?.energy??audio?.features?.energy??.5;
   const ranked=available.map(l=>{const evidence=l.probes.find(v=>v.line===nearest.line),choice=candidateCut(sp,c,l.id,font);if(!evidence?.eligible)return null;const roleFit=short?['hero','condensed','banner','frame'].includes(l.family):rep>0?['phrase','frame','banner','condensed','diagonal'].includes(l.family):['statement','condensed','phrase'].includes(l.family);const chantStage=J.vocaliseGroup?.(c.lineText)?rep%4:null,stageFamilies=[['statement','phrase'],['frame','banner'],['radial','split','depth','perspective'],['hero','condensed','diagonal']],stageFit=chantStage===null?0:stageFamilies[chantStage].includes(l.family)?.42:0;const novelty=previous?.family===l.family?-.45:rep>0?.17:0,streak=history.at(-1)===l.family?-.18:0,graphicPenalty=['banner','frame'].includes(l.family)&&history.slice(-2).some(x=>['banner','frame'].includes(x))?-.12:0;
    const ev=sample(sp,{...choice,style,styleKey:winner.id},.6);if(!ev.eligible)return null;return {layout:l.id,family:l.family,params:choice.params,score:.20*(ev.contrastFit??0)+.10*C(ev.opaqueInk/Math.max(1,ev.ink))+.12*C(ev.height/(short?.22:.14))+(roleFit?.18:0)+.4*J.songLayoutFit(l.family,musicProfile,energy,role,rep)+stageFit+novelty+streak+graphicPenalty,evidence:metrics(ev)};
   }).filter(Boolean).sort((a,b)=>b.score-a.score||a.layout.localeCompare(b.layout));
   const choice=ranked[0];if(!choice)throw Error('歌詞を保持できる構成候補がありません');const enters=motionResults.filter(x=>x.group==='enter'&&x.eligible&&!/scramble|glitch|blur|type|fade|spin|scatter|explode|random/i.test(x.id)),preferred=J.STYLES[winner.id].bias?.enter||{},enter=enters.sort((a,b)=>((preferred[b.id]||0)-(b.id===lastEnter?.35:0))-((preferred[a.id]||0)-(a.id===lastEnter?.35:0))||a.id.localeCompare(b.id))[rep%Math.min(3,enters.length)]?.id||'photoSettle';lastEnter=enter;
   const finalEnter=[enter,'photoSettle','cut'].find(id=>[.001,.03,.08,.16].every(dt=>sample(sp,{...candidateCut(sp,c,choice.layout,font,id),style,styleKey:winner.id},dt).eligible))||'cut';
   const holds=motionResults.filter(x=>x.group==='hold'&&x.eligible&&['still','breathe','pulse','float','sway'].includes(x.id)).sort((a,b)=>{const fit=m=>(c.line%4===0||J.vocaliseGroup?.(c.lineText)&&rep===0)?(m.id==='still'?.6:0):musicProfile.mode==='drift'?(m.id==='still'?.3:0):musicProfile.mode==='flow'?(['float','sway','breathe'].includes(m.id)&&m.contribution>.002?.3:0):energy>.4?(['pulse','breathe'].includes(m.id)&&m.contribution>.002&&m.contribution<.2?.3:0):m.id==='still'?.2:0;return fit(b)-fit(a)||a.delta-b.delta||a.id.localeCompare(b.id);});
   const nonRepeated=holds.filter(m=>!(holdHistory.length>=2&&holdHistory.at(-1)===m.id&&holdHistory.at(-2)===m.id));
   const hold=nonRepeated.find(m=>[.2,.6,Math.max(.2,c.dur-.08)].every(dt=>sample(sp,{...candidateCut(sp,c,choice.layout,font,finalEnter,m.id),style,styleKey:winner.id},dt).eligible))?.id||'still';
   holdHistory.push(hold);
   const anchorProbes=(J.photoAnchorCandidates?.(R.customBgBitmap)||[{x:.5,y:.5}]).map(anchor=>{const cut={...candidateCut(sp,c,choice.layout,font,finalEnter,hold),params:{...choice.params,photoAnchor:anchor},style,styleKey:winner.id},ev=sample(sp,cut,.6);return {anchor,evidence:metrics(ev),eligible:ev.eligible,rank:(ev.contrastFit??0)*.5+(1-(anchor.saliency??.5))*.35+(Math.abs(anchor.y-.5)>.1?.08:0)};}).filter(v=>v.eligible).sort((a,b)=>b.rank-a.rank);
   if(anchorProbes.length)choice.params.photoAnchor=anchorProbes[0].anchor;
   entries[c.line]={...choice,anchorComparisons:anchorProbes,enter:finalEnter,hold,inDur:.12,role,energy,musicMode:musicProfile.mode,repeat:rep};history.push(choice.family);seen.set(repeatKey,rep+1);seen.set(repeatKey+'|choice',choice);progress('反復フレーズの構成を選択しています');await yieldUI();
  }
  const selection={version:3,algorithm:'audio-conditioned-readable-render-comparison-v4',audioKey:J.registrySelectionAudioKey(audio),musicProfile,profileWeights:{image:.28,audio:.30,lyrics:.26,direction:.16},style:winner.id,font,backgroundKey:J.registrySelectionBackgroundKey(p),lyricsKey:J.registrySelectionLyricsKey(p),entries,fontComparisons:fontResults,styleComparisons:styles,layoutComparisons:layoutResults.map(l=>({...l,probes:l.probes?.map(({_mask,...v})=>v)})),motionComparisons:motionResults,framesCompared:frames,sampleWidth:w,profileRole:'audio/image/lyric compatibility, then measured readability and phrase continuity',limitations:['Low-resolution render samples are engineering evidence, not artistic or viral certification.','All catalogue fonts are compared; unavailable requested faces are excluded in browsers and the embedded fallback is labelled. Native font results do not establish browser availability.','No inferred word-level singing times. Multi-item layout backing is sampled before the first primary item; final export contrast remains a separate test.'],catalog: J.registrySelectionCatalog()};
  const proposal={...initial,style:winner.id,visualDNA:{...initial.visualDNA,style:winner.id,typographyStyle:font,layoutStrategy:'phraseRenderSelection',decorationStrategy:'none'},motionDNA:{...initial.motionDNA,font,fontCategory:J.FONTS[font].kind},debug:{...initial.debug,styleDecision:{...initial.debug.styleDecision,selected:winner.id,renderCompetition:styles.map(({id,rank,eligible})=>({id,rank,eligible}))}},styleSignature:J.styleSignature(winner.id),registrySelection:selection,summary:`${initial.visualDNA.type} · ${style.name} · 歌詞と反復から実描画選択`};
  const resultProject={...probeProject,style:winner.id};resultProject.artDirection=J.makeArtDirection(resultProject,audio,proposal);const finalPlan=J.plan(resultProject,audio);return {recommended:{variant:0,proposal,project:resultProject,plan:finalPlan,score:winner.rank,audit:J.auditDirectionReality(finalPlan),selection},candidates:[{variant:0,proposal,plan:finalPlan,score:winner.rank,selection}]};
 }finally{R.disposeAssets?.();R.customBgBitmap?.close?.();canvas.width=mask.width=1;canvas.height=mask.height=1;}
};
const optimize=J.optimizeDirectionCandidatesRendered;J.optimizeDirectionCandidatesRendered=async(p,a,image,max=1,telemetry={})=>{if(J.singleBackgroundMode&&p.customBg?.enabled&&!p.directorPlan){const result=await J.compareRegistryCandidates(p,a,image,{onProgress:telemetry.onProgress,ensureFonts:telemetry.ensureFonts});if(result)return result;}return optimize(p,a,image,max,telemetry);};
const context=J.directorContext;J.directorContext=(p,plan,...args)=>({...context(p,plan,...args),registrySelection:plan.artDirection?.registrySelection||null});
const provenance=J.createExportProvenance;J.createExportProvenance=async(...args)=>({...await provenance(...args),registrySelection:args[0]?.plan.artDirection?.registrySelection||null});
})();
