/* Regional 2.5D: connected colour/edge regions, not recognized objects or learned depth. */
(()=>{'use strict';const J=window.J,C=J.clamp,active=p=>!!p.musicalPhoto?.cinema,locked=(p,c)=>!!c&&J.photoChoreographyLocked(p,c),cache=new WeakMap(),ease=u=>{u=C(u);return u*u*(3-2*u);};
const canvas=(w,h)=>{const c=document.createElement('canvas');c.width=w;c.height=h;return c;};
J.segmentCinemaArtwork=image=>{
 if(cache.has(image))return cache.get(image);
 const w=160,h=Math.max(32,Math.min(240,Math.round(w*image.height/image.width))),cv=canvas(w,h),x=cv.getContext('2d');x.drawImage(image,0,0,w,h);const raw=x.getImageData(0,0,w,h),d=raw.data,n=w*h,lum=new Float32Array(n),edge=new Float32Array(n),used=new Uint8Array(n);
 for(let i=0;i<n;i++)lum[i]=d[i*4]*.2126+d[i*4+1]*.7152+d[i*4+2]*.0722;
 const seeds=[];for(let y=2;y<h-2;y++)for(let xx=2;xx<w-2;xx++){const i=y*w+xx;edge[i]=Math.abs(lum[i]-lum[i-1])+Math.abs(lum[i]-lum[i-w]);if(y%8===0&&xx%8===0)seeds.push({i,score:edge[i]+Math.abs(lum[i]-lum[(h>>1)*w+(w>>1)])*.25});}
 seeds.sort((a,b)=>b.score-a.score);const regions=[];
 for(const seed of seeds){if(regions.length===4)break;if(used[seed.i]||seed.score<18)continue;const sx=seed.i%w,sy=Math.floor(seed.i/w),queue=[seed.i],seen=new Set(queue),pixels=[];let strength=0;
  for(let q=0;q<queue.length&&queue.length<n*.3;q++){const i=queue[q],xx=i%w,y=Math.floor(i/w),diff=Math.abs(d[i*4]-d[seed.i*4])+Math.abs(d[i*4+1]-d[seed.i*4+1])+Math.abs(d[i*4+2]-d[seed.i*4+2]);if(used[i]||diff>105||Math.hypot((xx-sx)/w,(y-sy)/h)>.22)continue;pixels.push(i);strength+=edge[i];for(const j of [xx>0?i-1:-1,xx<w-1?i+1:-1,y>0?i-w:-1,y<h-1?i+w:-1])if(j>=0&&!seen.has(j)){seen.add(j);queue.push(j);}}
  if(pixels.length<n*.012||pixels.length>n*.24||strength/pixels.length<1.2)continue;
  for(const i of pixels)used[i]=1;const cx=pixels.reduce((s,i)=>s+i%w,0)/pixels.length/w,cy=pixels.reduce((s,i)=>s+Math.floor(i/w),0)/pixels.length/h;
  regions.push({pixels,cx,cy,coverage:pixels.length/n,edgeDensity:strength/pixels.length,depth:.35+.55*cy,id:regions.length});
 }
 // Fill only selected regions from their actual neighboring pixels. Bounded diffusion,
 // no generative reconstruction; this can be imperfect and is reported as a limitation.
 const filled=new Uint8ClampedArray(d),pending=new Uint8Array(used);let remaining=used.reduce((s,v)=>s+v,0);
 for(let pass=0;pass<80&&remaining;pass++){const updates=[];for(let i=0;i<n;i++)if(pending[i]){const xx=i%w,y=Math.floor(i/w),neighbors=[xx>0?i-1:-1,xx<w-1?i+1:-1,y>0?i-w:-1,y<h-1?i+w:-1].filter(j=>j>=0&&!pending[j]);if(neighbors.length)updates.push([i,...[0,1,2].map(k=>neighbors.reduce((s,j)=>s+filled[j*4+k],0)/neighbors.length)]);}if(!updates.length)break;for(const [i,r,g,b]of updates){filled[i*4]=r;filled[i*4+1]=g;filled[i*4+2]=b;pending[i]=0;remaining--;}}
 const base=canvas(w,h),bx=base.getContext('2d'),bd=bx.createImageData(w,h);bd.data.set(filled);bx.putImageData(bd,0,0);
 // Preserve source resolution outside the fill; only uncertain reconstructed holes are low-res.
 const k=Math.min(1,960/Math.max(image.width,image.height)),W=Math.max(1,Math.round(image.width*k)),H=Math.max(1,Math.round(image.height*k)),fullBase=canvas(W,H),fx=fullBase.getContext('2d');fx.drawImage(image,0,0,W,H);
 const hole=canvas(w,h),hx=hole.getContext('2d'),hd=hx.createImageData(w,h);for(let i=0;i<n;i++)if(used[i]){hd.data[i*4]=filled[i*4];hd.data[i*4+1]=filled[i*4+1];hd.data[i*4+2]=filled[i*4+2];hd.data[i*4+3]=255;}hx.putImageData(hd,0,0);fx.drawImage(hole,0,0,W,H);
 for(const r of regions){const mask=canvas(w,h),mx=mask.getContext('2d'),md=mx.createImageData(w,h);for(const i of r.pixels)md.data[i*4+3]=255;mx.putImageData(md,0,0);const layer=canvas(W,H),lx=layer.getContext('2d');lx.drawImage(image,0,0,W,H);lx.globalCompositeOperation='destination-in';lx.drawImage(mask,0,0,W,H);r.layer=layer;mask.width=mask.height=1;delete r.pixels;}
 const result={base:fullBase,regions,looks:new Map(),evidence:{method:'connected RGB regions ranked by edge and contrast; vertical-position depth heuristic',recognizedObjects:false,learnedDepth:false,regionCount:regions.length,coverage:regions.reduce((s,r)=>s+r.coverage,0),fallback:!regions.length,limitations:'Neighbor diffusion may reveal seams; masks are regional, not semantic object boundaries'}};
 cv.width=cv.height=base.width=base.height=hole.width=hole.height=1;cache.set(image,result);return result;
};
J.cinemaLayerMotion=(p,c,t,r)=>{const stage=c?.cinema?.stage||0,meaning=c?.cinema?.meaning,u=C((t-(c?.start||0))/Math.max(.1,c?.dur||3)),a=(c?.cinema?.quiet?.12:1)*(stage? .35+.22*stage:.65)*r.depth;
 const wave=Math.sin(u*Math.PI*2+r.id*.8),entry=1-ease(u*3);let dx=wave*.012,dy=Math.cos(u*Math.PI*2+r.id)*.006;
 if(meaning==='gather'){dx=(.5-r.cx)*.07*entry;dy=(.5-r.cy)*.04*entry;}
 if(meaning==='rage'){dx=(Math.sin(t*37+r.id)+Math.sin(t*61-r.id))*.009;dy=Math.sin(t*43+r.id)*.008;}
 if(meaning==='call'){dx=0;dy=-.008*ease(u);}
 if(meaning==='unity'){dx=dy=0;}
 return {dx:dx*a,dy:dy*a,scale:meaning==='call'?1+.045*ease(u)*r.depth:1+.008*a*Math.sin(u*Math.PI),stage};};
const grade=(data,look)=>{for(let i=0;i<data.length;i+=4){const l=data[i]*.2126+data[i+1]*.7152+data[i+2]*.0722,v=look==='silhouette'?(l>75?210:8):l;if(look==='color')continue;data[i]=look==='mono'?v:v*.12;data[i+1]=look==='mono'?v:v*.43;data[i+2]=look==='mono'?v:Math.min(255,v*1.35);}return data;};
J.drawLayeredCinema=(R,ctx,p,t,source,rect,look)=>{
 const data=J.segmentCinemaArtwork(source);R.layeredCinemaAssets=data;if(!data.regions.length)return false;
 if(!data.looks.has(look)){data.looks.set(look,[data.base,...data.regions.map(r=>r.layer)].map(image=>{const out=canvas(image.width,image.height),x=out.getContext('2d');x.drawImage(image,0,0);const d=x.getImageData(0,0,out.width,out.height);grade(d.data,look);x.putImageData(d,0,0);return out;}));}
 const images=data.looks.get(look),c=J.cutAt(p,t);ctx.drawImage(images[0],rect.x,rect.y,rect.w,rect.h);
 data.regions.forEach((r,i)=>{const m=R.cinemaNeutralLayers?{dx:0,dy:0,scale:1}:J.cinemaLayerMotion(p,c,t,r),cx=rect.x+rect.w*r.cx,cy=rect.y+rect.h*r.cy;ctx.save();ctx.translate(cx+m.dx*rect.w,cy+m.dy*rect.h);ctx.scale(m.scale,m.scale);ctx.translate(-cx,-cy);ctx.drawImage(images[i+1],rect.x,rect.y,rect.w,rect.h);ctx.restore();});return true;
};
const build=J.buildPhotoStory;J.buildPhotoStory=p=>{build(p);if(!active(p))return p;for(const c of p.cuts)if(c.cinema&&!locked(p,c)){const stage=Math.min(4,c.story?.stage||0);c.cinema={...c.cinema,stage,development:stage?{occupancy:.50+.07*stage,echoLayers:stage-1,speed:.5+.3*stage,contrast:.6+.1*stage}:null,physics:{gather:'convergence',pride:'light-sweep',rage:'irregular-vibration',call:'depth-arrival',unity:'grounded-lock',hero:'forward'}[c.cinema.meaning]||'read'};}p.musicalPhoto.cinema.version=2;p.musicalPhoto.cinema.limits='Connected colour/edge masks and heuristic parallax; no object recognition or learned depth; neighbor-fill seams possible';return p;};
const typo=J.applyTypography5;J.applyTypography5=(env,it)=>{typo(env,it);const c=env.cut;if(!active(env.plan)||locked(env.plan,c)||!it.cinemaMotion)return;const u=C(env.lt/Math.max(.1,c.dur)),m=c.cinema?.meaning;
 it.charFns.push((i,g)=>m==='gather'?{dx:g.x*.05*(1-ease(u*3))}:m==='rage'?{dx:env.W*.003*Math.sin(env.t*41+i*1.7),dy:env.H*.003*Math.sin(env.t*53+i*.9)}:m==='call'?{s:.94+.06*ease(u*2)}:m==='unity'?{dy:env.H*.008}:{});
};
// Chant echoes are decorative, drawn directly and excluded from the authoritative
// lyric mask. The full source phrase remains the single readable primary layer.
J.drawCinemaAccent=(ctx,p,t)=>{const c=J.cutAt(p,t);if(!active(p)||locked(p,c)||c?.photoExit)return;const f=p.musicalPhoto.cinema,u=c?C((t-c.start)/Math.max(.1,c.dur)):0,stage=c?.cinema?.stage||0;
 ctx.save();if(c?.cinema?.meaning==='pride'){const x=(u*1.4-.2)*p.W,g=ctx.createLinearGradient(x-p.W*.12,0,x+p.W*.12,0);g.addColorStop(0,'#1695ff00');g.addColorStop(.5,'#97d7ff');g.addColorStop(1,'#1695ff00');ctx.fillStyle=g;ctx.globalCompositeOperation='screen';ctx.globalAlpha=.12*Math.sin(u*Math.PI);ctx.fillRect(0,0,p.W,p.H);}
 if(stage>1){const s=stage-1;ctx.font=`900 ${p.H*(p.H>p.W?.042:.07)}px "JIZURA Noto CJK JP",sans-serif`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillStyle='#66b8ff';ctx.globalAlpha=.055+.012*s;for(let i=0;i<s;i++){const y=p.H*(i%2?.84:.16)+Math.sin(u*Math.PI*2*(.5+.3*stage)+i)*p.H*.015;ctx.fillText(c.lineText,p.W*.5,y,p.W*.84);}}
 const climax=Number.isFinite(f.climax)&&t>=f.climax;
 if(climax&&stage>=2){ctx.strokeStyle='#39aaff';ctx.lineWidth=p.H*.002*(stage-1);ctx.globalAlpha=.07+.025*stage;const spread=(.08+.06*stage)*p.W;for(let i=0;i<stage-1;i++){ctx.beginPath();ctx.moveTo(p.W*.5-spread-i*p.W*.07,0);ctx.lineTo(p.W*.5-spread*.5-i*p.W*.07,p.H);ctx.moveTo(p.W*.5+spread+i*p.W*.07,0);ctx.lineTo(p.W*.5+spread*.5+i*p.W*.07,p.H);ctx.stroke();}}
 // Short preview of the final palette during the first social hook.
 if(t>=.48&&t<.72&&f.introEnd>.75){ctx.globalCompositeOperation='screen';ctx.globalAlpha=.16*Math.sin((t-.48)/.24*Math.PI);ctx.fillStyle='#137fff';ctx.fillRect(0,0,p.W,p.H);}ctx.restore();
};
J.measureArtworkForeground=async(p,range)=>{const R=new J.Renderer(),w=160,h=Math.max(48,Math.round(w*p.H/p.W)),cv=canvas(w,h),x=cv.getContext('2d'),mc=canvas(w,h),mx=mc.getContext('2d'),start=range?.start??0,end=range?.end??p.duration;
 try{await R.loadCustomBackground(p.customBg.dataUrl);const data=J.segmentCinemaArtwork(R.customBgBitmap),samples=[],layerMasks=[];for(const c of p.cuts.filter(c=>c.cinema&&!locked(p,c)&&c.end>start&&c.start<end)){const t=Math.min(end-1/p.fps,Math.max(start,c.start+c.dur*.35));const render=neutral=>{R.cinemaNeutralLayers=neutral;x.setTransform(w/p.W,0,0,w/p.W,0,0);x.clearRect(0,0,p.W,p.H);R.drawCustomBackground(x,p,t);return x.getImageData(0,0,w,h).data;};const a=render(false),b=render(true);R.cinemaNeutralLayers=false;const canonical=canvas(w,h),kx=canonical.getContext('2d');if(c.grammar&&J.paintCinemaGrammarForeground){kx.save();kx.scale(w/p.W,h/p.H);J.paintCinemaGrammarForeground.call(R,kx,p,c,t,data,data.regions.map(r=>r.layer));kx.restore();}else for(const region of data.regions){const motion=J.cinemaLayerMotion(p,c,t,region);kx.save();kx.translate((region.cx+motion.dx)*w,(region.cy+motion.dy)*h);kx.scale(motion.scale,motion.scale);kx.translate(-region.cx*w,-region.cy*h);kx.drawImage(region.layer,0,0,w,h);kx.restore();}layerMasks.push(kx.getImageData(0,0,w,h).data);canonical.width=canonical.height=1;let diff=0,visible=0;for(let i=0;i<a.length;i+=4){const d=(Math.abs(a[i]-b[i])+Math.abs(a[i+1]-b[i+1])+Math.abs(a[i+2]-b[i+2]))/765;diff+=d;if(d>.02)visible++;}R.cinemaNeutralLayers=false;R.frame(x,p,t,{scale:w/p.W,production:true,lyricAuditCtx:mx,lyricAuditItems:[]});const mask=mx.getImageData(0,0,w,h).data,grid=Array(96).fill(0),counts=Array(96).fill(0);for(let yy=0;yy<h;yy++)for(let xx=0;xx<w;xx++){const cell=Math.min(7,Math.floor(yy/h*8))*12+Math.min(11,Math.floor(xx/w*12));grid[cell]+=mask[(yy*w+xx)*4+3]/255;counts[cell]++;}samples.push({line:c.line,time:t,difference:diff/(w*h),changedArea:visible/(w*h),physics:c.cinema.physics,structure:grid.map((v,i)=>v/Math.max(1,counts[i]))});}
 let maskChange=0;for(let k=1;k<layerMasks.length;k++){let changed=0,union=0;for(let i=3;i<layerMasks[k].length;i+=4){changed+=Math.abs(layerMasks[k][i]-layerMasks[k-1][i])/255;union+=Math.max(layerMasks[k][i],layerMasks[k-1][i])/255;}maskChange+=changed/Math.max(1,union);}const novelty=layerMasks.length>1?Math.round(Math.min(100,maskChange/(layerMasks.length-1)*260)):null;const structuralChanges=samples.slice(1).map((s,i)=>({time:s.time,difference:s.structure.reduce((sum,v,j)=>sum+Math.abs(v-samples[i].structure[j]),0)/96})),gaps=[];let last=start;for(const change of structuralChanges)if(change.difference>.035){if(change.time-last>8)gaps.push({from:last,to:change.time});last=change.time;}if(end-last>8)gaps.push({from:last,to:end});return {nonCropStructure:{method:'12×8 occupancy of actual lyric raster; background crop excluded',threshold:.035,changes:structuralChanges,gapsOverEightSeconds:gaps},status:'PRE_ENCODE_COUNTERFACTUAL',...data.evidence,samples,visibleSamples:samples.filter(s=>s.changedArea>.005).length,score:null,novelty:{score:data.regions.length?novelty:0,method:'mean consecutive alpha-mask displacement / mask union × 260; fixed camera, fixed palette, lyrics excluded',artisticQualityMeasured:false},note:'Actual artwork-layer movement versus identical camera/grade with layers at rest; motion visibility, not audience or semantic understanding'};
 }finally{R.disposeAssets?.();cv.width=cv.height=mc.width=mc.height=1;}};
const analyze=J.analyzeRenderedFrames;J.analyzeRenderedFrames=async(...args)=>{const r=await analyze(...args);if(r.completed&&active(args[0])){r.metrics.artworkForeground=await J.measureArtworkForeground(args[0],args[1]);r.metrics.foregroundChannels={...r.metrics.foregroundChannels,artworkLayers:r.metrics.artworkForeground};args[0].lastPixelQA=r;}return r;};
const check=J.checkMVQuality;J.checkMVQuality=(...args)=>{const r=check(...args),q=r.quality;if(!active(args[1]))return r;const art=args[4]?.metrics?.artworkForeground;q.artworkForegroundEvidence=art||null;if(art?.novelty){q.metrics.lyricForegroundNovelty=q.metrics.foregroundNovelty;q.metrics.foregroundNovelty=art.novelty.score;for(const i of r.issues)if(i.code==='LOW_FOREGROUND_NOVELTY'){i.code='LOW_LYRIC_FOREGROUND_NOVELTY';i.message='歌詞前景の新規性が基準80に達していません';}if(!Number.isFinite(art.novelty.score)||art.novelty.score<80)r.issues.push({code:'LOW_FOREGROUND_NOVELTY',severity:'ERROR',exportBlocking:false,score:art.novelty.score,minimum:80,message:'画像前景の新規性が基準80に達していません（固定カメラの領域マスク比較）'});}const d=q.productionDomains||{},constraints=[['perceptualNovelty',q.metrics?.perceptualNovelty],['foregroundNovelty',q.metrics?.foregroundNovelty],['temporalContrast',q.metrics?.temporalContrast],['semanticDirection',d.semanticDirection]],failures=constraints.filter(([,v])=>!Number.isFinite(v)||v<80),unmeasured=['semanticDirection','motionRealization','impactBeatSync'].filter(k=>!Number.isFinite(d[k]));
 q.cinemaScorePolicy={minimum:80,maximumWhenUnmet:89,failures:failures.map(([key,score])=>({key,score:score??null})),unmeasured,uncappedOverall:q.overallScore};q.artistic100Established=false;const gaps=args[4]?.metrics?.artworkForeground?.nonCropStructure?.gapsOverEightSeconds;if(gaps?.length){q.overallScore=q.score=Math.min(89,q.overallScore);q.certified100=q.perfectEligible=false;if(!r.issues.some(i=>i.code==='NON_CROP_STAGNATION'))r.issues.push({code:'NON_CROP_STAGNATION',severity:'ERROR',exportBlocking:false,message:'8秒超の文字構造の停滞を検出しました。背景クロップだけでは新規性を満たせません',windows:gaps});}
 if(failures.length){q.overallScore=q.score=Math.min(89,q.overallScore);q.certified100=q.perfectEligible=false;if(!r.issues.some(i=>i.code==='CINEMA_BOTTLENECK'))r.issues.push({code:'CINEMA_BOTTLENECK',severity:'ERROR',exportBlocking:false,message:'新規性・静動差・意味の実現が80未満または未計測のため総合は89以下です'});}
 if(unmeasured.length){q.certified100=q.perfectEligible=false;if(!r.issues.some(i=>i.code==='CINEMA_UNMEASURED'))r.issues.push({code:'CINEMA_UNMEASURED',severity:'WARNING',exportBlocking:false,message:'意味・動作・拍演出の未計測項目があるため100点認定できません'});}
 r.errors=r.issues.filter(i=>i.severity==='ERROR');r.warnings=r.issues.filter(i=>i.severity==='WARNING');q.hardGates={...q.hardGates,total:r.errors.length,passed:!r.errors.length};q.targetAcceptance=J.evaluateQualityTarget(r);if(failures.length||unmeasured.length)q.targetAcceptance.certified100=false;if(failures.length)q.qualification='QUALITY_UNMET';for(const i of r.issues)if(['LOW_FOREGROUND_NOVELTY','LOW_LYRIC_FOREGROUND_NOVELTY','CINEMA_BOTTLENECK','CINEMA_UNMEASURED','NON_CROP_STAGNATION'].includes(i.code))i.category='creative';return J.finalizeExportReadiness(r);};
})();
