/* Final encoded media is authoritative. No edge mask is called a subject mask. */
(()=>{'use strict';const J=window.J,C=J.clamp,mean=a=>a.length?a.reduce((s,v)=>s+v,0)/a.length:0,delta=(a,b)=>a?.length&&a.length===b?.length?mean(a.map((v,i)=>Math.abs(v-b[i]))):null;
const grid=(v,w,h)=>{const out=Array(144).fill(0),counts=Array(144).fill(0);for(let y=0;y<h;y++)for(let x=0;x<w;x++){const i=Math.min(7,Math.floor(y/h*8))*18+Math.min(17,Math.floor(x/w*18));out[i]+=v[y*w+x];counts[i]++;}return out.map((v,i)=>v/Math.max(1,counts[i]));};
J.measureDecodedCinemaFrames=(frames,p,range,width=96,height=Math.round(width*p.H/p.W))=>{
 const valid=frames.filter(f=>f.features?.luma?.length===width*height),start=range?.start??p.socialHook?.start??0,end=range?.end??p.socialHook?.end??p.duration,span=end-start,covered=valid.length>1&&valid[0].time<=start+.15&&valid.at(-1).time>=end-.15&&valid.every((f,i)=>!i||f.time-valid[i-1].time<=.21);if(!covered)return {status:'UNMEASURED',completed:false,reason:'Missing decoded pixels or time coverage',frameCount:valid.length};
 const steps=valid.slice(1).map((f,i)=>({time:f.time,dt:f.time-valid[i].time,motion:delta(f.features.luma,valid[i].features.luma),edge:delta(f.features.edge,valid[i].features.edge)})),cuts=(p.cuts||[]).filter(c=>c.grammar&&c.start<end&&c.end>start),samples=[];let previous=null,stagnationStart=start;
 for(const c of cuts){const interior=valid.filter(f=>f.time>=c.start+.15&&f.time<Math.min(c.end-.05,end)),motion=steps.filter(f=>f.time>=c.start+.2&&f.time<Math.min(c.end-.05,end)),mid=interior[Math.floor(interior.length/2)];if(!mid)continue;const signature=grid(mid.features.luma,width,height),distance=previous?delta(signature,previous):null;if(distance>.035)stagnationStart=c.start;const audioEnergy=p.musicalStructure?.sections?.find(s=>c.start>=s.from&&c.start<s.to)?.energy??p.musicalPhoto?.songProfile?.energy??.5,target=c.grammar.quiet?0:.001+.008*C(audioEnergy)*(c.grammar.temporal?(['echo','grounding','continuity'].includes(c.grammar.temporal.role)?.28:.65+.35*c.grammar.temporal.level):1),energy=mean(motion.map(f=>f.motion));samples.push({line:c.line,from:c.start,to:c.end,energy,compositionDistance:distance,stagnant:c.end-stagnationStart>8,quiet:!!c.grammar.quiet,targetMotion:target,energyGap:Math.max(0,target-energy)});previous=signature;}
 const motion=samples.map(s=>s.energy),dist=samples.map(s=>s.compositionDistance).filter(Number.isFinite),hook=valid.filter(f=>f.time<Math.min(end,start+3)),hookDelta=hook.length>1?Math.max(...hook.map(f=>delta(f.features.luma,hook[0].features.luma))):null,seam=delta(valid[0].features.luma,valid.at(-1).features.luma),contrast=motion.length>1?(Math.max(...motion)-Math.min(...motion))/Math.max(.003,mean(motion)):null;
 const metrics={perceptualNovelty:dist.length?Math.round(100*C(mean(dist)/.12)):null,motion:motion.length?Math.round(100*samples.filter(s=>s.quiet||s.energy>=s.targetMotion).length/samples.length):null,temporalContrast:contrast==null?null:Math.round(100*C(contrast/2)),hookNovelty:hookDelta==null?null:Math.round(100*C(hookDelta/.25)),loopQuality:seam==null?null:Math.round(100*C(1-seam*4)),foregroundNovelty:null,lyricForegroundNovelty:null,displayOnsetAccuracy:null};
 return {status:'DECODED_MP4_PIXEL_PROXY',completed:true,frameCount:valid.length,resolution:[width,height],duration:span,samples,metrics,loop:{fullFrameLumaSeam:seam,textIncluded:true,sampleTimes:[valid[0].time,valid.at(-1).time],lastFrameIncluded:valid.at(-1).time>=end-1/(p.fps||30)-.01},hook:{fullFrameLumaChange:hookDelta},weakLines:samples.filter(s=>s.stagnant||s.energyGap>0||s.compositionDistance!=null&&s.compositionDistance<.035).map(s=>s.line),limits:'Decoded RGB luminance/edge measurements, not OCR, optical flow, foreground segmentation, semantic understanding or audience evaluation. Text and image share full-frame novelty. Missing domains remain unmeasured.'};
};
// Project onto the expected layer pixels, so unrelated codec error cannot hide a line.
const compareLayer=(actual,on,off)=>{let norm=0,dot=0,onError=0,offError=0,count=0;for(let i=0;i<on.length;i++){const d=on[i]-off[i];if(Math.abs(d)<.004)continue;norm+=d*d;dot+=(actual[i]-off[i])*d;onError+=Math.abs(actual[i]-on[i]);offError+=Math.abs(actual[i]-off[i]);count++;}const gain=norm?dot/norm:null;return {referenceDifference:delta(on,off),expectedArea:count/on.length,projectionGain:gain,onError:count?onError/count:null,offError:count?offError/count:null,visible:count>=3&&gain>.30&&gain<1.8&&offError>onError};};
// Exact luma/alpha extraction without allocating unused edge, palette and saliency arrays.
J.cinemaReferenceLuma=rgba=>{const a=new Float32Array(rgba.length/4);for(let i=0;i<a.length;i++){const k=i*4;a[i]=(rgba[k]*.2126+rgba[k+1]*.7152+rgba[k+2]*.0722)/255;}return Array.from(a);};
J.cinemaPrimaryAlpha=rgba=>{const a=new Array(rgba.length/4);for(let i=0;i<a.length;i++)a[i]=rgba[i*4+3]/255;return a;};
// Optional diagnostic: retain primary-associated background paint, suppress only glyph drawFx.
// Historical reference and score remain unchanged unless explicitly requested by the diagnostic.
J.renderCinemaBackgroundAudit=(renderer,ctx,p,t,options)=>{
 const main=J.mainDraw,fx=J.drawFx;
 J.mainDraw=(env,it)=>env.plan._decodedNeutralPrimary&&env.pass==='main'?main({...env,plan:{...env.plan,_decodedNeutralPrimary:false},lyricAuditCtx:null,_cinemaBackgroundOnly:true},it):main(env,it);
 J.drawFx=(env,it)=>env._cinemaBackgroundOnly?null:fx(env,it);
 try{return renderer.frame(ctx,{...p,_decodedNeutralPrimary:true},t,options);}finally{J.mainDraw=main;J.drawFx=fx;}
};
J.measureCinemaOutputReadability=async(p,range,signal,options={})=>{
 const R=options.scope?.renderer||new J.Renderer(),native=document.createElement('canvas'),cv=document.createElement('canvas'),mc=document.createElement('canvas'),width=384,height=Math.round(width*p.H/p.W),start=range?.start??0,end=range?.end??p.duration,samples=[];
 native.width=p.cinemaDelivery?.width||1;native.height=p.cinemaDelivery?.height||1;cv.width=mc.width=width;cv.height=mc.height=height;
 const nx=native.getContext('2d',{alpha:false}),x=cv.getContext('2d'),mx=mc.getContext('2d');
 try{if(!p.cinemaDelivery)return {status:'UNMEASURED',score:null,samples,reason:'requested delivery raster unavailable'};if(!nx?.getImageData||!x?.drawImage)return {status:'UNMEASURED',score:null,samples,reason:'output raster unavailable'};
 if(signal?.aborted)throw new DOMException('Aborted','AbortError');
 const fontState=()=>J.canonicalJSON({status:document.fonts?.status??null,evidence:[...(J.fontLoadEvidence||[])]}),fontKey=fontState(),glyphResolution=J.glyphs?.maxRes;
 const cachePlanHash=J.cinemaV3?.enabled?await J.cinemaV3.planHash(p):null,cacheKey=cachePlanHash&&options.inputHash&&options.scope&&document.fonts?.status!=='loading'?J.canonicalJSON({planHash:cachePlanHash,inputHash:options.inputHash,profile:J.cinemaV3.outputProfile(p,range),texture:J.proceduralTextureVersion,fontKey,glyphResolution,physicalOnly:!!options.physicalOnly,backgroundConsistency:!!options.backgroundConsistency,additionalTimes:options.additionalTimes||[],times:options.times||null,lines:options.lines||null}):null;
 const cache=cacheKey?(options.scope.readabilityCache??=new Map()):null;
 if(cache?.has(cacheKey)){const result=J.clonePhotoRenderPlan(cache.get(cacheKey));Object.defineProperty(result,'measurementReuse',{value:{status:'REUSED_IDENTICAL_PLAN_INPUT_PROFILE_SAMPLES',freshNativeRenders:0},enumerable:false});return result;}
 await J.prepareCinemaProxyRenderer(R,p,options.scope);
 let actualFrame=null;const renderCounts={native:0,aligned:0,background:0,actualFrameHits:0};
 const regularTimes=[...new Set(p.cuts.filter(c=>c.grammar&&c.start<end&&c.end>start).flatMap(c=>[c.start+.04,c.start+c.dur*.25,c.start+c.dur*.5,c.start+c.dur*.75,c.end-.2,c.grammar.temporal?.hit]).filter(t=>Number.isFinite(t)&&t>=start&&t<end-.36))],times=[...new Set([...regularTimes,...(options.additionalTimes||[]).filter(t=>Number.isFinite(t)&&t>=start&&t<end-.36)])].sort((a,b)=>a-b);
 for(const t of times){if(options.times&&!options.times.includes(t))continue;if(options.lines&&!options.lines.includes(J.cutAt(p,t)?.line))continue;if(signal?.aborted)throw new DOMException('Aborted','AbortError');const actualTime=start+Math.floor((t-start)*p.fps+1e-7)/p.fps;
 // Share only the immutable actual-time pixels. Historical requested-time references stay separate.
 const reused=actualFrame?.time===actualTime;if(reused)renderCounts.actualFrameHits++;
 else{R.frame(nx,p,actualTime,{scale:native.width/p.W,production:true,range});renderCounts.native++;x.drawImage(native,0,0,width,height);actualFrame={time:actualTime,actual:J.cinemaReferenceLuma(x.getImageData(0,0,width,height).data)};}
 const actual=actualFrame.actual;
 if(!options.physicalOnly){R.frame(x,p,t,{scale:width/p.W,production:true,range,lyricAuditCtx:mx});}const mask=options.physicalOnly?null:J.cinemaPrimaryAlpha(mx.getImageData(0,0,width,height).data);
 if(!options.physicalOnly){R.frame(x,{...p,_decodedNeutralPrimary:true},t,{scale:width/p.W,production:true,range});}const background=options.physicalOnly?null:J.cinemaReferenceLuma(x.getImageData(0,0,width,height).data);
 // Preserve historical observer-cadence evidence; independently align physical references.
 if(!reused){R.frame(x,p,actualTime,{scale:width/p.W,production:true,range,lyricAuditCtx:mx});renderCounts.aligned++;actualFrame.mask=J.cinemaPrimaryAlpha(mx.getImageData(0,0,width,height).data);
 if(!options.physicalOnly){R.frame(x,{...p,_decodedNeutralPrimary:true},actualTime,{scale:width/p.W,production:true,range});renderCounts.background++;actualFrame.background=J.cinemaReferenceLuma(x.getImageData(0,0,width,height).data);}
 if(options.backgroundConsistency){J.renderCinemaBackgroundAudit(R,x,p,actualTime,{scale:width/p.W,production:true,range});renderCounts.background++;actualFrame.consistentBackground=J.cinemaReferenceLuma(x.getImageData(0,0,width,height).data);}}
 const alignedMask=actualFrame.mask,alignedBackground=actualFrame.background;
 let backgroundConsistentAlignedContrast=null;if(options.backgroundConsistency)backgroundConsistentAlignedContrast=J.decodedGlyphContrast(actual,actualFrame.consistentBackground,alignedMask,width,height);samples.push({backgroundConsistentAlignedContrast,supplemental:!regularTimes.includes(t),line:J.cutAt(p,t)?.line??null,time:t,actualTime,referenceTime:t,alignedReferenceTime:actualTime,contrast:options.physicalOnly?{score:null,status:'UNMEASURED',reason:'PHYSICAL_ONLY_REFERENCE'}:J.decodedGlyphContrast(actual,background,mask,width,height),alignedContrast:options.physicalOnly?{score:null,status:'UNMEASURED',reason:'PHYSICAL_ONLY_REFERENCE'}:J.decodedGlyphContrast(actual,alignedBackground,alignedMask,width,height)});
 }const regular=samples.filter(s=>!s.supplemental),measured=regular.length>0&&regular.every(s=>Number.isFinite(s.contrast.score));const result={renderCounts,status:measured?'MEASURED':'UNMEASURED',score:measured?Math.min(...regular.map(s=>s.contrast.score)):null,samples,frameAlignedScore:regular.length&&regular.every(s=>Number.isFinite(s.alignedContrast?.score))?Math.min(...regular.map(s=>s.alignedContrast.score)):null,alignedMethod:'requested raster decoded-grid Canvas image and glyph/background references at the same actual frame time; separate from historical final observer cadence',outputResolution:[native.width,native.height],observerResolution:[width,height],fps:p.fps,cacheIdentity:cachePlanHash?{planHash:cachePlanHash,unchanged:cachePlanHash===await J.cinemaV3.planHash(p),profileId:J.cinemaV3.profileId(J.cinemaV3.outputProfile(p,range)),textureVersion:J.proceduralTextureVersion,backgroundConsistency:!!options.backgroundConsistency,additionalTimes:[...new Set(options.additionalTimes||[])].sort((a,b)=>a-b),inputHash:options.inputHash??null,physicalOnly:!!options.physicalOnly,method:options.physicalOnly?'CANVAS actual-frame output and background-consistent glyph reference':'CANVAS requested-output raster / historical and actual-time glyph references'}:null,source:'CANVAS final-observer cadence simulation; codec not measured'};
 if(cache&&result.cacheIdentity?.unchanged&&fontKey===fontState()&&glyphResolution===J.glyphs?.maxRes){cache.set(cacheKey,J.clonePhotoRenderPlan(result));while(cache.size>16)cache.delete(cache.keys().next().value);}return result;
 }finally{if(!options.scope){R.customBgBitmap?.close?.();R.disposeAssets?.();}native.width=native.height=cv.width=cv.height=mc.width=mc.height=1;}
};
J.verifyDecodedCinemaLayers=async(frames,p,range,options={})=>{if((!p.musicalPhoto?.cinema?.architecture&&!options.includeAllLyrics)||!frames.length)return null;const R=new J.Renderer(),width=options.width||96,height=Math.round(width*p.H/p.W),cv=document.createElement('canvas'),mc=document.createElement('canvas');cv.width=mc.width=width;cv.height=mc.height=height;const x=cv.getContext('2d'),mx=mc.getContext('2d'),samples=[],primary=[];let textLoop=null;const start=range?.start??0,end=range?.end??p.duration;
 try{await R.loadCustomBackground(p.customBg.dataUrl);await R.loadAssetDeck?.(p);for(const c of p.cuts.filter(c=>(options.includeAllLyrics?c.line>=0:c.grammar&&!J.photoChoreographyLocked(p,c))&&c.start<end&&c.end>start)){
  const times=[c.start+.04,c.start+c.dur*.25,c.start+c.dur*.5,c.start+c.dur*.75,c.end-.2,c.grammar?.temporal?.hit??c.start+.3].filter(t=>t>=start&&t<end-.36),unique=[...new Set(times.map(t=>frames.reduce((best,f)=>Math.abs(f.time-t)<Math.abs(best.time-t)?f:best,frames[0])))].sort((a,b)=>a.time-b.time),glyphs=[];
  for(const frame of unique){if(!frame?.features?.luma?.length||frame.time<c.start||frame.time>=c.end)continue;const render=(layerNeutral,textNeutral)=>{R.cinemaNeutralLayers=layerNeutral;const plan=textNeutral?{...p,_decodedNeutralPrimary:true}:p;const renderOptions={scale:width/p.W,production:true,noHud:false,range,lyricAuditCtx:mx};if(textNeutral&&options.backgroundConsistency)J.renderCinemaBackgroundAudit(R,x,plan,frame.actualTime??frame.time,renderOptions);else R.frame(x,plan,frame.actualTime??frame.time,renderOptions);const luma=J.cinemaReferenceLuma(x.getImageData(0,0,width,height).data),mask=J.cinemaPrimaryAlpha(mx.getImageData(0,0,width,height).data);return {luma,mask};},on=render(false,false),off=render(false,true),actual=frame.features.luma,evidence=compareLayer(actual,on.luma,off.luma);glyphs.push({time:frame.time,phase:J.cinemaTemporalState?.(p,c,frame.time)?.phase??null,...evidence,contrast:J.decodedGlyphContrast?.(actual,off.luma,on.mask,width,height)??null,mask:on.mask,structure:grid(on.mask,width,height)});
   if(c.grammar?.safeDerived){const without=render(true,false);samples.push({line:c.line,time:frame.time,kind:c.grammar.derivedLayer,...compareLayer(actual,on.luma,without.luma)});}
  }
  if(glyphs.length){const steps=glyphs.slice(1).map((f,i)=>{const a=glyphs[i].mask,b=f.mask,union=mean(a.map((v,k)=>Math.max(v,b[k])));return delta(a,b)/Math.max(.0001,union);});const mid=glyphs[Math.floor(glyphs.length/2)];primary.push({line:c.line,role:c.grammar?.temporal?.role,visibleSamples:glyphs.filter(s=>s.visible).length,samples:glyphs.map(({mask,structure,...s})=>s),structure:mid.structure,withinPhraseMaskChange:mean(steps)});}await new Promise(r=>setTimeout(r,0));
 }const endpointMasks=[];for(const frame of [frames[0],frames.at(-1)]){R.cinemaNeutralLayers=false;R.frame(x,p,frame.actualTime??frame.time,{scale:width/p.W,production:true,noHud:false,range,lyricAuditCtx:mx});endpointMasks.push(J.cinemaPrimaryAlpha(mx.getImageData(0,0,width,height).data));}textLoop=J.decodedTextSeam?.(frames[0].features.luma,frames.at(-1).features.luma,...endpointMasks)??null;
 }finally{R.cinemaNeutralLayers=false;R.customBgBitmap?.close?.();R.disposeAssets?.();cv.width=cv.height=mc.width=mc.height=1;}
 const changes=primary.slice(1).map((s,i)=>delta(s.structure,primary[i].structure)/Math.max(.005,mean(s.structure.map((v,k)=>Math.max(v,primary[i].structure[k]))))),presence=primary.length?mean(primary.map(s=>s.samples.length?s.visibleSamples/s.samples.length:0)):0;
 return {resolution:[width,height],textLoop,samples,score:samples.length?Math.round(100*samples.filter(s=>s.visible).length/samples.length):null,method:'Decoded luma projected onto identical production on-minus-off reference; only expected layer pixels compared',objectSegmentation:false,primaryText:{samples:primary,visibleFraction:presence,lyricForegroundNovelty:primary.length>1?Math.round(100*C(mean(changes))*presence):null,meanWithinPhraseMaskChange:mean(primary.map(s=>s.withinPhraseMaskChange)),method:'18×8 actual primary alpha occupancy; normalized consecutive occupancy change × encoded compositing presence. Within-phrase alpha displacement reported separately.',limits:'Expected raster mask and compositing evidence, not OCR, exact string recognition or semantic realization.'}};
};
J.applyDecodedCinemaEvidence=d=>{if(d?.completed&&d.layerPresence?.primaryText)d.metrics.lyricForegroundNovelty=d.layerPresence.primaryText.lyricForegroundNovelty;return d;};
J.reconcileDecodedCinemaQuality=(r,decoded)=>{const q=r.quality;if(!decoded?.completed)return r;q.evidenceByStage={planned:{status:'INTENT_ONLY',source:'storyboard; never certification'},preEncode:{metrics:{...(q.metrics||{})},source:'production canvas before encoding'},decoded:{metrics:{...decoded.metrics},source:'decoded final MP4',definitions:decoded.limits,primaryText:decoded.layerPresence?.primaryText?.limits||null}};q.preEncodeCinemaScores={...(q.metrics||{})};
 for(const key of ['perceptualNovelty','temporalContrast','hookNovelty','loopQuality','lyricForegroundNovelty','foregroundNovelty'])q.metrics[key]=Number.isFinite(decoded.metrics[key])?decoded.metrics[key]:null;q.metrics.decodedMotion=decoded.metrics.motion;q.finalCinemaMetricSource='decoded-MP4';
 const gates=[['perceptualNovelty','LOW_PERCEPTUAL_NOVELTY'],['lyricForegroundNovelty','LOW_LYRIC_FOREGROUND_NOVELTY'],['foregroundNovelty','LOW_FOREGROUND_NOVELTY']],replaced=new Set([...gates.map(x=>x[1]),'ENCODED_CINEMA_UNMET','ENCODED_LAYER_NOT_REALIZED',...(decoded.layerPresence?.primaryText?.samples?.length?['NON_CROP_STAGNATION']:[])]);r.issues=r.issues.filter(i=>!replaced.has(i.code));
 for(const [key,code]of gates)if(!Number.isFinite(q.metrics[key])||q.metrics[key]<80)r.issues.push({code,score:q.metrics[key],minimum:80,severity:'ERROR',category:'creative',exportBlocking:false,measurementSource:'decoded-MP4',message:'最終MP4の '+key+' が基準80未達、または未計測です'});
 if(decoded.metrics.perceptualNovelty<80||decoded.samples.some(s=>s.stagnant||s.energyGap>0))r.issues.push({code:'ENCODED_CINEMA_UNMET',severity:'ERROR',category:'creative',exportBlocking:false,message:'最終MP4に新規性・動作不足が残っています',lines:decoded.weakLines});
 if(decoded.layerPresence?.samples?.some(s=>!s.visible))r.issues.push({code:'ENCODED_LAYER_NOT_REALIZED',severity:'ERROR',category:'creative',exportBlocking:false,message:'指定した派生レイヤーを最終MP4上で確認できません',lines:decoded.layerPresence.samples.filter(s=>!s.visible).map(s=>s.line)});
 const glyphs=decoded.layerPresence?.primaryText?.samples||[],gaps=[];let last=decoded.samples[0]?.from??0;for(const s of glyphs){const prev=glyphs[glyphs.indexOf(s)-1];if(prev&&delta(s.structure,prev.structure)>.035){if(s.samples[0].time-last>8)gaps.push({from:last,to:s.samples[0].time});last=s.samples[0].time;}}const lastTime=decoded.samples.at(-1)?.to??last;if(lastTime-last>8)gaps.push({from:last,to:lastTime});if(glyphs.length&&gaps.length)r.issues.push({code:'NON_CROP_STAGNATION',severity:'ERROR',category:'creative',exportBlocking:false,measurementSource:'decoded-MP4 verified primary alpha occupancy',windows:gaps,message:'最終MP4の文字構造に8秒超の停滞があります'});
 q.decodedLayerPresence=decoded.layerPresence||null;const category=q.categories?.find(c=>c.key==='motion');if(category&&Number.isFinite(decoded.metrics.motion))category.score=category.max*decoded.metrics.motion/100;
 const d=q.productionDomains||{},constraints=['perceptualNovelty','foregroundNovelty','lyricForegroundNovelty','temporalContrast'].map(key=>({key,score:q.metrics[key]??null}));constraints.push({key:'semanticDirection',score:d.semanticDirection??null});q.cinemaScorePolicy={...q.cinemaScorePolicy,minimum:80,failures:constraints.filter(s=>!Number.isFinite(s.score)||s.score<80),unmeasured:['semanticDirection','motionRealization','impactBeatSync'].filter(k=>!Number.isFinite(d[k])),finalMetricSource:'decoded-MP4; source foreground segmentation unmeasured'};J.applyCinemaDependencyCaps(r);r.errors=r.issues.filter(i=>i.severity==='ERROR');r.warnings=r.issues.filter(i=>i.severity==='WARNING');q.hardGates={...q.hardGates,total:r.errors.length,passed:!r.errors.length};return r;};
const check=J.checkMVQuality;J.checkMVQuality=(...args)=>{const r=check(...args),p=args[1],decoded=args[4]?.metrics?.decodedCinema;if(!p.musicalPhoto?.cinema?.architecture)return r;const q=r.quality;q.decodedCinema=decoded||{completed:false,status:'NOT_ENCODED_YET'};if(decoded?.completed)J.reconcileDecodedCinemaQuality(r,decoded);q.certified100=q.perfectEligible=false; // Decoded lyric/semantic realization is still unmeasured.
 q.certificationEvidence={finalEncodedPixels:!!decoded?.completed,decodedTextRecognition:false,decodedSemanticDirection:false,artistic100Established:false};q.targetAcceptance=J.evaluateQualityTarget(r);return J.finalizeExportReadiness(r);};
const provenance=J.createExportProvenance;J.createExportProvenance=async(...args)=>{const r=await provenance(...args);return {...r,decodedCinema:args[2].quality.decodedCinema||null,compositionSearch:args[0].plan.musicalPhoto?.cinema?.architectureSearch||null,measurementSources:{...r.measurementSources,perceptualNovelty:args[2].quality.decodedCinema?.completed?'decoded-MP4-full-frame-proxy':'pre-export-canvas',temporalContrast:args[2].quality.decodedCinema?.completed?'decoded-MP4':'pre-export-canvas',loopQuality:args[2].quality.decodedCinema?.completed?'decoded-MP4-image-and-text-luma-seam':'pre-export-canvas',foreground:'decoded-layer-presence-counterfactual; source segmentation unmeasured',lyricForegroundNovelty:args[2].quality.decodedCinema?.completed?'decoded-MP4-verified-primary-alpha-occupancy':'pre-export-primary-alpha-mask',displayOnsetAccuracy:'pre-export-full-glyph-mask; decoded-OCR-unmeasured'}};};

J.observeAlignedLyrics=async(blob,p,range,signal,options={})=>{
 const start=range?.start??0,end=range?.end??p.duration,width=384,height=Math.round(width*p.H/p.W),times=[...new Set([...p.cuts.filter(c=>c.line>=0&&c.start<end&&c.end>start).flatMap(c=>[c.start+.04,c.start+c.dur*.25,c.start+c.dur*.5,c.start+c.dur*.75,c.end-.2,c.grammar?.temporal?.hit??c.start+.3]),...(options.additionalTimes||[])].filter(t=>Number.isFinite(t)&&t>=start&&t<end-.36))].sort((a,b)=>a-b),frames=[...(options.frames||[])],known=new Set(frames.map(f=>f.time)),missing=times.filter(t=>!known.has(t)),control=new AbortController(),abort=()=>control.abort();signal?.addEventListener('abort',abort,{once:true});if(signal?.aborted)abort();
 try{if(missing.length)await J.waitExportStep(()=>window.JIZURAMedia.sampleMP4(blob,missing.map(t=>t-start),{width,height,signal:control.signal,onSample:(t,pixels,metadata)=>frames.push({time:start+t,decodedTimestamp:metadata?.timestamp==null?null:start+metadata.timestamp,features:{luma:J.cinemaReferenceLuma(pixels)}})}),{signal:control.signal,onTimeout:abort,timeout:30000,label:'最終MP4の実フレーム時刻と全歌詞を検査'});
 if(!frames.length||frames.some(f=>!Number.isFinite(f.decodedTimestamp)))return {status:'UNMEASURED',score:null,samples:[],reason:'ACTUAL_DECODER_TIMESTAMPS_UNAVAILABLE'};
 frames.sort((a,b)=>a.time-b.time);const layers=options.backgroundOnly?null:await J.verifyDecodedCinemaLayers(frames.map(f=>({...f,actualTime:f.decodedTimestamp})),p,range,{width,includeAllLyrics:true}),samples=(layers?.primaryText?.samples||[]).flatMap(phrase=>phrase.samples.map(sample=>({line:phrase.line,time:sample.time,actualTime:frames.find(f=>f.time===sample.time)?.decodedTimestamp??null,visible:sample.visible,contrast:sample.contrast}))),measured=samples.length>0&&samples.every(s=>s.visible&&Number.isFinite(s.contrast?.score));
 let backgroundConsistentReadability=null;if(options.backgroundConsistency){const consistent=await J.verifyDecodedCinemaLayers(frames.map(f=>({...f,actualTime:f.decodedTimestamp})),p,range,{width,includeAllLyrics:true,backgroundConsistency:true}),points=consistent.primaryText.samples.flatMap(phrase=>phrase.samples.map(s=>({line:phrase.line,time:s.time,actualTime:frames.find(f=>f.time===s.time)?.decodedTimestamp??null,contrast:s.contrast,visible:s.visible}))),complete=points.length>0&&points.every(s=>s.visible&&Number.isFinite(s.contrast?.score));backgroundConsistentReadability={status:complete?'MEASURED':'UNMEASURED',score:complete?Math.min(...points.map(s=>s.contrast.score)):null,samples:points,method:'Independent decoded actual-time pixels; same glyph contrast formula, masks, thresholds and cadence; neutral reference retains primary-associated background paint via drawFx suppression. Separate diagnostic, never substituted for historical localContrast.',limits:'Not OCR or human evaluation; counterfactual background ordering must be reviewed'};}return {backgroundConsistentReadability,additionalObservationTimes:options.additionalTimes||[],originalCadenceUnchanged:true,status:measured?'MEASURED':'UNMEASURED',score:measured?Math.min(...samples.map(s=>s.contrast.score)):null,samples,layerPresence:layers,source:'independent final MP4 decode; all lyric cuts including locks; production mask and neutral background at actual decoder timestamp; historical localContrast retained separately',resolution:[width,height],missingReasons:samples.filter(s=>!s.visible||!Number.isFinite(s.contrast?.score)).map(s=>({line:s.line,time:s.time,actualTime:s.actualTime,reason:!s.visible?'EXPECTED_PRIMARY_NOT_VERIFIED':'INSUFFICIENT_OPAQUE_GLYPH_OR_RING'}))};
 }finally{abort();signal?.removeEventListener('abort',abort);}
};
})();
