/* Temporal direction: principles conditioned on meaning, sound and content. */
(()=>{'use strict';const J=window.J,C=J.clamp,ease=u=>{u=C(u);return u*u*(3-2*u);},active=p=>!!p.musicalPhoto?.cinema?.architecture,locked=(p,c)=>!!c&&J.photoChoreographyLocked(p,c);
J.cinemaMotionRole=c=>c.story?.group?'participation':/いつも|変わら|続[くけ]|歩み|日々|again|always|every day/i.test(c.lineText)?'continuity':({gather:'gathering',hero:'identity',pride:'light',rage:'impact',call:'echo',unity:'grounding'})[c.cinema?.meaning]||'narrative';
const apply=J.applyCinemaArchitecture;J.applyCinemaArchitecture=(p,candidate)=>{
 const f=p.musicalPhoto.cinema,original=f.climax,all=p.cuts.filter(c=>c.grammar&&!locked(p,c)),lastGroup=all.filter(c=>c.story?.group).at(-1)?.story?.group,near=lastGroup&&all.find(c=>c.story?.group===lastGroup&&Number.isFinite(original)&&c.start>=original-c.dur*1.5&&c.start<=original);
 if(!candidate.quiet&&near&&p.musicalPhoto.songProfile.energy>.55)f.climax=near.start;
 apply(p,candidate);const peakCuts=all.filter(c=>c.start>=f.climax),count=Math.max(1,peakCuts.length-1),beats=p.beatHierarchy||[];
 for(const c of all){const g=c.grammar,role=J.cinemaMotionRole(c),peak=peakCuts.indexOf(c),energy=p.musicalStructure.sections.find(s=>c.start>=s.from&&c.start<s.to)?.energy??p.musicalPhoto.songProfile.energy,level=g.quiet?.18:role==='echo'?.25:role==='grounding'?.20:role==='continuity'?.30:role==='participation'?.55+.1*g.stage:role==='impact'?.90:.48+.18*C(energy),beat=beats.find(b=>b.time>c.start+.22&&b.time<Math.min(c.end-.2,c.start+.8)&&b.beatSalience>.35),hit=beat?.time??c.start+Math.min(.34,c.dur*.18);
  g.temporal={version:1,role,level:peak>=0&&!g.quiet?.7+.3*peak/count:level,hit,entry:Math.min(.32,c.dur*.18),exit:Math.min(.18,c.dur*.08),motionPrinciple:role==='gathering'?'converge':role==='echo'?'arrival-and-resonance':role==='light'?'open-and-illuminate':role==='impact'?'percussive-deformation':role==='continuity'?'stable-travel':role==='grounding'?'weighted-hold':role==='participation'?'phrase-call-response':'reveal-and-settle',climax:peak>=0&&!g.quiet,source:'lyric role + section energy + percussion profile + actual beat hierarchy; complete lyric visible at onset'};
  if(g.temporal.climax){g.field=peak===0?(candidate.direction?'arena':'hero'):peak===peakCuts.length-1?(candidate.direction?'hero':'arena'):candidate.id%2?'split':'graphic';g.climaxLevel=g.temporal.level;g.grade=peak===0?'blue':'silhouette';c.params.photoAnchor={x:.5,y:.5};g.derivedLayer=g.field==='arena'?'rails':g.field==='graphic'?'contour':null;g.safeDerived=!!g.derivedLayer;g.foregroundLayers=g.safeDerived?1:0;}
  if(role==='participation'&&!g.temporal.climax&&!g.quiet&&g.stage>=3){g.field=g.stage===4?(candidate.direction?'arena':'hero'):(candidate.id%2?'graphic':'arena');g.derivedLayer=g.field==='graphic'?'contour':g.field==='arena'?'rails':null;g.safeDerived=!!g.derivedLayer;g.foregroundLayers=g.safeDerived?1:0;c.params.photoAnchor={x:.5,y:.5};}
  g.motion=g.temporal.level;g.layerStrength=1;g.layerWidth=1;g.phraseMotion=role==='participation'?['call','response','wave','unison'][g.stage-1]:'semantic';
 }
 f.temporalDirection={version:1,climaxEntry:f.climax,contentSeed:candidate.seed,principles:[...new Set(all.map(c=>c.grammar.temporal.motionPrinciple))],thresholdsChanged:false};f.grammar.shots=all.map(c=>({line:c.line,from:c.start,to:c.end,...c.grammar}));for(const s of p.storyboard||[]){const c=all.find(c=>c.start===s.from);if(c)s.shotGrammar={...c.grammar};}return p;
};
J.cinemaTemporalState=(p,c,t)=>{const d=c?.grammar?.temporal;if(!d)return null;const elapsed=t-c.start,u=C(elapsed/Math.max(.1,c.dur)),phase=t<d.hit?'anticipation':t<d.hit+.16?'impact':t>c.end-d.exit?'release':'settle',impact=elapsed>=0?Math.exp(-Math.max(0,t-d.hit)*17)*(t>=d.hit?1:0):0,entry=1-ease(elapsed/Math.max(.1,d.entry));const phases=J.cinemaV3?.enabled&&c.grammar?.scenePhases,stagePhase=phases?J.cinemaV3.phaseAt(phases,t):null,at=span=>ease((t-span[0])/Math.max(1e-6,span[1]-span[0]));let sceneEntry=entry,travel=ease(u);if(phases){sceneEntry=1-ease((t-phases.ENTER[0])/Math.max(1e-6,phases.SETTLE[1]-phases.ENTER[0]));const intentional=c.grammar.intentionalHold===true,holdEnd=intentional?.2:.8;if(t<phases.HOLD[0])travel=.2*ease((t-phases.ENTER[0])/Math.max(1e-6,phases.HOLD[0]-phases.ENTER[0]));else if(t<phases.RELEASE[0])travel=intentional?.2:.2+.6*at(phases.HOLD);else travel=holdEnd+(intentional?0:1-holdEnd)*at([phases.RELEASE[0],phases.EXIT[1]]);}return {...d,elapsed,u,phase,stagePhase,impact,entry:sceneEntry,travel};};
J.temporalCinemaFocus=(p,c,focus,t)=>{const s=J.cinemaTemporalState(p,c,t);if(!s)return focus;const q={...focus},slow=['echo','grounding','continuity'].includes(s.role),percussive=C(p.musicalPhoto.songProfile.attack??.5),push=s.level*(slow?.06:.18),progress=s.travel;
 q.zoom=(q.zoom||1)*(1+push*progress+((s.role==='impact'||s.climax)?.035*percussive*s.impact:0));q.push=0;q.x=C(q.x+(s.role==='gathering'?(q.x-.5)*.07*s.entry:s.role==='continuity'?.025*progress:s.role==='participation'?(c.grammar.side?1:-1)*.04*Math.sin(s.u*Math.PI):0),.03,.97);q.y=C(q.y-(s.role==='light'?.04*progress:0),.03,.97);return q;};
// Linked image regions follow a continuous path where the music calls for travel.
const boxes=J.cinemaFieldBoxes;J.cinemaFieldBoxes=(p,g,t)=>{const current=boxes(p,g);if(!g.temporal||!Number.isFinite(t)||g.temporal.climax)return current;const c=p.cuts.find(c=>c.grammar===g),i=p.cuts.indexOf(c),previous=p.cuts[i-1];if(!previous?.grammar?.temporal||locked(p,previous)||!['echo','continuity','grounding'].includes(g.temporal.role))return current;const from=boxes(p,previous.grammar);if(!current||current.length!==1||from?.length!==1)return current;const u=ease((t-c.start)/Math.min(.40,c.dur*.18));return [{...current[0],...Object.fromEntries(['x','y','w','h'].map(k=>[k,J.lerp(from[0][k],current[0][k],u)]))}];};
const makeEnv=J.Renderer.prototype.makeEnv;J.Renderer.prototype.makeEnv=function(...args){return {...makeEnv.apply(this,args),range:this.renderRange};};
const draw=J.drawCinemaGrammar;J.drawCinemaGrammar=function(ctx,p,t){const value=draw.call(this,ctx,p,t),c=J.cutAt(p,t),s=J.cinemaTemporalState(p,c,t);if(!value||!s||locked(p,c))return value;const end=this.renderRange?.end??p.duration;if(t>=end-.7)return value;
 if(s.role==='light'||(s.impact>.015&&s.level>.4)){ctx.save();ctx.globalCompositeOperation='screen';ctx.globalAlpha=s.role==='light'?.055*Math.sin(s.u*Math.PI):.075*s.level*s.impact;ctx.fillStyle=p.style?.schemes?.[0]?.accent||'#73baff';ctx.fillRect(0,0,p.W,p.H);ctx.restore();}return value;};
// Typography keeps one authoritative complete phrase; echoes are decoration.
for(const [id,layout]of Object.entries(J.LAYOUTS))if(id.startsWith('cinemaGrammar')){const original=layout.render;layout.render=env=>{const g=env.cut.grammar;if(!g?.temporal||!g.stage||g.quiet)return original(env);const {W,H,cut}=env,source=String(cut.lineText||cut.text),chars=Array.from(source),text=W>H&&(g.temporal.climax||g.stage===2||g.stage===4)?chars.slice(0,Math.ceil(chars.length/2)).join('')+'\n'+chars.slice(Math.ceil(chars.length/2)).join(''):J.vocaliseUnits(source).join('\n'),font=cut.params.font||'embedded_bold',size=Math.min(H*(W>H?(g.temporal.climax?.185:[0,.135,.155,.175,.185][g.stage]):.105),J.fitSize(text,font,W*.84,H*.61,{lead:1.10,track:.028,sx:1.04}));return J.mainDraw(env,{text,font,size,x:W/2,y:H/2,lead:1.10,track:.028,sx:1.04,color:'#fff',noHold:true,grammarMode:g.mode,cinemaMotion:'read',enter:cut.enter,exit:cut.exit});};}
const main=J.mainDraw;J.mainDraw=(env,it)=>{if(env.plan._decodedNeutralPrimary&&env.pass==='main')return null;const g=env.cut.grammar,s=J.cinemaTemporalState(env.plan,env.cut,env.t);if(!s||locked(env.plan,env.cut)||!it.grammarMode)return main(env,it);const neutral=env.plan.cinemaSemanticNeutral,role=s.role;
 if(!neutral){it.track=role==='echo'?.060:role==='light'?.045:role==='impact'?.008:role==='grounding'?.015:role==='continuity'?.028:it.track;it.sx=(it.sx||1)*(role==='impact'?.95:role==='echo'?1.02:role==='identity'?1.05:1);it.fontWeight=Math.min(800,Math.max(500,Math.round((J.faceOf?.(it.font)?.weight||700)/100)*100-(['echo','continuity'].includes(role)?100:0)));}
 return main(env,it);};
const type=J.applyTypography5;J.applyTypography5=(env,it)=>{type(env,it);const s=J.cinemaTemporalState(env.plan,env.cut,env.t),g=env.cut.grammar;if(!s||!it.grammarMode||locked(env.plan,env.cut))return;const p=env.plan,end=env.range?.end??p.duration,last=Math.floor((end-1e-7)*p.fps)/p.fps,window=Math.min(.36,Math.max(0,end-env.cut.start-.55)),closing=window?ease((env.t-(end-window))/Math.max(1/p.fps,last-(end-window))):0;
 if(closing)it.alpha=(it.alpha??1)*(1-closing);if(p.cinemaSemanticNeutral)return;
 it.charFns.push((i,glyph)=>{const row=glyph.li||0,read=['echo','grounding','continuity'].includes(s.role),pressure=s.level,base=(s.climax?.075:s.role==='identity'?.04:.018)*s.impact,entry=s.entry,dx=s.role==='gathering'?(row%2?1:-1)*env.W*.025*entry:s.role==='participation'?((g.phraseMotion==='call'?-1:g.phraseMotion==='response'?1:row%2?1:-1)*env.W*.023*entry):0,dy=s.role==='light'?-env.H*.018*s.travel:s.role==='echo'?env.H*.008*Math.sin(s.u*Math.PI*2-row*.65):s.role==='continuity'?env.H*.002*Math.sin(s.u*Math.PI):s.role==='participation'?env.H*.009*pressure*Math.sin(s.u*Math.PI*2-row*.7):0;
 return {dx,dy,s:1+base+(read?.004:.008)*Math.sin(s.u*Math.PI)*pressure,sx:s.role==='impact'?1-.04*s.impact:1,sy:s.role==='impact'?1+.035*s.impact:1};});
};
const accent=J.drawCinemaAccent;J.drawCinemaAccent=(ctx,p,t)=>{accent(ctx,p,t);const c=J.cutAt(p,t),s=J.cinemaTemporalState(p,c,t);if(!s||locked(p,c))return;const end=ctx?.renderRange?.end??p.duration;if(t>=end-.7)return;
 if(s.role==='echo'&&s.u>.12&&s.u<.8){const word=String(c.lineText).match(/声|呼[ぶび]|聞|voice|call|echo/i)?.[0];if(word){ctx.save();ctx.font=J.fontCSS(c.params.font||'embedded_bold',p.H*.09,700);ctx.textAlign='center';ctx.textBaseline='middle';ctx.strokeStyle=p.style?.schemes?.[0]?.accent||'#80bfff';ctx.lineWidth=p.H*.002;ctx.globalAlpha=.16*Math.sin((s.u-.12)/.68*Math.PI);ctx.strokeText(word,p.W*(c.grammar.side?.82:.18),p.H*.20,p.W*.23);ctx.restore();}}
};
// Fade-in credit at the actual first frame, independent of legacy title timing.
const creditState=J.creditStateAt;J.creditStateAt=(p,t)=>{const r=creditState(p,t);return active(p)&&Number.isFinite(p._actualTemporalCreditTime)?{...r,opacity:(r.opacity??1)*ease(p._actualTemporalCreditTime/.22)}:r;};const credit=J.Renderer.prototype.drawTitleCredit;J.Renderer.prototype.drawTitleCredit=function(ctx,p,t,...args){if(active(p)&&ease(t/.22)<=.002)return;return credit.call(this,ctx,active(p)?{...p,_actualTemporalCreditTime:t}:p,t,...args);};
const provenance=J.createExportProvenance;J.createExportProvenance=async(...args)=>({...await provenance(...args),loopTextPolicy:active(args[0].plan)?'Background return; final primary lyric holds then resolves over the final 0.36 seconds where duration permits; opening title begins next playback, never overlapping':null});
const context=J.directorContext;J.directorContext=(...args)=>({...context(...args),temporalDirection:args[1].musicalPhoto?.cinema?.temporalDirection||null,loopTextPolicy:active(args[1])?'Background returns to opening; complete final lyric holds then fades over the final 0.36 seconds; title begins next playback without overlap':null});
})();
