/* Content-seeded composition tournament. Only visible raster improvements survive. */
(()=>{'use strict';const J=window.J,C=J.clamp,ease=u=>{u=C(u);return u*u*(3-2*u);},active=p=>!!p.musicalPhoto?.cinema,locked=(p,c)=>!!c&&J.photoChoreographyLocked(p,c);
const hash=s=>{let h=2166136261;for(const ch of String(s)){h^=ch.charCodeAt(0);h=Math.imul(h,16777619);}return h>>>0;};
J.cinemaContentSeed=p=>hash(JSON.stringify([p.artDirection?.registrySelection?.audioKey,p.artDirection?.registrySelection?.backgroundKey,p.lines?.map(l=>[l.start,l.text]),p.musicalPhoto?.songProfile,p.musicalPhoto?.cinema?.pool,p.styleKey]));
const fields=['hero','window','asymmetric','band','graphic','arena'],safeLayers=['frame','rails','grid','contour'];
J.cinemaArchitectureCandidates=p=>{const seed=J.cinemaContentSeed(p),quiet=['flow','drift'].includes(p.musicalPhoto.songProfile.mode);return Array.from({length:12},(_,id)=>({id,seed,quiet,rotation:hash(seed+':'+id)%6,direction:hash('side'+seed+id)%2,opening:hash('open'+seed+id)%3}));};
const sync=p=>{const f=p.musicalPhoto.cinema;if(f.visualDNA){f.visualDNA.master={...f.visualDNA.master,seed:f.architecture.seed};f.visualDNA.worlds=p.cuts.filter(c=>c.grammar).map(c=>({line:c.line,world:c.grammar.subWorld,role:c.grammar.temporal?.role,energy:p.musicalPhoto.localMusic?.find(x=>x.line===c.line)?.energy??c.grammar.temporal?.level}));}f.grammar.shots=p.cuts.filter(c=>c.grammar).map(c=>({line:c.line,from:c.start,to:c.end,...c.grammar}));for(const s of p.storyboard||[]){const c=p.cuts.find(c=>c.start===s.from&&c.grammar);if(c&&!s.locked)s.shotGrammar={...c.grammar};}};
J.applyCinemaArchitecture=(p,candidate)=>{const f=p.musicalPhoto.cinema,quiet=candidate.quiet,climaxCuts=p.cuts.filter(c=>c.grammar&&c.start>=f.climax&&!locked(p,c)),n=Math.max(1,climaxCuts.length-1);let prior='';
 for(const c of p.cuts)if(c.grammar&&!locked(p,c)){
  const g=c.grammar,meaning=c.cinema.meaning,stage=g.stage,climax=climaxCuts.indexOf(c),pick=hash(candidate.seed+':'+candidate.id+':'+c.line+':'+meaning),pool=quiet?['hero','window','band']:fields;
  let field=pool[(pick+candidate.rotation)%pool.length];if(meaning==='call')field='negative';else if(meaning==='rage'&&!quiet)field='split';else if(meaning==='unity')field='band';else if(meaning==='pride')field='window';else if(stage){field=quiet?['hero','window','band','arena'][(stage-1+candidate.rotation)%4]:fields[(stage-1+candidate.rotation+(c.story.group==='oh'?2:0))%fields.length];}
  if(climax>=0&&!quiet){const progress=climax/n;field=progress===1?(candidate.direction?'arena':'hero'):progress>=.6?(candidate.id%2?'graphic':'split'):progress>=.3?(candidate.id%2?'asymmetric':'band'):(candidate.id%2?'window':'hero');}
  if(field===prior&&meaning!=='call'&&climax<0)field=pool[(pool.indexOf(field)+1)%pool.length];prior=field;
  g.field=field;g.architectureVersion=1;g.side=candidate.direction;g.climaxLevel=climax<0?0:.70+.30*climax/n;g.climaxPhase=climax<0?null:climax===0?'entry':climax===climaxCuts.length-1?'peak':climax===climaxCuts.length-2?'escalation':'expansion';
  // Whole-source contours and authored geometry are not object masks or new assets.
  g.derivedLayer=quiet?(field==='window'?'frame':null):field==='graphic'?'contour':field==='arena'?'rails':field==='window'?'frame':field==='asymmetric'?'grid':null;g.safeDerived=safeLayers.includes(g.derivedLayer);g.foregroundLayers=g.safeDerived?1:0;g.foregroundPolicy='verified whole-image contour or authored geometry; no source fragments';
  g.phraseMotion=!stage?'semantic':['solo','response','wave','crowd'][stage-1];g.motion=quiet?(p.musicalPhoto.songProfile.mode==='drift'?.22:.5):(.7+stage*.16)*(g.climaxLevel?g.climaxLevel:1);
  g.grade=quiet?'color':g.climaxLevel?(g.climaxLevel<.81?'blue':'silhouette'):field==='graphic'||field==='negative'?'mono':meaning==='pride'?'color':meaning==='rage'?'blue':null;
  c.params.photoAnchor=field==='negative'?{x:g.side?.38:.62,y:.53}:field==='band'?{x:.5,y:.74}:field==='window'?{x:.5,y:.76}:field==='asymmetric'&&p.W>p.H?{x:g.side?.67:.33,y:.58}:{x:.5,y:field==='graphic'?.56:.51};
 }
 f.architecture={version:1,seed:candidate.seed,candidate:candidate.id,opening:candidate.opening,quiet,foregroundTypes:safeLayers,policy:'Content-seeded alternatives; music-conditioned structure; raster selection; source count unchanged'};sync(p);return p;
};
const build=J.buildPhotoStory;J.buildPhotoStory=p=>{p=build(p)||p;if(active(p))J.applyCinemaArchitecture(p,J.cinemaArchitectureCandidates(p)[0]);return p;};
const repair=J.repairPhotoBottlenecks;J.repairPhotoBottlenecks=(p,...args)=>{const r=repair(p,...args);if(active(p)){delete p.musicalPhoto.cinema.architectureSearch;J.applyCinemaArchitecture(p,J.cinemaArchitectureCandidates(p)[Math.min(11,Number(args[1])||1)]);}return r;};
const social=J.createSocialHookPlan;J.createSocialHookPlan=(...args)=>{const p=social(...args);if(active(p)){delete p.musicalPhoto.cinema.architectureSearch;J.applyCinemaArchitecture(p,J.cinemaArchitectureCandidates(p)[0]);}return p;};
J.cinemaFieldBoxes=(p,g)=>{const W=p.W,H=p.H,portrait=H>W,side=g.side;switch(g.field){
 case 'negative':return [{x:side?W*.64:0,y:H*.08,w:W*.36,h:H*.84,id:'HERO'}];
 case 'asymmetric':return portrait?[{x:0,y:0,w:W,h:H*.50,id:'HERO'}]:[{x:side?0:W*.5,y:0,w:W*.5,h:H,id:'HERO'}];
 case 'window':return [{x:W*.12,y:H*.07,w:W*.76,h:H*.52,id:'WIDE'}];
 case 'band':return [{x:0,y:H*.07,w:W,h:H*.45,id:'CROWD'}];
 case 'graphic':return [{x:W*.09,y:H*.08,w:W*.82,h:H*.84,id:'WIDE'}];
 case 'arena':return [{x:0,y:0,w:W,h:H,id:'WIDE'}];
 case 'hero':return [{x:0,y:0,w:W,h:H,id:'HERO'}];
 default:return null;}};
J.paintCinemaGrammarForeground=function(ctx,p,c,t){const g=c.grammar;if(!g?.safeDerived||!safeLayers.includes(g.derivedLayer)||this?.cinemaNeutralLayers)return false;const W=p.W,H=p.H,u=C((t-c.start)/Math.max(.1,c.dur)),accent=p.style?.schemes?.[0]?.accent||'#72bfff';ctx.save();ctx.strokeStyle=accent;ctx.fillStyle=accent;ctx.lineWidth=H*.006*(g.layerWidth||1);ctx.globalAlpha=Math.min(.88,(.68+.12*(g.climaxLevel||0))*(g.layerStrength||1));
 if(g.derivedLayer==='frame'){const pad=H*.025;for(const b of J.cinemaFieldBoxes(p,g,t)||[])ctx.strokeRect(b.x-pad,b.y-pad,b.w+pad*2,b.h+pad*2);}
 if(g.derivedLayer==='rails'){for(let i=0;i<4;i++){const y=H*(.10+i*.055),reach=W*(.1+.055*i+.02*u);ctx.fillRect(0,y,reach,H*.008);ctx.fillRect(W-reach,H-y,reach,H*.008);}}
 if(g.derivedLayer==='grid'){const x0=g.side?W*.52:0,x1=g.side?W:W*.48;ctx.lineWidth=H*.005*(g.layerWidth||1);for(let x=x0;x<x1;x+=H*.12){ctx.beginPath();ctx.moveTo(x,H*.12);ctx.lineTo(x,H*.9);ctx.stroke();}for(let y=H*.12;y<H*.9;y+=H*.12){ctx.beginPath();ctx.moveTo(x0,y);ctx.lineTo(x1,y);ctx.stroke();}}
 if(g.derivedLayer==='contour'&&this?.customBgBitmap){const edge=J.blueprintContour.call(this,this.customBgBitmap);ctx.globalAlpha=.26*(g.layerStrength||1);for(const v of this.cinemaGrammarViews||[])J.drawCinemaSourceTile(ctx,edge,v.box,v.focus,t,v.amount);}
 ctx.restore();return true;};
const draw=J.drawCinemaGrammar;J.drawCinemaGrammar=function(ctx,p,t){const result=draw.call(this,ctx,p,t),c=J.cutAt(p,t);if(result&&c?.grammar?.architectureVersion&&!this.cinemaNeutralLayers)J.paintCinemaGrammarForeground.call(this,ctx,p,c,t);return result;};
// Architecture changes actual reading regions, not just shot identifiers.
for(const [id,layout] of Object.entries(J.LAYOUTS))if(id.startsWith('cinemaGrammar')){const original=layout.render;layout.render=function(env){const g=env.cut.grammar;if(!g?.architectureVersion)return original(env);const {W,H,cut}=env,source=String(cut.lineText||cut.text),units=J.vocaliseUnits(source),stage=g.stage;let text=J.composeLyricPhrase(source);if(stage)text=units.join(stage===2&&W>H?' ':'\n');const field=g.field,width=W*(field==='asymmetric'&&W>H?.46:field==='negative'?.62:.76),height=H*(['window','band'].includes(field)?.30:stage?.56:.43),font=cut.params.font||'embedded_bold',lead=stage?1.12:1.24,size=Math.min(H*(H>W?.102:stage?.17:.16),J.fitSize(text,font,width,height,{lead,track:.015}));return J.mainDraw(env,{text,font,size,x:W/2,y:H/2,lead,track:.015,color:'#fff',noHold:true,cinemaMotion:'read',grammarMode:g.mode,enter:cut.enter,exit:cut.exit});};}
const type=J.applyTypography5;J.applyTypography5=(env,it)=>{type(env,it);const g=env.cut.grammar;if(!g?.architectureVersion||!it.grammarMode||env.plan.cinemaSemanticNeutral)return;const u=C(env.lt/Math.max(.1,env.cut.dur)),force=g.quiet?.35:1,stage=g.stage;
 if(stage)it.charFns.push((i,glyph)=>{const row=glyph.li||0;return g.phraseMotion==='response'?{dx:(row%2?1:-1)*env.W*.017*Math.sin(u*Math.PI*2)*force}:g.phraseMotion==='wave'?{dy:env.H*.012*Math.sin(u*Math.PI*2-row*.7)*force}:g.phraseMotion==='crowd'?{s:1+.045*ease(u)*force,dy:env.H*.012*Math.sin(u*Math.PI-row*.4)*force}:{};});
};
const center=J.centerPhotoLyricItem;J.centerPhotoLyricItem=(env,it)=>{const g=env.cut.grammar;if(!g?.architectureVersion||locked(env.plan,env.cut))return center(env,it);const old=env.cut.params.photoAnchor,end=env.range?.end??env.plan.duration,from=Math.max(end-.65,env.cut.start+env.cut.dur*.55),u=ease((env.t-from)/Math.max(1/env.plan.fps,end-from));if(u){const anchor=old||{x:.5,y:.5};env.cut.params.photoAnchor={x:J.lerp(anchor.x,.36,u),y:J.lerp(anchor.y,.23,u)};it.size*=J.lerp(1,.52,u);it._lay=it._m=null;}try{return center(env,it);}finally{env.cut.params.photoAnchor=old;}};
// All twelve alternatives are production renders; no ID diversity bonus.
const oldRepair=J.repairCinemaSequence;J.repairCinemaSequence=async(p,range,telemetry={})=>{if(!active(p)||!p.musicalPhoto.cinema.architecture)return oldRepair(p,range,telemetry);const cuts=p.cuts.filter(c=>c.grammar&&!locked(p,c)),save=()=>({cuts:cuts.map(c=>({grammar:{...c.grammar},params:{...c.params}})),architecture:{...p.musicalPhoto.cinema.architecture}}),restore=s=>{cuts.forEach((c,i)=>{c.grammar={...s.cuts[i].grammar};c.params={...s.cuts[i].params};});p.musicalPhoto.cinema.architecture={...s.architecture};};let best=await J.measureCinemaSequence(p,range),initial=best.rank,chosen=save();const baseline=save(),attempts=[],signatures=[];
 if(!p.musicalPhoto.cinema.architectureSearch)for(const candidate of J.cinemaArchitectureCandidates(p)){restore(baseline);J.applyCinemaArchitecture(p,candidate);telemetry.onProgress?.({label:'曲固有の構図候補を実描画で比較中 '+(candidate.id+1)+'/12'});const probe=await J.measureCinemaSequence(p,range),sig=probe.samples.flatMap(s=>s.signature),duplicate=signatures.some(v=>v.length===sig.length&&v.reduce((sum,x,i)=>sum+Math.abs(x-sig[i]),0)/Math.max(1,sig.length)<.012);signatures.push(sig);attempts.push({candidate:candidate.id,rank:probe.rank,duplicate,rejectedUnreadable:probe.samples.some(s=>!s.safe)});if(!duplicate&&probe.rank>best.rank){best=probe;chosen=save();}await new Promise(r=>setTimeout(r,0));}
 restore(chosen);sync(p);p.musicalPhoto.cinema.architectureSearch={count:12,attempts,initialRank:initial,selectedRank:best.rank,selectedCandidate:chosen.architecture.candidate,minimumRasterDistance:.012,scoreThresholdsChanged:false};p.musicalPhoto.cinema.feedback={method:'12 content-seeded composition arcs; full production glyph safety and pixel distance; perceptually close candidates rejected; best baseline retained',attempts,initialRank:initial,selectedRank:best.rank,scoreThresholdsChanged:false};return best;};
const foreground=J.measureArtworkForeground;J.measureArtworkForeground=async(p,...args)=>{const r=await foreground(p,...args);if(active(p)&&r){r.usedDerivedLayerCount=p.cuts.filter(c=>c.grammar?.safeDerived).length;r.note='Whole-image contour and authored geometric layers; source region count remains zero. Novelty is measured from masks, not layer labels.';}return r;};
const openingBackground=J.Renderer.prototype.drawCustomBackground;J.Renderer.prototype.drawCustomBackground=function(ctx,p,t,...args){const result=openingBackground.call(this,ctx,p,t,...args),a=p.musicalPhoto?.cinema?.architecture;if(!a||!this.customBgBitmap||t>=Math.min(.85,p.musicalPhoto.cinema.introEnd)||locked(p,J.cutAt(p,t)))return result;const u=ease(t/(a.quiet?1.4:.85)),W=p.W,H=p.H;ctx.save();if(a.opening===0){ctx.globalAlpha=(1-u)*.74;ctx.fillStyle='#071321';ctx.fillRect(0,0,W,H);ctx.globalAlpha=(1-u)*.55;ctx.drawImage(J.blueprintContour.call(this,this.customBgBitmap),0,0,W,H);}else if(a.opening===1){const shade=ctx.createRadialGradient(W*.5,H*.5,H*(.12+.6*u),W*.5,H*.5,W);shade.addColorStop(0,'rgba(2,8,20,0)');shade.addColorStop(1,'rgba(2,8,20,'+(.70*(1-u))+')');ctx.fillStyle=shade;ctx.fillRect(0,0,W,H);}else{ctx.globalAlpha=(1-u)*.85;J.drawCinemaSourceTile(ctx,this.customBgBitmap,{x:0,y:0,w:W,h:H},{x:.5,y:.45,zoom:1.65-.5*u,start:0,duration:1},t,0);}ctx.restore();return result;};
const context=J.directorContext;J.directorContext=(...args)=>({...context(...args),compositionSearch:args[1].musicalPhoto?.cinema?.architectureSearch||null,compositionArchitecture:args[1].musicalPhoto?.cinema?.architecture||null});
})();
