/* Climax alternatives are selected by production pixels, never by style IDs. */
(()=>{'use strict';const J=window.J,C=J.clamp,locked=(p,c)=>J.photoChoreographyLocked(p,c),active=p=>!!p.musicalPhoto?.cinema?.architecture;
const hash=s=>{let n=2166136261;for(const ch of String(s))n=Math.imul(n^ch.charCodeAt(0),16777619);return n>>>0;};
const arcs={expansion:['hero','band','asymmetric','arena'],depth:['hero','negative','graphic','arena'],unison:['hero','split','band','arena'],typeField:['hero','asymmetric','negative','hero']};
const candidates=J.cinemaArchitectureCandidates;J.cinemaArchitectureCandidates=p=>candidates(p).map(c=>{const crowd=p.cuts.some(x=>x.story?.group),attack=p.musicalPhoto.songProfile.attack??.5,pool=crowd?['unison','expansion','typeField','depth']:attack>.6?['depth','typeField','expansion']:['expansion','depth'];return {...c,climaxArchetype:pool[(hash(c.seed+':climax')+c.id)%pool.length]};});
const apply=J.applyCinemaArchitecture;J.applyCinemaArchitecture=(p,candidate)=>{apply(p,candidate);if(!active(p))return p;const all=p.cuts.filter(c=>c.grammar&&!locked(p,c)),peak=all.filter(c=>c.grammar.temporal?.climax),archetype=candidate.climaxArchetype||'expansion';let uiRun=0;
 for(const c of all){const g=c.grammar,i=peak.indexOf(c);if(i>=0){const phase=Math.min(3,Math.floor(i/Math.max(1,peak.length-1)*3));g.climaxArchetype=archetype;g.climaxStep=phase;g.field=arcs[archetype][phase];g.grade=phase===0?'blue':phase===1?'mono':phase===2?'blue':'silhouette';g.derivedLayer=phase===3?'contour':null;g.safeDerived=!!g.derivedLayer;g.foregroundLayers=g.safeDerived?1:0;c.params.photoAnchor=g.field==='negative'?{x:g.side?.30:.70,y:.55}:g.field==='asymmetric'?{x:g.side?.72:.28,y:.55}:g.field==='band'?{x:.5,y:.76}:{x:.5,y:.5};}
  const hud=['frame','grid','rails'].includes(g.derivedLayer)||c.decor?.some(d=>d.id==='cinemaBlueprint');uiRun=hud?uiRun+1:0;g.suppressBlueprint=i>=0||uiRun>=3;if(g.suppressBlueprint&&['frame','grid','rails'].includes(g.derivedLayer)){g.derivedLayer=null;g.safeDerived=false;g.foregroundLayers=0;uiRun=0;}if(g.layerRepair){g.layerStrength=g.layerRepair.strength;g.layerWidth=g.layerRepair.width;}
 }
 p.musicalPhoto.cinema.architecture.climaxArchetype=archetype;p.musicalPhoto.cinema.grammar.shots=all.map(c=>({line:c.line,from:c.start,to:c.end,...c.grammar}));for(const s of p.storyboard||[]){const c=all.find(c=>c.start===s.from);if(c)s.shotGrammar={...c.grammar};}return p;};
// Blueprint remains a selected visual language, but its grid is not a permanent UI.
for(const [id,layout]of Object.entries(J.LAYOUTS))if(id.startsWith('cinemaGrammar')){const original=layout.render;layout.render=env=>{const {cut,W,H}=env,g=cut.grammar;if(!g?.temporal?.climax||!g.stage||locked(env.plan,cut))return original(env);const source=String(cut.lineText||cut.text),chars=Array.from(source),side=['negative','asymmetric'].includes(g.field),rows=side?3:g.climaxStep===2?3:2,parts=Array.from({length:rows},(_,i)=>chars.slice(Math.ceil(chars.length*i/rows),Math.ceil(chars.length*(i+1)/rows)).join('')).join('\n'),font=cut.params.font||'embedded_bold',width=W*(side&&W>H?.43:.84),height=H*(g.field==='band'?.30:.64),size=Math.min(H*(W>H?.185:.105),J.fitSize(parts,font,width,height,{lead:1.12,track:.015}));return J.mainDraw(env,{text:parts,font,size,x:W/2,y:H/2,lead:1.12,track:.015,color:'#fff',noHold:true,grammarMode:g.mode,cinemaMotion:'read',enter:cut.enter,exit:cut.exit});};}
const distance=(a,b)=>a.reduce((v,x,i)=>v+Math.abs(x-b[i]),0)/Math.max(1,a.length),measure=J.measureCinemaSequence;
J.measureCinemaSequence=async(...args)=>{const r=await measure(...args),p=args[0];if(!active(p)||r.samples.some(s=>!s.safe))return r;const peak=r.samples.filter(s=>p.cuts.find(c=>c.line===s.line)?.grammar?.temporal?.climax),before=r.samples.filter(s=>s.from<(peak[0]?.from??0)).slice(-2),reference=before.at(-1),distances=peak.map(s=>({line:s.line,fromBuild:reference?distance(s.signature,reference.signature):null,adjacent:s.compositionDistance})),minimum=peak.length>1?Math.min(...peak.slice(1).map(s=>s.compositionDistance??0)):0;
 r.climaxEvidence={source:'production raster; not human impact or final encoded evidence',archetype:p.musicalPhoto.cinema.architecture.climaxArchetype,distances,minimumAdjacentDistance:minimum};if(peak.length>1)r.rank+=minimum*.35;const primary=r.samples.slice(1).map((s,i)=>distance(s.primarySignature,r.samples[i].primarySignature));r.primaryRasterDistance=primary;r.rank+=(primary.length?primary.reduce((a,b)=>a+b,0)/primary.length:0)*.20;return r;};
const decoded=J.measureDecodedCinemaFrames;J.measureDecodedCinemaFrames=(...args)=>{const d=decoded(...args),p=args[1];if(!d.completed||!active(p))return d;const peak=d.samples.filter(s=>p.cuts.find(c=>c.line===s.line)?.grammar?.temporal?.climax),before=d.samples.filter(s=>s.from<(peak[0]?.from??0)).slice(-3),mean=a=>a.length?a.reduce((v,x)=>v+x,0)/a.length:null,base=mean(before.map(s=>s.compositionDistance).filter(Number.isFinite)),value=mean(peak.map(s=>s.compositionDistance).filter(Number.isFinite));d.climaxEvidence={source:'decoded final MP4 luminance layout; camera and text not separated',archetype:p.musicalPhoto.cinema.architecture.climaxArchetype,buildDistance:base,climaxDistance:value,weak:peak.length>1&&base!=null&&value<base*.65};return d;};
const reconcile=J.reconcileDecodedCinemaQuality;J.reconcileDecodedCinemaQuality=(r,d)=>{r.issues=r.issues.filter(i=>i.code!=='ENCODED_CLIMAX_TOO_SIMILAR');reconcile(r,d);if(d?.climaxEvidence?.weak){r.issues.push({code:'ENCODED_CLIMAX_TOO_SIMILAR',severity:'ERROR',category:'creative',exportBlocking:false,message:'最終MP4の終盤構図差が直前の展開より弱いため、クライマックス再選定が必要です',evidence:d.climaxEvidence});r.quality.certified100=false;r.errors=r.issues.filter(i=>i.severity==='ERROR');r.quality.hardGates={...r.quality.hardGates,total:r.errors.length,passed:false};}return r;};
// A missing encoded layer changes the renderer on the next bounded retry.
const repair=J.repairPhotoBottlenecks;J.repairPhotoBottlenecks=(p,...args)=>{const d=p.lastPixelQA?.metrics?.decodedCinema,missing=d?.layerPresence?.samples?.filter(s=>!s.visible)||[],result=repair(p,...args);if(!active(p))return result;for(const s of missing){const c=p.cuts.find(c=>c.line===s.line);if(!c?.grammar?.safeDerived||locked(p,c))continue;c.grammar.layerRepair={strength:Math.min(2,(c.grammar.layerStrength||1)*1.4),width:Math.min(2,(c.grammar.layerWidth||1)*1.35),source:'decoded ON/OFF layer counterfactual'};c.grammar.layerStrength=c.grammar.layerRepair.strength;c.grammar.layerWidth=c.grammar.layerRepair.width;result.push('encoded-layer-render-repair:'+s.line);}return result;};
})();
