/* Input-conditioned production raster feedback. Scores are never repaired. */
(()=>{'use strict';const J=window.J,C=J.clamp,active=p=>!!p.musicalPhoto?.cinema,locked=(p,c)=>!!c&&J.photoChoreographyLocked(p,c);
const difference=(a,b)=>{let total=0;for(let i=0;i<a.length;i+=4)total+=(Math.abs(a[i]-b[i])+Math.abs(a[i+1]-b[i+1])+Math.abs(a[i+2]-b[i+2]))/765;return total/(a.length/4);};
const maskDifference=(a,b)=>{let total=0;for(let i=3;i<a.length;i+=4)total+=Math.abs(a[i]-b[i])/255;return total/(a.length/4);};
const signature=(bytes,w,h)=>{const v=Array(144).fill(0),n=Array(144).fill(0);for(let y=0;y<h;y++)for(let x=0;x<w;x++){const j=Math.min(7,Math.floor(y/h*8))*18+Math.min(17,Math.floor(x/w*18)),i=(y*w+x)*4;v[j]+=(bytes[i]*.2126+bytes[i+1]*.7152+bytes[i+2]*.0722)/255;n[j]++;}return v.map((x,i)=>x/Math.max(1,n[i]));};
const distance=(a,b)=>a.reduce((v,x,i)=>v+Math.abs(x-b[i]),0)/a.length;
J.measureCinemaSequence=async(p,range=null,options={})=>{
 const R=new J.Renderer(),w=128,h=Math.max(48,Math.round(w*p.H/p.W)),cv=document.createElement('canvas'),mc=document.createElement('canvas');cv.width=mc.width=w;cv.height=mc.height=h;const x=cv.getContext('2d'),mx=mc.getContext('2d'),start=range?.start??0,end=range?.end??p.duration;
 const frame=(t,neutral=false,layerOnly=false)=>{p.cinemaSemanticNeutral=neutral;R.cinemaNeutralLayers=neutral||layerOnly;const items=[],records=[],draw=J.drawItem;J.drawItem=(env,it)=>{if(env.pass==='main'&&env.ctx===x&&env.cut.line>=0){records.push({line:env.cut.line,text:J.layoutText(it).filter(g=>{const v=it.charFn?.(g.i,g);return !v?.hide&&(it.alpha??1)*(v?.a??1)>=.55;}).map(g=>it.charFn?.(g.i,g)?.ch||g.ch).join('').replace(/\s/g,''),readable:J.selectionGlyphEvidence(env,it).readable,glyphEvidence:J.selectionGlyphEvidence(env,it)});}return draw(env,it);};try{R.frame(x,p,t,{scale:w/p.W,production:true,noHud:false,range,lyricAuditCtx:mx,lyricAuditItems:items});return {bytes:x.getImageData(0,0,w,h).data,mask:mx.getImageData(0,0,w,h).data,items,records};}finally{J.drawItem=draw;p.cinemaSemanticNeutral=false;R.cinemaNeutralLayers=false;}};
 try{await R.loadCustomBackground(p.customBg.dataUrl);await R.loadAssetDeck?.(p);const samples=[],intent=[];let previous=null,stagnationStart=start;
 for(const c of p.cuts.filter(c=>c.grammar&&!locked(p,c)&&c.end>start&&c.start<end&&(!options.lines||options.lines.includes(c.line)))){
  const ts=[.12,.4,.72].map(u=>Math.min(end-1/p.fps,Math.max(start,c.start+c.dur*u))),frames=ts.map(t=>frame(t)),sig=signature(frames[1].bytes,w,h),delta=previous?distance(sig,previous):null,energy=(difference(frames[0].bytes,frames[1].bytes)+difference(frames[1].bytes,frames[2].bytes))/2;
  if(delta>.035)stagnationStart=c.start;const stagnant=c.end-stagnationStart>8,neutral=frame(ts[0],true),textChange=maskDifference(frames[0].mask,neutral.mask),motionVisible=energy>.003;
  const audioEnergy=p.musicalStructure?.sections.find(s=>c.start>=s.from&&c.start<s.to)?.energy??p.musicalPhoto.songProfile.energy,expected=(c.cinema.quiet||c.grammar.quiet)?'quiet':c.grammar.stage?'escalate':c.cinema.meaning==='rage'?'rush':'move',energyGap=expected==='quiet'?0:Math.max(0,.004+.022*C(audioEnergy)-energy);
  const safe=frames.every(f=>f.records.length&&f.records.every(r=>r.readable)&&f.records.map(r=>r.text).join('')===String(c.lineText).replace(/\s/g,''));
  samples.push({safe,readabilityFailures:frames.flatMap((f,i)=>f.records.filter(r=>!r.readable).map(r=>({time:ts[i],...r.glyphEvidence}))),line:c.line,from:c.start,to:c.end,energy,compositionDistance:delta,stagnant,energyGap,expected,audioEnergy,targetMotion:expected==='quiet'?0:.004+.022*C(audioEnergy),layerEvidence:c.grammar.safeDerived?{...J.cinemaLayerPixelEvidence(frames[1].bytes,frame(ts[1],false,true).bytes),kind:c.grammar.derivedLayer}:null,signature:sig,primarySignature:signature(Uint8ClampedArray.from(frames[1].mask,(v,i)=>i%4===3?255:frames[1].mask[i-i%4+3]),w,h)});
  intent.push({line:c.line,meaning:c.cinema.meaning,grammar:c.grammar.mode,required:expected!=='quiet',fullFrameMotion:energy,typographyCounterfactual:textChange,visible:motionVisible&&(textChange>.001||['ground','solo','openSky'].includes(c.grammar.mode)),source:'same production renderer vs semantic character motion disabled; background-layer neutral control; no linguistic understanding claim'});previous=sig;
 }
 const hookTimes=[start,...[.5,1.5,2.7].map(d=>Math.min(end-1/p.fps,start+d))],hooks=hookTimes.map(t=>frame(t)),hookChanges=hooks.slice(1).map((f,i)=>difference(hooks[i].bytes,f.bytes));
 const sequences=new Map();for(const c of p.cuts.filter(c=>c.story?.group&&c.grammar)){const k=c.story.group;sequences.set(k,[...(sequences.get(k)||[]),c.grammar.mode]);}const repeatedSequences=[...sequences.values()].map(s=>s.join('>')),windows=[];for(const sequence of sequences.values())for(let i=0;i+4<=sequence.length;i+=4)windows.push(sequence.slice(i,i+4).join('>'));const templateRepeats=Math.max(repeatedSequences.length-new Set(repeatedSequences).size,windows.length-new Set(windows).size);
 const rank=samples.length?Math.min(...samples.filter(s=>s.compositionDistance!=null).map(s=>s.compositionDistance).concat([1]))-samples.reduce((v,s)=>v+s.energyGap+(s.stagnant?.1:0),0)/samples.length:0;
 return {status:'PRODUCTION_RASTER_SAMPLES',resolution:[w,h],samples,intent,hook:{times:hookTimes,changes:hookChanges,weak:hookChanges.some(v=>v<.012)},templateAudit:{sequences:repeatedSequences,fourPhraseWindows:windows,repeats:templateRepeats,source:'actual rendered grammar sequence; geometric differences alone do not certify novelty'},rank:samples.some(s=>!s.safe)?-100:rank+Math.min(...hookChanges)*.15-templateRepeats*.1,limits:'Sparse pre-encode RGB and alpha samples; not decoded MP4, optical flow, human meaning, audience rating or proof of artistic novelty'};
 }finally{p.cinemaSemanticNeutral=false;R.disposeAssets?.();cv.width=cv.height=mc.width=mc.height=1;}
};
J.repairCinemaSequence=async(p,range=null,telemetry={})=>{
 if(!active(p))return null;let measured=await J.measureCinemaSequence(p,range),best=measured;const attempts=[],cuts=p.cuts.filter(c=>c.grammar&&!locked(p,c)),save=()=>cuts.map(c=>({grammar:{...c.grammar},params:{...c.params},layout:c.layout})),restore=s=>cuts.forEach((c,i)=>{c.grammar={...s[i].grammar};c.params={...s[i].params};c.layout=s[i].layout;}),initial=save(),initialHook=p.musicalPhoto.cinema.hookRepair||0;let chosen=initial,selectedAttempt=0;
 // Two bounded production variants; rejected raster states are restored exactly.
 const weak=measured.samples.filter(s=>s.stagnant||s.energyGap>0||s.compositionDistance!=null&&s.compositionDistance<.035).map(s=>s.line);
 if(!weak.length)weak.push(...cuts.filter(c=>c.grammar.stage||c.cinema.meaning==='read').map(c=>c.line));
 if(weak.length||measured.hook.weak||cuts.length>=3)for(let attempt=1;attempt<=2;attempt++){
  restore(initial);for(const c of cuts)if(weak.includes(c.line)){c.grammar.repair=attempt;c.grammar.motion*=1+attempt*.2;if(c.grammar.stage===3){c.grammar.mode=attempt===1?'gather':'stands';c.layout='cinemaGrammar'+c.grammar.mode;}else if(c.grammar.stage===2&&attempt===2){c.grammar.mode='gather';c.layout='cinemaGrammar'+c.grammar.mode;}if(c.grammar.mode==='solo'&&c.cinema.meaning==='read'){c.grammar.mode=attempt===1?'voice':'openSky';c.params.photoAnchor={x:attempt===1?.63:.5,y:attempt===1?.5:.3};c.layout='cinemaGrammar'+c.grammar.mode;}}
  if(measured.hook.weak)p.musicalPhoto.cinema.hookRepair=attempt;
  telemetry.onProgress?.({label:'似た画面と動作不足を実描画で比較・修復しています'});const probe=await J.measureCinemaSequence(p,range);attempts.push({attempt,rank:probe.rank,weakWindows:probe.samples.filter(s=>s.stagnant).map(s=>s.line)});if(probe.rank>best.rank){best=probe;selectedAttempt=attempt;chosen=save();chosen.forEach((s,i)=>s.layout=cuts[i].layout);}await new Promise(r=>setTimeout(r,0));
 }
 restore(chosen);cuts.forEach((c,i)=>{c.layout=chosen[i].layout||'cinemaGrammar'+c.grammar.mode;c.architecture=c.layout;});p.musicalPhoto.cinema.hookRepair=measured.hook.weak?selectedAttempt:initialHook;
 if(p.musicalPhoto.cinema.grammar)p.musicalPhoto.cinema.grammar.shots=p.cuts.filter(c=>c.grammar).map(c=>({line:c.line,from:c.start,to:c.end,...c.grammar}));for(const s of p.storyboard||[]){const c=p.cuts.find(c=>c.grammar&&c.start===s.from);if(c&&!s.locked){s.shotGrammar={...c.grammar};s.sceneIntent=c.grammar.mode;}}
 p.musicalPhoto.cinema.feedback={method:'two bounded same-source raster repairs; minimum adjacent luminance-layout distance minus energy deficit and >8s stagnation; best state retained',attempts,initialRank:measured.rank,selectedRank:best.rank,scoreThresholdsChanged:false};return best;
};
const compare=J.compareRegistryCandidates;J.compareRegistryCandidates=(project,...args)=>{const preset=project.exportSettings?.preset||'auto';if(preset!=='auto')return compare(project,...args);const p=J.clonePhotoRenderPlan(project);p.res=Math.max(1080,p.res||1080);if(p.exportSettings?.fpsMode!=='manual')p.fps=30;return compare(p,...args);};
const analyze=J.analyzeRenderedFrames;J.analyzeRenderedFrames=async(p,range,audio,telemetry={})=>{
 const feedback=active(p)?await J.repairCinemaSequence(p,range,telemetry):null,r=await analyze(p,range,audio,telemetry);if(r.completed&&feedback){r.metrics.cinemaFeedback=feedback;p.lastPixelQA=r;}return r;
};
// Intro is a distinct image treatment on energetic tracks, a slow reveal on calm tracks.
const bg=J.Renderer.prototype.drawCustomBackground;J.Renderer.prototype.drawCustomBackground=function(ctx,p,t,...args){const result=bg.call(this,ctx,p,t,...args);if(!active(p)||locked(p,J.cutAt(p,t))||this._grammarOpening||t>=p.musicalPhoto.cinema.introEnd||!this.customBgBitmap)return result;const f=p.musicalPhoto.cinema,profile=p.musicalPhoto.songProfile;if(!profile||profile.energy<.4)return result;const cue=f.hook[1]?.time??.5,u=(t-cue)/.28;if(u<0||u>1)return result;ctx.save();ctx.globalAlpha=Math.sin(u*Math.PI)*(.24+.08*(f.hookRepair||0));ctx.globalCompositeOperation='screen';ctx.strokeStyle=p.style?.schemes?.[0]?.accent||'#60aaff';ctx.lineWidth=p.H*.013;const radius=p.H*(.08+.8*u);ctx.beginPath();ctx.arc(p.W*.5,p.H*.5,radius,0,Math.PI*2);ctx.stroke();ctx.restore();return result;};
// Shrink the final lyric into a compact, readable resolution without showing title over it.
const type=J.applyTypography5;J.applyTypography5=(env,it)=>{type(env,it);if(!active(env.plan)||!it.grammarMode||locked(env.plan,env.cut))return;const p=env.plan,f=p.musicalPhoto.cinema,end=env.range?.end??p.duration,from=Math.max(end-.45,env.cut.start+Math.min(.8,env.cut.dur*.5)),u=C((env.t-from)/Math.max(1/p.fps,end-from));if(u&&env.cut.line>=0)it.charFns.push(()=>({s:1-.52*u*u*(3-2*u)}));};
const quality=J.checkMVQuality;J.checkMVQuality=(...args)=>{const r=quality(...args),p=args[1],q=r.quality;if(!active(p))return r;const m=q.metrics||{},d=q.productionDomains||{},feedback=args[4]?.metrics?.cinemaFeedback;
 q.renderFeedback=feedback||null;
 const weak=!Number.isFinite(m.perceptualNovelty)||m.perceptualNovelty<80||!Number.isFinite(m.temporalContrast)||m.temporalContrast<80;
 if(weak){for(const k of ['visualWorld','audienceImpact'])if(Number.isFinite(d[k]))d[k]=Math.min(89,d[k]);q.visualWorldScore=Math.min(89,q.visualWorldScore??89);q.audienceImpact={...q.audienceImpact,score:Math.min(89,q.audienceImpact?.score??89),artisticQualityMeasured:false};q.certified100=q.perfectEligible=false;}
 const actualDuration=(args[3]?.end??p.duration)-(args[3]?.start??0),short=!!p.socialHook&&p.H>p.W&&actualDuration>=12&&actualDuration<=15;
 q.socialScope={scope:short?'dedicated-short':'full-mv',aspect:p.W+':'+p.H,duration:actualDuration,shortMeasured:short&&args[4]?.completed===true,shortScore:short?q.socialScore:null,fullMVScore:short?null:q.socialScore,reason:short?'Separate portrait re-edit rendered and measured':'Full MV measurement only; no Short certification inferred'};
 if(!short&&Number.isFinite(d.social))d.social=q.socialScore;
 // Overall loop reports both image and text seam, never the background score alone.
 const loop=args[4]?.metrics?.singleImageCinema?.loop;if(loop){const seam=loop.fullFrameChannels?.text??0;q.loopComponents={background:loop.visualScore,textSeam:seam,audio:loop.audio?.score??null,policy:'final lyric contracts; title exchanged at boundary'};const score=Math.round(100*C(Math.min(loop.score??89,100-seam*260)/100));if(Number.isFinite(q.metrics.loopQuality))q.metrics.loopQuality=Math.min(q.metrics.loopQuality,score);}
 if(feedback?.intent.some(s=>s.required&&!s.visible)&&!r.issues.some(i=>i.code==='DIRECTION_NOT_REALIZED'))r.issues.push({code:'DIRECTION_NOT_REALIZED',severity:'ERROR',category:'creative',exportBlocking:false,message:'指定した文字・画像の動作が実描画で十分に観測できません',lines:feedback.intent.filter(s=>s.required&&!s.visible).map(s=>s.line)});
 if(feedback?.samples.some(s=>s.stagnant)&&!r.issues.some(i=>i.code==='NON_CROP_STAGNATION'))r.issues.push({code:'NON_CROP_STAGNATION',severity:'ERROR',category:'creative',exportBlocking:false,message:'修復後にも8秒超の似た実描画構図が残っています'});
 const preset=args[0]?.exportSettings?.preset;if(['xHigh','vertical','youtube1080'].includes(preset)&&Math.min(p.W,p.H)<1080)r.issues.push({code:'EXPORT_PROFILE_RESOLUTION',severity:'ERROR',category:'technical',exportBlocking:true,message:'1080pプリセットに対して実出力解像度が不足しています'});
 r.errors=r.issues.filter(i=>i.severity==='ERROR');r.warnings=r.issues.filter(i=>i.severity==='WARNING');q.targetAcceptance=J.evaluateQualityTarget(r);return J.finalizeExportReadiness(r);
};
const loopQuality=J.loopQuality;J.loopQuality=(p,...args)=>{const result=loopQuality(p,...args),loop=p.lastPixelQA?.metrics?.singleImageCinema?.loop;if(!active(p)||!loop)return result;const textPenalty=(loop.fullFrameChannels?.text||0)*2.6;return {...result,score:C(Math.min(result.score,1-textPenalty)),textSeamMeasured:true,backgroundScore:loop.visualScore,measurement:'production background + full-frame text occupancy seam + audio endpoints; not perfect musical continuity'};};
const preset=J.applyExportPreset;J.applyExportPreset=(p,key)=>{const result=preset(p,key);if(key==='auto'){p.res=1080;p.fps=30;p.exportSettings.fpsMode='auto';}return result;};
const context=J.directorContext;J.directorContext=(...args)=>{const result=context(...args),p=args[1];return {...result,socialTarget:{...result.socialTarget,appliesTo:'separately rendered portrait re-edit',fullMVIsShort:false},songGrammar:p.musicalPhoto?.cinema?.songGrammar||null,renderFeedback:p.musicalPhoto?.cinema?.feedback||null};};
const provenance=J.createExportProvenance;J.createExportProvenance=async(...args)=>({...await provenance(...args),socialScope:args[2].quality.socialScope||null,renderFeedback:args[2].quality.renderFeedback||null,loopComponents:args[2].quality.loopComponents||null});
// Automatic single-artwork export uses 30fps; explicit 60fps remains an authored choice.
const fps=J.chooseAdaptiveFPS;J.chooseAdaptiveFPS=(p,...args)=>p.customBg?.enabled&&p.exportSettings?.fpsMode==='auto'?{fps:30,reason:'single artwork lyric MV: 30fps delivery',capabilityVerified:false}:fps(p,...args);
})();
