/* Editorial shot grammar from the supplied artwork. No new imagery or object-recognition claims. */
(()=>{'use strict';const J=window.J,C=J.clamp,active=p=>!!p.musicalPhoto?.cinema,locked=(p,c)=>!!c&&J.photoChoreographyLocked(p,c),ease=u=>{u=C(u);return u*u*(3-2*u);};
const modes={gather:'gather',hero:'duo',pride:'openSky',rage:'fracture',call:'voice',unity:'ground',read:'solo'},names={solo:'個の視点',duo:'二つの視点',stands:'スタンドの多面構成',stadium:'全景と前景の合流',gather:'周囲から集う',openSky:'上方向へ開く',fracture:'断裂する三面',voice:'声と余白',ground:'動きを止める'};
const positions={gather:{x:.5,y:.72},duo:{x:.5,y:.48},openSky:{x:.5,y:.28},fracture:{x:.5,y:.55},voice:{x:.62,y:.53},ground:{x:.5,y:.68},solo:{x:.5,y:.61},stands:{x:.5,y:.5},stadium:{x:.5,y:.48}};
const configure=p=>{if(!active(p))return p;const f=p.musicalPhoto.cinema,profile=p.musicalPhoto.songProfile||{mode:'punch',energy:.5,rhythm:.5},variant=p.musicalPhoto.story?.variant||0;
 const calm=['flow','drift'].includes(profile.mode),anthem=p.cuts.some(c=>c.cinema?.meaning==='hero')&&p.cuts.some(c=>c.story?.group);
 f.songGrammar={mode:profile.mode,energy:profile.energy,rhythm:profile.rhythm,brightness:profile.brightness,variant,style:p.styleKey,source:'audio profile + selected measured style + lyric meaning + intact artwork framing',uniformShotSequence:false};
 const groupOrder=[...new Set(p.cuts.map(c=>c.story?.group).filter(Boolean))],arcs={punch:[['solo','duo','stands','stadium'],['ground','gather','fracture','stadium'],['solo','voice','fracture','stadium']],drive:[['duo','fracture','stands','stadium'],['solo','gather','openSky','stadium'],['ground','duo','gather','stadium']],flow:[['voice','openSky','gather','stadium'],['ground','voice','openSky','stadium'],['solo','voice','gather','stadium']],drift:[['ground','voice','gather','openSky'],['solo','openSky','voice','stadium'],['voice','ground','gather','stadium']]};
 for(const c of p.cuts)if(c.cinema&&!locked(p,c)){const stage=c.story?.group?Math.min(4,c.story.stage):0;let mode=stage?(arcs[profile.mode]||arcs.punch)[(Math.max(0,groupOrder.indexOf(c.story.group))+Math.floor((c.story.stage-1)/4))%3][(c.story.stage-1)%4]:modes[c.cinema.meaning]||'solo';
 const repair=c.grammar?.repair||0,semanticMode=mode;if(!stage&&c.cinema.meaning==='read')mode=calm?(profile.mode==='flow'?'openSky':'voice'):(profile.mode==='drive'?'stands':variant?'duo':'solo');
 if(calm&&mode==='fracture')mode='openSky';c.grammar={mode,name:names[mode],stage,panelCount:mode==='stands'?4:mode==='duo'?2:mode==='fracture'?3:1,foregroundLayers:0,foregroundPolicy:'no displaced saliency fragments; source object identity is unverified',source:'same supplied artwork; geometric views; no object-recognition claims',repair,variant,semanticMode,profile:profile.mode,quiet:calm,motion:calm?(profile.mode==='flow'?.5:.22):(.65+profile.attack*.45),treatment:calm?'source':(profile.brightness>.65&&!anthem?'mono':'poster')};c.cinema={...c.cinema,stage,development:stage?{occupancy:.50+.07*stage,echoLayers:stage-1,speed:.5+.3*stage,contrast:.6+.1*stage}:null};c.layout='cinemaGrammar'+mode;c.architecture=c.layout;c.params={...c.params,photoAnchor:{...positions[mode],x:mode==='voice'&&variant===1?.38:positions[mode].x},directionAngle:mode==='fracture'?-2:0,displayText:c.lineText};
 }

 f.version=4;f.loop={...f.loop,mode:'background-only-text-cut',titleOverlapAllowed:false};f.grammar={version:1,shots:p.cuts.filter(c=>c.grammar).map(c=>({line:c.line,from:c.start,to:c.end,...c.grammar})),recognizedObjects:false};
 // Export actual phrase shots instead of only the three macro asset assignments.
 const old=p.storyboard||[];p.storyboard=p.cuts.filter(c=>c.line>=0).map(c=>{const s=old.find(s=>c.start>=s.from&&c.start<s.to)||old[0]||{};return {...s,from:c.start,to:c.end,locked:s.locked||locked(p,c),shotGrammar:c.grammar||null,sceneIntent:c.grammar?.mode||s.sceneIntent,macroRole:s.role};});
 if(p.artDirection.vocabulary)p.artDirection.vocabulary.layout=[...new Set(p.cuts.map(c=>c.layout))];return p;};
const build=J.buildPhotoStory;J.buildPhotoStory=p=>configure(build(p)||p);
const attemptFrom=args=>Number(args[1])||1;const repair=J.repairPhotoBottlenecks;J.repairPhotoBottlenecks=(p,...args)=>{const changes=repair(p,...args);configure(p);for(const c of p.cuts||[])if(c.grammar&&!locked(p,c)){c.grammar.repair=Math.min(2,attemptFrom(args));}return changes;};
const social=J.createSocialHookPlan;J.createSocialHookPlan=(source,candidate)=>{const p=social(source,candidate);if(active(p)){for(const c of p.cuts)if(!locked(p,c)){const o=source.cuts.find(o=>o.line===c.line);if(o?.grammar){c.grammar={...o.grammar};c.params={...c.params,photoAnchor:{...o.params.photoAnchor}};}}configure(p);const V=J.cinemaV3,legacySource=V?.legacyPlanningStates?.get(source);if(legacySource){const legacyInput=V.clone(legacySource);legacyInput.cinemaCandidateMode='legacy';const legacy=social(legacyInput,candidate);if(active(legacy)){for(const c of legacy.cuts)if(!locked(legacy,c)){const o=legacyInput.cuts.find(o=>o.line===c.line);if(o?.grammar){c.grammar={...o.grammar};c.params={...c.params,photoAnchor:{...o.params.photoAnchor}};}}configure(legacy);const sourceClimax=legacySource.musicalPhoto?.cinema?.climax;if(Number.isFinite(sourceClimax)&&sourceClimax>=candidate.start&&sourceClimax<candidate.end){legacy.musicalPhoto.cinema.legacyReframeClimax={sourceClimax,reframedClimax:legacy.musicalPhoto.cinema.climax,reason:'pre-adaptation source climax retained as an internal legacy comparison, not an automatic musical-quality pass'};legacy.musicalPhoto.cinema.climax=sourceClimax;}}V.legacyPlanningStates.set(p,legacy);}if(source.cinemaV3Features){p.cinemaV3Features=J.clonePhotoRenderPlan(source.cinemaV3Features);J.cinemaV3?.adaptGrammar?.(p);J.cinemaV3?.invalidate?.(p);}}return p;};
for(const mode of Object.keys(names))J.LAYOUTS['cinemaGrammar'+mode]={name:names[mode],special:true,plan:()=>({font:'embedded_bold'}),render(env){const {W,H,cut}=env,source=String(cut.lineText||cut.text),units=J.vocaliseUnits(source),stage=cut.grammar?.stage||0;
 let text=J.composeLyricPhrase(source);if(stage===1)text=units.join('\n');if(stage===3)text=units.join('\n');if(mode==='duo'&&!stage)text=source.replace(/(青と黒の)(.*)/,'$1\n$2');
 const font=cut.params.font||'embedded_bold',width=W*(mode==='voice'?.62:stage?.50+.075*stage:mode==='ground'?.78:.72),height=H*(stage===3?.60:mode==='openSky'?.35:.45),lead=stage===3?1.15:mode==='ground'?1.10:1.26,cap=H*(H>W?(stage===4?.13:.105):stage===4?.22:mode==='ground'?.20:mode==='voice'?.15:.175),size=Math.min(cap,J.fitSize(text,font,width,height,{lead,track:.015}));
 return J.mainDraw(env,{text,font,size,x:W/2,y:H/2,lead,track:.015,color:'#fff',noHold:mode==='ground'||mode==='voice'||mode==='gather',cinemaMotion:'read',grammarMode:mode,enter:cut.enter,exit:cut.exit});
}};
const typography=J.applyTypography5;J.applyTypography5=(env,it)=>{typography(env,it);if(!active(env.plan)||locked(env.plan,env.cut)||!it.grammarMode)return;const mode=it.grammarMode,force=env.cut.grammar?.motion||1,stage=env.cut.grammar?.stage||0,u=C(env.lt/Math.max(.1,env.cut.dur)),settle=1-ease(u*3);
 if(stage>=2){const accent=J.mix(env.plan.style?.schemes?.[0]?.accent||'#68b9ff','#ffffff',.6);it.charFns.push((i,g)=>({color:g.li%2?accent:'#ffffff'}));}
 if(env.plan.cinemaSemanticNeutral)return;
 it.charFns.push((i,g)=>mode==='gather'?{dx:(g.li%2?1:-1)*env.W*.035*settle}:mode==='duo'?{dx:(g.li%2?1:-1)*env.W*(.035*settle+(stage===2?.013*Math.sin(u*Math.PI*4):0))}:mode==='openSky'?{dy:-env.H*.013*ease(u)}:mode==='fracture'?{dx:env.W*.003*Math.sin(env.t*37+(stage?i:g.li)),dy:env.H*.004*Math.sin(env.t*41+(stage?i:g.li)*.7),rot:-2*force}:mode==='voice'?{s:.96+.04*ease(u*2)+.007*Math.sin(u*Math.PI*2),dx:env.W*.006*Math.sin(u*Math.PI*2+(stage?i:g.li)*.05)}:mode==='stadium'?{s:1+.035*ease(u),dy:env.H*.008*Math.sin(u*Math.PI)}:mode==='stands'?{dx:(g.li%2?1:-1)*env.W*.012*Math.sin(u*Math.PI*2),dy:env.H*.007*Math.sin(u*Math.PI*2+g.li)}:{});
};
// Recheck after the contrast edge is applied: its stroke contributes to glyph height.
// Reduce rendered size, never loosen the independent readability threshold.
const readability=J.adjustLocalReadability;J.adjustLocalReadability=(env,it)=>{let out=readability(env,it);if(!out.grammarMode||locked(env.plan,env.cut))return out;const short=String(env.cut.lineText||'').replace(/\s/g,'').length<=4,cap=env.H>env.W?(short?.25:.145):(short?.29:.195),evidence=J.selectionGlyphEvidence(env,out);if(evidence.maxGlyphHeight>cap*.97){out.size*=cap*.95/evidence.maxGlyphHeight;out._lay=out._m=null;out=J.centerPhotoLyricItem(env,J.safeLyricItem(env,out));}return out;};
// Render independently framed panels, then the normal safety-checked primary lyric.
const shot=(p,id)=>p.musicalPhoto.cinema.pool.find(s=>s.id===id)||{x:.5,y:.5,zoom:1.3};
const tile=(ctx,image,box,focus,t,amount=0)=>{const sw=image.width,sh=image.height,zoom=Math.max(1,(focus.zoom||1)*(1+(focus.push||0)*C((t-focus.start)/Math.max(.1,focus.duration||1)))),ar=box.w/box.h,baseW=Math.min(sw,sh*ar),baseH=baseW/ar,cw=baseW/zoom,ch=baseH/zoom,dx=amount*Math.sin(t*1.7),sx=C(focus.x+dx,0,1)*(sw-cw),sy=C(focus.y,0,1)*(sh-ch);ctx.save();ctx.beginPath();ctx.rect(box.x,box.y,box.w,box.h);ctx.clip();ctx.drawImage(image,sx,sy,cw,ch,box.x,box.y,box.w,box.h);ctx.restore();};
// Saliency rectangles are not semantic cutouts. Never move or duplicate them.
J.paintCinemaGrammarForeground=()=>true;
J.drawCinemaSourceTile=tile;
J.drawCinemaGrammar=function(ctx,p,t){const c=J.cutAt(p,t),g=c?.grammar;if(!g||locked(p,c)||!this.customBgBitmap||c.photoExit)return false;
 const W=p.W,H=p.H,climax=Number.isFinite(p.musicalPhoto.cinema.climax)&&t>=p.musicalPhoto.cinema.climax,look=g.grade|| (climax?(g.treatment==='source'?'color':g.treatment==='mono'?'mono':'silhouette'):g.mode==='voice'?'mono':g.quiet?'color':g.mode==='openSky'||g.mode==='fracture'?'blue':'color');
 // Grade the intact source; no regional source fragments are constructed here.
 if(this.grammarLookSource!==this.customBgSource){for(const cv of this.grammarLooks?.values()||[])cv.width=cv.height=1;this.grammarLooks=new Map();this.grammarLookSource=this.customBgSource;this.grammarHue=null;}let image=this.grammarLooks.get(look);if(!image){const source=this.customBgBitmap,k=Math.min(1,1280/Math.max(source.width,source.height));image=document.createElement('canvas');image.width=Math.round(source.width*k);image.height=Math.round(source.height*k);const ix=image.getContext('2d');ix.drawImage(source,0,0,image.width,image.height);if(look!=='color'){const d=ix.getImageData(0,0,image.width,image.height);for(let i=0;i<d.data.length;i+=4){const l=d.data[i]*.2126+d.data[i+1]*.7152+d.data[i+2]*.0722,v=look==='silhouette'?(l>75?210:8):l;d.data[i]=look==='mono'?v:v*.12;d.data[i+1]=look==='mono'?v:v*.43;d.data[i+2]=look==='mono'?v:Math.min(255,v*1.35);}ix.putImageData(d,0,0);}this.grammarLooks.set(look,image);}if(this.grammarHue==null){const cv=document.createElement('canvas');cv.width=cv.height=32;const sx=cv.getContext('2d');sx.drawImage(this.customBgBitmap,0,0,32,32);const bytes=sx.getImageData(0,0,32,32).data,bins=Array.from({length:6},()=>({weight:0,x:0,y:0}));for(let i=0;i<bytes.length;i+=4){const r=bytes[i]/255,green=bytes[i+1]/255,b=bytes[i+2]/255,max=Math.max(r,green,b),min=Math.min(r,green,b),d=max-min;if(d<.1||max<.15)continue;let h=max===r?((green-b)/d)%6:max===green?(b-r)/d+2:(r-green)/d+4;h=(h*60+360)%360;const bin=bins[Math.round(h/60)%6];bin.weight+=d;bin.x+=Math.cos(h*Math.PI/180)*d;bin.y+=Math.sin(h*Math.PI/180)*d;}const winner=bins.sort((a,b)=>b.weight-a.weight)[0];this.grammarHue=winner.weight?((Math.atan2(winner.y,winner.x)*180/Math.PI+360)%360)-220:0;cv.width=cv.height=1;}
 const hue=['blue','silhouette'].includes(look)?'hue-rotate('+this.grammarHue+'deg)':null;
 const mode=g.mode,u=C((t-c.start)/Math.max(.1,c.dur));ctx.save();if(hue)ctx.filter=hue;ctx.fillStyle='#020814';ctx.fillRect(0,0,W,H);
 const prescribed=J.cinemaFieldBoxes?.(p,g,t),boxes=prescribed||[];if(prescribed){}else if(mode==='duo'){if(H>W||g.variant===1)boxes.push({x:0,y:0,w:W,h:H*.49,id:'LEFT_DETAIL'},{x:0,y:H*.51,w:W,h:H*.49,id:'RIGHT_DETAIL'});else boxes.push({x:0,y:0,w:W*.49,h:H,id:'LEFT_DETAIL'},{x:W*.51,y:0,w:W*.49,h:H,id:'RIGHT_DETAIL'});}
 else if(mode==='stands')for(let i=0;i<4;i++)boxes.push({x:(i%2)*W*.51,y:Math.floor(i/2)*H*.51,w:W*.49,h:H*.49,id:['HERO','LEFT_DETAIL','CROWD','RIGHT_DETAIL'][i]});
 else if(mode==='fracture')for(let i=0;i<3;i++)boxes.push({x:i*W/3+W*.005,y:0,w:W/3-W*.01,h:H,id:['LEFT_DETAIL','HERO','RIGHT_DETAIL'][i]});
 else if(mode==='voice')boxes.push({x:g.variant===1?W*.64:0,y:H*.08,w:W*.36,h:H*.84,id:'HERO'});
 else if(mode==='openSky')boxes.push({x:0,y:0,w:W,h:H,id:'LIGHT'});
 else boxes.push({x:0,y:0,w:W,h:H,id:mode==='stadium'||mode==='gather'||mode==='ground'?'WIDE':'HERO'});
 this.cinemaGrammarViews=[];for(const b of boxes){const focus={...shot(p,b.id)};if(g.quiet)focus.zoom=1+(focus.zoom-1)*.28;focus.start=c.start;focus.duration=c.dur;focus.push=g.mode==='voice'?.03:g.mode==='ground'?.04:(.012+.008*g.stage)*(g.motion||1);if(g.repair){focus.x=C(focus.x+(g.repair===1?-.08:.08),.1,.9);focus.push*=1.7;if(g.mode==='voice')focus.push=Math.min(.04,focus.push);}focus.zoom*=C(p.customBg.zoom||1,.5,3);if(climax)focus.zoom=Math.max(focus.zoom||1,(g.quiet?1.15:1.35)+(g.quiet?.06:.26)*(g.climaxLevel?g.climaxLevel*4:g.stage))+.03*u;const quiet=mode==='voice'||mode==='ground';if(mode==='fracture')focus.x+=.01*Math.sin(t*37+b.x);ctx.save();const filters=hue?[hue]:[];if(climax)filters.push('contrast('+(1+.12*(g.climaxLevel?g.climaxLevel*4:g.stage))+')');if(p.customBg.blur>0)filters.push('blur('+C(p.customBg.blur,0,30)+'px)');if(filters.length)ctx.filter=filters.join(' ');if(J.temporalCinemaFocus)Object.assign(focus,J.temporalCinemaFocus(p,c,focus,t));const amount=quiet?.002:(g.stage||1)*.008*(g.motion||1);tile(ctx,image,b,focus,t,amount);this.cinemaGrammarViews.push({box:{...b},focus:{...focus},amount});ctx.restore();}
 // Keep the supplied photograph intact: unverified saliency fragments are disabled.
 ctx.fillStyle='#020814';ctx.globalAlpha=Math.max(p.customBg.darkness||0,mode==='voice'?.10:mode==='ground'?.40:climax?.16:.25);ctx.fillRect(0,0,W,H);ctx.globalAlpha=1;
 if(mode==='gather'){ctx.strokeStyle='#55b1ff';ctx.globalAlpha=.25*(1-u);ctx.lineWidth=H*.003;for(const x of [0,W]){ctx.beginPath();ctx.moveTo(x,H*.28);ctx.lineTo(W*.5,H*.72);ctx.stroke();}}
 if(mode==='voice'){ctx.strokeStyle='#70c4ff';ctx.lineWidth=H*.003;ctx.globalAlpha=.12+.08*Math.sin(u*Math.PI);for(let i=0;i<3;i++){ctx.beginPath();ctx.arc(W*.23,H*.5,H*(.10+i*.065+.02*u),-.8,.8);ctx.stroke();}}
 if(mode==='ground'){ctx.fillStyle='#5aaaff';ctx.fillRect(W*.14,H*.84,W*.72,H*.008);}
 if(climax&&g.stage>=2&&!g.quiet){ctx.globalCompositeOperation='screen';ctx.globalAlpha=.025*g.stage;ctx.fillStyle='#1689ff';ctx.fillRect(0,0,W,H);}
 ctx.restore();J.drawCinemaAccent?.(ctx,p,t);return true;
};
const background=J.Renderer.prototype.drawCustomBackground;
J.Renderer.prototype.drawCustomBackground=function(ctx,p,t,...args){const painted=active(p)&&!locked(p,J.cutAt(p,t))?J.drawCinemaGrammar.call(this,ctx,p,t):false,value=painted||background.call(this,ctx,p,t,...args);if(!active(p)||locked(p,J.cutAt(p,t))||this._grammarOpening)return value;
 const start=this.renderRange?.start??0,end=this.renderRange?.end??p.duration,f=p.musicalPhoto.cinema,last=Math.floor((end-1e-7)*p.fps)/p.fps,window=this.renderRange?Math.min(.65,Math.max(0,end-(p.cuts.filter(c=>c.line>=0&&c.start<end).at(-1)?.end??end))+(p.cuts.filter(c=>c.line>=0&&c.start<end).at(-1)?.dur||0)*.15):f.loop.window,from=end-window;
 if(!value||window<=0||t<from||J.cutAt(p,t)?.photoExit||p.cuts.some(c=>locked(p,c)&&c.start<end&&c.end>from))return value;
 const cv=this.ensure(this.grammarOpening||(this.grammarOpening=document.createElement('canvas')),ctx.canvas.width,ctx.canvas.height),x=cv.getContext('2d'),m=ctx.getTransform();x.setTransform(m.a,m.b,m.c,m.d,m.e,m.f);x.clearRect(0,0,p.W,p.H);this._grammarOpening=true;try{this.drawCustomBackground(x,p,start,...args);}finally{this._grammarOpening=false;}
 ctx.save();ctx.setTransform(1,0,0,1,0,0);ctx.globalAlpha=ease((t-from)/Math.max(1/p.fps,last-from));ctx.drawImage(cv,0,0);ctx.restore();return value;
};
const credit=J.creditStateAt;J.creditStateAt=(p,t)=>{if(active(p)&&t>=p.musicalPhoto.cinema.introEnd&&(p.creditChoreography?.mode!=='always'||t>=p.musicalPhoto.cinema.loop.from)&&!locked(p,J.cutAt(p,t)))return {hidden:true,opacity:0,scale:1};return credit(p,t);};
// Title remains unobscured until a verified subject mask is available.
const dispose=J.Renderer.prototype.disposeAssets;J.Renderer.prototype.disposeAssets=function(){if(this.grammarOpening)this.grammarOpening.width=this.grammarOpening.height=1;for(const cv of this.grammarLooks?.values()||[])cv.width=cv.height=1;this.grammarLooks?.clear();return dispose.call(this);};
J.applyCinemaDependencyCaps=r=>{const q=r.quality,m=q.metrics||{},categories=q.categories||[],get=k=>{const c=categories.find(c=>c.key===k);return c?c.score/c.max*100:null;},d=q.productionDomains||{};
 q.engineeringScoresBeforeDependencies={creative:q.creativeScore,typography:q.typographyScore,visualWorld:q.visualWorldScore,motion:get('motion'),categories:categories.map(c=>({...c})),productionDomains:{...d}};const caps=[];
 const capCategory=(key)=>{const c=categories.find(c=>c.key===key);if(c)c.score=Math.min(c.score,c.max*.89);};
 const weak=k=>!Number.isFinite(m[k])||m[k]<80;
 if((get('styleRealization')??0)<80||weak('perceptualNovelty')){q.creativeScore=Math.min(89,q.creativeScore);caps.push({domain:'creative',maximum:89,because:['styleRealization','perceptualNovelty']});}
 if(weak('foregroundNovelty')){if(Number.isFinite(q.visualWorldScore))q.visualWorldScore=Math.min(89,q.visualWorldScore);if(Number.isFinite(d.visualWorld))d.visualWorld=Math.min(89,d.visualWorld);capCategory('composition');caps.push({domain:'visualWorld',maximum:89,because:['foregroundNovelty']});}
 if(weak('temporalContrast')){capCategory('motion');if(Number.isFinite(d.motionRealization))d.motionRealization=Math.min(89,d.motionRealization);caps.push({domain:'motion',maximum:89,because:['temporalContrast']});}
 if(weak('lyricForegroundNovelty')){if(Number.isFinite(q.typographyScore))q.typographyScore=Math.min(89,q.typographyScore);if(Number.isFinite(d.typography))d.typography=Math.min(89,d.typography);capCategory('lyrics');caps.push({domain:'typography',maximum:89,because:['lyricForegroundNovelty']});}
 if(Number.isFinite(d.creative))d.creative=Math.min(d.creative,q.creativeScore);for(const x of q.domains||[])if(x.key==='creative')x.score=q.creativeScore;
 q.domainDependencies={minimum:80,caps,rawScoresAreEngineeringProxies:true};if(caps.length||['semanticDirection','motionRealization','impactBeatSync'].some(k=>!Number.isFinite(d[k]))){q.certified100=q.perfectEligible=false;q.overallScore=q.score=Math.min(89,q.overallScore);}q.targetAcceptance=J.evaluateQualityTarget(r);return r;};
const check=J.checkMVQuality;J.checkMVQuality=(...args)=>{const r=check(...args);if(active(args[1]))J.applyCinemaDependencyCaps(r);return r;};
const provenance=J.createExportProvenance;J.createExportProvenance=async(...args)=>{const result=await provenance(...args),q=args[2].quality,p=args[0].plan;return {...result,domainDependencies:q.domainDependencies||null,engineeringScoresBeforeDependencies:q.engineeringScoresBeforeDependencies||null,shotGrammar:p.musicalPhoto?.cinema?.grammar||null,loopTextPolicy:active(p)?'Background-only return; final lyric retained; opening title begins at playback boundary':null,singleImageCinemaEvidence:q.singleImageCinemaEvidence||null,artworkForegroundEvidence:q.artworkForegroundEvidence||null};};
const context=J.directorContext;J.directorContext=(project,p,...args)=>({...context(project,p,...args),shotGrammar:p.musicalPhoto?.cinema?.grammar||null,loopTextPolicy:active(p)?'Background returns to opening; final lyric retained until boundary; title begins at next playback, no title/lyric crossfade':null});
})();
