/* Conservative single-source compositing and verifiable blueprint rendering. */
(()=>{'use strict';const J=window.J,C=J.clamp,active=p=>!!p.musicalPhoto?.cinema;
// Keep Japanese pronoun/particle groups intact instead of isolating one glyph.
const phrase=J.composeLyricPhrase;J.composeLyricPhrase=value=>{const text=String(value||''),m=text.match(/^((?:俺ら|我ら|僕ら|私たち|君たち|僕たち|我々)(?:は|が|と|も))(.{5,})$/u);return m&&!text.includes('\n')?m[1]+'\n'+m[2]:phrase(value);};
const decorate=p=>{if(!active(p))return p;for(const c of p.cuts||[])if(c.grammar&&!J.photoChoreographyLocked(p,c)){c.decor=(c.decor||[]).filter(d=>d.id!=='cinemaBlueprint');if(p.styleKey==='blueprint')c.decor.push({id:'cinemaBlueprint',layer:'background',source:'source contours + grid + dimension lines',alpha:1});}p.musicalPhoto.cinema.limits='Intact source framing and typography; unverified regional masks are not composited. No object recognition or learned depth.';p.musicalPhoto.cinema.compositing={version:1,unverifiedSourceFragments:'disabled',displacedSourceCopies:0,particles:'none without a semantic asset specification',sameSourceViewsAreNewAssets:false};return p;};
// Also suppress the legacy regional-parallax path used by opening backgrounds.
J.drawLayeredCinema=()=>false;
const build=J.buildPhotoStory;J.buildPhotoStory=p=>decorate(build(p)||p);
const repair=J.repairPhotoBottlenecks;J.repairPhotoBottlenecks=(p,...args)=>{const result=repair(p,...args);decorate(p);return result;};
const social=J.createSocialHookPlan;J.createSocialHookPlan=(...args)=>decorate(social(...args));
// A bounded contour cache contains the whole source, never rectangular extracts.
J.blueprintContour=function(image){if(this.blueprintSource===image&&this.blueprintEdges)return this.blueprintEdges;this.blueprintEdges&&(this.blueprintEdges.width=this.blueprintEdges.height=1);const cv=document.createElement('canvas'),w=384,h=Math.max(32,Math.round(w*image.height/image.width));cv.width=w;cv.height=h;const x=cv.getContext('2d');x.drawImage(image,0,0,w,h);const d=x.getImageData(0,0,w,h),l=new Float32Array(w*h),out=x.createImageData(w,h);for(let i=0;i<l.length;i++)l[i]=d.data[i*4]*.2126+d.data[i*4+1]*.7152+d.data[i*4+2]*.0722;for(let y=1;y<h-1;y++)for(let k=1;k<w-1;k++){const i=y*w+k,e=Math.abs(l[i+1]-l[i-1])+Math.abs(l[i+w]-l[i-w]);out.data[i*4]=out.data[i*4+1]=out.data[i*4+2]=255;out.data[i*4+3]=e>28?Math.min(210,(e-28)*2):0;}x.putImageData(out,0,0);this.blueprintSource=image;this.blueprintEdges=cv;return cv;};
const draw=J.drawCinemaGrammar;J.drawCinemaGrammar=function(ctx,p,t){const result=draw.call(this,ctx,p,t),c=J.cutAt(p,t);if(!result||p.styleKey!=='blueprint'||!c?.decor?.some(d=>d.id==='cinemaBlueprint'))return result;const W=p.W,H=p.H,accent=p.style?.schemes?.[0]?.accent||'#75bfff',u=C((t-c.start)/Math.max(.1,c.dur));ctx.save();ctx.fillStyle='#061728';ctx.globalAlpha=.28;ctx.fillRect(0,0,W,H);ctx.globalAlpha=.10;const edges=J.blueprintContour.call(this,this.customBgBitmap);for(const view of this.cinemaGrammarViews||[])J.drawCinemaSourceTile(ctx,edges,view.box,view.focus,t,view.amount);if(!c.grammar.suppressBlueprint){ctx.strokeStyle=accent;ctx.lineWidth=Math.max(1,H*.0015);ctx.globalAlpha=.22;const step=H*.09;ctx.beginPath();for(let x=0;x<W;x+=step){ctx.moveTo(x,0);ctx.lineTo(x,H);}for(let y=0;y<H;y+=step){ctx.moveTo(0,y);ctx.lineTo(W,y);}ctx.stroke();ctx.globalAlpha=.68;ctx.lineWidth=H*.002;ctx.beginPath();const pad=H*.06;ctx.moveTo(pad,pad);ctx.lineTo(W-pad,pad);ctx.moveTo(pad,H-pad);ctx.lineTo(W-pad,H-pad);for(const x of [pad,W-pad])for(const y of [pad,H-pad]){ctx.moveTo(x,y-H*.015);ctx.lineTo(x,y+H*.015);}const scan=pad+(W-2*pad)*u;ctx.moveTo(scan,pad);ctx.lineTo(scan,pad+H*.035);ctx.stroke();}ctx.restore();return result;};
const audit=J.auditDirectionReality;J.auditDirectionReality=(p,pixel)=>{const r=audit(p,pixel);if(!active(p)||p.styleKey!=='blueprint')return r;const present=p.cuts.some(c=>c.grammar&&c.decor?.some(d=>d.id==='cinemaBlueprint')),measured=pixel?.metrics?.styleCues,visible=present&&(!measured||measured.decor>.0001),checks=r.checks.map(c=>c.intent==='style core cues'?{...c,actual:{...c.actual,decor:present,decorRequired:true,renderer:'source contour/grid/dimension lines',measured},status:c.actual.font&&visible?'match':'mismatch'}:c),mismatches=checks.filter(c=>c.status==='mismatch');return {...r,checks,mismatches,ok:!mismatches.length,score:Math.round(100*(1-mismatches.length/Math.max(1,checks.length))),styleRealizationScore:(checks.find(c=>c.intent==='style core cues')?.actual.font&&(!measured||measured.font>.0001)?45:0)+(visible?35:0)+(measured?.accent>.0001?20:0)};};
const foreground=J.measureArtworkForeground;J.measureArtworkForeground=async(p,...args)=>{const r=await foreground(p,...args);if(active(p)&&r){r.usedRegionCount=0;r.sourceCandidatesAreUnverified=true;r.note='Heuristic source regions are diagnostic candidates only; production fragment compositing is disabled. Empty foreground masks do not establish artistic novelty.';}return r;};
// Cheap, actual counterfactuals used before the tournament's full QA shortlist.
J.measurePhotoStyleTrial=(R,x,p)=>{const cuts=p.cuts.filter(c=>c.line>=0&&c.grammar),chosen=[cuts[0],cuts[Math.floor(cuts.length/2)],cuts.at(-1)].filter(Boolean),totals={font:[],decor:[],accent:[]};for(const c of chosen){const t=c.start+Math.min(.6,c.dur*.5);R.frame(x,p,t,{scale:x.canvas.width/p.W,production:true,noHud:true});const baseline=x.getImageData(0,0,x.canvas.width,x.canvas.height).data;for(const kind of Object.keys(totals)){const altered={...p,cuts:p.cuts.map(c=>({...c,params:{...c.params},decor:[...(c.decor||[])]})),style:{...p.style,schemes:p.style.schemes.map(s=>({...s}))}};if(kind==='decor')altered.cuts.forEach(c=>c.decor=[]);if(kind==='font')altered.cuts.forEach(c=>c.params.font=c.params.font==='mincho_light'?'gothic_black':'mincho_light');if(kind==='accent'){altered.style.schemes.forEach(s=>{s.accent=s.accent2='#777777';});altered.cuts.forEach(c=>{if(!c.styleKey||c.styleKey===p.styleKey)c.style=altered.style;});}R.frame(x,altered,t,{scale:x.canvas.width/p.W,production:true,noHud:true});const bytes=x.getImageData(0,0,x.canvas.width,x.canvas.height).data;let delta=0;for(let i=0;i<bytes.length;i+=4)delta+=Math.abs(bytes[i]-baseline[i])+Math.abs(bytes[i+1]-baseline[i+1])+Math.abs(bytes[i+2]-baseline[i+2]);totals[kind].push(delta/(bytes.length/4*765));}}const styleCues=Object.fromEntries(Object.entries(totals).map(([k,v])=>[k,v.reduce((a,b)=>a+b,0)/Math.max(1,v.length)])),audit=J.auditDirectionReality(p,{completed:true,metrics:{styleCues}});return {styleCues,score:audit.styleRealizationScore,passed:audit.styleRealizationScore>=80,method:'three actual frames; font/decoration/accent ablation; not artistic certification'};};
const check=J.checkMVQuality;J.checkMVQuality=(project,p,...args)=>{const r=check(project,p,...args);if(!active(p))return r;const compositing=p.musicalPhoto.cinema.compositing,feedback=r.quality.renderFeedback||args[2]?.metrics?.cinemaFeedback||p.lastPixelQA?.metrics?.cinemaFeedback;
const fail=(code,message)=>{const issue={code,severity:'ERROR',message,category:'creative',exportBlocking:false};r.errors.push(issue);r.issues.push(issue);r.quality.qualification='QUALITY_UNMET';r.quality.certified100=r.quality.perfectEligible=false;r.quality.score=r.quality.overallScore=Math.min(89,r.quality.overallScore);};
if(!compositing||p.cuts.some(c=>c.grammar&&!J.photoChoreographyLocked(p,c)&&c.grammar.foregroundLayers>0&&!(c.grammar.safeDerived&&['frame','rails','grid','contour'].includes(c.grammar.derivedLayer))))fail('FOREGROUND_ARTIFACT_GATE','未検証の元画像断片を前景へ複製する演出は使用できません');
if(feedback?.templateAudit?.repeats)fail('REPEATED_SHOT_SEQUENCE','反復セクションで同じショット順が再使用されています');
const cues=args[2]?.metrics?.styleCues||p.lastPixelQA?.metrics?.styleCues;const styleEvidence=J.auditDirectionReality(p,args[2]||p.lastPixelQA);if(!cues||styleEvidence.styleRealizationScore<80)fail('STYLE_NOT_PIXEL_VERIFIED','選択したスタイルの主要表現を比較描画で基準80以上に確認できていません');r.quality.stylePixelGate={style:p.styleKey,minimum:80,score:styleEvidence.styleRealizationScore,completed:!!cues,passed:!!cues&&styleEvidence.styleRealizationScore>=80};
r.quality.antiTemplateEvidence=feedback?.templateAudit||{status:'UNMEASURED'};r.quality.foregroundArtifactPolicy={...compositing,method:'Prevent unverified source-copy paths; not a pixel classifier for garbage',humanArtifactDetection:false};r.quality.sameSourceReuse={uniqueSuppliedImages:1,viewChangesAreNotNewSourceAssets:true,structuralDiversityIsNotPerceptualNovelty:true};r.quality.hardGates={...r.quality.hardGates,total:r.errors.length,passed:!r.errors.length};r.quality.targetAcceptance=J.evaluateQualityTarget(r);return J.finalizeExportReadiness(r);};
const dispose=J.Renderer.prototype.disposeAssets;J.Renderer.prototype.disposeAssets=function(){if(this.blueprintEdges)this.blueprintEdges.width=this.blueprintEdges.height=1;this.blueprintEdges=null;this.blueprintSource=null;return dispose.call(this);};
const provenance=J.createExportProvenance;J.createExportProvenance=async(...args)=>({...await provenance(...args),foregroundArtifactPolicy:args[2].quality.foregroundArtifactPolicy||null,sameSourceReuse:args[2].quality.sameSourceReuse||null,antiTemplateEvidence:args[2].quality.antiTemplateEvidence||null});
const context=J.directorContext;J.directorContext=(project,p,...args)=>({...context(project,p,...args),foregroundArtifactPolicy:p.musicalPhoto?.cinema?.compositing||null,antiTemplatePolicy:'Different musical profiles select different arcs; repeated vocalise groups use different shot sequences. Actual raster novelty remains a separate requirement.'});
})();
