/* Explicit renderer capabilities, input-conditioned worlds and verified scores. */
(()=>{'use strict';const J=window.J,C=J.clamp,active=p=>!!p.musicalPhoto?.cinema?.architecture,locked=(p,c)=>J.photoChoreographyLocked(p,c),mean=a=>a.length?a.reduce((s,v)=>s+v,0)/a.length:0;
const score=v=>Number.isFinite(v)?Math.max(0,Math.min(100,v)):null;
J.TECHNIQUE_CAPABILITIES=Object.freeze(Object.fromEntries(['frame','grid','rails','contour','subjectParallax'].map(id=>[id,Object.freeze({canRender:id!=='subjectParallax',requiresSegmentation:id==='subjectParallax',requiresForegroundMask:id==='subjectParallax',minVisibleArea:.003,expectedPixelDelta:.001,supportsPhoto:true,supportsGraphic:id!=='subjectParallax',supportsMobileExport:id!=='subjectParallax'})])));
J.cinemaTechniqueSupported=(id,p)=>{const c=J.TECHNIQUE_CAPABILITIES[id];return !!c?.canRender&&!c.requiresSegmentation&&!c.requiresForegroundMask&&(p.H<=p.W||c.supportsMobileExport);};
J.cinemaLayerPixelEvidence=(on,off)=>{let delta=0,area=0;for(let i=0;i<on.length;i+=4){const x=(Math.abs(on[i]-off[i])+Math.abs(on[i+1]-off[i+1])+Math.abs(on[i+2]-off[i+2]))/765;delta+=x;if(x>.01)area++;}return {pixelDelta:delta/(on.length/4),visibleArea:area/(on.length/4)};};
const plan=J.plan;J.plan=(project,audio,...args)=>{const p=plan(project,audio,...args);if(!active(p))return p;const values=Array.from(audio?.energy||[]),rate=audio?.energyRate||(values.length/(audio?.duration||p.duration)),beat=p.beatHierarchy||[];
 p.musicalPhoto.localMusic=p.cuts.filter(c=>c.grammar).map(c=>{const samples=values.slice(Math.floor(c.start*rate),Math.ceil(c.end*rate)).filter(Number.isFinite),section=p.musicalStructure?.sections.find(s=>c.start>=s.from&&c.start<s.to);return {line:c.line,energy:samples.length?C(mean(samples)):C(section?.energy??p.musicalPhoto.songProfile.energy??.5),onsetDensity:beat.filter(b=>b.time>=c.start&&b.time<c.end&&b.beatSalience>.35).length/Math.max(.2,c.dur),source:samples.length?'decoded audio envelope + salient beats':'section estimate + salient beats'};});
 J.applyCinemaArchitecture(p,J.cinemaArchitectureCandidates(p)[p.musicalPhoto.cinema.architecture.candidate||0]);return p;};
const apply=J.applyCinemaArchitecture;J.applyCinemaArchitecture=(p,candidate)=>{apply(p,candidate);if(!active(p))return p;const all=p.cuts.filter(c=>c.grammar&&!locked(p,c)),master={palette:p.style.schemes?.[0],font:all[0]?.params.font,stylePersonality:p.styleKey,seed:candidate.seed},worlds=[];let previous=null;
 for(const c of all){const g=c.grammar,local=p.musicalPhoto.localMusic?.find(x=>x.line===c.line),energy=local?.energy??g.temporal.level,density=local?.onsetDensity??.5,delta=energy-(previous?.energy??energy),remaining=(p.duration-c.start)/Math.max(.2,c.dur),role=g.temporal.role;
  let world=candidate.quiet?'photograph':['echo','continuity','grounding'].includes(role)?'space':g.temporal.climax?(g.climaxStep===0?(g.climaxArchetype==='depth'?'space':g.climaxArchetype==='typeField'?'type':'graphic'):g.climaxStep===1?'space':g.climaxStep===2?'type':'graphic'):role==='impact'?'graphic':role==='participation'?(delta<-.12?'space':density>1.5?'type':'photograph'):'photograph';
  if(g.stage&&!candidate.quiet){const choice=delta<-.12?'breath':delta>.12?'unison':remaining<2.2?'unison':['call','response','wave','echo'][(Math.round(density*3+energy*7)+candidate.rotation+c.line)%4];g.phraseMotion=choice;g.temporal.motionPrinciple='local-audio-'+choice;g.temporal.level=C(.25+energy*.55+Math.min(.15,density*.04));if(g.temporal.climax)g.temporal.level=Math.max(g.climaxLevel,g.temporal.level);g.repetitionDecision={energy,delta,onsetDensity:density,remainingPhrases:remaining,choice,source:local?.source||'section estimate; not per-syllable analysis'};}
  g.subWorld=world;if(world==='space'&&(!g.temporal.climax||g.climaxStep===0)){g.field=candidate.direction?'negative':'asymmetric';g.grade='mono';c.params.photoAnchor={x:g.side?.30:.70,y:.55};}if(world==='type'){g.field='typefield';g.grade='mono';c.params.photoAnchor={x:.5,y:g.temporal.climax&&g.climaxStep===0?.29:.44};g.derivedLayer=null;}if(world==='photograph'&&!g.temporal.climax)g.grade='color';if(world==='graphic')g.grade=g.temporal.climax?'silhouette':'blue';g.suppressBlueprint=world!=='photograph'||g.suppressBlueprint;
  if(g.techniqueReplacement)g.derivedLayer=g.techniqueReplacement;if(g.derivedLayer&&!J.cinemaTechniqueSupported(g.derivedLayer,p)){g.rejectedTechnique=g.derivedLayer;g.derivedLayer=null;}g.safeDerived=!!g.derivedLayer;g.foregroundLayers=g.safeDerived?1:0;g.techniqueContract=g.derivedLayer?{id:g.derivedLayer,...J.TECHNIQUE_CAPABILITIES[g.derivedLayer]}:null;worlds.push({line:c.line,world,role,energy});previous={energy};
 }
 p.musicalPhoto.cinema.visualDNA={master,worlds,policy:'One palette and font personality; music/role-conditioned spatial worlds, not random Style mixing'};p.musicalPhoto.cinema.grammar.shots=all.map(c=>({line:c.line,from:c.start,to:c.end,...c.grammar}));for(const s of p.storyboard||[]){const c=all.find(c=>c.start===s.from);if(c)s.shotGrammar={...c.grammar};}return p;};
const boxes=J.cinemaFieldBoxes;J.cinemaFieldBoxes=(p,g,t)=>g.field==='typefield'?[{x:p.W*.68,y:p.H*.73,w:p.W*.30,h:p.H*.25,id:'DETAIL'}]:boxes(p,g,t);
// Local musical breaks settle the complete phrase rather than adding another bounce.
const type=J.applyTypography5;J.applyTypography5=(env,it)=>{type(env,it);const g=env.cut.grammar;if(!g?.stage||locked(env.plan,env.cut)||g.phraseMotion!=='breath'||env.plan.cinemaSemanticNeutral)return;it.charFns=it.charFns.map(fn=>(i,glyph)=>{const r=fn(i,glyph);if(!r)return r;return {...r,dx:(r.dx||0)*.12,dy:(r.dy||0)*.12,rot:(r.rot||0)*.12,s:1+((r.s??1)-1)*.12,sx:1+((r.sx??1)-1)*.12,sy:1+((r.sy??1)-1)*.12};});};
// Derived layers must make a visible contribution in production ON/OFF pixels.
const measure=J.measureCinemaSequence;J.measureCinemaSequence=async(...args)=>{const r=await measure(...args),p=args[0];if(!active(p))return r;const contracts=r.samples.filter(s=>s.layerEvidence).map(s=>{const c=p.cuts.find(c=>c.line===s.line),spec=c.grammar.techniqueContract||J.TECHNIQUE_CAPABILITIES[s.layerEvidence.kind];return {line:s.line,id:s.layerEvidence.kind,pixelDelta:s.layerEvidence.pixelDelta,expectedPixelDelta:spec.expectedPixelDelta,visibleArea:s.layerEvidence.visibleArea,minVisibleArea:spec.minVisibleArea,visible:s.layerEvidence.pixelDelta>=spec.expectedPixelDelta&&s.layerEvidence.visibleArea>=spec.minVisibleArea};});r.techniqueEvidence={source:'production layer ON/OFF pixels',contracts,realizedFraction:contracts.length?contracts.filter(c=>c.visible).length/contracts.length:null};if(contracts.some(c=>!c.visible)&&r.rank>-100)r.rank-=.1*contracts.filter(c=>!c.visible).length/Math.max(1,contracts.length);return r;};
const repair=J.repairPhotoBottlenecks;J.repairPhotoBottlenecks=(p,acceptance,attempt)=>{const failed=p.lastPixelQA?.metrics?.decodedCinema?.layerPresence?.samples?.filter(s=>!s.visible||s.expectedArea<(J.TECHNIQUE_CAPABILITIES[s.kind]?.minVisibleArea??0))||[],r=repair(p,acceptance,attempt);if(active(p)&&attempt>=2)for(const sample of failed){const c=p.cuts.find(c=>c.line===sample.line);if(!c?.grammar||locked(p,c))continue;const g=c.grammar;g.techniqueReplacement=sample.kind==='contour'?'rails':'contour';g.derivedLayer=g.techniqueReplacement;g.safeDerived=true;g.foregroundLayers=1;g.techniqueContract={id:g.derivedLayer,...J.TECHNIQUE_CAPABILITIES[g.derivedLayer]};r.push('encoded-technique-replacement:'+sample.line);}return r;};
const metricKeys=['perceptualNovelty','foregroundNovelty','lyricForegroundNovelty','temporalContrast','hookNovelty','loopQuality','motion','decodedMotion','structuralDiversity','typographyDiversity','styleRealization','styleArcRealization','layerDepth','hookStrength','scrollStopPower','visualEnergyDensity','socialShareability','peakImpact'];
J.qualityScoreStages=(q,d)=>{const normalize=m=>Object.fromEntries(metricKeys.map(k=>[k,score(m?.[k])])),preview=normalize(q.preEncodeCinemaScores||q.metrics),encoded=d?.completed?normalize(d.metrics):normalize({}),primary=['semanticDirection','motionRealization','impactBeatSync'];const verified={...encoded,...Object.fromEntries(primary.map(k=>[k,null]))};return {plannedScore:{metrics:normalize({structuralDiversity:q.metrics?.structuralDiversity}),source:'intent only'},previewScore:{metrics:preview,source:'production canvas; not final MP4'},encodedScore:{metrics:encoded,source:d?.completed?'decoded final MP4':'unmeasured'},verifiedScore:{metrics:verified,overall:null,unmeasuredPrimary:primary,source:d?.completed?'decoded MP4 engineering evidence; semantic and audience validation unmeasured':'unmeasured',certified100:false}};};
const check=J.checkMVQuality;J.checkMVQuality=(...args)=>{const r=check(...args),p=args[1];if(!active(p))return r;const q=r.quality,d=args[4]?.metrics?.decodedCinema;for(const k of metricKeys)if(k in q.metrics)q.metrics[k]=score(q.metrics[k]);const expected=p.cuts.filter(c=>c.grammar?.safeDerived&&!locked(p,c)),samples=d?.layerPresence?.samples||[];q.techniqueRealization={source:d?.completed?'decoded layer ON/OFF evidence':'unmeasured',checks:expected.map(c=>{const sample=samples.find(s=>s.line===c.line),contract=c.grammar.techniqueContract||J.TECHNIQUE_CAPABILITIES[c.grammar.derivedLayer];return {line:c.line,id:c.grammar.derivedLayer,verified:!!sample?.visible&&sample.expectedArea>=contract.minVisibleArea,evidence:sample||null};})};if(d?.completed&&expected.length){q.techniqueRealization.score=100*q.techniqueRealization.checks.filter(s=>s.verified).length/expected.length;if(q.techniqueRealization.score<95){r.issues.push({code:'TECHNIQUE_CONTRACT_UNMET',severity:'ERROR',category:'creative',exportBlocking:false,message:'演出の可視面積・実現率が契約基準95%未達です'});r.errors=r.issues.filter(i=>i.severity==='ERROR');q.hardGates={...q.hardGates,total:r.errors.length,passed:false};}}q.scoreStages=J.qualityScoreStages(q,d);q.verifiedScore=q.scoreStages.verifiedScore;q.certified100=q.perfectEligible=false;q.certificationCriteria={primaryMinimum:92,detailMinimum:85,noveltyMinimum:85,realizationMinimum:95,unmeasuredPrimaryAllowed:0,hardGatesAllowed:0,requiresTargetProfileVerification:true};
 q.antiTemplate={structural:score(q.metrics.structuralDiversity),perceptual:d?.completed?score(d.metrics.perceptualNovelty):null,conceptual:null,overall:null,source:'Structure is planned; perceptual is decoded; conceptual diversity unmeasured. Names never establish conceptual novelty.'};q.targetAcceptance=J.evaluateQualityTarget(r);return J.finalizeExportReadiness(r);};
J.measureSocialProfilePreviews=async(p,range)=>{const R=new J.Renderer(),cv=document.createElement('canvas'),mc=document.createElement('canvas'),start=range?.start??0,end=range?.end??p.duration,profiles=[];try{await R.loadCustomBackground(p.customBg.dataUrl);await R.loadAssetDeck?.(p);for(const [aspect,ratio]of [['16:9',16/9],['9:16',9/16],['1:1',1]]){const q=J.clonePhotoRenderPlan(p);q.W=720;q.H=Math.round(720/ratio);cv.width=mc.width=128;cv.height=mc.height=Math.round(128/ratio);const x=cv.getContext('2d'),mx=mc.getContext('2d'),samples=[];let previous=null;for(const offset of [0,.5,1.5,2.7,7.5,8,11.5,14.5]){if(start+offset>=end)continue;const glyphs=[],draw=J.drawItem;J.drawItem=(env,it)=>{if(env.pass==='main'&&env.cut.line>=0)glyphs.push(J.selectionGlyphEvidence(env,it).readable);return draw(env,it);};try{R.frame(x,q,start+offset,{scale:128/q.W,production:true,noHud:false,range,lyricAuditCtx:mx});}finally{J.drawItem=draw;}const pixels=x.getImageData(0,0,cv.width,cv.height).data,change=previous?J.cinemaLayerPixelEvidence(pixels,previous).pixelDelta:null;samples.push({time:offset,hasVisualInformation:J.observePixelFrame(pixels,cv.width,cv.height).luma.some(v=>v>.03),textSafeZone:glyphs.length?glyphs.every(Boolean):null,visualChange:change,subjectVisibility:null,captionCollision:null});previous=new Uint8ClampedArray(pixels);}profiles.push({aspect,firstInformationTime:samples.find(s=>s.hasVisualInformation)?.time??null,scrollStop:null,hookNovelty:null,scope:'virtual full-MV reframing; not dedicated Short edit or encoded Short',windows:[[0,1],[0,3],[0,8],[8,15]].map(([from,to])=>({from,to,samples:samples.filter(s=>s.time>=from&&s.time<to)})),shortScore:null,verifiedScore:null});}}finally{R.disposeAssets?.();cv.width=cv.height=mc.width=mc.height=1;}return {source:'production canvas samples',encoded:false,profiles,limits:'No subject segmentation, external caption model, platform audience measurement or short certification'};};
const provenance=J.createExportProvenance;J.createExportProvenance=async(...args)=>{const r=await provenance(...args),p=args[0].plan;if(!active(p))return r;return {...r,scoreStages:args[2].quality.scoreStages,verifiedScore:args[2].quality.verifiedScore,antiTemplate:args[2].quality.antiTemplate,visualDNA:p.musicalPhoto.cinema.visualDNA,techniqueCapabilities:J.TECHNIQUE_CAPABILITIES,socialProfilePreviews:await J.measureSocialProfilePreviews(p,args[0].range)};};
})();
