/* Final encoded media is authoritative. No edge mask is called a subject mask. */
(()=>{'use strict';const J=window.J,C=J.clamp,mean=a=>a.length?a.reduce((s,v)=>s+v,0)/a.length:0,delta=(a,b)=>a?.length&&a.length===b?.length?mean(a.map((v,i)=>Math.abs(v-b[i]))):null;
const grid=(v,w,h)=>{const out=Array(144).fill(0),counts=Array(144).fill(0);for(let y=0;y<h;y++)for(let x=0;x<w;x++){const i=Math.min(7,Math.floor(y/h*8))*18+Math.min(17,Math.floor(x/w*18));out[i]+=v[y*w+x];counts[i]++;}return out.map((v,i)=>v/Math.max(1,counts[i]));};
J.measureDecodedCinemaFrames=(frames,p,range,width=96,height=Math.round(width*p.H/p.W))=>{
 const valid=frames.filter(f=>f.features?.luma?.length===width*height),start=range?.start??p.socialHook?.start??0,end=range?.end??p.socialHook?.end??p.duration,span=end-start,covered=valid.length>1&&valid[0].time<=start+.15&&valid.at(-1).time>=end-.15&&valid.every((f,i)=>!i||f.time-valid[i-1].time<=.21);if(!covered)return {status:'UNMEASURED',completed:false,reason:'Missing decoded pixels or time coverage',frameCount:valid.length};
 const steps=valid.slice(1).map((f,i)=>({time:f.time,dt:f.time-valid[i].time,motion:delta(f.features.luma,valid[i].features.luma),edge:delta(f.features.edge,valid[i].features.edge)})),cuts=(p.cuts||[]).filter(c=>c.grammar&&c.start<end&&c.end>start),samples=[];let previous=null,stagnationStart=start;
 for(const c of cuts){const interior=valid.filter(f=>f.time>=c.start+.15&&f.time<Math.min(c.end-.05,end)),motion=steps.filter(f=>f.time>=c.start+.2&&f.time<Math.min(c.end-.05,end)),mid=interior[Math.floor(interior.length/2)];if(!mid)continue;const signature=grid(mid.features.luma,width,height),distance=previous?delta(signature,previous):null;if(distance>.035)stagnationStart=c.start;const audioEnergy=p.musicalStructure?.sections?.find(s=>c.start>=s.from&&c.start<s.to)?.energy??p.musicalPhoto?.songProfile?.energy??.5,target=c.grammar.quiet?0:.001+.008*C(audioEnergy)*(c.grammar.temporal?(['echo','grounding','continuity'].includes(c.grammar.temporal.role)?.28:.65+.35*c.grammar.temporal.level):1),energy=mean(motion.map(f=>f.motion));samples.push({line:c.line,from:c.start,to:c.end,energy,compositionDistance:distance,stagnant:c.end-stagnationStart>8,quiet:!!c.grammar.quiet,targetMotion:target,energyGap:Math.max(0,target-energy)});previous=signature;}
 const motion=samples.map(s=>s.energy),dist=samples.map(s=>s.compositionDistance).filter(Number.isFinite),hook=valid.filter(f=>f.time<Math.min(end,start+3)),hookDelta=hook.length>1?Math.max(...hook.map(f=>delta(f.features.luma,hook[0].features.luma))):null,seam=delta(valid[0].features.luma,valid.at(-1).features.luma),contrast=motion.length>1?(Math.max(...motion)-Math.min(...motion))/Math.max(.003,mean(motion)):null;
 const metrics={perceptualNovelty:dist.length?Math.round(100*C(mean(dist)/.12)):null,motion:motion.length?Math.round(100*samples.filter(s=>s.quiet||s.energy>=s.targetMotion).length/samples.length):null,temporalContrast:contrast==null?null:Math.round(100*C(contrast/2)),hookNovelty:hookDelta==null?null:Math.round(100*C(hookDelta/.25)),loopQuality:seam==null?null:Math.round(100*C(1-seam*4)),foregroundNovelty:null,lyricForegroundNovelty:null,displayOnsetAccuracy:null};
 return {status:'DECODED_MP4_PIXEL_PROXY',completed:true,frameCount:valid.length,resolution:[width,height],duration:span,samples,metrics,loop:{fullFrameLumaSeam:seam,textIncluded:true,sampleTimes:[valid[0].time,valid.at(-1).time],lastFrameIncluded:valid.at(-1).time>=end-1/(p.fps||30)-.01},hook:{fullFrameLumaChange:hookDelta},weakLines:samples.filter(s=>s.stagnant||s.energyGap>0||s.compositionDistance!=null&&s.compositionDistance<.035).map(s=>s.line),limits:'Decoded RGB luminance/edge measurements, not OCR, optical flow, foreground segmentation, semantic understanding or audience evaluation. Text and image share full-frame novelty. Missing domains remain unmeasured.'};
};
// Project onto the expected layer pixels, so unrelated codec error cannot hide a line.
const compareLayer=(actual,on,off)=>{let norm=0,dot=0,onError=0,offError=0,count=0;for(let i=0;i<on.length;i++){const d=on[i]-off[i];if(Math.abs(d)<.004)continue;norm+=d*d;dot+=(actual[i]-off[i])*d;onError+=Math.abs(actual[i]-on[i]);offError+=Math.abs(actual[i]-off[i]);count++;}const gain=norm?dot/norm:null;return {referenceDifference:delta(on,off),expectedArea:count/on.length,projectionGain:gain,onError:count?onError/count:null,offError:count?offError/count:null,visible:count>=3&&gain>.30&&gain<1.8&&offError>onError};};
J.verifyDecodedCinemaLayers=async(frames,p,range,options={})=>{if(!p.musicalPhoto?.cinema?.architecture||!frames.length)return null;const R=new J.Renderer(),width=options.width||96,height=Math.round(width*p.H/p.W),cv=document.createElement('canvas'),mc=document.createElement('canvas');cv.width=mc.width=width;cv.height=mc.height=height;const x=cv.getContext('2d'),mx=mc.getContext('2d'),samples=[],primary=[];let textLoop=null;const start=range?.start??0,end=range?.end??p.duration;
 try{await R.loadCustomBackground(p.customBg.dataUrl);await R.loadAssetDeck?.(p);for(const c of p.cuts.filter(c=>c.grammar&&!J.photoChoreographyLocked(p,c)&&c.start<end&&c.end>start)){
  const times=[c.start+.04,c.start+c.dur*.25,c.start+c.dur*.5,c.start+c.dur*.75,c.end-.2,c.grammar.temporal?.hit??c.start+.3].filter(t=>t>=start&&t<end-.36),unique=[...new Set(times.map(t=>frames.reduce((best,f)=>Math.abs(f.time-t)<Math.abs(best.time-t)?f:best,frames[0])))].sort((a,b)=>a.time-b.time),glyphs=[];
  for(const frame of unique){if(!frame?.features?.luma?.length||frame.time<c.start||frame.time>=c.end)continue;const render=(layerNeutral,textNeutral)=>{R.cinemaNeutralLayers=layerNeutral;const plan=textNeutral?{...p,_decodedNeutralPrimary:true}:p;R.frame(x,plan,frame.time,{scale:width/p.W,production:true,noHud:false,range,lyricAuditCtx:mx});const luma=J.observePixelFrame(x.getImageData(0,0,width,height).data,width,height).luma,mask=Array.from(mx.getImageData(0,0,width,height).data).filter((_,i)=>i%4===3).map(v=>v/255);return {luma,mask};},on=render(false,false),off=render(false,true),actual=frame.features.luma,evidence=compareLayer(actual,on.luma,off.luma);glyphs.push({time:frame.time,phase:J.cinemaTemporalState?.(p,c,frame.time)?.phase??null,...evidence,contrast:J.decodedGlyphContrast?.(actual,off.luma,on.mask,width,height)??null,mask:on.mask,structure:grid(on.mask,width,height)});
   if(c.grammar.safeDerived){const without=render(true,false);samples.push({line:c.line,time:frame.time,kind:c.grammar.derivedLayer,...compareLayer(actual,on.luma,without.luma)});}
  }
  if(glyphs.length){const steps=glyphs.slice(1).map((f,i)=>{const a=glyphs[i].mask,b=f.mask,union=mean(a.map((v,k)=>Math.max(v,b[k])));return delta(a,b)/Math.max(.0001,union);});const mid=glyphs[Math.floor(glyphs.length/2)];primary.push({line:c.line,role:c.grammar.temporal?.role,visibleSamples:glyphs.filter(s=>s.visible).length,samples:glyphs.map(({mask,structure,...s})=>s),structure:mid.structure,withinPhraseMaskChange:mean(steps)});}await new Promise(r=>setTimeout(r,0));
 }const endpointMasks=[];for(const frame of [frames[0],frames.at(-1)]){R.cinemaNeutralLayers=false;R.frame(x,p,frame.time,{scale:width/p.W,production:true,noHud:false,range,lyricAuditCtx:mx});endpointMasks.push(Array.from(mx.getImageData(0,0,width,height).data).filter((_,i)=>i%4===3).map(v=>v/255));}textLoop=J.decodedTextSeam?.(frames[0].features.luma,frames.at(-1).features.luma,...endpointMasks)??null;
 }finally{R.cinemaNeutralLayers=false;R.disposeAssets?.();cv.width=cv.height=mc.width=mc.height=1;}
 const changes=primary.slice(1).map((s,i)=>delta(s.structure,primary[i].structure)/Math.max(.005,mean(s.structure.map((v,k)=>Math.max(v,primary[i].structure[k]))))),presence=primary.length?mean(primary.map(s=>s.samples.length?s.visibleSamples/s.samples.length:0)):0;
 return {resolution:[width,height],textLoop,samples,score:samples.length?Math.round(100*samples.filter(s=>s.visible).length/samples.length):null,method:'Decoded luma projected onto identical production on-minus-off reference; only expected layer pixels compared',objectSegmentation:false,primaryText:{samples:primary,visibleFraction:presence,lyricForegroundNovelty:primary.length>1?Math.round(100*C(mean(changes))*presence):null,meanWithinPhraseMaskChange:mean(primary.map(s=>s.withinPhraseMaskChange)),method:'18×8 actual primary alpha occupancy; normalized consecutive occupancy change × encoded compositing presence. Within-phrase alpha displacement reported separately.',limits:'Expected raster mask and compositing evidence, not OCR, exact string recognition or semantic realization.'}};
};
J.applyDecodedCinemaEvidence=d=>{if(d?.completed&&d.layerPresence?.primaryText)d.metrics.lyricForegroundNovelty=d.layerPresence.primaryText.lyricForegroundNovelty;return d;};
J.reconcileDecodedCinemaQuality=(r,decoded)=>{const q=r.quality;if(!decoded?.completed)return r;q.evidenceByStage={planned:{status:'INTENT_ONLY',source:'storyboard; never certification'},preEncode:{metrics:{...(q.metrics||{})},source:'production canvas before encoding'},decoded:{metrics:{...decoded.metrics},source:'decoded final MP4',definitions:decoded.limits,primaryText:decoded.layerPresence?.primaryText?.limits||null}};q.preEncodeCinemaScores={...(q.metrics||{})};
 for(const key of ['perceptualNovelty','temporalContrast','hookNovelty','loopQuality','lyricForegroundNovelty','foregroundNovelty'])q.metrics[key]=Number.isFinite(decoded.metrics[key])?decoded.metrics[key]:null;q.metrics.decodedMotion=decoded.metrics.motion;q.finalCinemaMetricSource='decoded-MP4';
 const gates=[['perceptualNovelty','LOW_PERCEPTUAL_NOVELTY'],['lyricForegroundNovelty','LOW_LYRIC_FOREGROUND_NOVELTY'],['foregroundNovelty','LOW_FOREGROUND_NOVELTY']],replaced=new Set([...gates.map(x=>x[1]),'ENCODED_CINEMA_UNMET','ENCODED_LAYER_NOT_REALIZED',...(decoded.layerPresence?.primaryText?.samples?.length?['NON_CROP_STAGNATION']:[])]);r.issues=r.issues.filter(i=>!replaced.has(i.code));
 for(const [key,code]of gates)if(!Number.isFinite(q.metrics[key])||q.metrics[key]<80)r.issues.push({code,score:q.metrics[key],minimum:80,severity:'ERROR',category:'creative',exportBlocking:false,measurementSource:'decoded-MP4',message:'最終MP4の '+key+' が基準80未達、または未計測です'});
 if(decoded.metrics.perceptualNovelty<80||decoded.samples.some(s=>s.stagnant||s.energyGap>0))r.issues.push({code:'ENCODED_CINEMA_UNMET',severity:'ERROR',category:'creative',exportBlocking:false,message:'最終MP4に新規性・動作不足が残っています',lines:decoded.weakLines});
 if(decoded.layerPresence?.samples?.some(s=>!s.visible))r.issues.push({code:'ENCODED_LAYER_NOT_REALIZED',severity:'ERROR',category:'creative',exportBlocking:false,message:'指定した派生レイヤーを最終MP4上で確認できません',lines:decoded.layerPresence.samples.filter(s=>!s.visible).map(s=>s.line)});
 const glyphs=decoded.layerPresence?.primaryText?.samples||[],gaps=[];let last=decoded.samples[0]?.from??0;for(const s of glyphs){const prev=glyphs[glyphs.indexOf(s)-1];if(prev&&delta(s.structure,prev.structure)>.035){if(s.samples[0].time-last>8)gaps.push({from:last,to:s.samples[0].time});last=s.samples[0].time;}}const lastTime=decoded.samples.at(-1)?.to??last;if(lastTime-last>8)gaps.push({from:last,to:lastTime});if(glyphs.length&&gaps.length)r.issues.push({code:'NON_CROP_STAGNATION',severity:'ERROR',category:'creative',exportBlocking:false,measurementSource:'decoded-MP4 verified primary alpha occupancy',windows:gaps,message:'最終MP4の文字構造に8秒超の停滞があります'});
 q.decodedLayerPresence=decoded.layerPresence||null;const category=q.categories?.find(c=>c.key==='motion');if(category&&Number.isFinite(decoded.metrics.motion))category.score=category.max*decoded.metrics.motion/100;
 const d=q.productionDomains||{},constraints=['perceptualNovelty','foregroundNovelty','lyricForegroundNovelty','temporalContrast'].map(key=>({key,score:q.metrics[key]??null}));constraints.push({key:'semanticDirection',score:d.semanticDirection??null});q.cinemaScorePolicy={...q.cinemaScorePolicy,minimum:80,failures:constraints.filter(s=>!Number.isFinite(s.score)||s.score<80),unmeasured:['semanticDirection','motionRealization','impactBeatSync'].filter(k=>!Number.isFinite(d[k])),finalMetricSource:'decoded-MP4; source foreground segmentation unmeasured'};J.applyCinemaDependencyCaps(r);r.errors=r.issues.filter(i=>i.severity==='ERROR');r.warnings=r.issues.filter(i=>i.severity==='WARNING');q.hardGates={...q.hardGates,total:r.errors.length,passed:!r.errors.length};return r;};
const check=J.checkMVQuality;J.checkMVQuality=(...args)=>{const r=check(...args),p=args[1],decoded=args[4]?.metrics?.decodedCinema;if(!p.musicalPhoto?.cinema?.architecture)return r;const q=r.quality;q.decodedCinema=decoded||{completed:false,status:'NOT_ENCODED_YET'};if(decoded?.completed)J.reconcileDecodedCinemaQuality(r,decoded);q.certified100=q.perfectEligible=false; // Decoded lyric/semantic realization is still unmeasured.
 q.certificationEvidence={finalEncodedPixels:!!decoded?.completed,decodedTextRecognition:false,decodedSemanticDirection:false,artistic100Established:false};q.targetAcceptance=J.evaluateQualityTarget(r);return J.finalizeExportReadiness(r);};
const provenance=J.createExportProvenance;J.createExportProvenance=async(...args)=>{const r=await provenance(...args);return {...r,decodedCinema:args[2].quality.decodedCinema||null,compositionSearch:args[0].plan.musicalPhoto?.cinema?.architectureSearch||null,measurementSources:{...r.measurementSources,perceptualNovelty:args[2].quality.decodedCinema?.completed?'decoded-MP4-full-frame-proxy':'pre-export-canvas',temporalContrast:args[2].quality.decodedCinema?.completed?'decoded-MP4':'pre-export-canvas',loopQuality:args[2].quality.decodedCinema?.completed?'decoded-MP4-image-and-text-luma-seam':'pre-export-canvas',foreground:'decoded-layer-presence-counterfactual; source segmentation unmeasured',lyricForegroundNovelty:args[2].quality.decodedCinema?.completed?'decoded-MP4-verified-primary-alpha-occupancy':'pre-export-primary-alpha-mask',displayOnsetAccuracy:'pre-export-full-glyph-mask; decoded-OCR-unmeasured'}};};
})();
